import type { FlashCard } from '@/types'

export const geographicTerms: FlashCard[] = [
	{
		questionTitleHtml: '<strong>Geography Term</strong>',
		questionDescriptionHtml: 'Facility where aircraft take off and land, with runways and terminals',
		answerTitleHtml: '<strong>Airport</strong>',
		answerDescriptionHtml: null,
		pathToMedia: 'https://upload.wikimedia.org/wikipedia/commons/thumb/8/86/Airport_infrastructure.png/500px-Airport_infrastructure.png',
		category: 'geographic-terms',
	},
	{
		questionTitleHtml: '<strong>Geography Term</strong>',
		questionDescriptionHtml: 'Height of a location above sea level',
		answerTitleHtml: '<strong>Altitude</strong>',
		answerDescriptionHtml: null,
		pathToMedia: 'https://upload.wikimedia.org/wikipedia/commons/thumb/c/c2/Altitude.svg/250px-Altitude.svg.png',
		category: 'geographic-terms',
	},
	{
		questionTitleHtml: '<strong>Geography Term</strong>',
		questionDescriptionHtml: 'Group or chain of islands<br/><br/><strong>Examples:</strong> Hawaii; the Philippines; Indonesia',
		answerTitleHtml: '<strong>Archipelago</strong>',
		answerDescriptionHtml: null,
		pathToMedia: 'https://upload.wikimedia.org/wikipedia/commons/9/94/Indonesia_relief_location_map.jpg',
		category: 'geographic-terms',
	},
	{
		questionTitleHtml: '<strong>Geography Term</strong>',
		questionDescriptionHtml: 'Region around the North Pole, characterized by cold temperatures and ice',
		answerTitleHtml: '<strong>Arctic Region</strong>',
		answerDescriptionHtml: null,
		pathToMedia: 'https://upload.wikimedia.org/wikipedia/commons/thumb/f/f0/Arctic_%28orthographic_projection_with_highlights%29.svg/330px-Arctic_%28orthographic_projection_with_highlights%29.svg.png',
		category: 'geographic-terms',
	},
	{
		questionTitleHtml: '<strong>Geography Term</strong>',
		questionDescriptionHtml: 'Narrow extension, inlet, or smaller reach, of water flowing out from a much larger body of water, such as an ocean, a sea, or a lake',
		answerTitleHtml: '<strong>Arm</strong>',
		answerDescriptionHtml: null,
		pathToMedia: 'https://upload.wikimedia.org/wikipedia/en/5/53/ShuswapArms.png',
		category: 'geographic-terms',
	},
	{
		questionTitleHtml: '<strong>Geography Term</strong>',
		questionDescriptionHtml: 'Collection of maps bound together in book form',
		answerTitleHtml: '<strong>Atlas</strong>',
		answerDescriptionHtml: null,
		pathToMedia: null,
		category: 'geographic-terms',
	},
	{
		questionTitleHtml: '<strong>Geography Term</strong>',
		questionDescriptionHtml: 'Ring-shaped coral reef, island, or series of islets surrounding a lagoon<br/><br/><strong>Examples:</strong> Bikini (Marshall Islands); the Maldives',
		answerTitleHtml: '<strong>Atoll</strong>',
		answerDescriptionHtml: null,
		pathToMedia: 'https://upload.wikimedia.org/wikipedia/commons/thumb/3/31/Tetiaroa_from_sky.JPG/1920px-Tetiaroa_from_sky.JPG',
		category: 'geographic-terms',
	},
	{
		questionTitleHtml: '<strong>Geography Term</strong>',
		questionDescriptionHtml: 'Imaginary line through the center of a planet around which it rotates',
		answerTitleHtml: '<strong>Axis</strong>',
		answerDescriptionHtml: null,
		pathToMedia: 'https://upload.wikimedia.org/wikipedia/commons/0/02/Rotating_Sphere.gif',
		category: 'geographic-terms',
	},
	{
		questionTitleHtml: '<strong>Geography Term</strong>',
		questionDescriptionHtml: 'Land alongside a river, lake, or other body of water',
		answerTitleHtml: '<strong>Bank</strong>',
		answerDescriptionHtml: null,
		pathToMedia: 'https://upload.wikimedia.org/wikipedia/commons/thumb/7/7d/Perfume_River_Bank%2C_as_seen_from_Tr%C6%B0%E1%BB%9Dng_Ti%E1%BB%81n_Bridge%2C_2019.jpg/250px-Perfume_River_Bank%2C_as_seen_from_Tr%C6%B0%E1%BB%9Dng_Ti%E1%BB%81n_Bridge%2C_2019.jpg',
		category: 'geographic-terms',
	},
	{
		questionTitleHtml: '<strong>Geography Term</strong>',
		questionDescriptionHtml: 'Depression in the Earth\'s surface, often containing water',
		answerTitleHtml: '<strong>Basin</strong>',
		answerDescriptionHtml: null,
		pathToMedia: 'https://upload.wikimedia.org/wikipedia/commons/thumb/3/37/Uureg_Nuur.jpg/1280px-Uureg_Nuur.jpg',
		category: 'geographic-terms',
	},
	{
		questionTitleHtml: '<strong>Geography Term</strong>',
		questionDescriptionHtml: 'Body of water partially enclosed by land, smaller than a gulf<br/><br/><strong>Examples:</strong> Hudson (Canada); San Francisco (California)',
		answerTitleHtml: '<strong>Bay</strong>',
		answerDescriptionHtml: null,
		pathToMedia: 'https://upload.wikimedia.org/wikipedia/commons/b/b7/San_Sebastian_aerea.jpg',
		category: 'geographic-terms',
	},
	{
		questionTitleHtml: '<strong>Geography Term</strong>',
		questionDescriptionHtml: 'Sandy or pebbly shore of a body of water',
		answerTitleHtml: '<strong>Beach</strong>',
		answerDescriptionHtml: null,
		pathToMedia: 'https://upload.wikimedia.org/wikipedia/commons/thumb/7/73/Beach_at_Fort_Lauderdale.jpg/1920px-Beach_at_Fort_Lauderdale.jpg',
		category: 'geographic-terms',
	},
	{
		questionTitleHtml: '<strong>Geography Term</strong>',
		questionDescriptionHtml: 'Slow-moving stream or a marshy lake, especially in the southern United States',
		answerTitleHtml: '<strong>Bayou</strong>',
		answerDescriptionHtml: null,
		pathToMedia: 'https://upload.wikimedia.org/wikipedia/commons/7/7e/Atchafalaya_Basin.jpg',
		category: 'geographic-terms',
	},
	{
		questionTitleHtml: '<strong>Geography Term</strong>',
		questionDescriptionHtml: 'Large community of plants and animals that occupies a distinct region',
		answerTitleHtml: '<strong>Biome</strong>',
		answerDescriptionHtml: null,
		pathToMedia: 'https://upload.wikimedia.org/wikipedia/commons/e/e4/Vegetation.png',
		category: 'geographic-terms',
	},
	{
		questionTitleHtml: '<strong>Geography Term</strong>',
		questionDescriptionHtml: 'Barrier built to protect a harbor or beach from the force of waves',
		answerTitleHtml: '<strong>Breakwater</strong>',
		answerDescriptionHtml: null,
		pathToMedia: 'https://upload.wikimedia.org/wikipedia/commons/7/75/V%C3%A5gbrytare_-_Ystad-2019.jpg',
		category: 'geographic-terms',
	},
	{
		questionTitleHtml: '<strong>Geography Term</strong>',
		questionDescriptionHtml: 'Isolated hill with steep sides and a flat top, smaller than a mesa',
		answerTitleHtml: '<strong>Butte</strong>',
		answerDescriptionHtml: null,
		pathToMedia: 'https://upload.wikimedia.org/wikipedia/commons/e/e6/Monument_Valley%2C_late_afternoon.jpg',
		category: 'geographic-terms',
	},
	{
		questionTitleHtml: '<strong>Geography Term</strong>',
		questionDescriptionHtml: 'Artificial waterway constructed for navigation, irrigation, or drainage',
		answerTitleHtml: '<strong>Canal</strong>',
		answerDescriptionHtml: null,
		pathToMedia: 'https://upload.wikimedia.org/wikipedia/commons/thumb/c/c7/IMG_RoyalCanalnrKinnegad5706w.jpg/1920px-IMG_RoyalCanalnrKinnegad5706w.jpg',
		category: 'geographic-terms',
	},
	{
		questionTitleHtml: '<strong>Geography Term</strong>',
		questionDescriptionHtml: 'Deep, narrow valley with steep sides, often carved by a river<br/><br/><strong>Examples:</strong> Grand (Arizona); Colca (Peru)',
		answerTitleHtml: '<strong>Canyon</strong>',
		answerDescriptionHtml: null,
		pathToMedia: 'https://upload.wikimedia.org/wikipedia/commons/thumb/2/26/Aerial_view_of_canyons.jpg/960px-Aerial_view_of_canyons.jpg',
		category: 'geographic-terms',
	},
	{
		questionTitleHtml: '<strong>Geography Term</strong>',
		questionDescriptionHtml: 'Point of land extending into a body of water<br/><br/><strong>Examples:</strong> Cod (Massachusetts)',
		answerTitleHtml: '<strong>Cape</strong>',
		answerDescriptionHtml: null,
		pathToMedia: 'https://upload.wikimedia.org/wikipedia/commons/thumb/a/a7/Astronaut_photo_of_Cape_Town_STS081-738-23.jpg/1280px-Astronaut_photo_of_Cape_Town_STS081-738-23.jpg',
		category: 'geographic-terms',
	},
	{
		questionTitleHtml: '<strong>Geography Term</strong>',
		questionDescriptionHtml: 'Natural underground chamber or series of chambers',
		answerTitleHtml: '<strong>Cave</strong>',
		answerDescriptionHtml: null,
		pathToMedia: 'https://upload.wikimedia.org/wikipedia/commons/thumb/0/02/Lechuguilla_Cave_Pearlsian_Gulf.jpg/960px-Lechuguilla_Cave_Pearlsian_Gulf.jpg',
		category: 'geographic-terms',
	},
	{
		questionTitleHtml: '<strong>Geography Term</strong>',
		questionDescriptionHtml: 'Wider strait or passage of water connecting two larger bodies of water',
		answerTitleHtml: '<strong>Channel</strong>',
		answerDescriptionHtml: null,
		pathToMedia: 'https://upload.wikimedia.org/wikipedia/commons/a/a7/Vivari_Channel.jpg',
		category: 'geographic-terms',
	},
	{
		questionTitleHtml: '<strong>Geography Term</strong>',
		questionDescriptionHtml: 'Steep, high face of rock or earth',
		answerTitleHtml: '<strong>Cliff</strong>',
		answerDescriptionHtml: null,
		pathToMedia: 'https://upload.wikimedia.org/wikipedia/commons/thumb/7/74/White_Cliffs_of_Dover_02.JPG/1920px-White_Cliffs_of_Dover_02.JPG',
		category: 'geographic-terms',
	},
	{
		questionTitleHtml: '<strong>Geography Term</strong>',
		questionDescriptionHtml: 'Long-term pattern of weather conditions in a particular area',
		answerTitleHtml: '<strong>Climate</strong>',
		answerDescriptionHtml: null,
		pathToMedia: null,
		category: 'geographic-terms',
	},
	{
		questionTitleHtml: '<strong>Geography Term</strong>',
		questionDescriptionHtml: 'Land along the edge of a sea or ocean',
		answerTitleHtml: '<strong>Coast</strong>',
		answerDescriptionHtml: null,
		pathToMedia: null,
		category: 'geographic-terms',
	},
	{
		questionTitleHtml: '<strong>Geography Term</strong>',
		questionDescriptionHtml: 'Group of people living in the same area or having common interests',
		answerTitleHtml: '<strong>Community</strong>',
		answerDescriptionHtml: null,
		pathToMedia: null,
		category: 'geographic-terms',
	},
	{
		questionTitleHtml: '<strong>Geography Term</strong>',
		questionDescriptionHtml: 'Instrument used for navigation that shows direction relative to magnetic north',
		answerTitleHtml: '<strong>Compass</strong>',
		answerDescriptionHtml: null,
		pathToMedia: null,
		category: 'geographic-terms',
	},
	{
		questionTitleHtml: '<strong>Geography Term</strong>',
		questionDescriptionHtml: 'Symbol on a map showing the cardinal directions (north, south, east, west)',
		answerTitleHtml: '<strong>Compass Rose</strong>',
		answerDescriptionHtml: null,
		pathToMedia: 'https://upload.wikimedia.org/wikipedia/commons/thumb/4/47/Windrose_en.svg/1280px-Windrose_en.svg.png',
		category: 'geographic-terms',
	},
	{
		questionTitleHtml: '<strong>Geography Term</strong>',
		questionDescriptionHtml: 'Ridge of mountains that separates river systems flowing toward opposite sides of a continent',
		answerTitleHtml: '<strong>Continental Divide</strong>',
		answerDescriptionHtml: null,
		pathToMedia: 'https://upload.wikimedia.org/wikipedia/commons/4/4b/SouthAmerica-ContinentalDivide.png',
		category: 'geographic-terms',
	},
	{
		questionTitleHtml: '<strong>Geography Term</strong>',
		questionDescriptionHtml: 'Large, continuous landmass on Earth',
		answerTitleHtml: '<strong>Continent</strong>',
		answerDescriptionHtml: null,
		pathToMedia: null,
		category: 'geographic-terms',
	},
	{
		questionTitleHtml: '<strong>Geography Term</strong>',
		questionDescriptionHtml: 'Nation or sovereign state with defined borders and government',
		answerTitleHtml: '<strong>Country</strong>',
		answerDescriptionHtml: null,
		pathToMedia: null,
		category: 'geographic-terms',
	},
	{
		questionTitleHtml: '<strong>Geography Term</strong>',
		questionDescriptionHtml: 'Small, sheltered bay or inlet',
		answerTitleHtml: '<strong>Cove</strong>',
		answerDescriptionHtml: null,
		pathToMedia: 'https://upload.wikimedia.org/wikipedia/commons/8/89/McWay_cove_1.jpg',
		category: 'geographic-terms',
	},
	{
		questionTitleHtml: '<strong>Geography Term</strong>',
		questionDescriptionHtml: 'Small stream or tributary of a river',
		answerTitleHtml: '<strong>Creek</strong>',
		answerDescriptionHtml: null,
		pathToMedia: null,
		category: 'geographic-terms',
	},
	{
		questionTitleHtml: '<strong>Geography Term</strong>',
		questionDescriptionHtml: 'Continuous flow of water in a particular direction, especially in an ocean or river',
		answerTitleHtml: '<strong>Current</strong>',
		answerDescriptionHtml: null,
		pathToMedia: null,
		category: 'geographic-terms',
	},
	{
		questionTitleHtml: '<strong>Geography Term</strong>',
		questionDescriptionHtml: 'Barrier constructed to hold back water and raise its level',
		answerTitleHtml: '<strong>Dam</strong>',
		answerDescriptionHtml: null,
		pathToMedia: null,
		category: 'geographic-terms',
	},
	{
		questionTitleHtml: '<strong>Geography Term</strong>',
		questionDescriptionHtml: 'Landform at the mouth of a river where it flows into a larger body of water, typically triangular in shape<br/><br/><strong>Examples:</strong> Nile (Egypt); Mississippi (Louisiana)',
		answerTitleHtml: '<strong>Delta</strong>',
		answerDescriptionHtml: null,
		pathToMedia: 'https://upload.wikimedia.org/wikipedia/commons/c/cc/Nile_delta_landsat_false_color.jpg',
		category: 'geographic-terms',
	},
	{
		questionTitleHtml: '<strong>Geography Term</strong>',
		questionDescriptionHtml: 'Arid region with little rainfall and sparse vegetation<br/><br/><strong>Examples:</strong> the Sahara; the Gobi',
		answerTitleHtml: '<strong>Desert</strong>',
		answerDescriptionHtml: null,
		pathToMedia: null,
		category: 'geographic-terms',
	},
	{
		questionTitleHtml: '<strong>Geography Term</strong>',
		questionDescriptionHtml: 'Embankment, wall, or trench constructed from earth or stone to manage water flow, prevent flooding, and reclaim land from the sea or rivers',
		answerTitleHtml: '<strong>Dike</strong>',
		answerDescriptionHtml: null,
		pathToMedia: 'https://images.pond5.com/dike-water-works-man-made-footage-309290836_iconl.jpeg',
		category: 'geographic-terms',
	},
	{
		questionTitleHtml: '<strong>Geography Term</strong>',
		questionDescriptionHtml: 'Ridge of high ground separating two drainage basins',
		answerTitleHtml: '<strong>Divide</strong>',
		answerDescriptionHtml: null,
		pathToMedia: null,
		category: 'geographic-terms',
	},
	{
		questionTitleHtml: '<strong>Geography Term</strong>',
		questionDescriptionHtml: 'Direction toward the mouth of a river, in the direction of flow',
		answerTitleHtml: '<strong>Downstream</strong>',
		answerDescriptionHtml: null,
		pathToMedia: null,
		category: 'geographic-terms',
	},
	{
		questionTitleHtml: '<strong>Geography Term</strong>',
		questionDescriptionHtml: 'Area of land where all surface water converges to a single point',
		answerTitleHtml: '<strong>Drainage Basin</strong>',
		answerDescriptionHtml: null,
		pathToMedia: 'https://upload.wikimedia.org/wikipedia/commons/thumb/1/1a/Major_River_Systems_within_the_Mississippi_River_Basin.svg/1920px-Major_River_Systems_within_the_Mississippi_River_Basin.svg.png',
		category: 'geographic-terms',
	},
	{
		questionTitleHtml: '<strong>Geography Term</strong>',
		questionDescriptionHtml: 'Height of a location above sea level',
		answerTitleHtml: '<strong>Elevation</strong>',
		answerDescriptionHtml: null,
		pathToMedia: null,
		category: 'geographic-terms',
	},
	{
		questionTitleHtml: '<strong>Geography Term</strong>',
		questionDescriptionHtml: 'Imaginary line around Earth\'s middle, equidistant from the North and South Poles',
		answerTitleHtml: '<strong>Equator</strong>',
		answerDescriptionHtml: null,
		pathToMedia: null,
		category: 'geographic-terms',
	},
	{
		questionTitleHtml: '<strong>Geography Term</strong>',
		questionDescriptionHtml: 'Tidal mouth of a large river, where the tide meets the stream',
		answerTitleHtml: '<strong>Estuary</strong>',
		answerDescriptionHtml: null,
		pathToMedia: 'https://upload.wikimedia.org/wikipedia/commons/2/22/Mattole_River_Estuary_2005.jpg',
		category: 'geographic-terms',
	},
	{
		questionTitleHtml: '<strong>Geography Term</strong>',
		questionDescriptionHtml: 'Open area of land, often used for agriculture or pasture',
		answerTitleHtml: '<strong>Field</strong>',
		answerDescriptionHtml: null,
		pathToMedia: null,
		category: 'geographic-terms',
	},
	{
		questionTitleHtml: '<strong>Geography Term</strong>',
		questionDescriptionHtml: 'Long, narrow, deep inlet of the sea between high cliffs, typically formed by glacial erosion<br/><br/><strong>Examples:</strong> Norway\'s',
		answerTitleHtml: '<strong>Fjord</strong>',
		answerDescriptionHtml: null,
		pathToMedia: 'https://upload.wikimedia.org/wikipedia/commons/thumb/7/78/Geirangerfjord_%286-2007%29.jpg/500px-Geirangerfjord_%286-2007%29.jpg',
		category: 'geographic-terms',
	},
	{
		questionTitleHtml: '<strong>Geography Term</strong>',
		questionDescriptionHtml: 'Shallow place in a river or stream where one can cross by wading or drive over with their car',
		answerTitleHtml: '<strong>Ford</strong>',
		answerDescriptionHtml: null,
		pathToMedia: 'https://upload.wikimedia.org/wikipedia/commons/d/d5/Rawney_Ford_%28geograph_4388083%29.jpg',
		category: 'geographic-terms',
	},
	{
		questionTitleHtml: '<strong>Geography Term</strong>',
		questionDescriptionHtml: 'Low hill at the base of a mountain range',
		answerTitleHtml: '<strong>Foothill</strong>',
		answerDescriptionHtml: null,
		pathToMedia: null,
		category: 'geographic-terms',
	},
	{
		questionTitleHtml: '<strong>Geography Term</strong>',
		questionDescriptionHtml: 'Large area covered with trees and undergrowth',
		answerTitleHtml: '<strong>Forest</strong>',
		answerDescriptionHtml: null,
		pathToMedia: null,
		category: 'geographic-terms',
	},
	{
		questionTitleHtml: '<strong>Geography Term</strong>',
		questionDescriptionHtml: 'Hot spring that periodically erupts, throwing water and steam into the air',
		answerTitleHtml: '<strong>Geyser</strong>',
		answerDescriptionHtml: null,
		pathToMedia: null,
		category: 'geographic-terms',
	},
	{
		questionTitleHtml: '<strong>Geography Term</strong>',
		questionDescriptionHtml: 'Slow-moving mass of ice formed from compacted snow<br/><br/><strong>Examples:</strong> Mendenhall (Alaska)',
		answerTitleHtml: '<strong>Glacier</strong>',
		answerDescriptionHtml: null,
		pathToMedia: 'https://upload.wikimedia.org/wikipedia/commons/d/d3/Geikie_Plateau_Glacier.JPG',
		category: 'geographic-terms',
	},
	{
		questionTitleHtml: '<strong>Geography Term</strong>',
		questionDescriptionHtml: 'Spherical model of Earth showing continents and oceans',
		answerTitleHtml: '<strong>Globe</strong>',
		answerDescriptionHtml: null,
		pathToMedia: null,
		category: 'geographic-terms',
	},
	{
		questionTitleHtml: '<strong>Geography Term</strong>',
		questionDescriptionHtml: 'Deep, narrow valley with steep, rocky walls',
		answerTitleHtml: '<strong>Gorge</strong>',
		answerDescriptionHtml: null,
		pathToMedia: null,
		category: 'geographic-terms',
	},
	{
		questionTitleHtml: '<strong>Geography Term</strong>',
		questionDescriptionHtml: 'Network of lines used to locate places on a map, typically latitude and longitude lines',
		answerTitleHtml: '<strong>Grid</strong>',
		answerDescriptionHtml: null,
		pathToMedia: null,
		category: 'geographic-terms',
	},
	{
		questionTitleHtml: '<strong>Geography Term</strong>',
		questionDescriptionHtml: 'Large area of sea or ocean partially enclosed by land, larger than a bay<br/><br/><strong>Examples:</strong> Mexico (south of the U.S.)',
		answerTitleHtml: '<strong>Gulf</strong>',
		answerDescriptionHtml: null,
		pathToMedia: null,
		category: 'geographic-terms',
	},
	{
		questionTitleHtml: '<strong>Geography Term</strong>',
		questionDescriptionHtml: 'Sheltered area of water where ships can anchor safely',
		answerTitleHtml: '<strong>Harbor</strong>',
		answerDescriptionHtml: null,
		pathToMedia: null,
		category: 'geographic-terms',
	},
	{
		questionTitleHtml: '<strong>Geography Term</strong>',
		questionDescriptionHtml: 'Narrow piece of land that projects from a coastline into the sea',
		answerTitleHtml: '<strong>Headland</strong>',
		answerDescriptionHtml: null,
		pathToMedia: 'https://upload.wikimedia.org/wikipedia/commons/0/07/Land%27s_End_-_geograph.org.uk_-_171343.jpg',
		category: 'geographic-terms',
	},
	{
		questionTitleHtml: '<strong>Geography Term</strong>',
		questionDescriptionHtml: 'Half of Earth, divided by the equator (Northern/Southern) or Prime Meridian (Eastern/Western)',
		answerTitleHtml: '<strong>Hemisphere</strong>',
		answerDescriptionHtml: null,
		pathToMedia: null,
		category: 'geographic-terms',
	},
	{
		questionTitleHtml: '<strong>Geography Term</strong>',
		questionDescriptionHtml: 'Main road, especially one connecting major cities',
		answerTitleHtml: '<strong>Highway</strong>',
		answerDescriptionHtml: null,
		pathToMedia: null,
		category: 'geographic-terms',
	},
	{
		questionTitleHtml: '<strong>Geography Term</strong>',
		questionDescriptionHtml: 'Elevated area of land, smaller than a mountain',
		answerTitleHtml: '<strong>Hill</strong>',
		answerDescriptionHtml: null,
		pathToMedia: null,
		category: 'geographic-terms',
	},
	{
		questionTitleHtml: '<strong>Geography Term</strong>',
		questionDescriptionHtml: 'Line where the sky appears to meet the Earth\'s surface',
		answerTitleHtml: '<strong>Horizon</strong>',
		answerDescriptionHtml: null,
		pathToMedia: null,
		category: 'geographic-terms',
	},
	{
		questionTitleHtml: '<strong>Geography Term</strong>',
		questionDescriptionHtml: 'Large floating mass of ice detached from a glacier or ice sheet',
		answerTitleHtml: '<strong>Iceberg</strong>',
		answerDescriptionHtml: null,
		pathToMedia: null,
		category: 'geographic-terms',
	},
	{
		questionTitleHtml: '<strong>Geography Term</strong>',
		questionDescriptionHtml: 'Native to a particular region or environment',
		answerTitleHtml: '<strong>Indigenous</strong>',
		answerDescriptionHtml: null,
		pathToMedia: null,
		category: 'geographic-terms',
	},
	{
		questionTitleHtml: '<strong>Geography Term</strong>',
		questionDescriptionHtml: 'Long and narrow indentation of a shoreline such as a small arm, cove, bay, sound, fjord, lagoon or marsh,[1] that leads to an enclosed larger body of water such as a lake, estuary, gulf or marginal sea.',
		answerTitleHtml: '<strong>Inlet</strong>',
		answerDescriptionHtml: null,
		pathToMedia: null,
		category: 'geographic-terms',
	},
	{
		questionTitleHtml: '<strong>Geography Term</strong>',
		questionDescriptionHtml: 'Imaginary line of longitude approximately 180° east or west of the Prime Meridian, where the date changes',
		answerTitleHtml: '<strong>International Date Line</strong>',
		answerDescriptionHtml: null,
		pathToMedia: null,
		category: 'geographic-terms',
	},
	{
		questionTitleHtml: '<strong>Geography Term</strong>',
		questionDescriptionHtml: 'Highway system connecting states, especially in the United States',
		answerTitleHtml: '<strong>Interstate</strong>',
		answerDescriptionHtml: null,
		pathToMedia: null,
		category: 'geographic-terms',
	},
	{
		questionTitleHtml: '<strong>Geography Term</strong>',
		questionDescriptionHtml: 'Agricultural land supplied with water through artificial means',
		answerTitleHtml: '<strong>Irrigated Land</strong>',
		answerDescriptionHtml: null,
		pathToMedia: null,
		category: 'geographic-terms',
	},
	{
		questionTitleHtml: '<strong>Geography Term</strong>',
		questionDescriptionHtml: 'Piece of land completely surrounded by water',
		answerTitleHtml: '<strong>Island</strong>',
		answerDescriptionHtml: null,
		pathToMedia: null,
		category: 'geographic-terms',
	},
	{
		questionTitleHtml: '<strong>Geography Term</strong>',
		questionDescriptionHtml: 'Narrow strip of land connecting two larger land areas<br/><br/><strong>Examples:</strong> Panama land bridge',
		answerTitleHtml: '<strong>Isthmus</strong>',
		answerDescriptionHtml: null,
		pathToMedia: 'https://upload.wikimedia.org/wikipedia/commons/thumb/4/4d/The_Neck_Bruny_Island.jpg/960px-The_Neck_Bruny_Island.jpg',
		category: 'geographic-terms',
	},
	{
		questionTitleHtml: '<strong>Geography Term</strong>',
		questionDescriptionHtml: 'Point where roads, rivers, or railway lines meet',
		answerTitleHtml: '<strong>Junction</strong>',
		answerDescriptionHtml: null,
		pathToMedia: null,
		category: 'geographic-terms',
	},
	{
		questionTitleHtml: '<strong>Geography Term</strong>',
		questionDescriptionHtml: 'Explanation of symbols and colors used on a map',
		answerTitleHtml: '<strong>Key (Map)</strong>',
		answerDescriptionHtml: null,
		pathToMedia: null,
		category: 'geographic-terms',
	},
	{
		questionTitleHtml: '<strong>Geography Term</strong>',
		questionDescriptionHtml: 'Shallow body of water separated from a larger body of water by barrier islands or reefs<br/><br/><strong>Examples:</strong> Venice (Italy)',
		answerTitleHtml: '<strong>Lagoon</strong>',
		answerDescriptionHtml: null,
		pathToMedia: 'https://upload.wikimedia.org/wikipedia/commons/thumb/b/bf/Venice_Lagoon_December_9_2001.jpg/1280px-Venice_Lagoon_December_9_2001.jpg',
		category: 'geographic-terms',
	},
	{
		questionTitleHtml: '<strong>Geography Term</strong>',
		questionDescriptionHtml: 'Large body of water surrounded by land<br/><br/><strong>Examples:</strong> Michigan; Superior',
		answerTitleHtml: '<strong>Lake</strong>',
		answerDescriptionHtml: null,
		pathToMedia: null,
		category: 'geographic-terms',
	},
	{
		questionTitleHtml: '<strong>Geography Term</strong>',
		questionDescriptionHtml: 'Distance north or south of the equator, measured in degrees',
		answerTitleHtml: '<strong>Latitude</strong>',
		answerDescriptionHtml: null,
		pathToMedia: null,
		category: 'geographic-terms',
	},
	{
		questionTitleHtml: '<strong>Geography Term</strong>',
		questionDescriptionHtml: 'Explanation of symbols and colors used on a map',
		answerTitleHtml: '<strong>Legend (Map)</strong>',
		answerDescriptionHtml: null,
		pathToMedia: null,
		category: 'geographic-terms',
	},
	{
		questionTitleHtml: '<strong>Geography Term</strong>',
		questionDescriptionHtml: 'Embankment built to prevent the overflow of a river',
		answerTitleHtml: '<strong>Levee</strong>',
		answerDescriptionHtml: null,
		pathToMedia: 'https://upload.wikimedia.org/wikipedia/commons/thumb/5/5f/GretnaLevee.jpg/1920px-GretnaLevee.jpg',
		category: 'geographic-terms',
	},
	{
		questionTitleHtml: '<strong>Geography Term</strong>',
		questionDescriptionHtml: 'Enclosed sections of a canal or river with gates to raise or lower water levels for navigation<br/><br/><strong>Examples:</strong> Panana Canal',
		answerTitleHtml: '<strong>Locks</strong>',
		answerDescriptionHtml: null,
		pathToMedia: 'https://upload.wikimedia.org/wikipedia/commons/f/f7/Panama_Canal_Gatun_Locks.jpg',
		category: 'geographic-terms',
	},
	{
		questionTitleHtml: '<strong>Geography Term</strong>',
		questionDescriptionHtml: 'Distance east or west of the Prime Meridian, measured in degrees',
		answerTitleHtml: '<strong>Longitude</strong>',
		answerDescriptionHtml: null,
		pathToMedia: null,
		category: 'geographic-terms',
	},
	{
		questionTitleHtml: '<strong>Geography Term</strong>',
		questionDescriptionHtml: 'Representation of Earth\'s surface or part of it, drawn to scale',
		answerTitleHtml: '<strong>Map</strong>',
		answerDescriptionHtml: null,
		pathToMedia: null,
		category: 'geographic-terms',
	},
	{
		questionTitleHtml: '<strong>Geography Term</strong>',
		questionDescriptionHtml: 'Wetland area with grasses and reeds, often flooded',
		answerTitleHtml: '<strong>Marsh</strong>',
		answerDescriptionHtml: null,
		pathToMedia: null,
		category: 'geographic-terms',
	},
	{
		questionTitleHtml: '<strong>Geography Term</strong>',
		questionDescriptionHtml: 'Field of grass or wildflowers, often used for grazing',
		answerTitleHtml: '<strong>Meadow</strong>',
		answerDescriptionHtml: null,
		pathToMedia: null,
		category: 'geographic-terms',
	},
	{
		questionTitleHtml: '<strong>Geography Term</strong>',
		questionDescriptionHtml: 'Flat-topped hill with steep sides, larger than a butte',
		answerTitleHtml: '<strong>Mesa</strong>',
		answerDescriptionHtml: null,
		pathToMedia: 'https://upload.wikimedia.org/wikipedia/commons/thumb/9/9b/Over_Monument_Valley%2C_Navajo_Nation.jpg/1920px-Over_Monument_Valley%2C_Navajo_Nation.jpg',
		category: 'geographic-terms',
	},
	{
		questionTitleHtml: '<strong>Geography Term</strong>',
		questionDescriptionHtml: 'Excavation in the Earth from which minerals or other materials are extracted',
		answerTitleHtml: '<strong>Mine</strong>',
		answerDescriptionHtml: null,
		pathToMedia: null,
		category: 'geographic-terms',
	},
	{
		questionTitleHtml: '<strong>Geography Term</strong>',
		questionDescriptionHtml: 'High, elevated landform rising prominently above surrounding land',
		answerTitleHtml: '<strong>Mountain</strong>',
		answerDescriptionHtml: null,
		pathToMedia: null,
		category: 'geographic-terms',
	},
	{
		questionTitleHtml: '<strong>Geography Term</strong>',
		questionDescriptionHtml: 'Point where a river flows into a larger body of water',
		answerTitleHtml: '<strong>Mouth, River</strong>',
		answerDescriptionHtml: null,
		pathToMedia: null,
		category: 'geographic-terms',
	},
	{
		questionTitleHtml: '<strong>Geography Term</strong>',
		questionDescriptionHtml: 'Existing in or formed by nature, not artificial',
		answerTitleHtml: '<strong>Natural</strong>',
		answerDescriptionHtml: null,
		pathToMedia: null,
		category: 'geographic-terms',
	},
	{
		questionTitleHtml: '<strong>Geography Term</strong>',
		questionDescriptionHtml: 'Northernmost point on Earth, located at 90° north latitude',
		answerTitleHtml: '<strong>North Pole</strong>',
		answerDescriptionHtml: null,
		pathToMedia: null,
		category: 'geographic-terms',
	},
	{
		questionTitleHtml: '<strong>Geography Term</strong>',
		questionDescriptionHtml: 'Fertile area in a desert with water and vegetation',
		answerTitleHtml: '<strong>Oasis</strong>',
		answerDescriptionHtml: null,
		pathToMedia: null,
		category: 'geographic-terms',
	},
	{
		questionTitleHtml: '<strong>Geography Term</strong>',
		questionDescriptionHtml: 'Vast body of saltwater covering most of Earth\'s surface',
		answerTitleHtml: '<strong>Ocean</strong>',
		answerDescriptionHtml: null,
		pathToMedia: null,
		category: 'geographic-terms',
	},
	{
		questionTitleHtml: '<strong>Geography Term</strong>',
		questionDescriptionHtml: 'Supercontinent that existed during the late Paleozoic and early Mesozoic eras',
		answerTitleHtml: '<strong>Pangaea</strong>',
		answerDescriptionHtml: null,
		pathToMedia: null,
		category: 'geographic-terms',
	},
	{
		questionTitleHtml: '<strong>Geography Term</strong>',
		questionDescriptionHtml: 'Circle of latitude on Earth that runs east–west, the same distance from the equator',
		answerTitleHtml: '<strong>Parallel</strong>',
		answerDescriptionHtml: null,
		pathToMedia: null,
		category: 'geographic-terms',
	},
	{
		questionTitleHtml: '<strong>Geography Term</strong>',
		questionDescriptionHtml: 'Route through a mountain range or gap between hills',
		answerTitleHtml: '<strong>Pass</strong>',
		answerDescriptionHtml: null,
		pathToMedia: null,
		category: 'geographic-terms',
	},
	{
		questionTitleHtml: '<strong>Geography Term</strong>',
		questionDescriptionHtml: 'Highest point of a mountain or hill',
		answerTitleHtml: '<strong>Peak</strong>',
		answerDescriptionHtml: null,
		pathToMedia: null,
		category: 'geographic-terms',
	},
	{
		questionTitleHtml: '<strong>Geography Term</strong>',
		questionDescriptionHtml: 'Piece of land almost surrounded by water or projecting into a body of water<br/><br/><strong>Examples:</strong> Florida; Italy',
		answerTitleHtml: '<strong>Peninsula</strong>',
		answerDescriptionHtml: null,
		pathToMedia: 'https://upload.wikimedia.org/wikipedia/commons/thumb/9/9a/SeventeenSeventyNov082024_01.jpg/1920px-SeventeenSeventyNov082024_01.jpg',
		category: 'geographic-terms',
	},
	{
		questionTitleHtml: '<strong>Geography Term</strong>',
		questionDescriptionHtml: 'Map showing natural features such as mountains, rivers, and landforms',
		answerTitleHtml: '<strong>Physical Map</strong>',
		answerDescriptionHtml: null,
		pathToMedia: null,
		category: 'geographic-terms',
	},
	{
		questionTitleHtml: '<strong>Geography Term</strong>',
		questionDescriptionHtml: 'Gentle slope leading from the base of mountains to a region of flat land',
		answerTitleHtml: '<strong>Piedmont</strong>',
		answerDescriptionHtml: null,
		pathToMedia: 'https://i0.wp.com/rei-ink.com/wp-content/uploads/2022/07/Piedmont.jpg?fit=700%2C408&ssl=1',
		category: 'geographic-terms',
	},
	{
		questionTitleHtml: '<strong>Geography Term</strong>',
		questionDescriptionHtml: 'Large area of flat or gently rolling land<br/><br/><strong>Examples:</strong> central U.S. grasslands; the Pampas (Argentina)',
		answerTitleHtml: '<strong>Plain</strong>',
		answerDescriptionHtml: null,
		pathToMedia: null,
		category: 'geographic-terms',
	},
	{
		questionTitleHtml: '<strong>Geography Term</strong>',
		questionDescriptionHtml: 'Theory that Earth\'s outer shell is divided into several plates that glide over the mantle',
		answerTitleHtml: '<strong>Plate Tectonics</strong>',
		answerDescriptionHtml: null,
		pathToMedia: null,
		category: 'geographic-terms',
	},
	{
		questionTitleHtml: '<strong>Geography Term</strong>',
		questionDescriptionHtml: 'Elevated flat area of land, higher than surrounding land<br/><br/><strong>Examples:</strong> Colorado (Four Corners region); Tibet',
		answerTitleHtml: '<strong>Plateau</strong>',
		answerDescriptionHtml: null,
		pathToMedia: 'https://upload.wikimedia.org/wikipedia/commons/5/5c/Pajarito_Plateau.jpg',
		category: 'geographic-terms',
	},
	{
		questionTitleHtml: '<strong>Geography Term</strong>',
		questionDescriptionHtml: 'Map showing boundaries of countries, states, and cities',
		answerTitleHtml: '<strong>Political Map</strong>',
		answerDescriptionHtml: null,
		pathToMedia: null,
		category: 'geographic-terms',
	},
	{
		questionTitleHtml: '<strong>Geography Term</strong>',
		questionDescriptionHtml: 'Small body of still water, smaller than a lake',
		answerTitleHtml: '<strong>Pond</strong>',
		answerDescriptionHtml: null,
		pathToMedia: null,
		category: 'geographic-terms',
	},
	{
		questionTitleHtml: '<strong>Geography Term</strong>',
		questionDescriptionHtml: 'Facility that generates electricity',
		answerTitleHtml: '<strong>Power Plant</strong>',
		answerDescriptionHtml: null,
		pathToMedia: null,
		category: 'geographic-terms',
	},
	{
		questionTitleHtml: '<strong>Geography Term</strong>',
		questionDescriptionHtml: 'Large area of flat or rolling grassland, especially in North America',
		answerTitleHtml: '<strong>Prairie</strong>',
		answerDescriptionHtml: null,
		pathToMedia: null,
		category: 'geographic-terms',
	},
	{
		questionTitleHtml: '<strong>Geography Term</strong>',
		questionDescriptionHtml: 'Very steep or overhanging place on a rock face or cliff',
		answerTitleHtml: '<strong>Precipice</strong>',
		answerDescriptionHtml: null,
		pathToMedia: null,
		category: 'geographic-terms',
	},
	{
		questionTitleHtml: '<strong>Geography Term</strong>',
		questionDescriptionHtml: 'Method of representing the curved surface of Earth on a flat map',
		answerTitleHtml: '<strong>Projection</strong>',
		answerDescriptionHtml: null,
		pathToMedia: null,
		category: 'geographic-terms',
	},
	{
		questionTitleHtml: '<strong>Geography Term</strong>',
		questionDescriptionHtml: 'Track or system of tracks for trains',
		answerTitleHtml: '<strong>Railroad</strong>',
		answerDescriptionHtml: null,
		pathToMedia: null,
		category: 'geographic-terms',
	},
	{
		questionTitleHtml: '<strong>Geography Term</strong>',
		questionDescriptionHtml: 'Series of mountains or hills in a line',
		answerTitleHtml: '<strong>Range</strong>',
		answerDescriptionHtml: null,
		pathToMedia: null,
		category: 'geographic-terms',
	},
	{
		questionTitleHtml: '<strong>Geography Term</strong>',
		questionDescriptionHtml: 'Fast-flowing, turbulent section of a river with rocks and shallow water',
		answerTitleHtml: '<strong>Rapids</strong>',
		answerDescriptionHtml: null,
		pathToMedia: null,
		category: 'geographic-terms',
	},
	{
		questionTitleHtml: '<strong>Geography Term</strong>',
		questionDescriptionHtml: 'Ridge of rock, sand, or coral near the surface of water<br/><br/><strong>Examples:</strong> Great Barrier (Australia)',
		answerTitleHtml: '<strong>Reef</strong>',
		answerDescriptionHtml: null,
		pathToMedia: null,
		category: 'geographic-terms',
	},
	{
		questionTitleHtml: '<strong>Geography Term</strong>',
		questionDescriptionHtml: 'Artificial lake used to store water, often created by damming a river',
		answerTitleHtml: '<strong>Reservoir</strong>',
		answerDescriptionHtml: null,
		pathToMedia: null,
		category: 'geographic-terms',
	},
	{
		questionTitleHtml: '<strong>Geography Term</strong>',
		questionDescriptionHtml: 'Natural materials or features that can be used by people',
		answerTitleHtml: '<strong>Resources</strong>',
		answerDescriptionHtml: null,
		pathToMedia: null,
		category: 'geographic-terms',
	},
	{
		questionTitleHtml: '<strong>Geography Term</strong>',
		questionDescriptionHtml: 'Long, narrow elevation of land',
		answerTitleHtml: '<strong>Ridge</strong>',
		answerDescriptionHtml: null,
		pathToMedia: null,
		category: 'geographic-terms',
	},
	{
		questionTitleHtml: '<strong>Geography Term</strong>',
		questionDescriptionHtml: 'Large natural stream of water flowing in a channel to the sea, a lake, or another stream<br/><br/><strong>Examples:</strong> Mississippi; Nile',
		answerTitleHtml: '<strong>River</strong>',
		answerDescriptionHtml: null,
		pathToMedia: null,
		category: 'geographic-terms',
	},
	{
		questionTitleHtml: '<strong>Geography Term</strong>',
		questionDescriptionHtml: 'Wide way leading from one place to another, especially for vehicles',
		answerTitleHtml: '<strong>Road</strong>',
		answerDescriptionHtml: null,
		pathToMedia: null,
		category: 'geographic-terms',
	},
	{
		questionTitleHtml: '<strong>Geography Term</strong>',
		questionDescriptionHtml: 'Map showing roads and highways for navigation',
		answerTitleHtml: '<strong>Road Map</strong>',
		answerDescriptionHtml: null,
		pathToMedia: null,
		category: 'geographic-terms',
	},
	{
		questionTitleHtml: '<strong>Geography Term</strong>',
		questionDescriptionHtml: 'Relating to the countryside, as opposed to urban areas',
		answerTitleHtml: '<strong>Rural</strong>',
		answerDescriptionHtml: null,
		pathToMedia: null,
		category: 'geographic-terms',
	},
	{
		questionTitleHtml: '<strong>Geography Term</strong>',
		questionDescriptionHtml: 'Ridge of sand built up by currents in a river or along a shore',
		answerTitleHtml: '<strong>Sandbar</strong>',
		answerDescriptionHtml: null,
		pathToMedia: 'https://www.boatsetter.com/boating-resources/wp-content/uploads/2023/02/what-is-a-sandbar-party-1120x580.jpg.webp',
		category: 'geographic-terms',
	},
	{
		questionTitleHtml: '<strong>Geography Term</strong>',
		questionDescriptionHtml: 'Mound or ridge of sand formed by wind',
		answerTitleHtml: '<strong>Sand Dune</strong>',
		answerDescriptionHtml: null,
		pathToMedia: null,
		category: 'geographic-terms',
	},
	{
		questionTitleHtml: '<strong>Geography Term</strong>',
		questionDescriptionHtml: 'Grassy plain in tropical and subtropical regions, with few trees',
		answerTitleHtml: '<strong>Savanna</strong>',
		answerDescriptionHtml: null,
		pathToMedia: null,
		category: 'geographic-terms',
	},
	{
		questionTitleHtml: '<strong>Geography Term</strong>',
		questionDescriptionHtml: 'Ratio between distances on a map and actual distances on Earth',
		answerTitleHtml: '<strong>Scale</strong>',
		answerDescriptionHtml: null,
		pathToMedia: null,
		category: 'geographic-terms',
	},
	{
		questionTitleHtml: '<strong>Geography Term</strong>',
		questionDescriptionHtml: 'Large body of saltwater, smaller than an ocean',
		answerTitleHtml: '<strong>Sea</strong>',
		answerDescriptionHtml: null,
		pathToMedia: null,
		category: 'geographic-terms',
	},
	{
		questionTitleHtml: '<strong>Geography Term</strong>',
		questionDescriptionHtml: 'Average level of the ocean\'s surface, used as a reference for measuring elevation',
		answerTitleHtml: '<strong>Sea Level</strong>',
		answerDescriptionHtml: null,
		pathToMedia: null,
		category: 'geographic-terms',
	},
	{
		questionTitleHtml: '<strong>Geography Term</strong>',
		questionDescriptionHtml: 'Town or city with a harbor where ships load and unload',
		answerTitleHtml: '<strong>Seaport</strong>',
		answerDescriptionHtml: null,
		pathToMedia: null,
		category: 'geographic-terms',
	},
	{
		questionTitleHtml: '<strong>Geography Term</strong>',
		questionDescriptionHtml: 'Shallow place in a body of water, such as a sandbank or sandbar',
		answerTitleHtml: '<strong>Shoal</strong>',
		answerDescriptionHtml: null,
		pathToMedia: 'https://upload.wikimedia.org/wikipedia/commons/thumb/6/66/WayaWayasewa.jpg/960px-WayaWayasewa.jpg',
		category: 'geographic-terms',
	},
	{
		questionTitleHtml: '<strong>Geography Term</strong>',
		questionDescriptionHtml: 'Line where land meets a body of water',
		answerTitleHtml: '<strong>Shoreline</strong>',
		answerDescriptionHtml: null,
		pathToMedia: null,
		category: 'geographic-terms',
	},
	{
		questionTitleHtml: '<strong>Geography Term</strong>',
		questionDescriptionHtml: 'Inclined surface or side of a hill or mountain',
		answerTitleHtml: '<strong>Slope</strong>',
		answerDescriptionHtml: null,
		pathToMedia: null,
		category: 'geographic-terms',
	},
	{
		questionTitleHtml: '<strong>Geography Term</strong>',
		questionDescriptionHtml: 'Elevation above which snow remains year-round',
		answerTitleHtml: '<strong>Snowline</strong>',
		answerDescriptionHtml: null,
		pathToMedia: 'https://upload.wikimedia.org/wikipedia/commons/2/20/Cotopaxi_volcano_2008-06-27T1322.jpg',
		category: 'geographic-terms',
	},
	{
		questionTitleHtml: '<strong>Geography Term</strong>',
		questionDescriptionHtml: 'Large sea or ocean inlet larger than a bay, deeper than a bight, and wider than a fjord',
		answerTitleHtml: '<strong>Sound</strong>',
		answerDescriptionHtml: null,
		pathToMedia: null,
		category: 'geographic-terms',
	},
	{
		questionTitleHtml: '<strong>Geography Term</strong>',
		questionDescriptionHtml: 'Starting point of a river or stream',
		answerTitleHtml: '<strong>Source</strong>',
		answerDescriptionHtml: null,
		pathToMedia: null,
		category: 'geographic-terms',
	},
	{
		questionTitleHtml: '<strong>Geography Term</strong>',
		questionDescriptionHtml: 'Southernmost point on Earth, located at 90° south latitude',
		answerTitleHtml: '<strong>South Pole</strong>',
		answerDescriptionHtml: null,
		pathToMedia: null,
		category: 'geographic-terms',
	},
	{
		questionTitleHtml: '<strong>Geography Term</strong>',
		questionDescriptionHtml: 'Narrow point of land extending into a body of water',
		answerTitleHtml: '<strong>Spit</strong>',
		answerDescriptionHtml: null,
		pathToMedia: 'https://upload.wikimedia.org/wikipedia/commons/thumb/4/48/Accreting_coast_Image6.svg/3840px-Accreting_coast_Image6.svg.png',
		category: 'geographic-terms',
	},
	{
		questionTitleHtml: '<strong>Geography Term</strong>',
		questionDescriptionHtml: 'Large area of flat unforested grassland in southeastern Europe or Siberia',
		answerTitleHtml: '<strong>Steppe</strong>',
		answerDescriptionHtml: null,
		pathToMedia: 'https://upload.wikimedia.org/wikipedia/commons/thumb/7/79/Eurasian_steppe_belt.jpg/1920px-Eurasian_steppe_belt.jpg',
		category: 'geographic-terms',
	},
	{
		questionTitleHtml: '<strong>Geography Term</strong>',
		questionDescriptionHtml: 'Narrow passage of water connecting two larger bodies of water<br/><br/><strong>Examples:</strong> Golden Gate; Gibraltar',
		answerTitleHtml: '<strong>Strait</strong>',
		answerDescriptionHtml: null,
		pathToMedia: 'https://upload.wikimedia.org/wikipedia/commons/thumb/e/e8/STS059-238-074_Strait_of_Gibraltar.jpg/1280px-STS059-238-074_Strait_of_Gibraltar.jpg',
		category: 'geographic-terms',
	},
	{
		questionTitleHtml: '<strong>Geography Term</strong>',
		questionDescriptionHtml: 'Wetland area dominated by trees and shrubs',
		answerTitleHtml: '<strong>Swamp</strong>',
		answerDescriptionHtml: null,
		pathToMedia: null,
		category: 'geographic-terms',
	},
	{
		questionTitleHtml: '<strong>Geography Term</strong>',
		questionDescriptionHtml: 'Wood prepared for use in construction or other purposes',
		answerTitleHtml: '<strong>Timber</strong>',
		answerDescriptionHtml: null,
		pathToMedia: null,
		category: 'geographic-terms',
	},
	{
		questionTitleHtml: '<strong>Geography Term</strong>',
		questionDescriptionHtml: 'Elevation above which trees cannot grow due to harsh conditions',
		answerTitleHtml: '<strong>Timberline</strong>',
		answerDescriptionHtml: null,
		pathToMedia: null,
		category: 'geographic-terms',
	},
	{
		questionTitleHtml: '<strong>Geography Term</strong>',
		questionDescriptionHtml: 'Map that shows the shape and elevation of the land surface using contour lines',
		answerTitleHtml: '<strong>Topographical Map</strong>',
		answerDescriptionHtml: null,
		pathToMedia: null,
		category: 'geographic-terms',
	},
	{
		questionTitleHtml: '<strong>Geography Term</strong>',
		questionDescriptionHtml: 'Arrangement of the natural and artificial physical features of an area',
		answerTitleHtml: '<strong>Topography</strong>',
		answerDescriptionHtml: null,
		pathToMedia: null,
		category: 'geographic-terms',
	},
	{
		questionTitleHtml: '<strong>Geography Term</strong>',
		questionDescriptionHtml: 'Settlement larger than a village but smaller than a city',
		answerTitleHtml: '<strong>Town</strong>',
		answerDescriptionHtml: null,
		pathToMedia: null,
		category: 'geographic-terms',
	},
	{
		questionTitleHtml: '<strong>Geography Term</strong>',
		questionDescriptionHtml: 'River or stream flowing into a larger river or lake',
		answerTitleHtml: '<strong>Tributary</strong>',
		answerDescriptionHtml: null,
		pathToMedia: null,
		category: 'geographic-terms',
	},
	{
		questionTitleHtml: '<strong>Geography Term</strong>',
		questionDescriptionHtml: 'Either of two circles of latitude: Cancer and Capricorn',
		answerTitleHtml: '<strong>Tropic</strong>',
		answerDescriptionHtml: null,
		pathToMedia: null,
		category: 'geographic-terms',
	},
	{
		questionTitleHtml: '<strong>Geography Term</strong>',
		questionDescriptionHtml: 'Vast, flat, treeless Arctic region in which the subsoil is permanently frozen',
		answerTitleHtml: '<strong>Tundra</strong>',
		answerDescriptionHtml: null,
		pathToMedia: null,
		category: 'geographic-terms',
	},
	{
		questionTitleHtml: '<strong>Geography Term</strong>',
		questionDescriptionHtml: 'Underground passage through a hill or mountain',
		answerTitleHtml: '<strong>Tunnel</strong>',
		answerDescriptionHtml: null,
		pathToMedia: null,
		category: 'geographic-terms',
	},
	{
		questionTitleHtml: '<strong>Geography Term</strong>',
		questionDescriptionHtml: 'Relating to cities or towns, as opposed to rural areas',
		answerTitleHtml: '<strong>Urban</strong>',
		answerDescriptionHtml: null,
		pathToMedia: null,
		category: 'geographic-terms',
	},
	{
		questionTitleHtml: '<strong>Geography Term</strong>',
		questionDescriptionHtml: 'Direction toward the source of a river, opposite of downstream',
		answerTitleHtml: '<strong>Upstream</strong>',
		answerDescriptionHtml: null,
		pathToMedia: null,
		category: 'geographic-terms',
	},
	{
		questionTitleHtml: '<strong>Geography Term</strong>',
		questionDescriptionHtml: 'Low area between hills or mountains, often with a river flowing through it',
		answerTitleHtml: '<strong>Valley</strong>',
		answerDescriptionHtml: null,
		pathToMedia: null,
		category: 'geographic-terms',
	},
	{
		questionTitleHtml: '<strong>Geography Term</strong>',
		questionDescriptionHtml: 'Small settlement, typically smaller than a town',
		answerTitleHtml: '<strong>Village</strong>',
		answerDescriptionHtml: null,
		pathToMedia: null,
		category: 'geographic-terms',
	},
	{
		questionTitleHtml: '<strong>Geography Term</strong>',
		questionDescriptionHtml: 'Area or ridge of land that separates waters flowing to different rivers, basins, or seas',
		answerTitleHtml: '<strong>Watershed</strong>',
		answerDescriptionHtml: null,
		pathToMedia: null,
		category: 'geographic-terms',
	},
	{
		questionTitleHtml: '<strong>Geography Term</strong>',
		questionDescriptionHtml: 'Area of land that is saturated with water, such as a marsh or swamp',
		answerTitleHtml: '<strong>Wetland</strong>',
		answerDescriptionHtml: null,
		pathToMedia: null,
		category: 'geographic-terms',
	},
]