import type { FlashCard } from '@/types'

export const us_state_capitals: FlashCard[] = [
	{
		questionTitleHtml: 'Capital of <strong>Alabama</strong>',
		questionDescriptionHtml: null,
		answerTitleHtml: '<strong>Montgomery</strong>',
		answerDescriptionHtml: null,
		pathToMedia: null,
		category: 'us-state-capitals',
	},
	{
		questionTitleHtml: 'Capital of <strong>Alaska</strong>',
		questionDescriptionHtml: null,
		answerTitleHtml: '<strong>Juneau</strong>',
		answerDescriptionHtml: null,
		pathToMedia: null,
		category: 'us-state-capitals',
	},
	{
		questionTitleHtml: 'Capital of <strong>Arizona</strong>',
		questionDescriptionHtml: null,
		answerTitleHtml: '<strong>Phoenix</strong>',
		answerDescriptionHtml: null,
		pathToMedia: null,
		category: 'us-state-capitals',
	},
	{
		questionTitleHtml: 'Capital of <strong>Arkansas</strong>',
		questionDescriptionHtml: null,
		answerTitleHtml: '<strong>Little Rock</strong>',
		answerDescriptionHtml: null,
		pathToMedia: null,
		category: 'us-state-capitals',
	},
	{
		questionTitleHtml: 'Capital of <strong>California</strong>',
		questionDescriptionHtml: null,
		answerTitleHtml: '<strong>Sacramento</strong>',
		answerDescriptionHtml: null,
		pathToMedia: null,
		category: 'us-state-capitals',
	},
	{
		questionTitleHtml: 'Capital of <strong>Colorado</strong>',
		questionDescriptionHtml: null,
		answerTitleHtml: '<strong>Denver</strong>',
		answerDescriptionHtml: null,
		pathToMedia: null,
		category: 'us-state-capitals',
	},
	{
		questionTitleHtml: 'Capital of <strong>Connecticut</strong>',
		questionDescriptionHtml: null,
		answerTitleHtml: '<strong>Hartford</strong>',
		answerDescriptionHtml: null,
		pathToMedia: null,
		category: 'us-state-capitals',
	},
	{
		questionTitleHtml: 'Capital of <strong>Delaware</strong>',
		questionDescriptionHtml: null,
		answerTitleHtml: '<strong>Dover</strong>',
		answerDescriptionHtml: null,
		pathToMedia: null,
		category: 'us-state-capitals',
	},
	{
		questionTitleHtml: 'Capital of <strong>Florida</strong>',
		questionDescriptionHtml: null,
		answerTitleHtml: '<strong>Tallahassee</strong>',
		answerDescriptionHtml: null,
		pathToMedia: null,
		category: 'us-state-capitals',
	},
	{
		questionTitleHtml: 'Capital of <strong>Georgia</strong>',
		questionDescriptionHtml: null,
		answerTitleHtml: '<strong>Atlanta</strong>',
		answerDescriptionHtml: null,
		pathToMedia: null,
		category: 'us-state-capitals',
	},
	{
		questionTitleHtml: 'Capital of <strong>Hawaii</strong>',
		questionDescriptionHtml: null,
		answerTitleHtml: '<strong>Honolulu</strong>',
		answerDescriptionHtml: null,
		pathToMedia: null,
		category: 'us-state-capitals',
	},
	{
		questionTitleHtml: 'Capital of <strong>Idaho</strong>',
		questionDescriptionHtml: null,
		answerTitleHtml: '<strong>Boise</strong>',
		answerDescriptionHtml: null,
		pathToMedia: null,
		category: 'us-state-capitals',
	},
	{
		questionTitleHtml: 'Capital of <strong>Illinois</strong>',
		questionDescriptionHtml: null,
		answerTitleHtml: '<strong>Springfield</strong>',
		answerDescriptionHtml: null,
		pathToMedia: null,
		category: 'us-state-capitals',
	},
	{
		questionTitleHtml: 'Capital of <strong>Indiana</strong>',
		questionDescriptionHtml: null,
		answerTitleHtml: '<strong>Indianapolis</strong>',
		answerDescriptionHtml: null,
		pathToMedia: null,
		category: 'us-state-capitals',
	},
	{
		questionTitleHtml: 'Capital of <strong>Iowa</strong>',
		questionDescriptionHtml: null,
		answerTitleHtml: '<strong>Des Moines</strong>',
		answerDescriptionHtml: null,
		pathToMedia: null,
		category: 'us-state-capitals',
	},
	{
		questionTitleHtml: 'Capital of <strong>Kansas</strong>',
		questionDescriptionHtml: null,
		answerTitleHtml: '<strong>Topeka</strong>',
		answerDescriptionHtml: null,
		pathToMedia: null,
		category: 'us-state-capitals',
	},
	{
		questionTitleHtml: 'Capital of <strong>Kentucky</strong>',
		questionDescriptionHtml: null,
		answerTitleHtml: '<strong>Frankfort</strong>',
		answerDescriptionHtml: null,
		pathToMedia: null,
		category: 'us-state-capitals',
	},
	{
		questionTitleHtml: 'Capital of <strong>Louisiana</strong>',
		questionDescriptionHtml: null,
		answerTitleHtml: '<strong>Baton Rouge</strong>',
		answerDescriptionHtml: null,
		pathToMedia: null,
		category: 'us-state-capitals',
	},
	{
		questionTitleHtml: 'Capital of <strong>Maine</strong>',
		questionDescriptionHtml: null,
		answerTitleHtml: '<strong>Augusta</strong>',
		answerDescriptionHtml: null,
		pathToMedia: null,
		category: 'us-state-capitals',
	},
	{
		questionTitleHtml: 'Capital of <strong>Maryland</strong>',
		questionDescriptionHtml: null,
		answerTitleHtml: '<strong>Annapolis</strong>',
		answerDescriptionHtml: null,
		pathToMedia: null,
		category: 'us-state-capitals',
	},
	{
		questionTitleHtml: 'Capital of <strong>Massachusetts</strong>',
		questionDescriptionHtml: null,
		answerTitleHtml: '<strong>Boston</strong>',
		answerDescriptionHtml: null,
		pathToMedia: null,
		category: 'us-state-capitals',
	},
	{
		questionTitleHtml: 'Capital of <strong>Michigan</strong>',
		questionDescriptionHtml: null,
		answerTitleHtml: '<strong>Lansing</strong>',
		answerDescriptionHtml: null,
		pathToMedia: null,
		category: 'us-state-capitals',
	},
	{
		questionTitleHtml: 'Capital of <strong>Minnesota</strong>',
		questionDescriptionHtml: null,
		answerTitleHtml: '<strong>St. Paul</strong>',
		answerDescriptionHtml: null,
		pathToMedia: null,
		category: 'us-state-capitals',
	},
	{
		questionTitleHtml: 'Capital of <strong>Mississippi</strong>',
		questionDescriptionHtml: null,
		answerTitleHtml: '<strong>Jackson</strong>',
		answerDescriptionHtml: null,
		pathToMedia: null,
		category: 'us-state-capitals',
	},
	{
		questionTitleHtml: 'Capital of <strong>Missouri</strong>',
		questionDescriptionHtml: null,
		answerTitleHtml: '<strong>Jefferson City</strong>',
		answerDescriptionHtml: null,
		pathToMedia: null,
		category: 'us-state-capitals',
	},
	{
		questionTitleHtml: 'Capital of <strong>Montana</strong>',
		questionDescriptionHtml: null,
		answerTitleHtml: '<strong>Helena</strong>',
		answerDescriptionHtml: null,
		pathToMedia: null,
		category: 'us-state-capitals',
	},
	{
		questionTitleHtml: 'Capital of <strong>Nebraska</strong>',
		questionDescriptionHtml: null,
		answerTitleHtml: '<strong>Lincoln</strong>',
		answerDescriptionHtml: null,
		pathToMedia: null,
		category: 'us-state-capitals',
	},
	{
		questionTitleHtml: 'Capital of <strong>Nevada</strong>',
		questionDescriptionHtml: null,
		answerTitleHtml: '<strong>Carson City</strong>',
		answerDescriptionHtml: null,
		pathToMedia: null,
		category: 'us-state-capitals',
	},
	{
		questionTitleHtml: 'Capital of <strong>New Hampshire</strong>',
		questionDescriptionHtml: null,
		answerTitleHtml: '<strong>Concord</strong>',
		answerDescriptionHtml: null,
		pathToMedia: null,
		category: 'us-state-capitals',
	},
	{
		questionTitleHtml: 'Capital of <strong>New Jersey</strong>',
		questionDescriptionHtml: null,
		answerTitleHtml: '<strong>Trenton</strong>',
		answerDescriptionHtml: null,
		pathToMedia: null,
		category: 'us-state-capitals',
	},
	{
		questionTitleHtml: 'Capital of <strong>New Mexico</strong>',
		questionDescriptionHtml: null,
		answerTitleHtml: '<strong>Santa Fe</strong>',
		answerDescriptionHtml: null,
		pathToMedia: null,
		category: 'us-state-capitals',
	},
	{
		questionTitleHtml: 'Capital of <strong>New York</strong>',
		questionDescriptionHtml: null,
		answerTitleHtml: '<strong>Albany</strong>',
		answerDescriptionHtml: null,
		pathToMedia: null,
		category: 'us-state-capitals',
	},
	{
		questionTitleHtml: 'Capital of <strong>North Carolina</strong>',
		questionDescriptionHtml: null,
		answerTitleHtml: '<strong>Raleigh</strong>',
		answerDescriptionHtml: null,
		pathToMedia: null,
		category: 'us-state-capitals',
	},
	{
		questionTitleHtml: 'Capital of <strong>North Dakota</strong>',
		questionDescriptionHtml: null,
		answerTitleHtml: '<strong>Bismarck</strong>',
		answerDescriptionHtml: null,
		pathToMedia: null,
		category: 'us-state-capitals',
	},
	{
		questionTitleHtml: 'Capital of <strong>Ohio</strong>',
		questionDescriptionHtml: null,
		answerTitleHtml: '<strong>Columbus</strong>',
		answerDescriptionHtml: null,
		pathToMedia: null,
		category: 'us-state-capitals',
	},
	{
		questionTitleHtml: 'Capital of <strong>Oklahoma</strong>',
		questionDescriptionHtml: null,
		answerTitleHtml: '<strong>Oklahoma City</strong>',
		answerDescriptionHtml: null,
		pathToMedia: null,
		category: 'us-state-capitals',
	},
	{
		questionTitleHtml: 'Capital of <strong>Oregon</strong>',
		questionDescriptionHtml: null,
		answerTitleHtml: '<strong>Salem</strong>',
		answerDescriptionHtml: null,
		pathToMedia: null,
		category: 'us-state-capitals',
	},
	{
		questionTitleHtml: 'Capital of <strong>Pennsylvania</strong>',
		questionDescriptionHtml: null,
		answerTitleHtml: '<strong>Harrisburg</strong>',
		answerDescriptionHtml: null,
		pathToMedia: null,
		category: 'us-state-capitals',
	},
	{
		questionTitleHtml: 'Capital of <strong>Rhode Island</strong>',
		questionDescriptionHtml: null,
		answerTitleHtml: '<strong>Providence</strong>',
		answerDescriptionHtml: null,
		pathToMedia: null,
		category: 'us-state-capitals',
	},
	{
		questionTitleHtml: 'Capital of <strong>South Carolina</strong>',
		questionDescriptionHtml: null,
		answerTitleHtml: '<strong>Columbia</strong>',
		answerDescriptionHtml: null,
		pathToMedia: null,
		category: 'us-state-capitals',
	},
	{
		questionTitleHtml: 'Capital of <strong>South Dakota</strong>',
		questionDescriptionHtml: null,
		answerTitleHtml: '<strong>Pierre</strong>',
		answerDescriptionHtml: null,
		pathToMedia: null,
		category: 'us-state-capitals',
	},
	{
		questionTitleHtml: 'Capital of <strong>Tennessee</strong>',
		questionDescriptionHtml: null,
		answerTitleHtml: '<strong>Nashville</strong>',
		answerDescriptionHtml: null,
		pathToMedia: null,
		category: 'us-state-capitals',
	},
	{
		questionTitleHtml: 'Capital of <strong>Texas</strong>',
		questionDescriptionHtml: null,
		answerTitleHtml: '<strong>Austin</strong>',
		answerDescriptionHtml: null,
		pathToMedia: null,
		category: 'us-state-capitals',
	},
	{
		questionTitleHtml: 'Capital of <strong>Utah</strong>',
		questionDescriptionHtml: null,
		answerTitleHtml: '<strong>Salt Lake City</strong>',
		answerDescriptionHtml: null,
		pathToMedia: null,
		category: 'us-state-capitals',
	},
	{
		questionTitleHtml: 'Capital of <strong>Vermont</strong>',
		questionDescriptionHtml: null,
		answerTitleHtml: '<strong>Montpelier</strong>',
		answerDescriptionHtml: null,
		pathToMedia: null,
		category: 'us-state-capitals',
	},
	{
		questionTitleHtml: 'Capital of <strong>Virginia</strong>',
		questionDescriptionHtml: null,
		answerTitleHtml: '<strong>Richmond</strong>',
		answerDescriptionHtml: null,
		pathToMedia: null,
		category: 'us-state-capitals',
	},
	{
		questionTitleHtml: 'Capital of <strong>Washington</strong>',
		questionDescriptionHtml: null,
		answerTitleHtml: '<strong>Olympia</strong>',
		answerDescriptionHtml: null,
		pathToMedia: null,
		category: 'us-state-capitals',
	},
	{
		questionTitleHtml: 'Capital of <strong>West Virginia</strong>',
		questionDescriptionHtml: null,
		answerTitleHtml: '<strong>Charleston</strong>',
		answerDescriptionHtml: null,
		pathToMedia: null,
		category: 'us-state-capitals',
	},
	{
		questionTitleHtml: 'Capital of <strong>Wisconsin</strong>',
		questionDescriptionHtml: null,
		answerTitleHtml: '<strong>Madison</strong>',
		answerDescriptionHtml: null,
		pathToMedia: null,
		category: 'us-state-capitals',
	},
	{
		questionTitleHtml: 'Capital of <strong>Wyoming</strong>',
		questionDescriptionHtml: null,
		answerTitleHtml: '<strong>Cheyenne</strong>',
		answerDescriptionHtml: null,
		pathToMedia: null,
		category: 'us-state-capitals',
	},
]
