import type { FlashCard } from '@/types'

export const us_state_locations_nicknames: FlashCard[] = [
	{
		questionTitleHtml: 'What\'s this state?',
		questionDescriptionHtml: 'And its nickname',
		answerTitleHtml: '<strong>Alabama</strong>',
		answerDescriptionHtml: 'Location: <strong>Southeastern United States</strong><br>Nickname: <strong>Yellowhammer State</strong>',
		pathToMedia: 'images/us-state-locations/alabama.png',
		category: 'us-state-locations-nicknames',
	},
	{
		questionTitleHtml: 'What\'s this state?',
		questionDescriptionHtml: 'And its nickname',
		answerTitleHtml: '<strong>Alaska</strong>',
		answerDescriptionHtml: 'Location: Northwestern United States (non-contiguous)<br>Nickname: The Last Frontier',
		pathToMedia: 'images/us-state-locations/alaska.png',
		category: 'us-state-locations-nicknames',
	},
	{
		questionTitleHtml: 'What\'s this state?',
		questionDescriptionHtml: 'And its nickname',
		answerTitleHtml: '<strong>Arizona</strong>',
		answerDescriptionHtml: 'Location: Southwestern United States<br>Nickname: The Grand Canyon State',
		pathToMedia: 'images/us-state-locations/arizona.png',
		category: 'us-state-locations-nicknames',
	},
	{
		questionTitleHtml: 'What\'s this state?',
		questionDescriptionHtml: 'And its nickname',
		answerTitleHtml: '<strong>Arkansas</strong>',
		answerDescriptionHtml: 'Location: South Central United States<br>Nickname: The Natural State',
		pathToMedia: 'images/us-state-locations/arkansas.png',
		category: 'us-state-locations-nicknames',
	},
	{
		questionTitleHtml: 'What\'s this state?',
		questionDescriptionHtml: 'And its nickname',
		answerTitleHtml: '<strong>California</strong>',
		answerDescriptionHtml: 'Location: Western United States (Pacific Coast)<br>Nickname: The Golden State',
		pathToMedia: 'images/us-state-locations/california.png',
		category: 'us-state-locations-nicknames',
	},
	{
		questionTitleHtml: 'What\'s this state?',
		questionDescriptionHtml: 'And its nickname',
		answerTitleHtml: '<strong>Colorado</strong>',
		answerDescriptionHtml: 'Location: Western United States (Mountain Region)<br>Nickname: The Centennial State',
		pathToMedia: 'images/us-state-locations/colorado.png',
		category: 'us-state-locations-nicknames',
	},
	{
		questionTitleHtml: 'What\'s this state?',
		questionDescriptionHtml: 'And its nickname',
		answerTitleHtml: '<strong>Connecticut</strong>',
		answerDescriptionHtml: 'Location: Northeastern United States (New England)<br>Nickname: The Constitution State',
		pathToMedia: 'images/us-state-locations/connecticut.png',
		category: 'us-state-locations-nicknames',
	},
	{
		questionTitleHtml: 'What\'s this state?',
		questionDescriptionHtml: 'And its nickname',
		answerTitleHtml: '<strong>Delaware</strong>',
		answerDescriptionHtml: 'Location: Mid-Atlantic United States<br>Nickname: The First State',
		pathToMedia: 'images/us-state-locations/delaware.png',
		category: 'us-state-locations-nicknames',
	},
	{
		questionTitleHtml: 'What\'s this state?',
		questionDescriptionHtml: 'And its nickname',
		answerTitleHtml: '<strong>Florida</strong>',
		answerDescriptionHtml: 'Location: Southeastern United States (Peninsula)<br>Nickname: The Sunshine State',
		pathToMedia: 'images/us-state-locations/florida.png',
		category: 'us-state-locations-nicknames',
	},
	{
		questionTitleHtml: 'What\'s this state?',
		questionDescriptionHtml: 'And its nickname',
		answerTitleHtml: '<strong>Georgia</strong>',
		answerDescriptionHtml: 'Location: Southeastern United States<br>Nickname: The Peach State',
		pathToMedia: 'images/us-state-locations/georgia.png',
		category: 'us-state-locations-nicknames',
	},
	{
		questionTitleHtml: 'What\'s this state?',
		questionDescriptionHtml: 'And its nickname',
		answerTitleHtml: '<strong>Hawaii</strong>',
		answerDescriptionHtml: 'Location: Pacific Ocean (non-contiguous)<br>Nickname: The Aloha State',
		pathToMedia: 'images/us-state-locations/hawaii.png',
		category: 'us-state-locations-nicknames',
	},
	{
		questionTitleHtml: 'What\'s this state?',
		questionDescriptionHtml: 'And its nickname',
		answerTitleHtml: '<strong>Idaho</strong>',
		answerDescriptionHtml: 'Location: Northwestern United States (Mountain Region)<br>Nickname: The Gem State',
		pathToMedia: 'images/us-state-locations/idaho.png',
		category: 'us-state-locations-nicknames',
	},
	{
		questionTitleHtml: 'What\'s this state?',
		questionDescriptionHtml: 'And its nickname',
		answerTitleHtml: '<strong>Illinois</strong>',
		answerDescriptionHtml: 'Location: Midwestern United States<br>Nickname: Prairie State',
		pathToMedia: 'images/us-state-locations/illinois.png',
		category: 'us-state-locations-nicknames',
	},
	{
		questionTitleHtml: 'What\'s this state?',
		questionDescriptionHtml: 'And its nickname',
		answerTitleHtml: '<strong>Indiana</strong>',
		answerDescriptionHtml: 'Location: Midwestern United States<br>Nickname: The Hoosier State',
		pathToMedia: 'images/us-state-locations/indiana.png',
		category: 'us-state-locations-nicknames',
	},
	{
		questionTitleHtml: 'What\'s this state?',
		questionDescriptionHtml: 'And its nickname',
		answerTitleHtml: '<strong>Iowa</strong>',
		answerDescriptionHtml: 'Location: Midwestern United States<br>Nickname: The Hawkeye State',
		pathToMedia: 'images/us-state-locations/iowa.png',
		category: 'us-state-locations-nicknames',
	},
	{
		questionTitleHtml: 'What\'s this state?',
		questionDescriptionHtml: 'And its nickname',
		answerTitleHtml: '<strong>Kansas</strong>',
		answerDescriptionHtml: 'Location: Central United States<br>Nickname: The Sunflower State',
		pathToMedia: 'images/us-state-locations/kansas.png',
		category: 'us-state-locations-nicknames',
	},
	{
		questionTitleHtml: 'What\'s this state?',
		questionDescriptionHtml: 'And its nickname',
		answerTitleHtml: '<strong>Kentucky</strong>',
		answerDescriptionHtml: 'Location: East Central United States<br>Nickname: The Bluegrass State',
		pathToMedia: 'images/us-state-locations/kentucky.png',
		category: 'us-state-locations-nicknames',
	},
	{
		questionTitleHtml: 'What\'s this state?',
		questionDescriptionHtml: 'And its nickname',
		answerTitleHtml: '<strong>Louisiana</strong>',
		answerDescriptionHtml: 'Location: South Central United States<br>Nickname: The Pelican State',
		pathToMedia: 'images/us-state-locations/louisiana.png',
		category: 'us-state-locations-nicknames',
	},
	{
		questionTitleHtml: 'What\'s this state?',
		questionDescriptionHtml: 'And its nickname',
		answerTitleHtml: '<strong>Maine</strong>',
		answerDescriptionHtml: 'Location: Northeastern United States (New England)<br>Nickname: The Pine Tree State',
		pathToMedia: 'images/us-state-locations/maine.png',
		category: 'us-state-locations-nicknames',
	},
	{
		questionTitleHtml: 'What\'s this state?',
		questionDescriptionHtml: 'And its nickname',
		answerTitleHtml: '<strong>Maryland</strong>',
		answerDescriptionHtml: 'Location: Mid-Atlantic United States<br>Nickname: The Old Line State',
		pathToMedia: 'images/us-state-locations/maryland.png',
		category: 'us-state-locations-nicknames',
	},
	{
		questionTitleHtml: 'What\'s this state?',
		questionDescriptionHtml: 'And its nickname',
		answerTitleHtml: '<strong>Massachusetts</strong>',
		answerDescriptionHtml: 'Location: Northeastern United States (New England)<br>Nickname: The Bay State',
		pathToMedia: 'images/us-state-locations/massachusetts.png',
		category: 'us-state-locations-nicknames',
	},
	{
		questionTitleHtml: 'What\'s this state?',
		questionDescriptionHtml: 'And its nickname',
		answerTitleHtml: '<strong>Michigan</strong>',
		answerDescriptionHtml: 'Location: Midwestern United States (Great Lakes)<br>Nickname: The Great Lakes State',
		pathToMedia: 'images/us-state-locations/michigan.png',
		category: 'us-state-locations-nicknames',
	},
	{
		questionTitleHtml: 'What\'s this state?',
		questionDescriptionHtml: 'And its nickname',
		answerTitleHtml: '<strong>Minnesota</strong>',
		answerDescriptionHtml: 'Location: Midwestern United States (Upper Midwest)<br>Nickname: The North Star State',
		pathToMedia: 'images/us-state-locations/minnesota.png',
		category: 'us-state-locations-nicknames',
	},
	{
		questionTitleHtml: 'What\'s this state?',
		questionDescriptionHtml: 'And its nickname',
		answerTitleHtml: '<strong>Mississippi</strong>',
		answerDescriptionHtml: 'Location: Southeastern United States<br>Nickname: The Magnolia State',
		pathToMedia: 'images/us-state-locations/mississippi.png',
		category: 'us-state-locations-nicknames',
	},
	{
		questionTitleHtml: 'What\'s this state?',
		questionDescriptionHtml: 'And its nickname',
		answerTitleHtml: '<strong>Missouri</strong>',
		answerDescriptionHtml: 'Location: Midwestern United States<br>Nickname: The Show-Me State',
		pathToMedia: 'images/us-state-locations/missouri.png',
		category: 'us-state-locations-nicknames',
	},
	{
		questionTitleHtml: 'What\'s this state?',
		questionDescriptionHtml: 'And its nickname',
		answerTitleHtml: '<strong>Montana</strong>',
		answerDescriptionHtml: 'Location: Western United States (Mountain Region)<br>Nickname: The Treasure State',
		pathToMedia: 'images/us-state-locations/montana.png',
		category: 'us-state-locations-nicknames',
	},
	{
		questionTitleHtml: 'What\'s this state?',
		questionDescriptionHtml: 'And its nickname',
		answerTitleHtml: '<strong>Nebraska</strong>',
		answerDescriptionHtml: 'Location: Central United States (Great Plains)<br>Nickname: The Cornhusker State',
		pathToMedia: 'images/us-state-locations/nebraska.png',
		category: 'us-state-locations-nicknames',
	},
	{
		questionTitleHtml: 'What\'s this state?',
		questionDescriptionHtml: 'And its nickname',
		answerTitleHtml: '<strong>Nevada</strong>',
		answerDescriptionHtml: 'Location: Western United States<br>Nickname: The Silver State',
		pathToMedia: 'images/us-state-locations/nevada.png',
		category: 'us-state-locations-nicknames',
	},
	{
		questionTitleHtml: 'What\'s this state?',
		questionDescriptionHtml: 'And its nickname',
		answerTitleHtml: '<strong>New Hampshire</strong>',
		answerDescriptionHtml: 'Location: Northeastern United States (New England)<br>Nickname: The Granite State',
		pathToMedia: 'images/us-state-locations/new-hampshire.png',
		category: 'us-state-locations-nicknames',
	},
	{
		questionTitleHtml: 'What\'s this state?',
		questionDescriptionHtml: 'And its nickname',
		answerTitleHtml: '<strong>New Jersey</strong>',
		answerDescriptionHtml: 'Location: Mid-Atlantic United States<br>Nickname: Garden State',
		pathToMedia: 'images/us-state-locations/new-jersey.png',
		category: 'us-state-locations-nicknames',
	},
	{
		questionTitleHtml: 'What\'s this state?',
		questionDescriptionHtml: 'And its nickname',
		answerTitleHtml: '<strong>New Mexico</strong>',
		answerDescriptionHtml: 'Location: Southwestern United States<br>Nickname: Land of Enchantment',
		pathToMedia: 'images/us-state-locations/new-mexico.png',
		category: 'us-state-locations-nicknames',
	},
	{
		questionTitleHtml: 'What\'s this state?',
		questionDescriptionHtml: 'And its nickname',
		answerTitleHtml: '<strong>New York</strong>',
		answerDescriptionHtml: 'Location: Northeastern United States (Mid-Atlantic)<br>Nickname: The Empire State',
		pathToMedia: 'images/us-state-locations/new-york.png',
		category: 'us-state-locations-nicknames',
	},
	{
		questionTitleHtml: 'What\'s this state?',
		questionDescriptionHtml: 'And its nickname',
		answerTitleHtml: '<strong>North Carolina</strong>',
		answerDescriptionHtml: 'Location: Southeastern United States<br>Nickname: Tar Heel State',
		pathToMedia: 'images/us-state-locations/north-carolina.png',
		category: 'us-state-locations-nicknames',
	},
	{
		questionTitleHtml: 'What\'s this state?',
		questionDescriptionHtml: 'And its nickname',
		answerTitleHtml: '<strong>North Dakota</strong>',
		answerDescriptionHtml: 'Location: Midwestern United States (Great Plains)<br>Nickname: The Peace Garden State',
		pathToMedia: 'images/us-state-locations/north-dakota.png',
		category: 'us-state-locations-nicknames',
	},
	{
		questionTitleHtml: 'What\'s this state?',
		questionDescriptionHtml: 'And its nickname',
		answerTitleHtml: '<strong>Ohio</strong>',
		answerDescriptionHtml: 'Location: Midwestern United States<br>Nickname: The Buckeye State',
		pathToMedia: 'images/us-state-locations/ohio.png',
		category: 'us-state-locations-nicknames',
	},
	{
		questionTitleHtml: 'What\'s this state?',
		questionDescriptionHtml: 'And its nickname',
		answerTitleHtml: '<strong>Oklahoma</strong>',
		answerDescriptionHtml: 'Location: South Central United States<br>Nickname: The Sooner State',
		pathToMedia: 'images/us-state-locations/oklahoma.png',
		category: 'us-state-locations-nicknames',
	},
	{
		questionTitleHtml: 'What\'s this state?',
		questionDescriptionHtml: 'And its nickname',
		answerTitleHtml: '<strong>Oregon</strong>',
		answerDescriptionHtml: 'Location: Western United States (Pacific Coast)<br>Nickname: The Beaver State',
		pathToMedia: 'images/us-state-locations/oregon.png',
		category: 'us-state-locations-nicknames',
	},
	{
		questionTitleHtml: 'What\'s this state?',
		questionDescriptionHtml: 'And its nickname',
		answerTitleHtml: '<strong>Pennsylvania</strong>',
		answerDescriptionHtml: 'Location: Mid-Atlantic United States<br>Nickname: The Keystone State',
		pathToMedia: 'images/us-state-locations/pennsylvania.png',
		category: 'us-state-locations-nicknames',
	},
	{
		questionTitleHtml: 'What\'s this state?',
		questionDescriptionHtml: 'And its nickname',
		answerTitleHtml: '<strong>Rhode Island</strong>',
		answerDescriptionHtml: 'Location: Northeastern United States (New England)<br>Nickname: The Ocean State',
		pathToMedia: 'images/us-state-locations/rhode-island.png',
		category: 'us-state-locations-nicknames',
	},
	{
		questionTitleHtml: 'What\'s this state?',
		questionDescriptionHtml: 'And its nickname',
		answerTitleHtml: '<strong>South Carolina</strong>',
		answerDescriptionHtml: 'Location: Southeastern United States<br>Nickname: The Palmetto State',
		pathToMedia: 'images/us-state-locations/south-carolina.png',
		category: 'us-state-locations-nicknames',
	},
	{
		questionTitleHtml: 'What\'s this state?',
		questionDescriptionHtml: 'And its nickname',
		answerTitleHtml: '<strong>South Dakota</strong>',
		answerDescriptionHtml: 'Location: Midwestern United States (Great Plains)<br>Nickname: Mount Rushmore State',
		pathToMedia: 'images/us-state-locations/south-dakota.png',
		category: 'us-state-locations-nicknames',
	},
	{
		questionTitleHtml: 'What\'s this state?',
		questionDescriptionHtml: 'And its nickname',
		answerTitleHtml: '<strong>Tennessee</strong>',
		answerDescriptionHtml: 'Location: East Central United States<br>Nickname: The Volunteer State',
		pathToMedia: 'images/us-state-locations/tennessee.png',
		category: 'us-state-locations-nicknames',
	},
	{
		questionTitleHtml: 'What\'s this state?',
		questionDescriptionHtml: 'And its nickname',
		answerTitleHtml: '<strong>Texas</strong>',
		answerDescriptionHtml: 'Location: South Central United States<br>Nickname: The Lone Star State',
		pathToMedia: 'images/us-state-locations/texas.png',
		category: 'us-state-locations-nicknames',
	},
	{
		questionTitleHtml: 'What\'s this state?',
		questionDescriptionHtml: 'And its nickname',
		answerTitleHtml: '<strong>Utah</strong>',
		answerDescriptionHtml: 'Location: Western United States (Mountain Region)<br>Nickname: The Beehive State',
		pathToMedia: 'images/us-state-locations/utah.png',
		category: 'us-state-locations-nicknames',
	},
	{
		questionTitleHtml: 'What\'s this state?',
		questionDescriptionHtml: 'And its nickname',
		answerTitleHtml: '<strong>Vermont</strong>',
		answerDescriptionHtml: 'Location: Northeastern United States (New England)<br>Nickname: The Green Mountain State',
		pathToMedia: 'images/us-state-locations/vermont.png',
		category: 'us-state-locations-nicknames',
	},
	{
		questionTitleHtml: 'What\'s this state?',
		questionDescriptionHtml: 'And its nickname',
		answerTitleHtml: '<strong>Virginia</strong>',
		answerDescriptionHtml: 'Location: Mid-Atlantic United States<br>Nickname: Old Dominion',
		pathToMedia: 'images/us-state-locations/virginia.png',
		category: 'us-state-locations-nicknames',
	},
	{
		questionTitleHtml: 'What\'s this state?',
		questionDescriptionHtml: 'And its nickname',
		answerTitleHtml: '<strong>Washington</strong>',
		answerDescriptionHtml: 'Location: Western United States (Pacific Coast)<br>Nickname: The Evergreen State',
		pathToMedia: 'images/us-state-locations/washington.png',
		category: 'us-state-locations-nicknames',
	},
	{
		questionTitleHtml: 'What\'s this state?',
		questionDescriptionHtml: 'And its nickname',
		answerTitleHtml: '<strong>West Virginia</strong>',
		answerDescriptionHtml: 'Location: East Central United States<br>Nickname: The Mountain State',
		pathToMedia: 'images/us-state-locations/west-virginia.png',
		category: 'us-state-locations-nicknames',
	},
	{
		questionTitleHtml: 'What\'s this state?',
		questionDescriptionHtml: 'And its nickname',
		answerTitleHtml: '<strong>Wisconsin</strong>',
		answerDescriptionHtml: 'Location: Midwestern United States (Great Lakes)<br>Nickname: The Badger State',
		pathToMedia: 'images/us-state-locations/wisconsin.png',
		category: 'us-state-locations-nicknames',
	},
	{
		questionTitleHtml: 'What\'s this state?',
		questionDescriptionHtml: 'And its nickname',
		answerTitleHtml: '<strong>Wyoming</strong>',
		answerDescriptionHtml: 'Location: Western United States (Mountain Region)<br>Nickname: The Equality State',
		pathToMedia: 'images/us-state-locations/wyoming.png',
		category: 'us-state-locations-nicknames',
	},
	{
		questionTitleHtml: 'What\'s this? (hint: Capital of the United States of America)',
		questionDescriptionHtml: 'Can you tell me what states border it?',
		answerTitleHtml: '<strong>District of Columbia (Washington, D.C.)</strong>',
		answerDescriptionHtml: 'It is bordered by two states: Maryland to the north, east, and west, and Virginia to the south/southwest across the Potomac River',
		pathToMedia: 'images/us-state-locations/dc.jpg',
		category: 'us-state-locations-nicknames',
	},
]
