import type { FlashCard } from '@/types'

export const us_state_locations_nicknames: FlashCard[] = [
	{
		questionTitleHtml: 'What\'s this state?',
		questionDescriptionHtml: 'And its nickname',
		answerTitleHtml: '<strong>Alabama</strong>',
		answerDescriptionHtml: 'Location: <strong>Southeastern United States</strong><br>Nickname: <strong>Yellowhammer State</strong>',
		pathToMedia: 'https://upload.wikimedia.org/wikipedia/commons/thumb/1/1a/Alabama_in_United_States.svg/330px-Alabama_in_United_States.svg.png',
		category: 'us-state-locations-nicknames',
	},
	{
		questionTitleHtml: 'What\'s this state?',
		questionDescriptionHtml: 'And its nickname',
		answerTitleHtml: '<strong>Alaska</strong>',
		answerDescriptionHtml: 'Location: Northwestern United States (non-contiguous)<br>Nickname: The Last Frontier',
		pathToMedia: 'https://upload.wikimedia.org/wikipedia/commons/thumb/c/c4/Alaska_in_United_States_%28US49%2B1%29.svg/330px-Alaska_in_United_States_%28US49%2B1%29.svg.png',
		category: 'us-state-locations-nicknames',
	},
	{
		questionTitleHtml: 'What\'s this state?',
		questionDescriptionHtml: 'And its nickname',
		answerTitleHtml: '<strong>Arizona</strong>',
		answerDescriptionHtml: 'Location: Southwestern United States<br>Nickname: The Grand Canyon State',
		pathToMedia: 'https://upload.wikimedia.org/wikipedia/commons/thumb/d/d8/Arizona_in_United_States.svg/330px-Arizona_in_United_States.svg.png',
		category: 'us-state-locations-nicknames',
	},
	{
		questionTitleHtml: 'What\'s this state?',
		questionDescriptionHtml: 'And its nickname',
		answerTitleHtml: '<strong>Arkansas</strong>',
		answerDescriptionHtml: 'Location: South Central United States<br>Nickname: The Natural State',
		pathToMedia: 'https://upload.wikimedia.org/wikipedia/commons/thumb/8/86/Arkansas_in_United_States.svg/330px-Arkansas_in_United_States.svg.png',
		category: 'us-state-locations-nicknames',
	},
	{
		questionTitleHtml: 'What\'s this state?',
		questionDescriptionHtml: 'And its nickname',
		answerTitleHtml: '<strong>California</strong>',
		answerDescriptionHtml: 'Location: Western United States (Pacific Coast)<br>Nickname: The Golden State',
		pathToMedia: 'https://upload.wikimedia.org/wikipedia/commons/thumb/9/94/California_in_United_States.svg/330px-California_in_United_States.svg.png',
		category: 'us-state-locations-nicknames',
	},
	{
		questionTitleHtml: 'What\'s this state?',
		questionDescriptionHtml: 'And its nickname',
		answerTitleHtml: '<strong>Colorado</strong>',
		answerDescriptionHtml: 'Location: Western United States (Mountain Region)<br>Nickname: The Centennial State',
		pathToMedia: 'https://upload.wikimedia.org/wikipedia/commons/thumb/6/60/Colorado_in_United_States.svg/330px-Colorado_in_United_States.svg.png',
		category: 'us-state-locations-nicknames',
	},
	{
		questionTitleHtml: 'What\'s this state?',
		questionDescriptionHtml: 'And its nickname',
		answerTitleHtml: '<strong>Connecticut</strong>',
		answerDescriptionHtml: 'Location: Northeastern United States (New England)<br>Nickname: The Constitution State',
		pathToMedia: 'https://upload.wikimedia.org/wikipedia/commons/thumb/3/3a/Connecticut_in_United_States_%28zoom%29.svg/330px-Connecticut_in_United_States_%28zoom%29.svg.png',
		category: 'us-state-locations-nicknames',
	},
	{
		questionTitleHtml: 'What\'s this state?',
		questionDescriptionHtml: 'And its nickname',
		answerTitleHtml: '<strong>Delaware</strong>',
		answerDescriptionHtml: 'Location: Mid-Atlantic United States<br>Nickname: The First State',
		pathToMedia: 'https://upload.wikimedia.org/wikipedia/commons/thumb/8/8c/Delaware_in_United_States_%28zoom%29.svg/330px-Delaware_in_United_States_%28zoom%29.svg.png',
		category: 'us-state-locations-nicknames',
	},
	{
		questionTitleHtml: 'What\'s this state?',
		questionDescriptionHtml: 'And its nickname',
		answerTitleHtml: '<strong>Florida</strong>',
		answerDescriptionHtml: 'Location: Southeastern United States (Peninsula)<br>Nickname: The Sunshine State',
		pathToMedia: 'https://upload.wikimedia.org/wikipedia/commons/thumb/1/15/Florida_in_United_States.svg/330px-Florida_in_United_States.svg.png',
		category: 'us-state-locations-nicknames',
	},
	{
		questionTitleHtml: 'What\'s this state?',
		questionDescriptionHtml: 'And its nickname',
		answerTitleHtml: '<strong>Georgia</strong>',
		answerDescriptionHtml: 'Location: Southeastern United States<br>Nickname: The Peach State',
		pathToMedia: 'https://upload.wikimedia.org/wikipedia/commons/thumb/d/d1/Georgia_in_United_States.svg/330px-Georgia_in_United_States.svg.png',
		category: 'us-state-locations-nicknames',
	},
	{
		questionTitleHtml: 'What\'s this state?',
		questionDescriptionHtml: 'And its nickname',
		answerTitleHtml: '<strong>Hawaii</strong>',
		answerDescriptionHtml: 'Location: Pacific Ocean (non-contiguous)<br>Nickname: The Aloha State',
		pathToMedia: 'https://upload.wikimedia.org/wikipedia/commons/thumb/b/b4/Hawaii_in_United_States_%28US50%29_%28%2Bgrid%29_%28zoom%29_%28W3%29.svg/330px-Hawaii_in_United_States_%28US50%29_%28%2Bgrid%29_%28zoom%29_%28W3%29.svg.png',
		category: 'us-state-locations-nicknames',
	},
	{
		questionTitleHtml: 'What\'s this state?',
		questionDescriptionHtml: 'And its nickname',
		answerTitleHtml: '<strong>Idaho</strong>',
		answerDescriptionHtml: 'Location: Northwestern United States (Mountain Region)<br>Nickname: The Gem State',
		pathToMedia: 'https://upload.wikimedia.org/wikipedia/commons/thumb/a/a0/Idaho_in_United_States.svg/330px-Idaho_in_United_States.svg.png',
		category: 'us-state-locations-nicknames',
	},
	{
		questionTitleHtml: 'What\'s this state?',
		questionDescriptionHtml: 'And its nickname',
		answerTitleHtml: '<strong>Illinois</strong>',
		answerDescriptionHtml: 'Location: Midwestern United States<br>Nickname: Prairie State',
		pathToMedia: 'https://upload.wikimedia.org/wikipedia/commons/thumb/5/53/Illinois_in_United_States.svg/330px-Illinois_in_United_States.svg.png',
		category: 'us-state-locations-nicknames',
	},
	{
		questionTitleHtml: 'What\'s this state?',
		questionDescriptionHtml: 'And its nickname',
		answerTitleHtml: '<strong>Indiana</strong>',
		answerDescriptionHtml: 'Location: Midwestern United States<br>Nickname: The Hoosier State',
		pathToMedia: 'https://upload.wikimedia.org/wikipedia/commons/thumb/d/d2/Indiana_in_United_States.svg/330px-Indiana_in_United_States.svg.png',
		category: 'us-state-locations-nicknames',
	},
	{
		questionTitleHtml: 'What\'s this state?',
		questionDescriptionHtml: 'And its nickname',
		answerTitleHtml: '<strong>Iowa</strong>',
		answerDescriptionHtml: 'Location: Midwestern United States<br>Nickname: The Hawkeye State',
		pathToMedia: 'https://upload.wikimedia.org/wikipedia/commons/thumb/5/57/Iowa_in_United_States.svg/330px-Iowa_in_United_States.svg.png',
		category: 'us-state-locations-nicknames',
	},
	{
		questionTitleHtml: 'What\'s this state?',
		questionDescriptionHtml: 'And its nickname',
		answerTitleHtml: '<strong>Kansas</strong>',
		answerDescriptionHtml: 'Location: Central United States<br>Nickname: The Sunflower State',
		pathToMedia: 'https://upload.wikimedia.org/wikipedia/commons/thumb/a/a6/Kansas_in_United_States.svg/330px-Kansas_in_United_States.svg.png',
		category: 'us-state-locations-nicknames',
	},
	{
		questionTitleHtml: 'What\'s this state?',
		questionDescriptionHtml: 'And its nickname',
		answerTitleHtml: '<strong>Kentucky</strong>',
		answerDescriptionHtml: 'Location: East Central United States<br>Nickname: The Bluegrass State',
		pathToMedia: 'https://upload.wikimedia.org/wikipedia/commons/thumb/e/e2/Kentucky_in_United_States.svg/330px-Kentucky_in_United_States.svg.png',
		category: 'us-state-locations-nicknames',
	},
	{
		questionTitleHtml: 'What\'s this state?',
		questionDescriptionHtml: 'And its nickname',
		answerTitleHtml: '<strong>Louisiana</strong>',
		answerDescriptionHtml: 'Location: South Central United States<br>Nickname: The Pelican State',
		pathToMedia: 'placehohttps://upload.wikimedia.org/wikipedia/commons/thumb/2/2a/Louisiana_in_United_States.svg/330px-Louisiana_in_United_States.svg.pnglder',
		category: 'us-state-locations-nicknames',
	},
	{
		questionTitleHtml: 'What\'s this state?',
		questionDescriptionHtml: 'And its nickname',
		answerTitleHtml: '<strong>Maine</strong>',
		answerDescriptionHtml: 'Location: Northeastern United States (New England)<br>Nickname: The Pine Tree State',
		pathToMedia: 'https://upload.wikimedia.org/wikipedia/commons/thumb/7/78/Maine_in_United_States.svg/330px-Maine_in_United_States.svg.png',
		category: 'us-state-locations-nicknames',
	},
	{
		questionTitleHtml: 'What\'s this state?',
		questionDescriptionHtml: 'And its nickname',
		answerTitleHtml: '<strong>Maryland</strong>',
		answerDescriptionHtml: 'Location: Mid-Atlantic United States<br>Nickname: The Old Line State',
		pathToMedia: 'https://upload.wikimedia.org/wikipedia/commons/thumb/d/da/Maryland_in_United_States_%28zoom%29.svg/330px-Maryland_in_United_States_%28zoom%29.svg.png',
		category: 'us-state-locations-nicknames',
	},
	{
		questionTitleHtml: 'What\'s this state?',
		questionDescriptionHtml: 'And its nickname',
		answerTitleHtml: '<strong>Massachusetts</strong>',
		answerDescriptionHtml: 'Location: Northeastern United States (New England)<br>Nickname: The Bay State',
		pathToMedia: 'https://upload.wikimedia.org/wikipedia/commons/thumb/3/35/Massachusetts_in_United_States_%28zoom%29.svg/330px-Massachusetts_in_United_States_%28zoom%29.svg.png',
		category: 'us-state-locations-nicknames',
	},
	{
		questionTitleHtml: 'What\'s this state?',
		questionDescriptionHtml: 'And its nickname',
		answerTitleHtml: '<strong>Michigan</strong>',
		answerDescriptionHtml: 'Location: Midwestern United States (Great Lakes)<br>Nickname: The Great Lakes State',
		pathToMedia: 'https://upload.wikimedia.org/wikipedia/commons/thumb/5/50/Michigan_in_United_States.svg/330px-Michigan_in_United_States.svg.png',
		category: 'us-state-locations-nicknames',
	},
	{
		questionTitleHtml: 'What\'s this state?',
		questionDescriptionHtml: 'And its nickname',
		answerTitleHtml: '<strong>Minnesota</strong>',
		answerDescriptionHtml: 'Location: Midwestern United States (Upper Midwest)<br>Nickname: The North Star State',
		pathToMedia: 'https://upload.wikimedia.org/wikipedia/commons/thumb/8/81/Minnesota_in_United_States.svg/330px-Minnesota_in_United_States.svg.png',
		category: 'us-state-locations-nicknames',
	},
	{
		questionTitleHtml: 'What\'s this state?',
		questionDescriptionHtml: 'And its nickname',
		answerTitleHtml: '<strong>Mississippi</strong>',
		answerDescriptionHtml: 'Location: Southeastern United States<br>Nickname: The Magnolia State',
		pathToMedia: 'https://upload.wikimedia.org/wikipedia/commons/thumb/2/22/Mississippi_in_United_States.svg/330px-Mississippi_in_United_States.svg.png',
		category: 'us-state-locations-nicknames',
	},
	{
		questionTitleHtml: 'What\'s this state?',
		questionDescriptionHtml: 'And its nickname',
		answerTitleHtml: '<strong>Missouri</strong>',
		answerDescriptionHtml: 'Location: Midwestern United States<br>Nickname: The Show-Me State',
		pathToMedia: 'https://upload.wikimedia.org/wikipedia/commons/thumb/6/62/Missouri_in_United_States.svg/330px-Missouri_in_United_States.svg.png',
		category: 'us-state-locations-nicknames',
	},
	{
		questionTitleHtml: 'What\'s this state?',
		questionDescriptionHtml: 'And its nickname',
		answerTitleHtml: '<strong>Montana</strong>',
		answerDescriptionHtml: 'Location: Western United States (Mountain Region)<br>Nickname: The Treasure State',
		pathToMedia: 'https://upload.wikimedia.org/wikipedia/commons/thumb/6/67/Montana_in_United_States.svg/330px-Montana_in_United_States.svg.png',
		category: 'us-state-locations-nicknames',
	},
	{
		questionTitleHtml: 'What\'s this state?',
		questionDescriptionHtml: 'And its nickname',
		answerTitleHtml: '<strong>Nebraska</strong>',
		answerDescriptionHtml: 'Location: Central United States (Great Plains)<br>Nickname: The Cornhusker State',
		pathToMedia: 'https://upload.wikimedia.org/wikipedia/commons/thumb/4/44/Nebraska_in_United_States.svg/330px-Nebraska_in_United_States.svg.png',
		category: 'us-state-locations-nicknames',
	},
	{
		questionTitleHtml: 'What\'s this state?',
		questionDescriptionHtml: 'And its nickname',
		answerTitleHtml: '<strong>Nevada</strong>',
		answerDescriptionHtml: 'Location: Western United States<br>Nickname: The Silver State',
		pathToMedia: 'https://upload.wikimedia.org/wikipedia/commons/thumb/b/ba/Nevada_in_United_States.svg/330px-Nevada_in_United_States.svg.png',
		category: 'us-state-locations-nicknames',
	},
	{
		questionTitleHtml: 'What\'s this state?',
		questionDescriptionHtml: 'And its nickname',
		answerTitleHtml: '<strong>New Hampshire</strong>',
		answerDescriptionHtml: 'Location: Northeastern United States (New England)<br>Nickname: The Granite State',
		pathToMedia: 'https://upload.wikimedia.org/wikipedia/commons/thumb/6/64/New_Hampshire_in_United_States_%28zoom%29.svg/330px-New_Hampshire_in_United_States_%28zoom%29.svg.png',
		category: 'us-state-locations-nicknames',
	},
	{
		questionTitleHtml: 'What\'s this state?',
		questionDescriptionHtml: 'And its nickname',
		answerTitleHtml: '<strong>New Jersey</strong>',
		answerDescriptionHtml: 'Location: Mid-Atlantic United States<br>Nickname: Garden State',
		pathToMedia: 'https://upload.wikimedia.org/wikipedia/commons/thumb/8/84/New_Jersey_in_United_States_%28zoom%29.svg/330px-New_Jersey_in_United_States_%28zoom%29.svg.png',
		category: 'us-state-locations-nicknames',
	},
	{
		questionTitleHtml: 'What\'s this state?',
		questionDescriptionHtml: 'And its nickname',
		answerTitleHtml: '<strong>New Mexico</strong>',
		answerDescriptionHtml: 'Location: Southwestern United States<br>Nickname: Land of Enchantment',
		pathToMedia: 'https://upload.wikimedia.org/wikipedia/commons/thumb/f/fe/New_Mexico_in_United_States.svg/330px-New_Mexico_in_United_States.svg.png',
		category: 'us-state-locations-nicknames',
	},
	{
		questionTitleHtml: 'What\'s this state?',
		questionDescriptionHtml: 'And its nickname',
		answerTitleHtml: '<strong>New York</strong>',
		answerDescriptionHtml: 'Location: Northeastern United States (Mid-Atlantic)<br>Nickname: The Empire State',
		pathToMedia: 'https://upload.wikimedia.org/wikipedia/commons/thumb/0/06/New_York_in_United_States.svg/330px-New_York_in_United_States.svg.png',
		category: 'us-state-locations-nicknames',
	},
	{
		questionTitleHtml: 'What\'s this state?',
		questionDescriptionHtml: 'And its nickname',
		answerTitleHtml: '<strong>North Carolina</strong>',
		answerDescriptionHtml: 'Location: Southeastern United States<br>Nickname: Tar Heel State',
		pathToMedia: 'https://upload.wikimedia.org/wikipedia/commons/thumb/2/20/North_Carolina_in_United_States.svg/330px-North_Carolina_in_United_States.svg.png',
		category: 'us-state-locations-nicknames',
	},
	{
		questionTitleHtml: 'What\'s this state?',
		questionDescriptionHtml: 'And its nickname',
		answerTitleHtml: '<strong>North Dakota</strong>',
		answerDescriptionHtml: 'Location: Midwestern United States (Great Plains)<br>Nickname: The Peace Garden State',
		pathToMedia: 'https://upload.wikimedia.org/wikipedia/commons/thumb/b/bc/North_Dakota_in_United_States.svg/330px-North_Dakota_in_United_States.svg.png',
		category: 'us-state-locations-nicknames',
	},
	{
		questionTitleHtml: 'What\'s this state?',
		questionDescriptionHtml: 'And its nickname',
		answerTitleHtml: '<strong>Ohio</strong>',
		answerDescriptionHtml: 'Location: Midwestern United States<br>Nickname: The Buckeye State',
		pathToMedia: 'https://upload.wikimedia.org/wikipedia/commons/thumb/5/58/Ohio_in_United_States.svg/330px-Ohio_in_United_States.svg.png',
		category: 'us-state-locations-nicknames',
	},
	{
		questionTitleHtml: 'What\'s this state?',
		questionDescriptionHtml: 'And its nickname',
		answerTitleHtml: '<strong>Oklahoma</strong>',
		answerDescriptionHtml: 'Location: South Central United States<br>Nickname: The Sooner State',
		pathToMedia: 'https://upload.wikimedia.org/wikipedia/commons/thumb/9/99/Oklahoma_in_United_States.svg/330px-Oklahoma_in_United_States.svg.png',
		category: 'us-state-locations-nicknames',
	},
	{
		questionTitleHtml: 'What\'s this state?',
		questionDescriptionHtml: 'And its nickname',
		answerTitleHtml: '<strong>Oregon</strong>',
		answerDescriptionHtml: 'Location: Western United States (Pacific Coast)<br>Nickname: The Beaver State',
		pathToMedia: 'https://upload.wikimedia.org/wikipedia/commons/thumb/5/59/Oregon_in_United_States.svg/330px-Oregon_in_United_States.svg.png',
		category: 'us-state-locations-nicknames',
	},
	{
		questionTitleHtml: 'What\'s this state?',
		questionDescriptionHtml: 'And its nickname',
		answerTitleHtml: '<strong>Pennsylvania</strong>',
		answerDescriptionHtml: 'Location: Mid-Atlantic United States<br>Nickname: The Keystone State',
		pathToMedia: 'https://upload.wikimedia.org/wikipedia/commons/thumb/6/6d/Pennsylvania_in_United_States.svg/330px-Pennsylvania_in_United_States.svg.png',
		category: 'us-state-locations-nicknames',
	},
	{
		questionTitleHtml: 'What\'s this state?',
		questionDescriptionHtml: 'And its nickname',
		answerTitleHtml: '<strong>Rhode Island</strong>',
		answerDescriptionHtml: 'Location: Northeastern United States (New England)<br>Nickname: The Ocean State',
		pathToMedia: 'https://upload.wikimedia.org/wikipedia/commons/thumb/2/22/Rhode_Island_in_United_States_%28zoom%29_%28extra_close%29.svg/330px-Rhode_Island_in_United_States_%28zoom%29_%28extra_close%29.svg.png',
		category: 'us-state-locations-nicknames',
	},
	{
		questionTitleHtml: 'What\'s this state?',
		questionDescriptionHtml: 'And its nickname',
		answerTitleHtml: '<strong>South Carolina</strong>',
		answerDescriptionHtml: 'Location: Southeastern United States<br>Nickname: The Palmetto State',
		pathToMedia: 'https://upload.wikimedia.org/wikipedia/commons/thumb/8/8e/South_Carolina_in_United_States.svg/330px-South_Carolina_in_United_States.svg.png',
		category: 'us-state-locations-nicknames',
	},
	{
		questionTitleHtml: 'What\'s this state?',
		questionDescriptionHtml: 'And its nickname',
		answerTitleHtml: '<strong>South Dakota</strong>',
		answerDescriptionHtml: 'Location: Midwestern United States (Great Plains)<br>Nickname: Mount Rushmore State',
		pathToMedia: 'https://upload.wikimedia.org/wikipedia/commons/thumb/8/8f/South_Dakota_in_United_States.svg/330px-South_Dakota_in_United_States.svg.png',
		category: 'us-state-locations-nicknames',
	},
	{
		questionTitleHtml: 'What\'s this state?',
		questionDescriptionHtml: 'And its nickname',
		answerTitleHtml: '<strong>Tennessee</strong>',
		answerDescriptionHtml: 'Location: East Central United States<br>Nickname: The Volunteer State',
		pathToMedia: 'https://upload.wikimedia.org/wikipedia/commons/thumb/2/29/Tennessee_in_United_States.svg/330px-Tennessee_in_United_States.svg.png',
		category: 'us-state-locations-nicknames',
	},
	{
		questionTitleHtml: 'What\'s this state?',
		questionDescriptionHtml: 'And its nickname',
		answerTitleHtml: '<strong>Texas</strong>',
		answerDescriptionHtml: 'Location: South Central United States<br>Nickname: The Lone Star State',
		pathToMedia: 'https://upload.wikimedia.org/wikipedia/commons/thumb/a/ad/Texas_in_United_States.svg/330px-Texas_in_United_States.svg.png',
		category: 'us-state-locations-nicknames',
	},
	{
		questionTitleHtml: 'What\'s this state?',
		questionDescriptionHtml: 'And its nickname',
		answerTitleHtml: '<strong>Utah</strong>',
		answerDescriptionHtml: 'Location: Western United States (Mountain Region)<br>Nickname: The Beehive State',
		pathToMedia: 'https://upload.wikimedia.org/wikipedia/commons/thumb/8/82/Utah_in_United_States.svg/330px-Utah_in_United_States.svg.png',
		category: 'us-state-locations-nicknames',
	},
	{
		questionTitleHtml: 'What\'s this state?',
		questionDescriptionHtml: 'And its nickname',
		answerTitleHtml: '<strong>Vermont</strong>',
		answerDescriptionHtml: 'Location: Northeastern United States (New England)<br>Nickname: The Green Mountain State',
		pathToMedia: 'https://upload.wikimedia.org/wikipedia/commons/thumb/f/f3/Vermont_in_United_States_%28zoom%29.svg/330px-Vermont_in_United_States_%28zoom%29.svg.png',
		category: 'us-state-locations-nicknames',
	},
	{
		questionTitleHtml: 'What\'s this state?',
		questionDescriptionHtml: 'And its nickname',
		answerTitleHtml: '<strong>Virginia</strong>',
		answerDescriptionHtml: 'Location: Mid-Atlantic United States<br>Nickname: Old Dominion',
		pathToMedia: 'https://upload.wikimedia.org/wikipedia/commons/thumb/c/c6/Virginia_in_United_States.svg/330px-Virginia_in_United_States.svg.png',
		category: 'us-state-locations-nicknames',
	},
	{
		questionTitleHtml: 'What\'s this state?',
		questionDescriptionHtml: 'And its nickname',
		answerTitleHtml: '<strong>Washington</strong>',
		answerDescriptionHtml: 'Location: Western United States (Pacific Coast)<br>Nickname: The Evergreen State',
		pathToMedia: 'https://upload.wikimedia.org/wikipedia/commons/thumb/3/30/Washington_in_United_States.svg/330px-Washington_in_United_States.svg.png',
		category: 'us-state-locations-nicknames',
	},
	{
		questionTitleHtml: 'What\'s this state?',
		questionDescriptionHtml: 'And its nickname',
		answerTitleHtml: '<strong>West Virginia</strong>',
		answerDescriptionHtml: 'Location: East Central United States<br>Nickname: The Mountain State',
		pathToMedia: 'https://upload.wikimedia.org/wikipedia/commons/thumb/2/2a/West_Virginia_in_United_States.svg/330px-West_Virginia_in_United_States.svg.png',
		category: 'us-state-locations-nicknames',
	},
	{
		questionTitleHtml: 'What\'s this state?',
		questionDescriptionHtml: 'And its nickname',
		answerTitleHtml: '<strong>Wisconsin</strong>',
		answerDescriptionHtml: 'Location: Midwestern United States (Great Lakes)<br>Nickname: The Badger State',
		pathToMedia: 'https://upload.wikimedia.org/wikipedia/commons/thumb/a/a7/Wisconsin_in_United_States.svg/330px-Wisconsin_in_United_States.svg.png',
		category: 'us-state-locations-nicknames',
	},
	{
		questionTitleHtml: 'What\'s this state?',
		questionDescriptionHtml: 'And its nickname',
		answerTitleHtml: '<strong>Wyoming</strong>',
		answerDescriptionHtml: 'Location: Western United States (Mountain Region)<br>Nickname: The Equality State',
		pathToMedia: 'https://upload.wikimedia.org/wikipedia/commons/thumb/5/5b/Wyoming_in_United_States.svg/330px-Wyoming_in_United_States.svg.png',
		category: 'us-state-locations-nicknames',
	},
	{
		questionTitleHtml: 'What\'s this? (hint: Capital of the United States of America)',
		questionDescriptionHtml: 'Can you tell me what states border it?',
		answerTitleHtml: '<strong>District of Columbia (Washington, D.C.)</strong>',
		answerDescriptionHtml: 'It is bordered by two states: Maryland to the north, east, and west, and Virginia to the south/southwest across the Potomac River',
		pathToMedia: 'https://upload.wikimedia.org/wikipedia/commons/a/a1/DC_locator_map_with_state_names.jpg',
		category: 'us-state-locations-nicknames',
	},
]
