import type { FlashCard } from '@/types'

export const us_state_locations_nicknames: FlashCard[] = [
	{
		questionTitleHtml: '<strong>Alabama</strong>',
		questionDescriptionHtml: 'What is the location and nickname of this state?',
		answerTitleHtml: '<strong>Alabama</strong>',
		answerDescriptionHtml: 'Location: <strong>Southeastern United States</strong><br>Nickname: <strong>The Yellowhammer State</strong>, The Heart of Dixie',
		pathToMedia: 'placeholder',
		category: 'us-state-locations-nicknames',
	},
	{
		questionTitleHtml: '<strong>Alaska</strong>',
		questionDescriptionHtml: 'What is the location and nickname of this state?',
		answerTitleHtml: '<strong>Alaska</strong>',
		answerDescriptionHtml: 'Location: Northwestern United States (non-contiguous)<br>Nickname: The Last Frontier, Land of the Midnight Sun',
		pathToMedia: 'placeholder',
		category: 'us-state-locations-nicknames',
	},
	{
		questionTitleHtml: '<strong>Arizona</strong>',
		questionDescriptionHtml: 'What is the location and nickname of this state?',
		answerTitleHtml: '<strong>Arizona</strong>',
		answerDescriptionHtml: 'Location: Southwestern United States<br>Nickname: The Grand Canyon State, The Copper State',
		pathToMedia: 'placeholder',
		category: 'us-state-locations-nicknames',
	},
	{
		questionTitleHtml: '<strong>Arkansas</strong>',
		questionDescriptionHtml: 'What is the location and nickname of this state?',
		answerTitleHtml: '<strong>Arkansas</strong>',
		answerDescriptionHtml: 'Location: South Central United States<br>Nickname: The Natural State, Land of Opportunity',
		pathToMedia: 'placeholder',
		category: 'us-state-locations-nicknames',
	},
	{
		questionTitleHtml: '<strong>California</strong>',
		questionDescriptionHtml: 'What is the location and nickname of this state?',
		answerTitleHtml: '<strong>California</strong>',
		answerDescriptionHtml: 'Location: Western United States (Pacific Coast)<br>Nickname: The Golden State',
		pathToMedia: 'placeholder',
		category: 'us-state-locations-nicknames',
	},
	{
		questionTitleHtml: '<strong>Colorado</strong>',
		questionDescriptionHtml: 'What is the location and nickname of this state?',
		answerTitleHtml: '<strong>Colorado</strong>',
		answerDescriptionHtml: 'Location: Western United States (Mountain Region)<br>Nickname: The Centennial State, Colorful Colorado',
		pathToMedia: 'placeholder',
		category: 'us-state-locations-nicknames',
	},
	{
		questionTitleHtml: '<strong>Connecticut</strong>',
		questionDescriptionHtml: 'What is the location and nickname of this state?',
		answerTitleHtml: '<strong>Connecticut</strong>',
		answerDescriptionHtml: 'Location: Northeastern United States (New England)<br>Nickname: The Constitution State, The Nutmeg State',
		pathToMedia: 'placeholder',
		category: 'us-state-locations-nicknames',
	},
	{
		questionTitleHtml: '<strong>Delaware</strong>',
		questionDescriptionHtml: 'What is the location and nickname of this state?',
		answerTitleHtml: '<strong>Delaware</strong>',
		answerDescriptionHtml: 'Location: Mid-Atlantic United States<br>Nickname: The First State, The Diamond State',
		pathToMedia: 'placeholder',
		category: 'us-state-locations-nicknames',
	},
	{
		questionTitleHtml: '<strong>Florida</strong>',
		questionDescriptionHtml: 'What is the location and nickname of this state?',
		answerTitleHtml: '<strong>Florida</strong>',
		answerDescriptionHtml: 'Location: Southeastern United States (Peninsula)<br>Nickname: The Sunshine State',
		pathToMedia: 'placeholder',
		category: 'us-state-locations-nicknames',
	},
	{
		questionTitleHtml: '<strong>Georgia</strong>',
		questionDescriptionHtml: 'What is the location and nickname of this state?',
		answerTitleHtml: '<strong>Georgia</strong>',
		answerDescriptionHtml: 'Location: Southeastern United States<br>Nickname: The Peach State, The Empire State of the South',
		pathToMedia: 'placeholder',
		category: 'us-state-locations-nicknames',
	},
	{
		questionTitleHtml: '<strong>Hawaii</strong>',
		questionDescriptionHtml: 'What is the location and nickname of this state?',
		answerTitleHtml: '<strong>Hawaii</strong>',
		answerDescriptionHtml: 'Location: Pacific Ocean (non-contiguous)<br>Nickname: The Aloha State, Paradise of the Pacific',
		pathToMedia: 'placeholder',
		category: 'us-state-locations-nicknames',
	},
	{
		questionTitleHtml: '<strong>Idaho</strong>',
		questionDescriptionHtml: 'What is the location and nickname of this state?',
		answerTitleHtml: '<strong>Idaho</strong>',
		answerDescriptionHtml: 'Location: Northwestern United States (Mountain Region)<br>Nickname: The Gem State',
		pathToMedia: 'placeholder',
		category: 'us-state-locations-nicknames',
	},
	{
		questionTitleHtml: '<strong>Illinois</strong>',
		questionDescriptionHtml: 'What is the location and nickname of this state?',
		answerTitleHtml: '<strong>Illinois</strong>',
		answerDescriptionHtml: 'Location: Midwestern United States<br>Nickname: The Prairie State, Land of Lincoln',
		pathToMedia: 'placeholder',
		category: 'us-state-locations-nicknames',
	},
	{
		questionTitleHtml: '<strong>Indiana</strong>',
		questionDescriptionHtml: 'What is the location and nickname of this state?',
		answerTitleHtml: '<strong>Indiana</strong>',
		answerDescriptionHtml: 'Location: Midwestern United States<br>Nickname: The Hoosier State',
		pathToMedia: 'placeholder',
		category: 'us-state-locations-nicknames',
	},
	{
		questionTitleHtml: '<strong>Iowa</strong>',
		questionDescriptionHtml: 'What is the location and nickname of this state?',
		answerTitleHtml: '<strong>Iowa</strong>',
		answerDescriptionHtml: 'Location: Midwestern United States<br>Nickname: The Hawkeye State',
		pathToMedia: 'placeholder',
		category: 'us-state-locations-nicknames',
	},
	{
		questionTitleHtml: '<strong>Kansas</strong>',
		questionDescriptionHtml: 'What is the location and nickname of this state?',
		answerTitleHtml: '<strong>Kansas</strong>',
		answerDescriptionHtml: 'Location: Central United States<br>Nickname: The Sunflower State, The Wheat State',
		pathToMedia: 'placeholder',
		category: 'us-state-locations-nicknames',
	},
	{
		questionTitleHtml: '<strong>Kentucky</strong>',
		questionDescriptionHtml: 'What is the location and nickname of this state?',
		answerTitleHtml: '<strong>Kentucky</strong>',
		answerDescriptionHtml: 'Location: East Central United States<br>Nickname: The Bluegrass State',
		pathToMedia: 'placeholder',
		category: 'us-state-locations-nicknames',
	},
	{
		questionTitleHtml: '<strong>Louisiana</strong>',
		questionDescriptionHtml: 'What is the location and nickname of this state?',
		answerTitleHtml: '<strong>Louisiana</strong>',
		answerDescriptionHtml: 'Location: South Central United States<br>Nickname: The Pelican State, The Bayou State',
		pathToMedia: 'placeholder',
		category: 'us-state-locations-nicknames',
	},
	{
		questionTitleHtml: '<strong>Maine</strong>',
		questionDescriptionHtml: 'What is the location and nickname of this state?',
		answerTitleHtml: '<strong>Maine</strong>',
		answerDescriptionHtml: 'Location: Northeastern United States (New England)<br>Nickname: The Pine Tree State, Vacationland',
		pathToMedia: 'placeholder',
		category: 'us-state-locations-nicknames',
	},
	{
		questionTitleHtml: '<strong>Maryland</strong>',
		questionDescriptionHtml: 'What is the location and nickname of this state?',
		answerTitleHtml: '<strong>Maryland</strong>',
		answerDescriptionHtml: 'Location: Mid-Atlantic United States<br>Nickname: The Old Line State, The Free State',
		pathToMedia: 'placeholder',
		category: 'us-state-locations-nicknames',
	},
	{
		questionTitleHtml: '<strong>Massachusetts</strong>',
		questionDescriptionHtml: 'What is the location and nickname of this state?',
		answerTitleHtml: '<strong>Massachusetts</strong>',
		answerDescriptionHtml: 'Location: Northeastern United States (New England)<br>Nickname: The Bay State, The Old Colony State',
		pathToMedia: 'placeholder',
		category: 'us-state-locations-nicknames',
	},
	{
		questionTitleHtml: '<strong>Michigan</strong>',
		questionDescriptionHtml: 'What is the location and nickname of this state?',
		answerTitleHtml: '<strong>Michigan</strong>',
		answerDescriptionHtml: 'Location: Midwestern United States (Great Lakes)<br>Nickname: The Great Lakes State, The Wolverine State',
		pathToMedia: 'placeholder',
		category: 'us-state-locations-nicknames',
	},
	{
		questionTitleHtml: '<strong>Minnesota</strong>',
		questionDescriptionHtml: 'What is the location and nickname of this state?',
		answerTitleHtml: '<strong>Minnesota</strong>',
		answerDescriptionHtml: 'Location: Midwestern United States (Upper Midwest)<br>Nickname: The Land of 10,000 Lakes, The North Star State',
		pathToMedia: 'placeholder',
		category: 'us-state-locations-nicknames',
	},
	{
		questionTitleHtml: '<strong>Mississippi</strong>',
		questionDescriptionHtml: 'What is the location and nickname of this state?',
		answerTitleHtml: '<strong>Mississippi</strong>',
		answerDescriptionHtml: 'Location: Southeastern United States<br>Nickname: The Magnolia State, The Hospitality State',
		pathToMedia: 'placeholder',
		category: 'us-state-locations-nicknames',
	},
	{
		questionTitleHtml: '<strong>Missouri</strong>',
		questionDescriptionHtml: 'What is the location and nickname of this state?',
		answerTitleHtml: '<strong>Missouri</strong>',
		answerDescriptionHtml: 'Location: Midwestern United States<br>Nickname: The Show-Me State',
		pathToMedia: 'placeholder',
		category: 'us-state-locations-nicknames',
	},
	{
		questionTitleHtml: '<strong>Montana</strong>',
		questionDescriptionHtml: 'What is the location and nickname of this state?',
		answerTitleHtml: '<strong>Montana</strong>',
		answerDescriptionHtml: 'Location: Western United States (Mountain Region)<br>Nickname: The Treasure State, Big Sky Country',
		pathToMedia: 'placeholder',
		category: 'us-state-locations-nicknames',
	},
	{
		questionTitleHtml: '<strong>Nebraska</strong>',
		questionDescriptionHtml: 'What is the location and nickname of this state?',
		answerTitleHtml: '<strong>Nebraska</strong>',
		answerDescriptionHtml: 'Location: Central United States (Great Plains)<br>Nickname: The Cornhusker State',
		pathToMedia: 'placeholder',
		category: 'us-state-locations-nicknames',
	},
	{
		questionTitleHtml: '<strong>Nevada</strong>',
		questionDescriptionHtml: 'What is the location and nickname of this state?',
		answerTitleHtml: '<strong>Nevada</strong>',
		answerDescriptionHtml: 'Location: Western United States<br>Nickname: The Silver State, The Sagebrush State',
		pathToMedia: 'placeholder',
		category: 'us-state-locations-nicknames',
	},
	{
		questionTitleHtml: '<strong>New Hampshire</strong>',
		questionDescriptionHtml: 'What is the location and nickname of this state?',
		answerTitleHtml: '<strong>New Hampshire</strong>',
		answerDescriptionHtml: 'Location: Northeastern United States (New England)<br>Nickname: The Granite State',
		pathToMedia: 'placeholder',
		category: 'us-state-locations-nicknames',
	},
	{
		questionTitleHtml: '<strong>New Jersey</strong>',
		questionDescriptionHtml: 'What is the location and nickname of this state?',
		answerTitleHtml: '<strong>New Jersey</strong>',
		answerDescriptionHtml: 'Location: Mid-Atlantic United States<br>Nickname: The Garden State',
		pathToMedia: 'placeholder',
		category: 'us-state-locations-nicknames',
	},
	{
		questionTitleHtml: '<strong>New Mexico</strong>',
		questionDescriptionHtml: 'What is the location and nickname of this state?',
		answerTitleHtml: '<strong>New Mexico</strong>',
		answerDescriptionHtml: 'Location: Southwestern United States<br>Nickname: The Land of Enchantment',
		pathToMedia: 'placeholder',
		category: 'us-state-locations-nicknames',
	},
	{
		questionTitleHtml: '<strong>New York</strong>',
		questionDescriptionHtml: 'What is the location and nickname of this state?',
		answerTitleHtml: '<strong>New York</strong>',
		answerDescriptionHtml: 'Location: Northeastern United States (Mid-Atlantic)<br>Nickname: The Empire State',
		pathToMedia: 'placeholder',
		category: 'us-state-locations-nicknames',
	},
	{
		questionTitleHtml: '<strong>North Carolina</strong>',
		questionDescriptionHtml: 'What is the location and nickname of this state?',
		answerTitleHtml: '<strong>North Carolina</strong>',
		answerDescriptionHtml: 'Location: Southeastern United States<br>Nickname: The Tar Heel State, The Old North State',
		pathToMedia: 'placeholder',
		category: 'us-state-locations-nicknames',
	},
	{
		questionTitleHtml: '<strong>North Dakota</strong>',
		questionDescriptionHtml: 'What is the location and nickname of this state?',
		answerTitleHtml: '<strong>North Dakota</strong>',
		answerDescriptionHtml: 'Location: Midwestern United States (Great Plains)<br>Nickname: The Peace Garden State, The Flickertail State',
		pathToMedia: 'placeholder',
		category: 'us-state-locations-nicknames',
	},
	{
		questionTitleHtml: '<strong>Ohio</strong>',
		questionDescriptionHtml: 'What is the location and nickname of this state?',
		answerTitleHtml: '<strong>Ohio</strong>',
		answerDescriptionHtml: 'Location: Midwestern United States<br>Nickname: The Buckeye State',
		pathToMedia: 'placeholder',
		category: 'us-state-locations-nicknames',
	},
	{
		questionTitleHtml: '<strong>Oklahoma</strong>',
		questionDescriptionHtml: 'What is the location and nickname of this state?',
		answerTitleHtml: '<strong>Oklahoma</strong>',
		answerDescriptionHtml: 'Location: South Central United States<br>Nickname: The Sooner State',
		pathToMedia: 'placeholder',
		category: 'us-state-locations-nicknames',
	},
	{
		questionTitleHtml: '<strong>Oregon</strong>',
		questionDescriptionHtml: 'What is the location and nickname of this state?',
		answerTitleHtml: '<strong>Oregon</strong>',
		answerDescriptionHtml: 'Location: Western United States (Pacific Coast)<br>Nickname: The Beaver State',
		pathToMedia: 'placeholder',
		category: 'us-state-locations-nicknames',
	},
	{
		questionTitleHtml: '<strong>Pennsylvania</strong>',
		questionDescriptionHtml: 'What is the location and nickname of this state?',
		answerTitleHtml: '<strong>Pennsylvania</strong>',
		answerDescriptionHtml: 'Location: Mid-Atlantic United States<br>Nickname: The Keystone State',
		pathToMedia: 'placeholder',
		category: 'us-state-locations-nicknames',
	},
	{
		questionTitleHtml: '<strong>Rhode Island</strong>',
		questionDescriptionHtml: 'What is the location and nickname of this state?',
		answerTitleHtml: '<strong>Rhode Island</strong>',
		answerDescriptionHtml: 'Location: Northeastern United States (New England)<br>Nickname: The Ocean State, Little Rhody',
		pathToMedia: 'placeholder',
		category: 'us-state-locations-nicknames',
	},
	{
		questionTitleHtml: '<strong>South Carolina</strong>',
		questionDescriptionHtml: 'What is the location and nickname of this state?',
		answerTitleHtml: '<strong>South Carolina</strong>',
		answerDescriptionHtml: 'Location: Southeastern United States<br>Nickname: The Palmetto State',
		pathToMedia: 'placeholder',
		category: 'us-state-locations-nicknames',
	},
	{
		questionTitleHtml: '<strong>South Dakota</strong>',
		questionDescriptionHtml: 'What is the location and nickname of this state?',
		answerTitleHtml: '<strong>South Dakota</strong>',
		answerDescriptionHtml: 'Location: Midwestern United States (Great Plains)<br>Nickname: The Mount Rushmore State, The Coyote State',
		pathToMedia: 'placeholder',
		category: 'us-state-locations-nicknames',
	},
	{
		questionTitleHtml: '<strong>Tennessee</strong>',
		questionDescriptionHtml: 'What is the location and nickname of this state?',
		answerTitleHtml: '<strong>Tennessee</strong>',
		answerDescriptionHtml: 'Location: East Central United States<br>Nickname: The Volunteer State',
		pathToMedia: 'placeholder',
		category: 'us-state-locations-nicknames',
	},
	{
		questionTitleHtml: '<strong>Texas</strong>',
		questionDescriptionHtml: 'What is the location and nickname of this state?',
		answerTitleHtml: '<strong>Texas</strong>',
		answerDescriptionHtml: 'Location: South Central United States<br>Nickname: The Lone Star State',
		pathToMedia: 'placeholder',
		category: 'us-state-locations-nicknames',
	},
	{
		questionTitleHtml: '<strong>Utah</strong>',
		questionDescriptionHtml: 'What is the location and nickname of this state?',
		answerTitleHtml: '<strong>Utah</strong>',
		answerDescriptionHtml: 'Location: Western United States (Mountain Region)<br>Nickname: The Beehive State',
		pathToMedia: 'placeholder',
		category: 'us-state-locations-nicknames',
	},
	{
		questionTitleHtml: '<strong>Vermont</strong>',
		questionDescriptionHtml: 'What is the location and nickname of this state?',
		answerTitleHtml: '<strong>Vermont</strong>',
		answerDescriptionHtml: 'Location: Northeastern United States (New England)<br>Nickname: The Green Mountain State',
		pathToMedia: 'placeholder',
		category: 'us-state-locations-nicknames',
	},
	{
		questionTitleHtml: '<strong>Virginia</strong>',
		questionDescriptionHtml: 'What is the location and nickname of this state?',
		answerTitleHtml: '<strong>Virginia</strong>',
		answerDescriptionHtml: 'Location: Mid-Atlantic United States<br>Nickname: The Old Dominion, Mother of Presidents',
		pathToMedia: 'placeholder',
		category: 'us-state-locations-nicknames',
	},
	{
		questionTitleHtml: '<strong>Washington</strong>',
		questionDescriptionHtml: 'What is the location and nickname of this state?',
		answerTitleHtml: '<strong>Washington</strong>',
		answerDescriptionHtml: 'Location: Western United States (Pacific Coast)<br>Nickname: The Evergreen State',
		pathToMedia: 'placeholder',
		category: 'us-state-locations-nicknames',
	},
	{
		questionTitleHtml: '<strong>West Virginia</strong>',
		questionDescriptionHtml: 'What is the location and nickname of this state?',
		answerTitleHtml: '<strong>West Virginia</strong>',
		answerDescriptionHtml: 'Location: East Central United States<br>Nickname: The Mountain State',
		pathToMedia: 'placeholder',
		category: 'us-state-locations-nicknames',
	},
	{
		questionTitleHtml: '<strong>Wisconsin</strong>',
		questionDescriptionHtml: 'What is the location and nickname of this state?',
		answerTitleHtml: '<strong>Wisconsin</strong>',
		answerDescriptionHtml: 'Location: Midwestern United States (Great Lakes)<br>Nickname: The Badger State, America\'s Dairyland',
		pathToMedia: 'placeholder',
		category: 'us-state-locations-nicknames',
	},
	{
		questionTitleHtml: '<strong>Wyoming</strong>',
		questionDescriptionHtml: 'What is the location and nickname of this state?',
		answerTitleHtml: '<strong>Wyoming</strong>',
		answerDescriptionHtml: 'Location: Western United States (Mountain Region)<br>Nickname: The Equality State, The Cowboy State',
		pathToMedia: 'placeholder',
		category: 'us-state-locations-nicknames',
	},
]
