import type { FlashCard } from '@/types'

export const world_country_capitals_asia: FlashCard[] = [
	{
		questionTitleHtml: '<strong>Afghanistan</strong>',
		questionDescriptionHtml: 'What is the capital of this country?',
		answerTitleHtml: '<strong>Kabul</strong>',
		answerDescriptionHtml: 'Capital of <strong>Afghanistan</strong>',
		pathToMedia: null,
		category: 'world-country-capitals-asia',
	},
	{
		questionTitleHtml: '<strong>Bangladesh</strong>',
		questionDescriptionHtml: 'What is the capital of this country?',
		answerTitleHtml: '<strong>Dhaka</strong>',
		answerDescriptionHtml: 'Capital of <strong>Bangladesh</strong>',
		pathToMedia: null,
		category: 'world-country-capitals-asia',
	},
	{
		questionTitleHtml: '<strong>Burma (Myanmar)</strong>',
		questionDescriptionHtml: 'What is the capital of this country?',
		answerTitleHtml: '<strong>Naypyidaw</strong>',
		answerDescriptionHtml: 'Capital of <strong>Burma (Myanmar)</strong>',
		pathToMedia: null,
		category: 'world-country-capitals-asia',
	},
	{
		questionTitleHtml: '<strong>Cambodia</strong>',
		questionDescriptionHtml: 'What is the capital of this country?',
		answerTitleHtml: '<strong>Phnom Penh</strong>',
		answerDescriptionHtml: 'Capital of <strong>Cambodia</strong>',
		pathToMedia: null,
		category: 'world-country-capitals-asia',
	},
	{
		questionTitleHtml: '<strong>China</strong>',
		questionDescriptionHtml: 'What is the capital of this country?',
		answerTitleHtml: '<strong>Beijing</strong>',
		answerDescriptionHtml: 'Capital of <strong>China</strong>',
		pathToMedia: null,
		category: 'world-country-capitals-asia',
	},
	{
		questionTitleHtml: '<strong>India</strong>',
		questionDescriptionHtml: 'What is the capital of this country?',
		answerTitleHtml: '<strong>New Delhi</strong>',
		answerDescriptionHtml: 'Capital of <strong>India</strong>',
		pathToMedia: null,
		category: 'world-country-capitals-asia',
	},
	{
		questionTitleHtml: '<strong>Indonesia</strong>',
		questionDescriptionHtml: 'What is the capital of this country?',
		answerTitleHtml: '<strong>Jakarta</strong>',
		answerDescriptionHtml: 'Capital of <strong>Indonesia</strong>',
		pathToMedia: null,
		category: 'world-country-capitals-asia',
	},
	{
		questionTitleHtml: '<strong>Iran</strong>',
		questionDescriptionHtml: 'What is the capital of this country?',
		answerTitleHtml: '<strong>Tehran</strong>',
		answerDescriptionHtml: 'Capital of <strong>Iran</strong>',
		pathToMedia: null,
		category: 'world-country-capitals-asia',
	},
	{
		questionTitleHtml: '<strong>Iraq</strong>',
		questionDescriptionHtml: 'What is the capital of this country?',
		answerTitleHtml: '<strong>Baghdad</strong>',
		answerDescriptionHtml: 'Capital of <strong>Iraq</strong>',
		pathToMedia: null,
		category: 'world-country-capitals-asia',
	},
	{
		questionTitleHtml: '<strong>Israel</strong>',
		questionDescriptionHtml: 'What is the capital of this country?',
		answerTitleHtml: '<strong>Jerusalem</strong>',
		answerDescriptionHtml: 'Capital of <strong>Israel</strong>',
		pathToMedia: null,
		category: 'world-country-capitals-asia',
	},
	{
		questionTitleHtml: '<strong>Japan</strong>',
		questionDescriptionHtml: 'What is the capital of this country?',
		answerTitleHtml: '<strong>Tokyo</strong>',
		answerDescriptionHtml: 'Capital of <strong>Japan</strong>',
		pathToMedia: null,
		category: 'world-country-capitals-asia',
	},
	{
		questionTitleHtml: '<strong>Jordan</strong>',
		questionDescriptionHtml: 'What is the capital of this country?',
		answerTitleHtml: '<strong>Amman</strong>',
		answerDescriptionHtml: 'Capital of <strong>Jordan</strong>',
		pathToMedia: null,
		category: 'world-country-capitals-asia',
	},
	{
		questionTitleHtml: '<strong>Kuwait</strong>',
		questionDescriptionHtml: 'What is the capital of this country?',
		answerTitleHtml: '<strong>Kuwait City</strong>',
		answerDescriptionHtml: 'Capital of <strong>Kuwait</strong>',
		pathToMedia: null,
		category: 'world-country-capitals-asia',
	},
	{
		questionTitleHtml: '<strong>Kyrgyzstan</strong>',
		questionDescriptionHtml: 'What is the capital of this country?',
		answerTitleHtml: '<strong>Bishkek</strong>',
		answerDescriptionHtml: 'Capital of <strong>Kyrgyzstan</strong>',
		pathToMedia: null,
		category: 'world-country-capitals-asia',
	},
	{
		questionTitleHtml: '<strong>Laos</strong>',
		questionDescriptionHtml: 'What is the capital of this country?',
		answerTitleHtml: '<strong>Vientiane</strong>',
		answerDescriptionHtml: 'Capital of <strong>Laos</strong>',
		pathToMedia: null,
		category: 'world-country-capitals-asia',
	},
	{
		questionTitleHtml: '<strong>Lebanon</strong>',
		questionDescriptionHtml: 'What is the capital of this country?',
		answerTitleHtml: '<strong>Beirut</strong>',
		answerDescriptionHtml: 'Capital of <strong>Lebanon</strong>',
		pathToMedia: null,
		category: 'world-country-capitals-asia',
	},
	{
		questionTitleHtml: '<strong>Malaysia</strong>',
		questionDescriptionHtml: 'What is the capital of this country?',
		answerTitleHtml: '<strong>Kuala Lumpur</strong>',
		answerDescriptionHtml: 'Capital of <strong>Malaysia</strong>',
		pathToMedia: null,
		category: 'world-country-capitals-asia',
	},
	{
		questionTitleHtml: '<strong>Mongolia</strong>',
		questionDescriptionHtml: 'What is the capital of this country?',
		answerTitleHtml: '<strong>Ulaanbaatar</strong>',
		answerDescriptionHtml: 'Capital of <strong>Mongolia</strong>',
		pathToMedia: null,
		category: 'world-country-capitals-asia',
	},
	{
		questionTitleHtml: '<strong>Myanmar (Burma)</strong>',
		questionDescriptionHtml: 'What is the capital of this country?',
		answerTitleHtml: '<strong>Naypyidaw</strong>',
		answerDescriptionHtml: 'Capital of <strong>Myanmar (Burma)</strong>',
		pathToMedia: null,
		category: 'world-country-capitals-asia',
	},
	{
		questionTitleHtml: '<strong>Nepal</strong>',
		questionDescriptionHtml: 'What is the capital of this country?',
		answerTitleHtml: '<strong>Kathmandu</strong>',
		answerDescriptionHtml: 'Capital of <strong>Nepal</strong>',
		pathToMedia: null,
		category: 'world-country-capitals-asia',
	},
	{
		questionTitleHtml: '<strong>North Korea</strong>',
		questionDescriptionHtml: 'What is the capital of this country?',
		answerTitleHtml: '<strong>Pyongyang</strong>',
		answerDescriptionHtml: 'Capital of <strong>North Korea</strong>',
		pathToMedia: null,
		category: 'world-country-capitals-asia',
	},
	{
		questionTitleHtml: '<strong>Oman</strong>',
		questionDescriptionHtml: 'What is the capital of this country?',
		answerTitleHtml: '<strong>Muscat</strong>',
		answerDescriptionHtml: 'Capital of <strong>Oman</strong>',
		pathToMedia: null,
		category: 'world-country-capitals-asia',
	},
	{
		questionTitleHtml: '<strong>Pakistan</strong>',
		questionDescriptionHtml: 'What is the capital of this country?',
		answerTitleHtml: '<strong>Islamabad</strong>',
		answerDescriptionHtml: 'Capital of <strong>Pakistan</strong>',
		pathToMedia: null,
		category: 'world-country-capitals-asia',
	},
	{
		questionTitleHtml: '<strong>Palestine</strong>',
		questionDescriptionHtml: 'What is the capital of this country?',
		answerTitleHtml: '<strong>East Jerusalem (claimed), Ramallah (administrative)</strong>',
		answerDescriptionHtml: 'Capital of <strong>Palestine</strong>',
		pathToMedia: null,
		category: 'world-country-capitals-asia',
	},
	{
		questionTitleHtml: '<strong>Philippines</strong>',
		questionDescriptionHtml: 'What is the capital of this country?',
		answerTitleHtml: '<strong>Manila</strong>',
		answerDescriptionHtml: 'Capital of <strong>Philippines</strong>',
		pathToMedia: null,
		category: 'world-country-capitals-asia',
	},
	{
		questionTitleHtml: '<strong>Qatar</strong>',
		questionDescriptionHtml: 'What is the capital of this country?',
		answerTitleHtml: '<strong>Doha</strong>',
		answerDescriptionHtml: 'Capital of <strong>Qatar</strong>',
		pathToMedia: null,
		category: 'world-country-capitals-asia',
	},
	{
		questionTitleHtml: '<strong>Saudi Arabia</strong>',
		questionDescriptionHtml: 'What is the capital of this country?',
		answerTitleHtml: '<strong>Riyadh</strong>',
		answerDescriptionHtml: 'Capital of <strong>Saudi Arabia</strong>',
		pathToMedia: null,
		category: 'world-country-capitals-asia',
	},
	{
		questionTitleHtml: '<strong>Singapore</strong>',
		questionDescriptionHtml: 'What is the capital of this country?',
		answerTitleHtml: '<strong>Singapore</strong>',
		answerDescriptionHtml: 'Capital of <strong>Singapore</strong>',
		pathToMedia: null,
		category: 'world-country-capitals-asia',
	},
	{
		questionTitleHtml: '<strong>South Korea</strong>',
		questionDescriptionHtml: 'What is the capital of this country?',
		answerTitleHtml: '<strong>Seoul</strong>',
		answerDescriptionHtml: 'Capital of <strong>South Korea</strong>',
		pathToMedia: null,
		category: 'world-country-capitals-asia',
	},
	{
		questionTitleHtml: '<strong>Sri Lanka</strong>',
		questionDescriptionHtml: 'What is the capital of this country?',
		answerTitleHtml: '<strong>Colombo (commercial), Sri Jayawardenepura Kotte (legislative)</strong>',
		answerDescriptionHtml: 'Capital of <strong>Sri Lanka</strong>',
		pathToMedia: null,
		category: 'world-country-capitals-asia',
	},
	{
		questionTitleHtml: '<strong>Syria</strong>',
		questionDescriptionHtml: 'What is the capital of this country?',
		answerTitleHtml: '<strong>Damascus</strong>',
		answerDescriptionHtml: 'Capital of <strong>Syria</strong>',
		pathToMedia: null,
		category: 'world-country-capitals-asia',
	},
	{
		questionTitleHtml: '<strong>Tajikistan</strong>',
		questionDescriptionHtml: 'What is the capital of this country?',
		answerTitleHtml: '<strong>Dushanbe</strong>',
		answerDescriptionHtml: 'Capital of <strong>Tajikistan</strong>',
		pathToMedia: null,
		category: 'world-country-capitals-asia',
	},
	{
		questionTitleHtml: '<strong>Thailand</strong>',
		questionDescriptionHtml: 'What is the capital of this country?',
		answerTitleHtml: '<strong>Bangkok</strong>',
		answerDescriptionHtml: 'Capital of <strong>Thailand</strong>',
		pathToMedia: null,
		category: 'world-country-capitals-asia',
	},
	{
		questionTitleHtml: '<strong>Turkmenistan</strong>',
		questionDescriptionHtml: 'What is the capital of this country?',
		answerTitleHtml: '<strong>Ashgabat</strong>',
		answerDescriptionHtml: 'Capital of <strong>Turkmenistan</strong>',
		pathToMedia: null,
		category: 'world-country-capitals-asia',
	},
	{
		questionTitleHtml: '<strong>United Arab Emirates</strong>',
		questionDescriptionHtml: 'What is the capital of this country?',
		answerTitleHtml: '<strong>Abu Dhabi</strong>',
		answerDescriptionHtml: 'Capital of <strong>United Arab Emirates</strong>',
		pathToMedia: null,
		category: 'world-country-capitals-asia',
	},
	{
		questionTitleHtml: '<strong>Uzbekistan</strong>',
		questionDescriptionHtml: 'What is the capital of this country?',
		answerTitleHtml: '<strong>Tashkent</strong>',
		answerDescriptionHtml: 'Capital of <strong>Uzbekistan</strong>',
		pathToMedia: null,
		category: 'world-country-capitals-asia',
	},
	{
		questionTitleHtml: '<strong>Vietnam</strong>',
		questionDescriptionHtml: 'What is the capital of this country?',
		answerTitleHtml: '<strong>Hanoi</strong>',
		answerDescriptionHtml: 'Capital of <strong>Vietnam</strong>',
		pathToMedia: null,
		category: 'world-country-capitals-asia',
	},
	{
		questionTitleHtml: '<strong>Yemen</strong>',
		questionDescriptionHtml: 'What is the capital of this country?',
		answerTitleHtml: '<strong>Sana\'a</strong>',
		answerDescriptionHtml: 'Capital of <strong>Yemen</strong>',
		pathToMedia: null,
		category: 'world-country-capitals-asia',
	},
]
