import type { FlashCard } from '@/types'

export const world_country_flags_south_america: FlashCard[] = [
	{
		questionTitleHtml: '<strong>What country is this flag?</strong>',
		questionDescriptionHtml: '',
		answerTitleHtml: '<strong>Argentina</strong>',
		answerDescriptionHtml: 'Country Flag',
		pathToMedia: 'node_modules/svg-country-flags/svg/ar.svg',
		category: 'world-country-flags-south-america',
	},
	{
		questionTitleHtml: '<strong>What country is this flag?</strong>',
		questionDescriptionHtml: '',
		answerTitleHtml: '<strong>Bolivia</strong>',
		answerDescriptionHtml: 'Country Flag',
		pathToMedia: 'node_modules/svg-country-flags/svg/bo.svg',
		category: 'world-country-flags-south-america',
	},
	{
		questionTitleHtml: '<strong>What country is this flag?</strong>',
		questionDescriptionHtml: '',
		answerTitleHtml: '<strong>Brazil</strong>',
		answerDescriptionHtml: 'Country Flag',
		pathToMedia: 'node_modules/svg-country-flags/svg/br.svg',
		category: 'world-country-flags-south-america',
	},
	{
		questionTitleHtml: '<strong>What country is this flag?</strong>',
		questionDescriptionHtml: '',
		answerTitleHtml: '<strong>Chile</strong>',
		answerDescriptionHtml: 'Country Flag',
		pathToMedia: 'node_modules/svg-country-flags/svg/cl.svg',
		category: 'world-country-flags-south-america',
	},
	{
		questionTitleHtml: '<strong>What country is this flag?</strong>',
		questionDescriptionHtml: '',
		answerTitleHtml: '<strong>Colombia</strong>',
		answerDescriptionHtml: 'Country Flag',
		pathToMedia: 'node_modules/svg-country-flags/svg/co.svg',
		category: 'world-country-flags-south-america',
	},
	{
		questionTitleHtml: '<strong>What country is this flag?</strong>',
		questionDescriptionHtml: '',
		answerTitleHtml: '<strong>Ecuador</strong>',
		answerDescriptionHtml: 'Country Flag',
		pathToMedia: 'node_modules/svg-country-flags/svg/ec.svg',
		category: 'world-country-flags-south-america',
	},
	{
		questionTitleHtml: '<strong>What country is this flag?</strong>',
		questionDescriptionHtml: '',
		answerTitleHtml: '<strong>Guyana</strong>',
		answerDescriptionHtml: 'Country Flag',
		pathToMedia: 'node_modules/svg-country-flags/svg/gy.svg',
		category: 'world-country-flags-south-america',
	},
	{
		questionTitleHtml: '<strong>What country is this flag?</strong>',
		questionDescriptionHtml: '',
		answerTitleHtml: '<strong>Paraguay</strong>',
		answerDescriptionHtml: 'Country Flag',
		pathToMedia: 'node_modules/svg-country-flags/svg/py.svg',
		category: 'world-country-flags-south-america',
		censorBlocks: [
			{ top: '41%', left: '52%', width: '4%', height: '15%' }, // "PARAGUAY" text
		],
	},
	{
		questionTitleHtml: '<strong>What country is this flag?</strong>',
		questionDescriptionHtml: '',
		answerTitleHtml: '<strong>Peru</strong>',
		answerDescriptionHtml: 'Country Flag',
		pathToMedia: 'node_modules/svg-country-flags/svg/pe.svg',
		category: 'world-country-flags-south-america',
	},
	{
		questionTitleHtml: '<strong>What country is this flag?</strong>',
		questionDescriptionHtml: '',
		answerTitleHtml: '<strong>Suriname</strong>',
		answerDescriptionHtml: 'Country Flag',
		pathToMedia: 'node_modules/svg-country-flags/svg/sr.svg',
		category: 'world-country-flags-south-america',
	},
	{
		questionTitleHtml: '<strong>What country is this flag?</strong>',
		questionDescriptionHtml: '',
		answerTitleHtml: '<strong>Uruguay</strong>',
		answerDescriptionHtml: 'Country Flag',
		pathToMedia: 'node_modules/svg-country-flags/svg/uy.svg',
		category: 'world-country-flags-south-america',
	},
	{
		questionTitleHtml: '<strong>What country is this flag?</strong>',
		questionDescriptionHtml: '',
		answerTitleHtml: '<strong>Venezuela</strong>',
		answerDescriptionHtml: 'Country Flag',
		pathToMedia: 'node_modules/svg-country-flags/svg/ve.svg',
		category: 'world-country-flags-south-america',
	},
]
