import type { FlashCard } from '@/types'

export const world_country_locations_languages_europe: FlashCard[] = [
	{
		questionTitleHtml: '<strong>What\'s this country in Europe?</strong>',
		questionDescriptionHtml: 'And its principal language',
		answerTitleHtml: '<strong>Albania</strong>',
		answerDescriptionHtml: 'Location: Southeastern Europe (Balkans)<br>Principal Language: Albanian',
		pathToMedia: 'images/world-country-locations/europe/albania.png',
		category: 'world-country-locations-languages-europe',
	},
	{
		questionTitleHtml: '<strong>What\'s this country in Europe?</strong>',
		questionDescriptionHtml: 'And its principal language',
		answerTitleHtml: '<strong>Armenia</strong>',
		answerDescriptionHtml: 'Location: Western Asia (Caucasus)<br>Principal Language: Armenian',
		pathToMedia: 'images/world-country-locations/europe/armenia.png',
		category: 'world-country-locations-languages-europe',
	},
	{
		questionTitleHtml: '<strong>What\'s this country in Europe?</strong>',
		questionDescriptionHtml: 'And its principal language',
		answerTitleHtml: '<strong>Austria</strong>',
		answerDescriptionHtml: 'Location: Central Europe<br>Principal Language: German',
		pathToMedia: 'images/world-country-locations/europe/austria.png',
		category: 'world-country-locations-languages-europe',
	},
	{
		questionTitleHtml: '<strong>What\'s this country in Europe?</strong>',
		questionDescriptionHtml: 'And its principal language',
		answerTitleHtml: '<strong>Belgium</strong>',
		answerDescriptionHtml: 'Location: Western Europe<br>Principal Language: Dutch',
		pathToMedia: 'images/world-country-locations/europe/belgium.png',
		category: 'world-country-locations-languages-europe',
	},
	{
		questionTitleHtml: '<strong>What\'s this country in Europe?</strong>',
		questionDescriptionHtml: 'And its principal language',
		answerTitleHtml: '<strong>Bosnia and Herzegovina</strong>',
		answerDescriptionHtml: 'Location: Southeastern Europe (Balkans)<br>Principal Language: Bosnian',
		pathToMedia: 'images/world-country-locations/europe/bosnia-and-herzegovina.png',
		category: 'world-country-locations-languages-europe',
	},
	{
		questionTitleHtml: '<strong>What\'s this country in Europe?</strong>',
		questionDescriptionHtml: 'And its principal language',
		answerTitleHtml: '<strong>Bulgaria</strong>',
		answerDescriptionHtml: 'Location: Southeastern Europe<br>Principal Language: Bulgarian',
		pathToMedia: 'images/world-country-locations/europe/bulgaria.png',
		category: 'world-country-locations-languages-europe',
	},
	{
		questionTitleHtml: '<strong>What\'s this country in Europe?</strong>',
		questionDescriptionHtml: 'And its principal language',
		answerTitleHtml: '<strong>Croatia</strong>',
		answerDescriptionHtml: 'Location: Southeastern Europe<br>Principal Language: Croatian',
		pathToMedia: 'images/world-country-locations/europe/croatia.png',
		category: 'world-country-locations-languages-europe',
	},
	{
		questionTitleHtml: '<strong>What\'s this country in Europe?</strong>',
		questionDescriptionHtml: 'And its principal language',
		answerTitleHtml: '<strong>Czech Republic</strong>',
		answerDescriptionHtml: 'Location: Central Europe<br>Principal Language: Czech',
		pathToMedia: 'images/world-country-locations/europe/czech-republic.png',
		category: 'world-country-locations-languages-europe',
	},
	{
		questionTitleHtml: '<strong>What\'s this country in Europe?</strong>',
		questionDescriptionHtml: 'And its principal language',
		answerTitleHtml: '<strong>Denmark</strong>',
		answerDescriptionHtml: 'Location: Northern Europe (Scandinavia)<br>Principal Language: Danish',
		pathToMedia: 'images/world-country-locations/europe/denmark.png',
		category: 'world-country-locations-languages-europe',
	},
	{
		questionTitleHtml: '<strong>What\'s this country in Europe?</strong>',
		questionDescriptionHtml: 'And its principal language',
		answerTitleHtml: '<strong>Estonia</strong>',
		answerDescriptionHtml: 'Location: Northern Europe (Baltic)<br>Principal Language: Estonian',
		pathToMedia: 'images/world-country-locations/europe/estonia.png',
		category: 'world-country-locations-languages-europe',
	},
	{
		questionTitleHtml: '<strong>What\'s this country in Europe?</strong>',
		questionDescriptionHtml: 'And its principal language',
		answerTitleHtml: '<strong>Finland</strong>',
		answerDescriptionHtml: 'Location: Northern Europe<br>Principal Language: Finnish',
		pathToMedia: 'images/world-country-locations/europe/finland.png',
		category: 'world-country-locations-languages-europe',
	},
	{
		questionTitleHtml: '<strong>What\'s this country in Europe?</strong>',
		questionDescriptionHtml: 'And its principal language',
		answerTitleHtml: '<strong>France</strong>',
		answerDescriptionHtml: 'Location: Western Europe<br>Principal Language: French',
		pathToMedia: 'images/world-country-locations/europe/france.png',
		category: 'world-country-locations-languages-europe',
	},
	{
		questionTitleHtml: '<strong>What\'s this country in Europe?</strong>',
		questionDescriptionHtml: 'And its principal language',
		answerTitleHtml: '<strong>Georgia</strong>',
		answerDescriptionHtml: 'Location: Western Asia (Caucasus)<br>Principal Language: Georgian',
		pathToMedia: 'images/world-country-locations/europe/georgia.png',
		category: 'world-country-locations-languages-europe',
	},
	{
		questionTitleHtml: '<strong>What\'s this country in Europe?</strong>',
		questionDescriptionHtml: 'And its principal language',
		answerTitleHtml: '<strong>Germany</strong>',
		answerDescriptionHtml: 'Location: Central Europe<br>Principal Language: German',
		pathToMedia: 'images/world-country-locations/europe/germany.png',
		category: 'world-country-locations-languages-europe',
	},
	{
		questionTitleHtml: '<strong>What\'s this country in Europe?</strong>',
		questionDescriptionHtml: 'And its principal language',
		answerTitleHtml: '<strong>Greece</strong>',
		answerDescriptionHtml: 'Location: Southeastern Europe<br>Principal Language: Greek',
		pathToMedia: 'images/world-country-locations/europe/greece.png',
		category: 'world-country-locations-languages-europe',
	},
	{
		questionTitleHtml: '<strong>What\'s this country in Europe?</strong>',
		questionDescriptionHtml: 'And its principal language',
		answerTitleHtml: '<strong>Hungary</strong>',
		answerDescriptionHtml: 'Location: Central Europe<br>Principal Language: Hungarian',
		pathToMedia: 'images/world-country-locations/europe/hungary.png',
		category: 'world-country-locations-languages-europe',
	},
	{
		questionTitleHtml: '<strong>What\'s this country in Europe?</strong>',
		questionDescriptionHtml: 'And its principal language',
		answerTitleHtml: '<strong>Iceland</strong>',
		answerDescriptionHtml: 'Location: Northern Europe (North Atlantic)<br>Principal Language: Icelandic',
		pathToMedia: 'images/world-country-locations/europe/iceland.png',
		category: 'world-country-locations-languages-europe',
	},
	{
		questionTitleHtml: '<strong>What\'s this country in Europe?</strong>',
		questionDescriptionHtml: 'And its principal language',
		answerTitleHtml: '<strong>Ireland</strong>',
		answerDescriptionHtml: 'Location: Northern Europe<br>Principal Language: English',
		pathToMedia: 'images/world-country-locations/europe/ireland.png',
		category: 'world-country-locations-languages-europe',
	},
	{
		questionTitleHtml: '<strong>What\'s this country in Europe?</strong>',
		questionDescriptionHtml: 'And its principal language',
		answerTitleHtml: '<strong>Italy</strong>',
		answerDescriptionHtml: 'Location: Southern Europe<br>Principal Language: Italian',
		pathToMedia: 'images/world-country-locations/europe/italy.png',
		category: 'world-country-locations-languages-europe',
	},
	{
		questionTitleHtml: '<strong>What\'s this country in Europe?</strong>',
		questionDescriptionHtml: 'And its principal language',
		answerTitleHtml: '<strong>Latvia</strong>',
		answerDescriptionHtml: 'Location: Northern Europe (Baltic)<br>Principal Language: Latvian',
		pathToMedia: 'images/world-country-locations/europe/latvia.png',
		category: 'world-country-locations-languages-europe',
	},
	{
		questionTitleHtml: '<strong>What\'s this country in Europe?</strong>',
		questionDescriptionHtml: 'And its principal language',
		answerTitleHtml: '<strong>Liechtenstein</strong>',
		answerDescriptionHtml: 'Location: Central Europe<br>Principal Language: German',
		pathToMedia: 'images/world-country-locations/europe/liechtenstein.png',
		category: 'world-country-locations-languages-europe',
	},
	{
		questionTitleHtml: '<strong>What\'s this country in Europe?</strong>',
		questionDescriptionHtml: 'And its principal language',
		answerTitleHtml: '<strong>Lithuania</strong>',
		answerDescriptionHtml: 'Location: Northern Europe (Baltic)<br>Principal Language: Lithuanian',
		pathToMedia: 'images/world-country-locations/europe/lithuania.png',
		category: 'world-country-locations-languages-europe',
	},
	{
		questionTitleHtml: '<strong>What\'s this country in Europe?</strong>',
		questionDescriptionHtml: 'And its principal language',
		answerTitleHtml: '<strong>Luxembourg</strong>',
		answerDescriptionHtml: 'Location: Western Europe<br>Principal Language: Luxembourgish',
		pathToMedia: 'images/world-country-locations/europe/luxembourg.png',
		category: 'world-country-locations-languages-europe',
	},
	{
		questionTitleHtml: '<strong>What\'s this country in Europe?</strong>',
		questionDescriptionHtml: 'And its principal language',
		answerTitleHtml: '<strong>Macedonia (North Macedonia)</strong>',
		answerDescriptionHtml: 'Location: Southeastern Europe (Balkans)<br>Principal Language: Macedonian',
		pathToMedia: 'images/world-country-locations/europe/north-macedonia.png',
		category: 'world-country-locations-languages-europe',
	},
	{
		questionTitleHtml: '<strong>What\'s this country in Europe?</strong>',
		questionDescriptionHtml: 'And its principal language',
		answerTitleHtml: '<strong>Malta</strong>',
		answerDescriptionHtml: 'Location: Southern Europe (Mediterranean)<br>Principal Language: Maltese',
		pathToMedia: 'images/world-country-locations/europe/malta.png',
		category: 'world-country-locations-languages-europe',
	},
	{
		questionTitleHtml: '<strong>What\'s this country in Europe?</strong>',
		questionDescriptionHtml: 'And its principal language',
		answerTitleHtml: '<strong>Moldova</strong>',
		answerDescriptionHtml: 'Location: Eastern Europe<br>Principal Language: Romanian',
		pathToMedia: 'images/world-country-locations/europe/moldova.png',
		category: 'world-country-locations-languages-europe',
	},
	{
		questionTitleHtml: '<strong>What\'s this country in Europe?</strong>',
		questionDescriptionHtml: 'And its principal language',
		answerTitleHtml: '<strong>Monaco</strong>',
		answerDescriptionHtml: 'Location: Western Europe<br>Principal Language: French',
		pathToMedia: 'images/world-country-locations/europe/monaco.png',
		category: 'world-country-locations-languages-europe',
	},
	{
		questionTitleHtml: '<strong>What\'s this country in Europe?</strong>',
		questionDescriptionHtml: 'And its principal language',
		answerTitleHtml: '<strong>Montenegro</strong>',
		answerDescriptionHtml: 'Location: Southeastern Europe (Balkans)<br>Principal Language: Montenegrin',
		pathToMedia: 'images/world-country-locations/europe/montenegro.png',
		category: 'world-country-locations-languages-europe',
	},
	{
		questionTitleHtml: '<strong>What\'s this country in Europe?</strong>',
		questionDescriptionHtml: 'And its principal language',
		answerTitleHtml: '<strong>Netherlands</strong>',
		answerDescriptionHtml: 'Location: Western Europe<br>Principal Language: Dutch',
		pathToMedia: 'images/world-country-locations/europe/netherlands.png',
		category: 'world-country-locations-languages-europe',
	},
	{
		questionTitleHtml: '<strong>What\'s this country in Europe?</strong>',
		questionDescriptionHtml: 'And its principal language',
		answerTitleHtml: '<strong>Norway</strong>',
		answerDescriptionHtml: 'Location: Northern Europe (Scandinavia)<br>Principal Language: Norwegian',
		pathToMedia: 'images/world-country-locations/europe/norway.png',
		category: 'world-country-locations-languages-europe',
	},
	{
		questionTitleHtml: '<strong>What\'s this country in Europe?</strong>',
		questionDescriptionHtml: 'And its principal language',
		answerTitleHtml: '<strong>Poland</strong>',
		answerDescriptionHtml: 'Location: Central Europe<br>Principal Language: Polish',
		pathToMedia: 'images/world-country-locations/europe/poland.png',
		category: 'world-country-locations-languages-europe',
	},
	{
		questionTitleHtml: '<strong>What\'s this country in Europe?</strong>',
		questionDescriptionHtml: 'And its principal language',
		answerTitleHtml: '<strong>Portugal</strong>',
		answerDescriptionHtml: 'Location: Southern Europe<br>Principal Language: Portuguese',
		pathToMedia: 'images/world-country-locations/europe/portugal.png',
		category: 'world-country-locations-languages-europe',
	},
	{
		questionTitleHtml: '<strong>What\'s this country in Europe?</strong>',
		questionDescriptionHtml: 'And its principal language',
		answerTitleHtml: '<strong>Romania</strong>',
		answerDescriptionHtml: 'Location: Eastern Europe<br>Principal Language: Romanian',
		pathToMedia: 'images/world-country-locations/europe/romania.png',
		category: 'world-country-locations-languages-europe',
	},
	{
		questionTitleHtml: '<strong>What\'s this country in Europe?</strong>',
		questionDescriptionHtml: 'And its principal language',
		answerTitleHtml: '<strong>Russia</strong>',
		answerDescriptionHtml: 'Location: Eastern Europe/Asia<br>Principal Language: Russian',
		pathToMedia: 'images/world-country-locations/europe/russia.png',
		category: 'world-country-locations-languages-europe',
	},
	{
		questionTitleHtml: '<strong>What\'s this country in Europe?</strong>',
		questionDescriptionHtml: 'And its principal language',
		answerTitleHtml: '<strong>Serbia</strong>',
		answerDescriptionHtml: 'Location: Southeastern Europe (Balkans)<br>Principal Language: Serbian',
		pathToMedia: 'images/world-country-locations/europe/serbia.png',
		category: 'world-country-locations-languages-europe',
	},
	{
		questionTitleHtml: '<strong>What\'s this country in Europe?</strong>',
		questionDescriptionHtml: 'And its principal language',
		answerTitleHtml: '<strong>Slovakia</strong>',
		answerDescriptionHtml: 'Location: Central Europe<br>Principal Language: Slovak',
		pathToMedia: 'images/world-country-locations/europe/slovakia.png',
		category: 'world-country-locations-languages-europe',
	},
	{
		questionTitleHtml: '<strong>What\'s this country in Europe?</strong>',
		questionDescriptionHtml: 'And its principal language',
		answerTitleHtml: '<strong>Slovenia</strong>',
		answerDescriptionHtml: 'Location: Southern Europe<br>Principal Language: Slovenian',
		pathToMedia: 'images/world-country-locations/europe/slovenia.png',
		category: 'world-country-locations-languages-europe',
	},
	{
		questionTitleHtml: '<strong>What\'s this country in Europe?</strong>',
		questionDescriptionHtml: 'And its principal language',
		answerTitleHtml: '<strong>Spain</strong>',
		answerDescriptionHtml: 'Location: Southern Europe<br>Principal Language: Spanish',
		pathToMedia: 'images/world-country-locations/europe/spain.png',
		category: 'world-country-locations-languages-europe',
	},
	{
		questionTitleHtml: '<strong>What\'s this country in Europe?</strong>',
		questionDescriptionHtml: 'And its principal language',
		answerTitleHtml: '<strong>Sweden</strong>',
		answerDescriptionHtml: 'Location: Northern Europe (Scandinavia)<br>Principal Language: Swedish',
		pathToMedia: 'images/world-country-locations/europe/sweden.png',
		category: 'world-country-locations-languages-europe',
	},
	{
		questionTitleHtml: '<strong>What\'s this country in Europe?</strong>',
		questionDescriptionHtml: 'And its principal language',
		answerTitleHtml: '<strong>Switzerland</strong>',
		answerDescriptionHtml: 'Location: Central Europe<br>Principal Language: German',
		pathToMedia: 'images/world-country-locations/europe/switzerland.png',
		category: 'world-country-locations-languages-europe',
	},
	{
		questionTitleHtml: '<strong>What\'s this country in Europe?</strong>',
		questionDescriptionHtml: 'And its principal language',
		answerTitleHtml: '<strong>Turkey</strong>',
		answerDescriptionHtml: 'Location: Western Asia/Southeastern Europe<br>Principal Language: Turkish',
		pathToMedia: 'images/world-country-locations/europe/turkey.png',
		category: 'world-country-locations-languages-europe',
	},
	{
		questionTitleHtml: '<strong>What\'s this country in Europe?</strong>',
		questionDescriptionHtml: 'And its principal language',
		answerTitleHtml: '<strong>Ukraine</strong>',
		answerDescriptionHtml: 'Location: Eastern Europe<br>Principal Language: Ukrainian',
		pathToMedia: 'images/world-country-locations/europe/ukraine.png',
		category: 'world-country-locations-languages-europe',
	},
	{
		questionTitleHtml: '<strong>What\'s this country in Europe?</strong>',
		questionDescriptionHtml: 'And its principal language',
		answerTitleHtml: '<strong>United Kingdom</strong>',
		answerDescriptionHtml: 'Location: Northern Europe<br>Principal Language: English',
		pathToMedia: 'images/world-country-locations/europe/united-kingdom.png',
		category: 'world-country-locations-languages-europe',
	},
	{
		questionTitleHtml: '<strong>What\'s this country in Europe?</strong>',
		questionDescriptionHtml: 'And its principal language',
		answerTitleHtml: '<strong>Vatican City</strong>',
		answerDescriptionHtml: 'Location: Southern Europe (within Rome, Italy)<br>Principal Language: Italian',
		pathToMedia: 'images/world-country-locations/europe/vatican-city.png',
		category: 'world-country-locations-languages-europe',
	},
]
