import type { FlashCard } from '@/types'

export const world_country_locations_languages_asia: FlashCard[] = [
	{
		questionTitleHtml: '<strong>Afghanistan</strong>',
		questionDescriptionHtml: 'What is the location and principal language of this country?',
		answerTitleHtml: '<strong>Afghanistan</strong>',
		answerDescriptionHtml: 'Location: Central/South Asia<br>Principal Language: Pashto',
		pathToMedia: 'placeholder',
		category: 'world-country-locations-languages-asia',
	},
	{
		questionTitleHtml: '<strong>Bangladesh</strong>',
		questionDescriptionHtml: 'What is the location and principal language of this country?',
		answerTitleHtml: '<strong>Bangladesh</strong>',
		answerDescriptionHtml: 'Location: South Asia<br>Principal Language: Bengali',
		pathToMedia: 'placeholder',
		category: 'world-country-locations-languages-asia',
	},
	{
		questionTitleHtml: '<strong>Burma (Myanmar)</strong>',
		questionDescriptionHtml: 'What is the location and principal language of this country?',
		answerTitleHtml: '<strong>Burma (Myanmar)</strong>',
		answerDescriptionHtml: 'Location: Southeast Asia<br>Principal Language: Burmese',
		pathToMedia: 'placeholder',
		category: 'world-country-locations-languages-asia',
	},
	{
		questionTitleHtml: '<strong>Cambodia</strong>',
		questionDescriptionHtml: 'What is the location and principal language of this country?',
		answerTitleHtml: '<strong>Cambodia</strong>',
		answerDescriptionHtml: 'Location: Southeast Asia<br>Principal Language: Khmer',
		pathToMedia: 'placeholder',
		category: 'world-country-locations-languages-asia',
	},
	{
		questionTitleHtml: '<strong>China</strong>',
		questionDescriptionHtml: 'What is the location and principal language of this country?',
		answerTitleHtml: '<strong>China</strong>',
		answerDescriptionHtml: 'Location: East Asia<br>Principal Language: Mandarin Chinese',
		pathToMedia: 'placeholder',
		category: 'world-country-locations-languages-asia',
	},
	{
		questionTitleHtml: '<strong>India</strong>',
		questionDescriptionHtml: 'What is the location and principal language of this country?',
		answerTitleHtml: '<strong>India</strong>',
		answerDescriptionHtml: 'Location: South Asia<br>Principal Language: Hindi',
		pathToMedia: 'placeholder',
		category: 'world-country-locations-languages-asia',
	},
	{
		questionTitleHtml: '<strong>Indonesia</strong>',
		questionDescriptionHtml: 'What is the location and principal language of this country?',
		answerTitleHtml: '<strong>Indonesia</strong>',
		answerDescriptionHtml: 'Location: Southeast Asia<br>Principal Language: Indonesian',
		pathToMedia: 'placeholder',
		category: 'world-country-locations-languages-asia',
	},
	{
		questionTitleHtml: '<strong>Iran</strong>',
		questionDescriptionHtml: 'What is the location and principal language of this country?',
		answerTitleHtml: '<strong>Iran</strong>',
		answerDescriptionHtml: 'Location: Western Asia (Middle East)<br>Principal Language: Persian (Farsi)',
		pathToMedia: 'placeholder',
		category: 'world-country-locations-languages-asia',
	},
	{
		questionTitleHtml: '<strong>Iraq</strong>',
		questionDescriptionHtml: 'What is the location and principal language of this country?',
		answerTitleHtml: '<strong>Iraq</strong>',
		answerDescriptionHtml: 'Location: Western Asia (Middle East)<br>Principal Language: Arabic',
		pathToMedia: 'placeholder',
		category: 'world-country-locations-languages-asia',
	},
	{
		questionTitleHtml: '<strong>Israel</strong>',
		questionDescriptionHtml: 'What is the location and principal language of this country?',
		answerTitleHtml: '<strong>Israel</strong>',
		answerDescriptionHtml: 'Location: Western Asia (Middle East)<br>Principal Language: Hebrew',
		pathToMedia: 'placeholder',
		category: 'world-country-locations-languages-asia',
	},
	{
		questionTitleHtml: '<strong>Japan</strong>',
		questionDescriptionHtml: 'What is the location and principal language of this country?',
		answerTitleHtml: '<strong>Japan</strong>',
		answerDescriptionHtml: 'Location: East Asia<br>Principal Language: Japanese',
		pathToMedia: 'placeholder',
		category: 'world-country-locations-languages-asia',
	},
	{
		questionTitleHtml: '<strong>Jordan</strong>',
		questionDescriptionHtml: 'What is the location and principal language of this country?',
		answerTitleHtml: '<strong>Jordan</strong>',
		answerDescriptionHtml: 'Location: Western Asia (Middle East)<br>Principal Language: Arabic',
		pathToMedia: 'placeholder',
		category: 'world-country-locations-languages-asia',
	},
	{
		questionTitleHtml: '<strong>Kuwait</strong>',
		questionDescriptionHtml: 'What is the location and principal language of this country?',
		answerTitleHtml: '<strong>Kuwait</strong>',
		answerDescriptionHtml: 'Location: Western Asia (Middle East)<br>Principal Language: Arabic',
		pathToMedia: 'placeholder',
		category: 'world-country-locations-languages-asia',
	},
	{
		questionTitleHtml: '<strong>Kyrgyzstan</strong>',
		questionDescriptionHtml: 'What is the location and principal language of this country?',
		answerTitleHtml: '<strong>Kyrgyzstan</strong>',
		answerDescriptionHtml: 'Location: Central Asia<br>Principal Language: Kyrgyz',
		pathToMedia: 'placeholder',
		category: 'world-country-locations-languages-asia',
	},
	{
		questionTitleHtml: '<strong>Laos</strong>',
		questionDescriptionHtml: 'What is the location and principal language of this country?',
		answerTitleHtml: '<strong>Laos</strong>',
		answerDescriptionHtml: 'Location: Southeast Asia<br>Principal Language: Lao',
		pathToMedia: 'placeholder',
		category: 'world-country-locations-languages-asia',
	},
	{
		questionTitleHtml: '<strong>Lebanon</strong>',
		questionDescriptionHtml: 'What is the location and principal language of this country?',
		answerTitleHtml: '<strong>Lebanon</strong>',
		answerDescriptionHtml: 'Location: Western Asia (Middle East)<br>Principal Language: Arabic',
		pathToMedia: 'placeholder',
		category: 'world-country-locations-languages-asia',
	},
	{
		questionTitleHtml: '<strong>Malaysia</strong>',
		questionDescriptionHtml: 'What is the location and principal language of this country?',
		answerTitleHtml: '<strong>Malaysia</strong>',
		answerDescriptionHtml: 'Location: Southeast Asia<br>Principal Language: Malay',
		pathToMedia: 'placeholder',
		category: 'world-country-locations-languages-asia',
	},
	{
		questionTitleHtml: '<strong>Mongolia</strong>',
		questionDescriptionHtml: 'What is the location and principal language of this country?',
		answerTitleHtml: '<strong>Mongolia</strong>',
		answerDescriptionHtml: 'Location: East Asia<br>Principal Language: Mongolian',
		pathToMedia: 'placeholder',
		category: 'world-country-locations-languages-asia',
	},
	{
		questionTitleHtml: '<strong>Myanmar (Burma)</strong>',
		questionDescriptionHtml: 'What is the location and principal language of this country?',
		answerTitleHtml: '<strong>Myanmar (Burma)</strong>',
		answerDescriptionHtml: 'Location: Southeast Asia<br>Principal Language: Burmese',
		pathToMedia: 'placeholder',
		category: 'world-country-locations-languages-asia',
	},
	{
		questionTitleHtml: '<strong>Nepal</strong>',
		questionDescriptionHtml: 'What is the location and principal language of this country?',
		answerTitleHtml: '<strong>Nepal</strong>',
		answerDescriptionHtml: 'Location: South Asia<br>Principal Language: Nepali',
		pathToMedia: 'placeholder',
		category: 'world-country-locations-languages-asia',
	},
	{
		questionTitleHtml: '<strong>North Korea</strong>',
		questionDescriptionHtml: 'What is the location and principal language of this country?',
		answerTitleHtml: '<strong>North Korea</strong>',
		answerDescriptionHtml: 'Location: East Asia<br>Principal Language: Korean',
		pathToMedia: 'placeholder',
		category: 'world-country-locations-languages-asia',
	},
	{
		questionTitleHtml: '<strong>Oman</strong>',
		questionDescriptionHtml: 'What is the location and principal language of this country?',
		answerTitleHtml: '<strong>Oman</strong>',
		answerDescriptionHtml: 'Location: Western Asia (Middle East)<br>Principal Language: Arabic',
		pathToMedia: 'placeholder',
		category: 'world-country-locations-languages-asia',
	},
	{
		questionTitleHtml: '<strong>Pakistan</strong>',
		questionDescriptionHtml: 'What is the location and principal language of this country?',
		answerTitleHtml: '<strong>Pakistan</strong>',
		answerDescriptionHtml: 'Location: South Asia<br>Principal Language: Urdu',
		pathToMedia: 'placeholder',
		category: 'world-country-locations-languages-asia',
	},
	{
		questionTitleHtml: '<strong>Palestine</strong>',
		questionDescriptionHtml: 'What is the location and principal language of this country?',
		answerTitleHtml: '<strong>Palestine</strong>',
		answerDescriptionHtml: 'Location: Western Asia (Middle East)<br>Principal Language: Arabic',
		pathToMedia: 'placeholder',
		category: 'world-country-locations-languages-asia',
	},
	{
		questionTitleHtml: '<strong>Philippines</strong>',
		questionDescriptionHtml: 'What is the location and principal language of this country?',
		answerTitleHtml: '<strong>Philippines</strong>',
		answerDescriptionHtml: 'Location: Southeast Asia<br>Principal Language: Filipino',
		pathToMedia: 'placeholder',
		category: 'world-country-locations-languages-asia',
	},
	{
		questionTitleHtml: '<strong>Qatar</strong>',
		questionDescriptionHtml: 'What is the location and principal language of this country?',
		answerTitleHtml: '<strong>Qatar</strong>',
		answerDescriptionHtml: 'Location: Western Asia (Middle East)<br>Principal Language: Arabic',
		pathToMedia: 'placeholder',
		category: 'world-country-locations-languages-asia',
	},
	{
		questionTitleHtml: '<strong>Saudi Arabia</strong>',
		questionDescriptionHtml: 'What is the location and principal language of this country?',
		answerTitleHtml: '<strong>Saudi Arabia</strong>',
		answerDescriptionHtml: 'Location: Western Asia (Middle East)<br>Principal Language: Arabic',
		pathToMedia: 'placeholder',
		category: 'world-country-locations-languages-asia',
	},
	{
		questionTitleHtml: '<strong>Singapore</strong>',
		questionDescriptionHtml: 'What is the location and principal language of this country?',
		answerTitleHtml: '<strong>Singapore</strong>',
		answerDescriptionHtml: 'Location: Southeast Asia<br>Principal Language: English',
		pathToMedia: 'placeholder',
		category: 'world-country-locations-languages-asia',
	},
	{
		questionTitleHtml: '<strong>South Korea</strong>',
		questionDescriptionHtml: 'What is the location and principal language of this country?',
		answerTitleHtml: '<strong>South Korea</strong>',
		answerDescriptionHtml: 'Location: East Asia<br>Principal Language: Korean',
		pathToMedia: 'placeholder',
		category: 'world-country-locations-languages-asia',
	},
	{
		questionTitleHtml: '<strong>Sri Lanka</strong>',
		questionDescriptionHtml: 'What is the location and principal language of this country?',
		answerTitleHtml: '<strong>Sri Lanka</strong>',
		answerDescriptionHtml: 'Location: South Asia<br>Principal Language: Sinhala',
		pathToMedia: 'placeholder',
		category: 'world-country-locations-languages-asia',
	},
	{
		questionTitleHtml: '<strong>Syria</strong>',
		questionDescriptionHtml: 'What is the location and principal language of this country?',
		answerTitleHtml: '<strong>Syria</strong>',
		answerDescriptionHtml: 'Location: Western Asia (Middle East)<br>Principal Language: Arabic',
		pathToMedia: 'placeholder',
		category: 'world-country-locations-languages-asia',
	},
	{
		questionTitleHtml: '<strong>Tajikistan</strong>',
		questionDescriptionHtml: 'What is the location and principal language of this country?',
		answerTitleHtml: '<strong>Tajikistan</strong>',
		answerDescriptionHtml: 'Location: Central Asia<br>Principal Language: Tajik',
		pathToMedia: 'placeholder',
		category: 'world-country-locations-languages-asia',
	},
	{
		questionTitleHtml: '<strong>Thailand</strong>',
		questionDescriptionHtml: 'What is the location and principal language of this country?',
		answerTitleHtml: '<strong>Thailand</strong>',
		answerDescriptionHtml: 'Location: Southeast Asia<br>Principal Language: Thai',
		pathToMedia: 'placeholder',
		category: 'world-country-locations-languages-asia',
	},
	{
		questionTitleHtml: '<strong>Turkmenistan</strong>',
		questionDescriptionHtml: 'What is the location and principal language of this country?',
		answerTitleHtml: '<strong>Turkmenistan</strong>',
		answerDescriptionHtml: 'Location: Central Asia<br>Principal Language: Turkmen',
		pathToMedia: 'placeholder',
		category: 'world-country-locations-languages-asia',
	},
	{
		questionTitleHtml: '<strong>United Arab Emirates</strong>',
		questionDescriptionHtml: 'What is the location and principal language of this country?',
		answerTitleHtml: '<strong>United Arab Emirates</strong>',
		answerDescriptionHtml: 'Location: Western Asia (Middle East)<br>Principal Language: Arabic',
		pathToMedia: 'placeholder',
		category: 'world-country-locations-languages-asia',
	},
	{
		questionTitleHtml: '<strong>Uzbekistan</strong>',
		questionDescriptionHtml: 'What is the location and principal language of this country?',
		answerTitleHtml: '<strong>Uzbekistan</strong>',
		answerDescriptionHtml: 'Location: Central Asia<br>Principal Language: Uzbek',
		pathToMedia: 'placeholder',
		category: 'world-country-locations-languages-asia',
	},
	{
		questionTitleHtml: '<strong>Vietnam</strong>',
		questionDescriptionHtml: 'What is the location and principal language of this country?',
		answerTitleHtml: '<strong>Vietnam</strong>',
		answerDescriptionHtml: 'Location: Southeast Asia<br>Principal Language: Vietnamese',
		pathToMedia: 'placeholder',
		category: 'world-country-locations-languages-asia',
	},
	{
		questionTitleHtml: '<strong>Yemen</strong>',
		questionDescriptionHtml: 'What is the location and principal language of this country?',
		answerTitleHtml: '<strong>Yemen</strong>',
		answerDescriptionHtml: 'Location: Western Asia (Middle East)<br>Principal Language: Arabic',
		pathToMedia: 'placeholder',
		category: 'world-country-locations-languages-asia',
	},
]
