import type { FlashCard } from '@/types'

export const world_country_locations_languages_south_america: FlashCard[] = [
	{
		questionTitleHtml: '<strong>What\'s this country in South America?</strong>',
		questionDescriptionHtml: 'And its principal language',
		answerTitleHtml: '<strong>Argentina</strong>',
		answerDescriptionHtml: 'Location: South America<br>Principal Language: Spanish',
		pathToMedia: 'images/world-country-locations/south-america/argentina.png',
		category: 'world-country-locations-languages-south-america',
	},
	{
		questionTitleHtml: '<strong>What\'s this country in South America?</strong>',
		questionDescriptionHtml: 'And its principal language',
		answerTitleHtml: '<strong>Bolivia</strong>',
		answerDescriptionHtml: 'Location: South America<br>Principal Language: Spanish',
		pathToMedia: 'images/world-country-locations/south-america/bolivia.png',
		category: 'world-country-locations-languages-south-america',
	},
	{
		questionTitleHtml: '<strong>What\'s this country in South America?</strong>',
		questionDescriptionHtml: 'And its principal language',
		answerTitleHtml: '<strong>Brazil</strong>',
		answerDescriptionHtml: 'Location: South America<br>Principal Language: Portuguese',
		pathToMedia: 'images/world-country-locations/south-america/brazil.png',
		category: 'world-country-locations-languages-south-america',
	},
	{
		questionTitleHtml: '<strong>What\'s this country in South America?</strong>',
		questionDescriptionHtml: 'And its principal language',
		answerTitleHtml: '<strong>Chile</strong>',
		answerDescriptionHtml: 'Location: South America<br>Principal Language: Spanish',
		pathToMedia: 'images/world-country-locations/south-america/chile.png',
		category: 'world-country-locations-languages-south-america',
	},
	{
		questionTitleHtml: '<strong>What\'s this country in South America?</strong>',
		questionDescriptionHtml: 'And its principal language',
		answerTitleHtml: '<strong>Colombia</strong>',
		answerDescriptionHtml: 'Location: South America<br>Principal Language: Spanish',
		pathToMedia: 'images/world-country-locations/south-america/colombia.png',
		category: 'world-country-locations-languages-south-america',
	},
	{
		questionTitleHtml: '<strong>What\'s this country in South America?</strong>',
		questionDescriptionHtml: 'And its principal language',
		answerTitleHtml: '<strong>Ecuador</strong>',
		answerDescriptionHtml: 'Location: South America<br>Principal Language: Spanish',
		pathToMedia: 'images/world-country-locations/south-america/ecuador.png',
		category: 'world-country-locations-languages-south-america',
	},
	{
		questionTitleHtml: '<strong>What\'s this country in South America?</strong>',
		questionDescriptionHtml: 'And its principal language',
		answerTitleHtml: '<strong>Guyana</strong>',
		answerDescriptionHtml: 'Location: South America<br>Principal Language: English',
		pathToMedia: 'images/world-country-locations/south-america/guyana.png',
		category: 'world-country-locations-languages-south-america',
	},
	{
		questionTitleHtml: '<strong>What\'s this country in South America?</strong>',
		questionDescriptionHtml: 'And its principal language',
		answerTitleHtml: '<strong>Paraguay</strong>',
		answerDescriptionHtml: 'Location: South America<br>Principal Language: Spanish',
		pathToMedia: 'images/world-country-locations/south-america/paraguay.png',
		category: 'world-country-locations-languages-south-america',
	},
	{
		questionTitleHtml: '<strong>What\'s this country in South America?</strong>',
		questionDescriptionHtml: 'And its principal language',
		answerTitleHtml: '<strong>Peru</strong>',
		answerDescriptionHtml: 'Location: South America<br>Principal Language: Spanish',
		pathToMedia: 'images/world-country-locations/south-america/peru.png',
		category: 'world-country-locations-languages-south-america',
	},
	{
		questionTitleHtml: '<strong>What\'s this country in South America?</strong>',
		questionDescriptionHtml: 'And its principal language',
		answerTitleHtml: '<strong>Suriname</strong>',
		answerDescriptionHtml: 'Location: South America<br>Principal Language: Dutch',
		pathToMedia: 'images/world-country-locations/south-america/suriname.png',
		category: 'world-country-locations-languages-south-america',
	},
	{
		questionTitleHtml: '<strong>What\'s this country in South America?</strong>',
		questionDescriptionHtml: 'And its principal language',
		answerTitleHtml: '<strong>Uruguay</strong>',
		answerDescriptionHtml: 'Location: South America<br>Principal Language: Spanish',
		pathToMedia: 'images/world-country-locations/south-america/uruguay.png',
		category: 'world-country-locations-languages-south-america',
	},
	{
		questionTitleHtml: '<strong>What\'s this country in South America?</strong>',
		questionDescriptionHtml: 'And its principal language',
		answerTitleHtml: '<strong>Venezuela</strong>',
		answerDescriptionHtml: 'Location: South America<br>Principal Language: Spanish',
		pathToMedia: 'images/world-country-locations/south-america/venezuela.png',
		category: 'world-country-locations-languages-south-america',
	},
]
