import type { FlashCard } from '@/types'

export const world_country_capitals_south_america: FlashCard[] = [
	{
		questionTitleHtml: '<strong>Argentina</strong>',
		questionDescriptionHtml: 'What is the capital of this country?',
		answerTitleHtml: '<strong>Buenos Aires</strong>',
		answerDescriptionHtml: 'Capital of <strong>Argentina</strong>',
		pathToMedia: null,
		category: 'world-country-capitals-south-america',
	},
	{
		questionTitleHtml: '<strong>Bolivia</strong>',
		questionDescriptionHtml: 'What is the capital of this country?',
		answerTitleHtml: '<strong>La Paz (administrative), Sucre (constitutional)</strong>',
		answerDescriptionHtml: 'Capital of <strong>Bolivia</strong>',
		pathToMedia: null,
		category: 'world-country-capitals-south-america',
	},
	{
		questionTitleHtml: '<strong>Brazil</strong>',
		questionDescriptionHtml: 'What is the capital of this country?',
		answerTitleHtml: '<strong>Brasília</strong>',
		answerDescriptionHtml: 'Capital of <strong>Brazil</strong>',
		pathToMedia: null,
		category: 'world-country-capitals-south-america',
	},
	{
		questionTitleHtml: '<strong>Chile</strong>',
		questionDescriptionHtml: 'What is the capital of this country?',
		answerTitleHtml: '<strong>Santiago</strong>',
		answerDescriptionHtml: 'Capital of <strong>Chile</strong>',
		pathToMedia: null,
		category: 'world-country-capitals-south-america',
	},
	{
		questionTitleHtml: '<strong>Colombia</strong>',
		questionDescriptionHtml: 'What is the capital of this country?',
		answerTitleHtml: '<strong>Bogotá</strong>',
		answerDescriptionHtml: 'Capital of <strong>Colombia</strong>',
		pathToMedia: null,
		category: 'world-country-capitals-south-america',
	},
	{
		questionTitleHtml: '<strong>Ecuador</strong>',
		questionDescriptionHtml: 'What is the capital of this country?',
		answerTitleHtml: '<strong>Quito</strong>',
		answerDescriptionHtml: 'Capital of <strong>Ecuador</strong>',
		pathToMedia: null,
		category: 'world-country-capitals-south-america',
	},
	{
		questionTitleHtml: '<strong>Guyana</strong>',
		questionDescriptionHtml: 'What is the capital of this country?',
		answerTitleHtml: '<strong>Georgetown</strong>',
		answerDescriptionHtml: 'Capital of <strong>Guyana</strong>',
		pathToMedia: null,
		category: 'world-country-capitals-south-america',
	},
	{
		questionTitleHtml: '<strong>Paraguay</strong>',
		questionDescriptionHtml: 'What is the capital of this country?',
		answerTitleHtml: '<strong>Asunción</strong>',
		answerDescriptionHtml: 'Capital of <strong>Paraguay</strong>',
		pathToMedia: null,
		category: 'world-country-capitals-south-america',
	},
	{
		questionTitleHtml: '<strong>Peru</strong>',
		questionDescriptionHtml: 'What is the capital of this country?',
		answerTitleHtml: '<strong>Lima</strong>',
		answerDescriptionHtml: 'Capital of <strong>Peru</strong>',
		pathToMedia: null,
		category: 'world-country-capitals-south-america',
	},
	{
		questionTitleHtml: '<strong>Suriname</strong>',
		questionDescriptionHtml: 'What is the capital of this country?',
		answerTitleHtml: '<strong>Paramaribo</strong>',
		answerDescriptionHtml: 'Capital of <strong>Suriname</strong>',
		pathToMedia: null,
		category: 'world-country-capitals-south-america',
	},
	{
		questionTitleHtml: '<strong>Uruguay</strong>',
		questionDescriptionHtml: 'What is the capital of this country?',
		answerTitleHtml: '<strong>Montevideo</strong>',
		answerDescriptionHtml: 'Capital of <strong>Uruguay</strong>',
		pathToMedia: null,
		category: 'world-country-capitals-south-america',
	},
	{
		questionTitleHtml: '<strong>Venezuela</strong>',
		questionDescriptionHtml: 'What is the capital of this country?',
		answerTitleHtml: '<strong>Caracas</strong>',
		answerDescriptionHtml: 'Capital of <strong>Venezuela</strong>',
		pathToMedia: null,
		category: 'world-country-capitals-south-america',
	},
]
