import type { FlashCard } from '@/types'

export const world_country_flags_asia: FlashCard[] = [
	{
		questionTitleHtml: '<strong>What country is this flag?</strong>',
		questionDescriptionHtml: '',
		answerTitleHtml: '<strong>Afghanistan</strong>',
		answerDescriptionHtml: 'Country Flag',
		pathToMedia: 'node_modules/svg-country-flags/svg/af.svg',
		category: 'world-country-flags-asia',
	},
	{
		questionTitleHtml: '<strong>What country is this flag?</strong>',
		questionDescriptionHtml: '',
		answerTitleHtml: '<strong>Bangladesh</strong>',
		answerDescriptionHtml: 'Country Flag',
		pathToMedia: 'node_modules/svg-country-flags/svg/bd.svg',
		category: 'world-country-flags-asia',
	},
	{
		questionTitleHtml: '<strong>What country is this flag?</strong>',
		questionDescriptionHtml: '',
		answerTitleHtml: '<strong>Burma (Myanmar)</strong>',
		answerDescriptionHtml: 'Country Flag',
		pathToMedia: 'node_modules/svg-country-flags/svg/mm.svg',
		category: 'world-country-flags-asia',
	},
	{
		questionTitleHtml: '<strong>What country is this flag?</strong>',
		questionDescriptionHtml: '',
		answerTitleHtml: '<strong>Cambodia</strong>',
		answerDescriptionHtml: 'Country Flag',
		pathToMedia: 'node_modules/svg-country-flags/svg/kh.svg',
		category: 'world-country-flags-asia',
	},
	{
		questionTitleHtml: '<strong>What country is this flag?</strong>',
		questionDescriptionHtml: '',
		answerTitleHtml: '<strong>China</strong>',
		answerDescriptionHtml: 'Country Flag',
		pathToMedia: 'node_modules/svg-country-flags/svg/cn.svg',
		category: 'world-country-flags-asia',
	},
	{
		questionTitleHtml: '<strong>What country is this flag?</strong>',
		questionDescriptionHtml: '',
		answerTitleHtml: '<strong>India</strong>',
		answerDescriptionHtml: 'Country Flag',
		pathToMedia: 'node_modules/svg-country-flags/svg/in.svg',
		category: 'world-country-flags-asia',
	},
	{
		questionTitleHtml: '<strong>What country is this flag?</strong>',
		questionDescriptionHtml: '',
		answerTitleHtml: '<strong>Indonesia</strong>',
		answerDescriptionHtml: 'Country Flag',
		pathToMedia: 'node_modules/svg-country-flags/svg/id.svg',
		category: 'world-country-flags-asia',
	},
	{
		questionTitleHtml: '<strong>What country is this flag?</strong>',
		questionDescriptionHtml: '',
		answerTitleHtml: '<strong>Iran</strong>',
		answerDescriptionHtml: 'Country Flag',
		pathToMedia: 'node_modules/svg-country-flags/svg/ir.svg',
		category: 'world-country-flags-asia',
	},
	{
		questionTitleHtml: '<strong>What country is this flag?</strong>',
		questionDescriptionHtml: '',
		answerTitleHtml: '<strong>Iraq</strong>',
		answerDescriptionHtml: 'Country Flag',
		pathToMedia: 'node_modules/svg-country-flags/svg/iq.svg',
		category: 'world-country-flags-asia',
	},
	{
		questionTitleHtml: '<strong>What country is this flag?</strong>',
		questionDescriptionHtml: '',
		answerTitleHtml: '<strong>Israel</strong>',
		answerDescriptionHtml: 'Country Flag',
		pathToMedia: 'node_modules/svg-country-flags/svg/il.svg',
		category: 'world-country-flags-asia',
	},
	{
		questionTitleHtml: '<strong>What country is this flag?</strong>',
		questionDescriptionHtml: '',
		answerTitleHtml: '<strong>Japan</strong>',
		answerDescriptionHtml: 'Country Flag',
		pathToMedia: 'node_modules/svg-country-flags/svg/jp.svg',
		category: 'world-country-flags-asia',
	},
	{
		questionTitleHtml: '<strong>What country is this flag?</strong>',
		questionDescriptionHtml: '',
		answerTitleHtml: '<strong>Jordan</strong>',
		answerDescriptionHtml: 'Country Flag',
		pathToMedia: 'node_modules/svg-country-flags/svg/jo.svg',
		category: 'world-country-flags-asia',
	},
	{
		questionTitleHtml: '<strong>What country is this flag?</strong>',
		questionDescriptionHtml: '',
		answerTitleHtml: '<strong>Kuwait</strong>',
		answerDescriptionHtml: 'Country Flag',
		pathToMedia: 'node_modules/svg-country-flags/svg/kw.svg',
		category: 'world-country-flags-asia',
	},
	{
		questionTitleHtml: '<strong>What country is this flag?</strong>',
		questionDescriptionHtml: '',
		answerTitleHtml: '<strong>Kyrgyzstan</strong>',
		answerDescriptionHtml: 'Country Flag',
		pathToMedia: 'node_modules/svg-country-flags/svg/kg.svg',
		category: 'world-country-flags-asia',
	},
	{
		questionTitleHtml: '<strong>What country is this flag?</strong>',
		questionDescriptionHtml: '',
		answerTitleHtml: '<strong>Laos</strong>',
		answerDescriptionHtml: 'Country Flag',
		pathToMedia: 'node_modules/svg-country-flags/svg/la.svg',
		category: 'world-country-flags-asia',
	},
	{
		questionTitleHtml: '<strong>What country is this flag?</strong>',
		questionDescriptionHtml: '',
		answerTitleHtml: '<strong>Lebanon</strong>',
		answerDescriptionHtml: 'Country Flag',
		pathToMedia: 'node_modules/svg-country-flags/svg/lb.svg',
		category: 'world-country-flags-asia',
	},
	{
		questionTitleHtml: '<strong>What country is this flag?</strong>',
		questionDescriptionHtml: '',
		answerTitleHtml: '<strong>Malaysia</strong>',
		answerDescriptionHtml: 'Country Flag',
		pathToMedia: 'node_modules/svg-country-flags/svg/my.svg',
		category: 'world-country-flags-asia',
	},
	{
		questionTitleHtml: '<strong>What country is this flag?</strong>',
		questionDescriptionHtml: '',
		answerTitleHtml: '<strong>Mongolia</strong>',
		answerDescriptionHtml: 'Country Flag',
		pathToMedia: 'node_modules/svg-country-flags/svg/mn.svg',
		category: 'world-country-flags-asia',
	},
	{
		questionTitleHtml: '<strong>What country is this flag?</strong>',
		questionDescriptionHtml: '',
		answerTitleHtml: '<strong>Myanmar (Burma)</strong>',
		answerDescriptionHtml: 'Country Flag',
		pathToMedia: 'node_modules/svg-country-flags/svg/mm.svg',
		category: 'world-country-flags-asia',
	},
	{
		questionTitleHtml: '<strong>What country is this flag?</strong>',
		questionDescriptionHtml: '',
		answerTitleHtml: '<strong>Nepal</strong>',
		answerDescriptionHtml: 'Country Flag',
		pathToMedia: 'node_modules/svg-country-flags/svg/np.svg',
		category: 'world-country-flags-asia',
	},
	{
		questionTitleHtml: '<strong>What country is this flag?</strong>',
		questionDescriptionHtml: '',
		answerTitleHtml: '<strong>North Korea</strong>',
		answerDescriptionHtml: 'Country Flag',
		pathToMedia: 'node_modules/svg-country-flags/svg/kp.svg',
		category: 'world-country-flags-asia',
	},
	{
		questionTitleHtml: '<strong>What country is this flag?</strong>',
		questionDescriptionHtml: '',
		answerTitleHtml: '<strong>Oman</strong>',
		answerDescriptionHtml: 'Country Flag',
		pathToMedia: 'node_modules/svg-country-flags/svg/om.svg',
		category: 'world-country-flags-asia',
	},
	{
		questionTitleHtml: '<strong>What country is this flag?</strong>',
		questionDescriptionHtml: '',
		answerTitleHtml: '<strong>Pakistan</strong>',
		answerDescriptionHtml: 'Country Flag',
		pathToMedia: 'node_modules/svg-country-flags/svg/pk.svg',
		category: 'world-country-flags-asia',
	},
	{
		questionTitleHtml: '<strong>What country is this flag?</strong>',
		questionDescriptionHtml: '',
		answerTitleHtml: '<strong>Palestine</strong>',
		answerDescriptionHtml: 'Country Flag',
		pathToMedia: 'node_modules/svg-country-flags/svg/ps.svg',
		category: 'world-country-flags-asia',
	},
	{
		questionTitleHtml: '<strong>What country is this flag?</strong>',
		questionDescriptionHtml: '',
		answerTitleHtml: '<strong>Philippines</strong>',
		answerDescriptionHtml: 'Country Flag',
		pathToMedia: 'node_modules/svg-country-flags/svg/ph.svg',
		category: 'world-country-flags-asia',
	},
	{
		questionTitleHtml: '<strong>What country is this flag?</strong>',
		questionDescriptionHtml: '',
		answerTitleHtml: '<strong>Qatar</strong>',
		answerDescriptionHtml: 'Country Flag',
		pathToMedia: 'node_modules/svg-country-flags/svg/qa.svg',
		category: 'world-country-flags-asia',
	},
	{
		questionTitleHtml: '<strong>What country is this flag?</strong>',
		questionDescriptionHtml: '',
		answerTitleHtml: '<strong>Saudi Arabia</strong>',
		answerDescriptionHtml: 'Country Flag',
		pathToMedia: 'node_modules/svg-country-flags/svg/sa.svg',
		category: 'world-country-flags-asia',
	},
	{
		questionTitleHtml: '<strong>What country is this flag?</strong>',
		questionDescriptionHtml: '',
		answerTitleHtml: '<strong>Singapore</strong>',
		answerDescriptionHtml: 'Country Flag',
		pathToMedia: 'node_modules/svg-country-flags/svg/sg.svg',
		category: 'world-country-flags-asia',
	},
	{
		questionTitleHtml: '<strong>What country is this flag?</strong>',
		questionDescriptionHtml: '',
		answerTitleHtml: '<strong>South Korea</strong>',
		answerDescriptionHtml: 'Country Flag',
		pathToMedia: 'node_modules/svg-country-flags/svg/kr.svg',
		category: 'world-country-flags-asia',
	},
	{
		questionTitleHtml: '<strong>What country is this flag?</strong>',
		questionDescriptionHtml: '',
		answerTitleHtml: '<strong>Sri Lanka</strong>',
		answerDescriptionHtml: 'Country Flag',
		pathToMedia: 'node_modules/svg-country-flags/svg/lk.svg',
		category: 'world-country-flags-asia',
	},
	{
		questionTitleHtml: '<strong>What country is this flag?</strong>',
		questionDescriptionHtml: '',
		answerTitleHtml: '<strong>Syria</strong>',
		answerDescriptionHtml: 'Country Flag',
		pathToMedia: 'node_modules/svg-country-flags/svg/sy.svg',
		category: 'world-country-flags-asia',
	},
	{
		questionTitleHtml: '<strong>What country is this flag?</strong>',
		questionDescriptionHtml: '',
		answerTitleHtml: '<strong>Tajikistan</strong>',
		answerDescriptionHtml: 'Country Flag',
		pathToMedia: 'node_modules/svg-country-flags/svg/tj.svg',
		category: 'world-country-flags-asia',
	},
	{
		questionTitleHtml: '<strong>What country is this flag?</strong>',
		questionDescriptionHtml: '',
		answerTitleHtml: '<strong>Thailand</strong>',
		answerDescriptionHtml: 'Country Flag',
		pathToMedia: 'node_modules/svg-country-flags/svg/th.svg',
		category: 'world-country-flags-asia',
	},
	{
		questionTitleHtml: '<strong>What country is this flag?</strong>',
		questionDescriptionHtml: '',
		answerTitleHtml: '<strong>Turkmenistan</strong>',
		answerDescriptionHtml: 'Country Flag',
		pathToMedia: 'node_modules/svg-country-flags/svg/tm.svg',
		category: 'world-country-flags-asia',
	},
	{
		questionTitleHtml: '<strong>What country is this flag?</strong>',
		questionDescriptionHtml: '',
		answerTitleHtml: '<strong>United Arab Emirates</strong>',
		answerDescriptionHtml: 'Country Flag',
		pathToMedia: 'node_modules/svg-country-flags/svg/ae.svg',
		category: 'world-country-flags-asia',
	},
	{
		questionTitleHtml: '<strong>What country is this flag?</strong>',
		questionDescriptionHtml: '',
		answerTitleHtml: '<strong>Uzbekistan</strong>',
		answerDescriptionHtml: 'Country Flag',
		pathToMedia: 'node_modules/svg-country-flags/svg/uz.svg',
		category: 'world-country-flags-asia',
	},
	{
		questionTitleHtml: '<strong>What country is this flag?</strong>',
		questionDescriptionHtml: '',
		answerTitleHtml: '<strong>Vietnam</strong>',
		answerDescriptionHtml: 'Country Flag',
		pathToMedia: 'node_modules/svg-country-flags/svg/vn.svg',
		category: 'world-country-flags-asia',
	},
	{
		questionTitleHtml: '<strong>What country is this flag?</strong>',
		questionDescriptionHtml: '',
		answerTitleHtml: '<strong>Yemen</strong>',
		answerDescriptionHtml: 'Country Flag',
		pathToMedia: 'node_modules/svg-country-flags/svg/ye.svg',
		category: 'world-country-flags-asia',
	},
]
