import type { FlashCard } from '@/types'

export const world_country_capitals_africa: FlashCard[] = [
	{
		questionTitleHtml: 'Capital of <strong>Algeria</strong>',
		questionDescriptionHtml: null,
		answerTitleHtml: '<strong>Algiers</strong>',
		answerDescriptionHtml: null,
		pathToMedia: null,
		category: 'world-country-capitals-africa',
	},
	{
		questionTitleHtml: 'Capital of <strong>Angola</strong>',
		questionDescriptionHtml: null,
		answerTitleHtml: '<strong>Luanda</strong>',
		answerDescriptionHtml: null,
		pathToMedia: null,
		category: 'world-country-capitals-africa',
	},
	{
		questionTitleHtml: 'Capital of <strong>Botswana</strong>',
		questionDescriptionHtml: null,
		answerTitleHtml: '<strong>Gaborone</strong>',
		answerDescriptionHtml: null,
		pathToMedia: null,
		category: 'world-country-capitals-africa',
	},
	{
		questionTitleHtml: 'Capital of <strong>Burundi</strong>',
		questionDescriptionHtml: null,
		answerTitleHtml: '<strong>Gitega</strong>',
		answerDescriptionHtml: null,
		pathToMedia: null,
		category: 'world-country-capitals-africa',
	},
	{
		questionTitleHtml: 'Capital of <strong>Central African Republic</strong>',
		questionDescriptionHtml: null,
		answerTitleHtml: '<strong>Bangui</strong>',
		answerDescriptionHtml: null,
		pathToMedia: null,
		category: 'world-country-capitals-africa',
	},
	{
		questionTitleHtml: 'Capital of <strong>Chad</strong>',
		questionDescriptionHtml: null,
		answerTitleHtml: '<strong>N\'Djamena</strong>',
		answerDescriptionHtml: null,
		pathToMedia: null,
		category: 'world-country-capitals-africa',
	},
	{
		questionTitleHtml: 'Capital of <strong>Democratic Republic of the Congo</strong>',
		questionDescriptionHtml: null,
		answerTitleHtml: '<strong>Kinshasa</strong>',
		answerDescriptionHtml: null,
		pathToMedia: null,
		category: 'world-country-capitals-africa',
	},
	{
		questionTitleHtml: 'Capital of <strong>Egypt</strong>',
		questionDescriptionHtml: null,
		answerTitleHtml: '<strong>Cairo</strong>',
		answerDescriptionHtml: null,
		pathToMedia: null,
		category: 'world-country-capitals-africa',
	},
	{
		questionTitleHtml: 'Capital of <strong>Ethiopia</strong>',
		questionDescriptionHtml: null,
		answerTitleHtml: '<strong>Addis Ababa</strong>',
		answerDescriptionHtml: null,
		pathToMedia: null,
		category: 'world-country-capitals-africa',
	},
	{
		questionTitleHtml: 'Capital of <strong>Ghana</strong>',
		questionDescriptionHtml: null,
		answerTitleHtml: '<strong>Accra</strong>',
		answerDescriptionHtml: null,
		pathToMedia: null,
		category: 'world-country-capitals-africa',
	},
	{
		questionTitleHtml: 'Capital of <strong>Guinea</strong>',
		questionDescriptionHtml: null,
		answerTitleHtml: '<strong>Conakry</strong>',
		answerDescriptionHtml: null,
		pathToMedia: null,
		category: 'world-country-capitals-africa',
	},
	{
		questionTitleHtml: 'Capital of <strong>Kenya</strong>',
		questionDescriptionHtml: null,
		answerTitleHtml: '<strong>Nairobi</strong>',
		answerDescriptionHtml: null,
		pathToMedia: null,
		category: 'world-country-capitals-africa',
	},
	{
		questionTitleHtml: 'Capital of <strong>Liberia</strong>',
		questionDescriptionHtml: null,
		answerTitleHtml: '<strong>Monrovia</strong>',
		answerDescriptionHtml: null,
		pathToMedia: null,
		category: 'world-country-capitals-africa',
	},
	{
		questionTitleHtml: 'Capital of <strong>Libya</strong>',
		questionDescriptionHtml: null,
		answerTitleHtml: '<strong>Tripoli</strong>',
		answerDescriptionHtml: null,
		pathToMedia: null,
		category: 'world-country-capitals-africa',
	},
	{
		questionTitleHtml: 'Capital of <strong>Madagascar</strong>',
		questionDescriptionHtml: null,
		answerTitleHtml: '<strong>Antananarivo</strong>',
		answerDescriptionHtml: null,
		pathToMedia: null,
		category: 'world-country-capitals-africa',
	},
	{
		questionTitleHtml: 'Capital of <strong>Mali</strong>',
		questionDescriptionHtml: null,
		answerTitleHtml: '<strong>Bamako</strong>',
		answerDescriptionHtml: null,
		pathToMedia: null,
		category: 'world-country-capitals-africa',
	},
	{
		questionTitleHtml: 'Capital of <strong>Morocco</strong>',
		questionDescriptionHtml: null,
		answerTitleHtml: '<strong>Rabat</strong>',
		answerDescriptionHtml: null,
		pathToMedia: null,
		category: 'world-country-capitals-africa',
	},
	{
		questionTitleHtml: 'Capital of <strong>Mozambique</strong>',
		questionDescriptionHtml: null,
		answerTitleHtml: '<strong>Maputo</strong>',
		answerDescriptionHtml: null,
		pathToMedia: null,
		category: 'world-country-capitals-africa',
	},
	{
		questionTitleHtml: 'Capital of <strong>Niger</strong>',
		questionDescriptionHtml: null,
		answerTitleHtml: '<strong>Niamey</strong>',
		answerDescriptionHtml: null,
		pathToMedia: null,
		category: 'world-country-capitals-africa',
	},
	{
		questionTitleHtml: 'Capital of <strong>Nigeria</strong>',
		questionDescriptionHtml: null,
		answerTitleHtml: '<strong>Abuja</strong>',
		answerDescriptionHtml: null,
		pathToMedia: null,
		category: 'world-country-capitals-africa',
	},
	{
		questionTitleHtml: 'Capital of <strong>Republic of the Congo</strong>',
		questionDescriptionHtml: null,
		answerTitleHtml: '<strong>Brazzaville</strong>',
		answerDescriptionHtml: null,
		pathToMedia: null,
		category: 'world-country-capitals-africa',
	},
	{
		questionTitleHtml: 'Capital of <strong>Rwanda</strong>',
		questionDescriptionHtml: null,
		answerTitleHtml: '<strong>Kigali</strong>',
		answerDescriptionHtml: null,
		pathToMedia: null,
		category: 'world-country-capitals-africa',
	},
	{
		questionTitleHtml: 'Capital of <strong>Somalia</strong>',
		questionDescriptionHtml: null,
		answerTitleHtml: '<strong>Mogadishu</strong>',
		answerDescriptionHtml: null,
		pathToMedia: null,
		category: 'world-country-capitals-africa',
	},
	{
		questionTitleHtml: 'Capital of <strong>South Africa</strong>',
		questionDescriptionHtml: null,
		answerTitleHtml: '<strong>Cape Town (legislative), Pretoria (administrative), Bloemfontein (judicial)</strong>',
		answerDescriptionHtml: null,
		pathToMedia: null,
		category: 'world-country-capitals-africa',
	},
	{
		questionTitleHtml: 'Capital of <strong>Sudan</strong>',
		questionDescriptionHtml: null,
		answerTitleHtml: '<strong>Khartoum</strong>',
		answerDescriptionHtml: null,
		pathToMedia: null,
		category: 'world-country-capitals-africa',
	},
	{
		questionTitleHtml: 'Capital of <strong>Swaziland (Eswatini)</strong>',
		questionDescriptionHtml: null,
		answerTitleHtml: '<strong>Mbabane (administrative), Lobamba (legislative)</strong>',
		answerDescriptionHtml: null,
		pathToMedia: null,
		category: 'world-country-capitals-africa',
	},
	{
		questionTitleHtml: 'Capital of <strong>Tanzania</strong>',
		questionDescriptionHtml: null,
		answerTitleHtml: '<strong>Dodoma</strong>',
		answerDescriptionHtml: null,
		pathToMedia: null,
		category: 'world-country-capitals-africa',
	},
	{
		questionTitleHtml: 'Capital of <strong>Tunisia</strong>',
		questionDescriptionHtml: null,
		answerTitleHtml: '<strong>Tunis</strong>',
		answerDescriptionHtml: null,
		pathToMedia: null,
		category: 'world-country-capitals-africa',
	},
	{
		questionTitleHtml: 'Capital of <strong>Uganda</strong>',
		questionDescriptionHtml: null,
		answerTitleHtml: '<strong>Kampala</strong>',
		answerDescriptionHtml: null,
		pathToMedia: null,
		category: 'world-country-capitals-africa',
	},
	{
		questionTitleHtml: 'Capital of <strong>Zambia</strong>',
		questionDescriptionHtml: null,
		answerTitleHtml: '<strong>Lusaka</strong>',
		answerDescriptionHtml: null,
		pathToMedia: null,
		category: 'world-country-capitals-africa',
	},
	{
		questionTitleHtml: 'Capital of <strong>Zimbabwe</strong>',
		questionDescriptionHtml: null,
		answerTitleHtml: '<strong>Harare</strong>',
		answerDescriptionHtml: null,
		pathToMedia: null,
		category: 'world-country-capitals-africa',
	},
]
