import type { FlashCard } from '@/types'

export const world_cities_landmarks_africa: FlashCard[] = [
	{
		questionTitleHtml: '<strong>Alexandria</strong>',
		questionDescriptionHtml: 'What is the location or description of this?',
		answerTitleHtml: '<strong>Alexandria</strong>',
		answerDescriptionHtml: 'Location: Egypt<br>Major port city on the Mediterranean Sea',
		pathToMedia: 'images/world-cities-landmarks-africa/alexandria.jpg',
		category: 'world-cities-landmarks-africa',
	},
	{
		questionTitleHtml: '<strong>Kalahari Desert</strong>',
		questionDescriptionHtml: 'What is the location or description of this?',
		answerTitleHtml: '<strong>Kalahari Desert</strong>',
		answerDescriptionHtml: 'Location: Botswana, Namibia, South Africa<br>Large semi-arid sandy savanna',
		pathToMedia: 'images/world-cities-landmarks-africa/kalahari-desert.png',
		category: 'world-cities-landmarks-africa',
	},
	{
		questionTitleHtml: '<strong>Cape of Good Hope</strong>',
		questionDescriptionHtml: 'What is the location or description of this?',
		answerTitleHtml: '<strong>Cape of Good Hope</strong>',
		answerDescriptionHtml: 'Location: South Africa',
		pathToMedia: 'images/world-cities-landmarks-africa/cape-of-good-hope.png',
		category: 'world-cities-landmarks-africa',
	},
	{
		questionTitleHtml: '<strong>Red Sea</strong>',
		questionDescriptionHtml: 'What is the location or description of this?',
		answerTitleHtml: '<strong>Red Sea</strong>',
		answerDescriptionHtml: 'Location: Between Africa and Arabian Peninsula',
		pathToMedia: 'images/world-cities-landmarks-africa/red-sea.jpg',
		category: 'world-cities-landmarks-africa',
	},
	{
		questionTitleHtml: '<strong>The Pyramids</strong>',
		questionDescriptionHtml: 'What is the location or description of this?',
		answerTitleHtml: '<strong>The Pyramids</strong>',
		answerDescriptionHtml: 'Location: Giza, Egypt',
		pathToMedia: 'images/world-cities-landmarks-africa/pyramids-giza.jpg',
		category: 'world-cities-landmarks-africa',
	},
	{
		questionTitleHtml: '<strong>The Great Sphinx</strong>',
		questionDescriptionHtml: 'What is the location or description of this?',
		answerTitleHtml: '<strong>The Great Sphinx</strong>',
		answerDescriptionHtml: 'Location: Giza, Egypt',
		pathToMedia: 'images/world-cities-landmarks-africa/great-sphinx.jpg',
		category: 'world-cities-landmarks-africa',
	},
	{
		questionTitleHtml: '<strong>Suez Canal</strong>',
		questionDescriptionHtml: 'What is the location or description of this?',
		answerTitleHtml: '<strong>Suez Canal</strong>',
		answerDescriptionHtml: 'Location: Egypt, connecting Mediterranean Sea and Red Sea',
		pathToMedia: 'images/world-cities-landmarks-africa/suez-canal.jpg',
		category: 'world-cities-landmarks-africa',
	},
	{
		questionTitleHtml: '<strong>Madagascar</strong>',
		questionDescriptionHtml: 'What is the location or description of this?',
		answerTitleHtml: '<strong>Madagascar</strong>',
		answerDescriptionHtml: 'Location: Indian Ocean (country)',
		pathToMedia: 'images/world-cities-landmarks-africa/madagascar.png',
		category: 'world-cities-landmarks-africa',
	},
]
