import type { FlashCard } from '@/types'

export const world_country_locations_languages_australia_oceania: FlashCard[] = [
	{
		questionTitleHtml: '<strong>What\'s this country in Oceania?</strong>',
		questionDescriptionHtml: 'And its principal language',
		answerTitleHtml: '<strong>Australia</strong>',
		answerDescriptionHtml: 'Location: Oceania<br>Principal Language: English',
		pathToMedia: 'images/world-country-locations/australia-oceania/australia.png',
		category: 'world-country-locations-languages-australia-oceania',
	},
	{
		questionTitleHtml: '<strong>What\'s this country in Oceania?</strong>',
		questionDescriptionHtml: 'And its principal language',
		answerTitleHtml: '<strong>Fiji</strong>',
		answerDescriptionHtml: 'Location: Oceania (Pacific)<br>Principal Language: English',
		pathToMedia: 'images/world-country-locations/australia-oceania/fiji.png',
		category: 'world-country-locations-languages-australia-oceania',
	},
	{
		questionTitleHtml: '<strong>What\'s this country in Oceania?</strong>',
		questionDescriptionHtml: 'And its principal language',
		answerTitleHtml: '<strong>New Zealand</strong>',
		answerDescriptionHtml: 'Location: Oceania<br>Principal Language: English',
		pathToMedia: 'images/world-country-locations/australia-oceania/new-zealand.png',
		category: 'world-country-locations-languages-australia-oceania',
	},
	{
		questionTitleHtml: '<strong>What\'s this country in Oceania?</strong>',
		questionDescriptionHtml: 'And its principal language',
		answerTitleHtml: '<strong>Papua New Guinea</strong>',
		answerDescriptionHtml: 'Location: Oceania<br>Principal Language: English',
		pathToMedia: 'images/world-country-locations/australia-oceania/papua-new-guinea.png',
		category: 'world-country-locations-languages-australia-oceania',
	},
	{
		questionTitleHtml: '<strong>What\'s this country in Oceania?</strong>',
		questionDescriptionHtml: 'And its principal language',
		answerTitleHtml: '<strong>Samoa</strong>',
		answerDescriptionHtml: 'Location: Oceania (Pacific)<br>Principal Language: Samoan',
		pathToMedia: 'images/world-country-locations/australia-oceania/samoa.png',
		category: 'world-country-locations-languages-australia-oceania',
	},
	{
		questionTitleHtml: '<strong>What\'s this country in Oceania?</strong>',
		questionDescriptionHtml: 'And its principal language',
		answerTitleHtml: '<strong>Tonga</strong>',
		answerDescriptionHtml: 'Location: Oceania (Pacific)<br>Principal Language: Tongan',
		pathToMedia: 'images/world-country-locations/australia-oceania/tonga.png',
		category: 'world-country-locations-languages-australia-oceania',
	},
	{
		questionTitleHtml: '<strong>What\'s this country in Oceania?</strong>',
		questionDescriptionHtml: 'And its principal language',
		answerTitleHtml: '<strong>Vanuatu</strong>',
		answerDescriptionHtml: 'Location: Oceania (Pacific)<br>Principal Language: Bislama',
		pathToMedia: 'images/world-country-locations/australia-oceania/vanuatu.png',
		category: 'world-country-locations-languages-australia-oceania',
	},
]
