import type { FlashCard } from '@/types'

export const world_cities_landmarks_europe: FlashCard[] = [
	{
		questionTitleHtml: '<strong>Cannes</strong>',
		questionDescriptionHtml: 'What is the location or description of this?',
		answerTitleHtml: '<strong>Cannes</strong>',
		answerDescriptionHtml: 'Location: France<br>Famous resort city on the French Riviera, known for its film festival',
		pathToMedia: 'images/world-cities-landmarks-europe/cannes.jpg',
		category: 'world-cities-landmarks-europe',
	},
	{
		questionTitleHtml: '<strong>Florence</strong>',
		questionDescriptionHtml: 'What is the location or description of this?',
		answerTitleHtml: '<strong>Florence</strong>',
		answerDescriptionHtml: 'Location: Italy<br>Historic city in Tuscany, known for Renaissance art and architecture',
		pathToMedia: 'images/world-cities-landmarks-europe/florence.jpg',
		category: 'world-cities-landmarks-europe',
	},
	{
		questionTitleHtml: '<strong>Milan</strong>',
		questionDescriptionHtml: 'What is the location or description of this?',
		answerTitleHtml: '<strong>Milan</strong>',
		answerDescriptionHtml: 'Location: Italy<br>Major city in northern Italy, known for fashion and finance',
		pathToMedia: 'images/world-cities-landmarks-europe/milan.jpg',
		category: 'world-cities-landmarks-europe',
	},
	{
		questionTitleHtml: '<strong>Munich</strong>',
		questionDescriptionHtml: 'What is the location or description of this?',
		answerTitleHtml: '<strong>Munich</strong>',
		answerDescriptionHtml: 'Location: Germany<br>Major city in southern Germany, capital of Bavaria',
		pathToMedia: 'images/world-cities-landmarks-europe/munich.jpg',
		category: 'world-cities-landmarks-europe',
	},
	{
		questionTitleHtml: '<strong>Nice</strong>',
		questionDescriptionHtml: 'What is the location or description of this?',
		answerTitleHtml: '<strong>Nice</strong>',
		answerDescriptionHtml: 'Location: France<br>City on the French Riviera',
		pathToMedia: 'images/world-cities-landmarks-europe/nice.jpg',
		category: 'world-cities-landmarks-europe',
	},
	{
		questionTitleHtml: '<strong>Venice</strong>',
		questionDescriptionHtml: 'What is the location or description of this?',
		answerTitleHtml: '<strong>Venice</strong>',
		answerDescriptionHtml: 'Location: Italy<br>Historic city built on canals in northeastern Italy',
		pathToMedia: 'images/world-cities-landmarks-europe/venice.jpg',
		category: 'world-cities-landmarks-europe',
	},
	{
		questionTitleHtml: '<strong>Zurich</strong>',
		questionDescriptionHtml: 'What is the location or description of this?',
		answerTitleHtml: '<strong>Zurich</strong>',
		answerDescriptionHtml: 'Location: Switzerland<br>Major city and financial center',
		pathToMedia: 'images/world-cities-landmarks-europe/zurich.jpg',
		category: 'world-cities-landmarks-europe',
	},
	{
		questionTitleHtml: '<strong>Baltic Sea</strong>',
		questionDescriptionHtml: 'What is the location or description of this?',
		answerTitleHtml: '<strong>Baltic Sea</strong>',
		answerDescriptionHtml: 'Location: Northern Europe, between Scandinavia and Central Europe',
		pathToMedia: 'images/world-cities-landmarks-europe/baltic-sea.png',
		category: 'world-cities-landmarks-europe',
	},
	{
		questionTitleHtml: '<strong>Black Sea</strong>',
		questionDescriptionHtml: 'What is the location or description of this?',
		answerTitleHtml: '<strong>Black Sea</strong>',
		answerDescriptionHtml: 'Location: Between Europe and Asia, bordered by Turkey, Bulgaria, Romania, Ukraine, Russia, Georgia',
		pathToMedia: 'images/world-cities-landmarks-europe/black-sea.png',
		category: 'world-cities-landmarks-europe',
	},
	{
		questionTitleHtml: '<strong>Mediterranean Sea</strong>',
		questionDescriptionHtml: 'What is the location or description of this?',
		answerTitleHtml: '<strong>Mediterranean Sea</strong>',
		answerDescriptionHtml: 'Location: Between Europe, Africa, and Asia',
		pathToMedia: 'images/world-cities-landmarks-europe/mediterranean-sea.jpg',
		category: 'world-cities-landmarks-europe',
	},
	{
		questionTitleHtml: '<strong>English Channel</strong>',
		questionDescriptionHtml: 'What is the location or description of this?',
		answerTitleHtml: '<strong>English Channel</strong>',
		answerDescriptionHtml: 'Location: Between England and France',
		pathToMedia: 'images/world-cities-landmarks-europe/english-channel.jpg',
		category: 'world-cities-landmarks-europe',
	},
	{
		questionTitleHtml: '<strong>Strait of Gibraltar</strong>',
		questionDescriptionHtml: 'What is the location or description of this?',
		answerTitleHtml: '<strong>Strait of Gibraltar</strong>',
		answerDescriptionHtml: 'Location: Between Spain and Morocco, connecting Mediterranean Sea and Atlantic Ocean',
		pathToMedia: 'images/world-cities-landmarks-europe/strait-of-gibraltar.png',
		category: 'world-cities-landmarks-europe',
	},
	{
		questionTitleHtml: '<strong>Bosporus Strait</strong>',
		questionDescriptionHtml: 'What is the location or description of this?',
		answerTitleHtml: '<strong>Bosporus Strait</strong>',
		answerDescriptionHtml: 'Location: Turkey, connecting Black Sea and Sea of Marmara',
		pathToMedia: 'images/world-cities-landmarks-europe/turkish-strait.png',
		category: 'world-cities-landmarks-europe',
	},
	{
		questionTitleHtml: '<strong>Dardanelles</strong>',
		questionDescriptionHtml: 'What is the location or description of this?',
		answerTitleHtml: '<strong>Dardanelles</strong>',
		answerDescriptionHtml: 'Location: Turkey, connecting Sea of Marmara and Aegean Sea',
		pathToMedia: 'images/world-cities-landmarks-europe/turkish-strait.png',
		category: 'world-cities-landmarks-europe',
	},
	{
		questionTitleHtml: '<strong>Balkan Peninsula</strong>',
		questionDescriptionHtml: 'What is the location or description of this?',
		answerTitleHtml: '<strong>Balkan Peninsula</strong>',
		answerDescriptionHtml: 'Location: Southeastern Europe',
		pathToMedia: 'images/world-cities-landmarks-europe/balkan-peninsula.webp',
		category: 'world-cities-landmarks-europe',
	},
	{
		questionTitleHtml: '<strong>Iberian Peninsula</strong>',
		questionDescriptionHtml: 'What is the location or description of this?',
		answerTitleHtml: '<strong>Iberian Peninsula</strong>',
		answerDescriptionHtml: 'Location: Southwestern Europe (Spain, Portugal)',
		pathToMedia: 'images/world-cities-landmarks-europe/iberian-peninsula.jpg',
		category: 'world-cities-landmarks-europe',
	},
	{
		questionTitleHtml: '<strong>Scandinavian Peninsula</strong>',
		questionDescriptionHtml: 'What is the location or description of this?',
		answerTitleHtml: '<strong>Scandinavian Peninsula</strong>',
		answerDescriptionHtml: 'Location: Northern Europe (Norway, Sweden)',
		pathToMedia: 'images/world-cities-landmarks-europe/scandinavian-peninsula.png',
		category: 'world-cities-landmarks-europe',
	},
	{
		questionTitleHtml: '<strong>Venice Canals</strong>',
		questionDescriptionHtml: 'What is the location or description of this?',
		answerTitleHtml: '<strong>Venice Canals</strong>',
		answerDescriptionHtml: 'Location: Venice, Italy',
		pathToMedia: 'images/world-cities-landmarks-europe/venice-canals.jpg',
		category: 'world-cities-landmarks-europe',
	},
	{
		questionTitleHtml: '<strong>Leaning Tower of Pisa</strong>',
		questionDescriptionHtml: 'What is the location or description of this?',
		answerTitleHtml: '<strong>Leaning Tower of Pisa</strong>',
		answerDescriptionHtml: 'Location: Pisa, Italy',
		pathToMedia: 'images/world-cities-landmarks-europe/leaning-tower.jpg',
		category: 'world-cities-landmarks-europe',
	},
	{
		questionTitleHtml: '<strong>Stonehenge</strong>',
		questionDescriptionHtml: 'What is the location or description of this?',
		answerTitleHtml: '<strong>Stonehenge</strong>',
		answerDescriptionHtml: 'Location: England, United Kingdom',
		pathToMedia: 'images/world-cities-landmarks-europe/stonehenge.jpg',
		category: 'world-cities-landmarks-europe',
	},
	{
		questionTitleHtml: '<strong>Versailles</strong>',
		questionDescriptionHtml: 'What is the location or description of this?',
		answerTitleHtml: '<strong>Versailles</strong>',
		answerDescriptionHtml: 'Location: France',
		pathToMedia: 'images/world-cities-landmarks-europe/versailles.jpg',
		category: 'world-cities-landmarks-europe',
	},
	{
		questionTitleHtml: '<strong>The Colosseum</strong>',
		questionDescriptionHtml: 'What is the location or description of this?',
		answerTitleHtml: '<strong>The Colosseum</strong>',
		answerDescriptionHtml: 'Location: Rome, Italy',
		pathToMedia: 'images/world-cities-landmarks-europe/colosseum.jpg',
		category: 'world-cities-landmarks-europe',
	},
	{
		questionTitleHtml: '<strong>The Tower of London</strong>',
		questionDescriptionHtml: 'What is the location or description of this?',
		answerTitleHtml: '<strong>The Tower of London</strong>',
		answerDescriptionHtml: 'Location: London, England, United Kingdom',
		pathToMedia: 'images/world-cities-landmarks-europe/tower-of-london.jpg',
		category: 'world-cities-landmarks-europe',
	},
	{
		questionTitleHtml: '<strong>Big Ben</strong>',
		questionDescriptionHtml: 'What is the location or description of this?',
		answerTitleHtml: '<strong>Big Ben</strong>',
		answerDescriptionHtml: 'Location: London, England, United Kingdom',
		pathToMedia: 'images/world-cities-landmarks-europe/big-ben.jpg',
		category: 'world-cities-landmarks-europe',
	},
	{
		questionTitleHtml: '<strong>Eiffel Tower</strong>',
		questionDescriptionHtml: 'What is the location or description of this?',
		answerTitleHtml: '<strong>Eiffel Tower</strong>',
		answerDescriptionHtml: 'Location: Paris, France',
		pathToMedia: 'images/world-cities-landmarks-europe/eiffel-tower.jpg',
		category: 'world-cities-landmarks-europe',
	},
	{
		questionTitleHtml: '<strong>Vatican</strong>',
		questionDescriptionHtml: 'What is the location or description of this?',
		answerTitleHtml: '<strong>Vatican</strong>',
		answerDescriptionHtml: 'Location: Vatican City (within Rome, Italy)',
		pathToMedia: 'images/world-cities-landmarks-europe/vatican.jpg',
		category: 'world-cities-landmarks-europe',
	},
	{
		questionTitleHtml: '<strong>Red Square</strong>',
		questionDescriptionHtml: 'What is the location or description of this?',
		answerTitleHtml: '<strong>Red Square</strong>',
		answerDescriptionHtml: 'Location: Moscow, Russia',
		pathToMedia: 'images/world-cities-landmarks-europe/red-square.jpg',
		category: 'world-cities-landmarks-europe',
	},
	{
		questionTitleHtml: '<strong>Low Countries</strong>',
		questionDescriptionHtml: 'What is the location or description of this?',
		answerTitleHtml: '<strong>Low Countries</strong>',
		answerDescriptionHtml: 'Location: Belgium, Netherlands, Luxembourg',
		pathToMedia: 'images/world-cities-landmarks-europe/low-countries.png',
		category: 'world-cities-landmarks-europe',
	},
	{
		questionTitleHtml: '<strong>Scandinavia</strong>',
		questionDescriptionHtml: 'What is the location or description of this?',
		answerTitleHtml: '<strong>Scandinavia</strong>',
		answerDescriptionHtml: 'Location: Northern Europe (traditionally Norway, Sweden, Denmark)',
		pathToMedia: 'images/world-cities-landmarks-europe/scandinavia.png',
		category: 'world-cities-landmarks-europe',
	},
	{
		questionTitleHtml: '<strong>The Eternal City</strong>',
		questionDescriptionHtml: 'What is the location or description of this?',
		answerTitleHtml: '<strong>The Eternal City</strong>',
		answerDescriptionHtml: 'A nickname for Rome, Italy',
		pathToMedia: null,
		category: 'world-cities-landmarks-europe',
	},
	{
		questionTitleHtml: '<strong>What is this?</strong>',
		questionDescriptionHtml: null,
		answerTitleHtml: '<strong>Sicily</strong>',
		answerDescriptionHtml: 'Location: Mediterranean Sea (part of Italy)',
		pathToMedia: 'images/world-cities-landmarks-europe/sicily.png',
		category: 'world-cities-landmarks-europe',
	},
	{
		questionTitleHtml: '<strong>Azores</strong>',
		questionDescriptionHtml: 'What is the location or description of this?',
		answerTitleHtml: '<strong>Azores</strong>',
		answerDescriptionHtml: 'Location: Islands in North Atlantic Ocean (autonomous region of Portugal)',
		pathToMedia: 'images/world-cities-landmarks-europe/azores.png',
		category: 'world-cities-landmarks-europe',
	},
]
