import type { FlashCard } from '@/types'

export const world_country_flags_europe: FlashCard[] = [
	{
		questionTitleHtml: '<strong>What country is this flag?</strong>',
		questionDescriptionHtml: '',
		answerTitleHtml: '<strong>Albania</strong>',
		answerDescriptionHtml: 'Country Flag',
		pathToMedia: 'node_modules/svg-country-flags/svg/al.svg',
		category: 'world-country-flags-europe',
	},
	{
		questionTitleHtml: '<strong>What country is this flag?</strong>',
		questionDescriptionHtml: '',
		answerTitleHtml: '<strong>Armenia</strong>',
		answerDescriptionHtml: 'Country Flag',
		pathToMedia: 'node_modules/svg-country-flags/svg/am.svg',
		category: 'world-country-flags-europe',
	},
	{
		questionTitleHtml: '<strong>What country is this flag?</strong>',
		questionDescriptionHtml: '',
		answerTitleHtml: '<strong>Austria</strong>',
		answerDescriptionHtml: 'Country Flag',
		pathToMedia: 'node_modules/svg-country-flags/svg/at.svg',
		category: 'world-country-flags-europe',
	},
	{
		questionTitleHtml: '<strong>What country is this flag?</strong>',
		questionDescriptionHtml: '',
		answerTitleHtml: '<strong>Belgium</strong>',
		answerDescriptionHtml: 'Country Flag',
		pathToMedia: 'node_modules/svg-country-flags/svg/be.svg',
		category: 'world-country-flags-europe',
	},
	{
		questionTitleHtml: '<strong>What country is this flag?</strong>',
		questionDescriptionHtml: '',
		answerTitleHtml: '<strong>Bosnia and Herzegovina</strong>',
		answerDescriptionHtml: 'Country Flag',
		pathToMedia: 'node_modules/svg-country-flags/svg/ba.svg',
		category: 'world-country-flags-europe',
	},
	{
		questionTitleHtml: '<strong>What country is this flag?</strong>',
		questionDescriptionHtml: '',
		answerTitleHtml: '<strong>Bulgaria</strong>',
		answerDescriptionHtml: 'Country Flag',
		pathToMedia: 'node_modules/svg-country-flags/svg/bg.svg',
		category: 'world-country-flags-europe',
	},
	{
		questionTitleHtml: '<strong>What country is this flag?</strong>',
		questionDescriptionHtml: '',
		answerTitleHtml: '<strong>Croatia</strong>',
		answerDescriptionHtml: 'Country Flag',
		pathToMedia: 'node_modules/svg-country-flags/svg/hr.svg',
		category: 'world-country-flags-europe',
	},
	{
		questionTitleHtml: '<strong>What country is this flag?</strong>',
		questionDescriptionHtml: '',
		answerTitleHtml: '<strong>Czech Republic</strong>',
		answerDescriptionHtml: 'Country Flag',
		pathToMedia: 'node_modules/svg-country-flags/svg/cz.svg',
		category: 'world-country-flags-europe',
	},
	{
		questionTitleHtml: '<strong>What country is this flag?</strong>',
		questionDescriptionHtml: '',
		answerTitleHtml: '<strong>Denmark</strong>',
		answerDescriptionHtml: 'Country Flag',
		pathToMedia: 'node_modules/svg-country-flags/svg/dk.svg',
		category: 'world-country-flags-europe',
	},
	{
		questionTitleHtml: '<strong>What country is this flag?</strong>',
		questionDescriptionHtml: '',
		answerTitleHtml: '<strong>Estonia</strong>',
		answerDescriptionHtml: 'Country Flag',
		pathToMedia: 'node_modules/svg-country-flags/svg/ee.svg',
		category: 'world-country-flags-europe',
	},
	{
		questionTitleHtml: '<strong>What country is this flag?</strong>',
		questionDescriptionHtml: '',
		answerTitleHtml: '<strong>Finland</strong>',
		answerDescriptionHtml: 'Country Flag',
		pathToMedia: 'node_modules/svg-country-flags/svg/fi.svg',
		category: 'world-country-flags-europe',
	},
	{
		questionTitleHtml: '<strong>What country is this flag?</strong>',
		questionDescriptionHtml: '',
		answerTitleHtml: '<strong>France</strong>',
		answerDescriptionHtml: 'Country Flag',
		pathToMedia: 'node_modules/svg-country-flags/svg/fr.svg',
		category: 'world-country-flags-europe',
	},
	{
		questionTitleHtml: '<strong>What country is this flag?</strong>',
		questionDescriptionHtml: '',
		answerTitleHtml: '<strong>Georgia</strong>',
		answerDescriptionHtml: 'Country Flag',
		pathToMedia: 'node_modules/svg-country-flags/svg/ge.svg',
		category: 'world-country-flags-europe',
	},
	{
		questionTitleHtml: '<strong>What country is this flag?</strong>',
		questionDescriptionHtml: '',
		answerTitleHtml: '<strong>Germany</strong>',
		answerDescriptionHtml: 'Country Flag',
		pathToMedia: 'node_modules/svg-country-flags/svg/de.svg',
		category: 'world-country-flags-europe',
	},
	{
		questionTitleHtml: '<strong>What country is this flag?</strong>',
		questionDescriptionHtml: '',
		answerTitleHtml: '<strong>Greece</strong>',
		answerDescriptionHtml: 'Country Flag',
		pathToMedia: 'node_modules/svg-country-flags/svg/gr.svg',
		category: 'world-country-flags-europe',
	},
	{
		questionTitleHtml: '<strong>What country is this flag?</strong>',
		questionDescriptionHtml: '',
		answerTitleHtml: '<strong>Hungary</strong>',
		answerDescriptionHtml: 'Country Flag',
		pathToMedia: 'node_modules/svg-country-flags/svg/hu.svg',
		category: 'world-country-flags-europe',
	},
	{
		questionTitleHtml: '<strong>What country is this flag?</strong>',
		questionDescriptionHtml: '',
		answerTitleHtml: '<strong>Iceland</strong>',
		answerDescriptionHtml: 'Country Flag',
		pathToMedia: 'node_modules/svg-country-flags/svg/is.svg',
		category: 'world-country-flags-europe',
	},
	{
		questionTitleHtml: '<strong>What country is this flag?</strong>',
		questionDescriptionHtml: '',
		answerTitleHtml: '<strong>Ireland</strong>',
		answerDescriptionHtml: 'Country Flag',
		pathToMedia: 'node_modules/svg-country-flags/svg/ie.svg',
		category: 'world-country-flags-europe',
	},
	{
		questionTitleHtml: '<strong>What country is this flag?</strong>',
		questionDescriptionHtml: '',
		answerTitleHtml: '<strong>Italy</strong>',
		answerDescriptionHtml: 'Country Flag',
		pathToMedia: 'node_modules/svg-country-flags/svg/it.svg',
		category: 'world-country-flags-europe',
	},
	{
		questionTitleHtml: '<strong>What country is this flag?</strong>',
		questionDescriptionHtml: '',
		answerTitleHtml: '<strong>Latvia</strong>',
		answerDescriptionHtml: 'Country Flag',
		pathToMedia: 'node_modules/svg-country-flags/svg/lv.svg',
		category: 'world-country-flags-europe',
	},
	{
		questionTitleHtml: '<strong>What country is this flag?</strong>',
		questionDescriptionHtml: '',
		answerTitleHtml: '<strong>Liechtenstein</strong>',
		answerDescriptionHtml: 'Country Flag',
		pathToMedia: 'node_modules/svg-country-flags/svg/li.svg',
		category: 'world-country-flags-europe',
	},
	{
		questionTitleHtml: '<strong>What country is this flag?</strong>',
		questionDescriptionHtml: '',
		answerTitleHtml: '<strong>Lithuania</strong>',
		answerDescriptionHtml: 'Country Flag',
		pathToMedia: 'node_modules/svg-country-flags/svg/lt.svg',
		category: 'world-country-flags-europe',
	},
	{
		questionTitleHtml: '<strong>What country is this flag?</strong>',
		questionDescriptionHtml: '',
		answerTitleHtml: '<strong>Luxembourg</strong>',
		answerDescriptionHtml: 'Country Flag',
		pathToMedia: 'node_modules/svg-country-flags/svg/lu.svg',
		category: 'world-country-flags-europe',
	},
	{
		questionTitleHtml: '<strong>What country is this flag?</strong>',
		questionDescriptionHtml: '',
		answerTitleHtml: '<strong>Macedonia (North Macedonia)</strong>',
		answerDescriptionHtml: 'Country Flag',
		pathToMedia: 'node_modules/svg-country-flags/svg/mk.svg',
		category: 'world-country-flags-europe',
	},
	{
		questionTitleHtml: '<strong>What country is this flag?</strong>',
		questionDescriptionHtml: '',
		answerTitleHtml: '<strong>Malta</strong>',
		answerDescriptionHtml: 'Country Flag',
		pathToMedia: 'node_modules/svg-country-flags/svg/mt.svg',
		category: 'world-country-flags-europe',
	},
	{
		questionTitleHtml: '<strong>What country is this flag?</strong>',
		questionDescriptionHtml: '',
		answerTitleHtml: '<strong>Moldova</strong>',
		answerDescriptionHtml: 'Country Flag',
		pathToMedia: 'node_modules/svg-country-flags/svg/md.svg',
		category: 'world-country-flags-europe',
	},
	{
		questionTitleHtml: '<strong>What country is this flag?</strong>',
		questionDescriptionHtml: '',
		answerTitleHtml: '<strong>Monaco</strong>',
		answerDescriptionHtml: 'Country Flag',
		pathToMedia: 'node_modules/svg-country-flags/svg/mc.svg',
		category: 'world-country-flags-europe',
	},
	{
		questionTitleHtml: '<strong>What country is this flag?</strong>',
		questionDescriptionHtml: '',
		answerTitleHtml: '<strong>Montenegro</strong>',
		answerDescriptionHtml: 'Country Flag',
		pathToMedia: 'node_modules/svg-country-flags/svg/me.svg',
		category: 'world-country-flags-europe',
	},
	{
		questionTitleHtml: '<strong>What country is this flag?</strong>',
		questionDescriptionHtml: '',
		answerTitleHtml: '<strong>Netherlands</strong>',
		answerDescriptionHtml: 'Country Flag',
		pathToMedia: 'node_modules/svg-country-flags/svg/nl.svg',
		category: 'world-country-flags-europe',
	},
	{
		questionTitleHtml: '<strong>What country is this flag?</strong>',
		questionDescriptionHtml: '',
		answerTitleHtml: '<strong>Norway</strong>',
		answerDescriptionHtml: 'Country Flag',
		pathToMedia: 'node_modules/svg-country-flags/svg/no.svg',
		category: 'world-country-flags-europe',
	},
	{
		questionTitleHtml: '<strong>What country is this flag?</strong>',
		questionDescriptionHtml: '',
		answerTitleHtml: '<strong>Poland</strong>',
		answerDescriptionHtml: 'Country Flag',
		pathToMedia: 'node_modules/svg-country-flags/svg/pl.svg',
		category: 'world-country-flags-europe',
	},
	{
		questionTitleHtml: '<strong>What country is this flag?</strong>',
		questionDescriptionHtml: '',
		answerTitleHtml: '<strong>Portugal</strong>',
		answerDescriptionHtml: 'Country Flag',
		pathToMedia: 'node_modules/svg-country-flags/svg/pt.svg',
		category: 'world-country-flags-europe',
	},
	{
		questionTitleHtml: '<strong>What country is this flag?</strong>',
		questionDescriptionHtml: '',
		answerTitleHtml: '<strong>Romania</strong>',
		answerDescriptionHtml: 'Country Flag',
		pathToMedia: 'node_modules/svg-country-flags/svg/ro.svg',
		category: 'world-country-flags-europe',
	},
	{
		questionTitleHtml: '<strong>What country is this flag?</strong>',
		questionDescriptionHtml: '',
		answerTitleHtml: '<strong>Russia</strong>',
		answerDescriptionHtml: 'Country Flag',
		pathToMedia: 'node_modules/svg-country-flags/svg/ru.svg',
		category: 'world-country-flags-europe',
	},
	{
		questionTitleHtml: '<strong>What country is this flag?</strong>',
		questionDescriptionHtml: '',
		answerTitleHtml: '<strong>Serbia</strong>',
		answerDescriptionHtml: 'Country Flag',
		pathToMedia: 'node_modules/svg-country-flags/svg/rs.svg',
		category: 'world-country-flags-europe',
	},
	{
		questionTitleHtml: '<strong>What country is this flag?</strong>',
		questionDescriptionHtml: '',
		answerTitleHtml: '<strong>Slovakia</strong>',
		answerDescriptionHtml: 'Country Flag',
		pathToMedia: 'node_modules/svg-country-flags/svg/sk.svg',
		category: 'world-country-flags-europe',
	},
	{
		questionTitleHtml: '<strong>What country is this flag?</strong>',
		questionDescriptionHtml: '',
		answerTitleHtml: '<strong>Slovenia</strong>',
		answerDescriptionHtml: 'Country Flag',
		pathToMedia: 'node_modules/svg-country-flags/svg/si.svg',
		category: 'world-country-flags-europe',
	},
	{
		questionTitleHtml: '<strong>What country is this flag?</strong>',
		questionDescriptionHtml: '',
		answerTitleHtml: '<strong>Spain</strong>',
		answerDescriptionHtml: 'Country Flag',
		pathToMedia: 'node_modules/svg-country-flags/svg/es.svg',
		category: 'world-country-flags-europe',
	},
	{
		questionTitleHtml: '<strong>What country is this flag?</strong>',
		questionDescriptionHtml: '',
		answerTitleHtml: '<strong>Sweden</strong>',
		answerDescriptionHtml: 'Country Flag',
		pathToMedia: 'node_modules/svg-country-flags/svg/se.svg',
		category: 'world-country-flags-europe',
	},
	{
		questionTitleHtml: '<strong>What country is this flag?</strong>',
		questionDescriptionHtml: '',
		answerTitleHtml: '<strong>Switzerland</strong>',
		answerDescriptionHtml: 'Country Flag',
		pathToMedia: 'node_modules/svg-country-flags/svg/ch.svg',
		category: 'world-country-flags-europe',
	},
	{
		questionTitleHtml: '<strong>What country is this flag?</strong>',
		questionDescriptionHtml: '',
		answerTitleHtml: '<strong>Turkey</strong>',
		answerDescriptionHtml: 'Country Flag',
		pathToMedia: 'node_modules/svg-country-flags/svg/tr.svg',
		category: 'world-country-flags-europe',
	},
	{
		questionTitleHtml: '<strong>What country is this flag?</strong>',
		questionDescriptionHtml: '',
		answerTitleHtml: '<strong>Ukraine</strong>',
		answerDescriptionHtml: 'Country Flag',
		pathToMedia: 'node_modules/svg-country-flags/svg/ua.svg',
		category: 'world-country-flags-europe',
	},
	{
		questionTitleHtml: '<strong>What country is this flag?</strong>',
		questionDescriptionHtml: '',
		answerTitleHtml: '<strong>United Kingdom</strong>',
		answerDescriptionHtml: 'Country Flag',
		pathToMedia: 'node_modules/svg-country-flags/svg/gb.svg',
		category: 'world-country-flags-europe',
	},
	{
		questionTitleHtml: '<strong>What country is this flag?</strong>',
		questionDescriptionHtml: '',
		answerTitleHtml: '<strong>Vatican City</strong>',
		answerDescriptionHtml: 'Country Flag',
		pathToMedia: 'node_modules/svg-country-flags/svg/va.svg',
		category: 'world-country-flags-europe',
	},
]
