import type { FlashCard } from '@/types'

export const world_cities_landmarks_north_america: FlashCard[] = [
	{
		questionTitleHtml: '<strong>Atlantic City</strong>',
		questionDescriptionHtml: 'What is the location or description of this?',
		answerTitleHtml: '<strong>Atlantic City</strong>',
		answerDescriptionHtml: 'Location: New Jersey, United States<br>Famous resort city on the Atlantic coast',
		pathToMedia: 'placeholder',
		category: 'world-cities-landmarks-north-america',
	},
	{
		questionTitleHtml: '<strong>Chicago</strong>',
		questionDescriptionHtml: 'What is the location or description of this?',
		answerTitleHtml: '<strong>Chicago</strong>',
		answerDescriptionHtml: 'Location: Illinois, United States<br>Major city on Lake Michigan',
		pathToMedia: 'placeholder',
		category: 'world-cities-landmarks-north-america',
	},
	{
		questionTitleHtml: '<strong>Los Angeles</strong>',
		questionDescriptionHtml: 'What is the location or description of this?',
		answerTitleHtml: '<strong>Los Angeles</strong>',
		answerDescriptionHtml: 'Location: California, United States<br>Major city on the Pacific coast, center of entertainment industry',
		pathToMedia: 'placeholder',
		category: 'world-cities-landmarks-north-america',
	},
	{
		questionTitleHtml: '<strong>Montreal</strong>',
		questionDescriptionHtml: 'What is the location or description of this?',
		answerTitleHtml: '<strong>Montreal</strong>',
		answerDescriptionHtml: 'Location: Quebec, Canada<br>Major city in eastern Canada',
		pathToMedia: 'placeholder',
		category: 'world-cities-landmarks-north-america',
	},
	{
		questionTitleHtml: '<strong>New York</strong>',
		questionDescriptionHtml: 'What is the location or description of this?',
		answerTitleHtml: '<strong>New York</strong>',
		answerDescriptionHtml: 'Location: New York, United States<br>Major city on the Atlantic coast, largest city in the U.S.',
		pathToMedia: 'placeholder',
		category: 'world-cities-landmarks-north-america',
	},
	{
		questionTitleHtml: '<strong>Philadelphia</strong>',
		questionDescriptionHtml: 'What is the location or description of this?',
		answerTitleHtml: '<strong>Philadelphia</strong>',
		answerDescriptionHtml: 'Location: Pennsylvania, United States<br>Historic city, birthplace of American independence',
		pathToMedia: 'placeholder',
		category: 'world-cities-landmarks-north-america',
	},
	{
		questionTitleHtml: '<strong>San Francisco</strong>',
		questionDescriptionHtml: 'What is the location or description of this?',
		answerTitleHtml: '<strong>San Francisco</strong>',
		answerDescriptionHtml: 'Location: California, United States<br>Major city on the Pacific coast',
		pathToMedia: 'placeholder',
		category: 'world-cities-landmarks-north-america',
	},
	{
		questionTitleHtml: '<strong>Chihuahuan Desert</strong>',
		questionDescriptionHtml: 'What is the location or description of this?',
		answerTitleHtml: '<strong>Chihuahuan Desert</strong>',
		answerDescriptionHtml: 'Location: Mexico, United States<br>Largest desert in North America',
		pathToMedia: 'placeholder',
		category: 'world-cities-landmarks-north-america',
	},
	{
		questionTitleHtml: '<strong>Sonoran Desert</strong>',
		questionDescriptionHtml: 'What is the location or description of this?',
		answerTitleHtml: '<strong>Sonoran Desert</strong>',
		answerDescriptionHtml: 'Location: United States (Arizona, California), Mexico<br>Hottest desert in North America',
		pathToMedia: 'placeholder',
		category: 'world-cities-landmarks-north-america',
	},
	{
		questionTitleHtml: '<strong>Andaman Sea</strong>',
		questionDescriptionHtml: 'What is the location or description of this?',
		answerTitleHtml: '<strong>Andaman Sea</strong>',
		answerDescriptionHtml: 'Location: Eastern Indian Ocean, between India and Myanmar',
		pathToMedia: 'placeholder',
		category: 'world-cities-landmarks-north-america',
	},
	{
		questionTitleHtml: '<strong>Arabian Sea</strong>',
		questionDescriptionHtml: 'What is the location or description of this?',
		answerTitleHtml: '<strong>Arabian Sea</strong>',
		answerDescriptionHtml: 'Location: Northern Indian Ocean, between Arabian Peninsula and India',
		pathToMedia: 'placeholder',
		category: 'world-cities-landmarks-north-america',
	},
	{
		questionTitleHtml: '<strong>Baltic Sea</strong>',
		questionDescriptionHtml: 'What is the location or description of this?',
		answerTitleHtml: '<strong>Baltic Sea</strong>',
		answerDescriptionHtml: 'Location: Northern Europe, between Scandinavia and Central Europe',
		pathToMedia: 'placeholder',
		category: 'world-cities-landmarks-north-america',
	},
	{
		questionTitleHtml: '<strong>Bering Sea</strong>',
		questionDescriptionHtml: 'What is the location or description of this?',
		answerTitleHtml: '<strong>Bering Sea</strong>',
		answerDescriptionHtml: 'Location: Northern Pacific Ocean, between Alaska and Russia',
		pathToMedia: 'placeholder',
		category: 'world-cities-landmarks-north-america',
	},
	{
		questionTitleHtml: '<strong>Black Sea</strong>',
		questionDescriptionHtml: 'What is the location or description of this?',
		answerTitleHtml: '<strong>Black Sea</strong>',
		answerDescriptionHtml: 'Location: Between Europe and Asia, bordered by Turkey, Bulgaria, Romania, Ukraine, Russia, Georgia',
		pathToMedia: 'placeholder',
		category: 'world-cities-landmarks-north-america',
	},
	{
		questionTitleHtml: '<strong>Caribbean Sea</strong>',
		questionDescriptionHtml: 'What is the location or description of this?',
		answerTitleHtml: '<strong>Caribbean Sea</strong>',
		answerDescriptionHtml: 'Location: Western Atlantic Ocean, between North and South America',
		pathToMedia: 'placeholder',
		category: 'world-cities-landmarks-north-america',
	},
	{
		questionTitleHtml: '<strong>East China Sea</strong>',
		questionDescriptionHtml: 'What is the location or description of this?',
		answerTitleHtml: '<strong>East China Sea</strong>',
		answerDescriptionHtml: 'Location: Western Pacific Ocean, between China and Japan',
		pathToMedia: 'placeholder',
		category: 'world-cities-landmarks-north-america',
	},
	{
		questionTitleHtml: '<strong>Gulf of Mexico</strong>',
		questionDescriptionHtml: 'What is the location or description of this?',
		answerTitleHtml: '<strong>Gulf of Mexico</strong>',
		answerDescriptionHtml: 'Location: Between United States and Mexico',
		pathToMedia: 'placeholder',
		category: 'world-cities-landmarks-north-america',
	},
	{
		questionTitleHtml: '<strong>Hudson Bay</strong>',
		questionDescriptionHtml: 'What is the location or description of this?',
		answerTitleHtml: '<strong>Hudson Bay</strong>',
		answerDescriptionHtml: 'Location: Northeastern Canada',
		pathToMedia: 'placeholder',
		category: 'world-cities-landmarks-north-america',
	},
	{
		questionTitleHtml: '<strong>Mediterranean Sea</strong>',
		questionDescriptionHtml: 'What is the location or description of this?',
		answerTitleHtml: '<strong>Mediterranean Sea</strong>',
		answerDescriptionHtml: 'Location: Between Europe, Africa, and Asia',
		pathToMedia: 'placeholder',
		category: 'world-cities-landmarks-north-america',
	},
	{
		questionTitleHtml: '<strong>Red Sea</strong>',
		questionDescriptionHtml: 'What is the location or description of this?',
		answerTitleHtml: '<strong>Red Sea</strong>',
		answerDescriptionHtml: 'Location: Between Africa and Arabian Peninsula',
		pathToMedia: 'placeholder',
		category: 'world-cities-landmarks-north-america',
	},
	{
		questionTitleHtml: '<strong>Sea of Japan</strong>',
		questionDescriptionHtml: 'What is the location or description of this?',
		answerTitleHtml: '<strong>Sea of Japan</strong>',
		answerDescriptionHtml: 'Location: Between Japan and Korea',
		pathToMedia: 'placeholder',
		category: 'world-cities-landmarks-north-america',
	},
	{
		questionTitleHtml: '<strong>Sea of Okhotsk</strong>',
		questionDescriptionHtml: 'What is the location or description of this?',
		answerTitleHtml: '<strong>Sea of Okhotsk</strong>',
		answerDescriptionHtml: 'Location: Northwestern Pacific Ocean, between Russia and Japan',
		pathToMedia: 'placeholder',
		category: 'world-cities-landmarks-north-america',
	},
	{
		questionTitleHtml: '<strong>South China Sea</strong>',
		questionDescriptionHtml: 'What is the location or description of this?',
		answerTitleHtml: '<strong>South China Sea</strong>',
		answerDescriptionHtml: 'Location: Western Pacific Ocean, between China and Southeast Asia',
		pathToMedia: 'placeholder',
		category: 'world-cities-landmarks-north-america',
	},
	{
		questionTitleHtml: '<strong>Cape Horn</strong>',
		questionDescriptionHtml: 'What is the location or description of this?',
		answerTitleHtml: '<strong>Cape Horn</strong>',
		answerDescriptionHtml: 'Location: Southern Chile, South America',
		pathToMedia: 'placeholder',
		category: 'world-cities-landmarks-north-america',
	},
	{
		questionTitleHtml: '<strong>Cape Cod</strong>',
		questionDescriptionHtml: 'What is the location or description of this?',
		answerTitleHtml: '<strong>Cape Cod</strong>',
		answerDescriptionHtml: 'Location: Massachusetts, United States',
		pathToMedia: 'placeholder',
		category: 'world-cities-landmarks-north-america',
	},
	{
		questionTitleHtml: '<strong>Cape Canaveral</strong>',
		questionDescriptionHtml: 'What is the location or description of this?',
		answerTitleHtml: '<strong>Cape Canaveral</strong>',
		answerDescriptionHtml: 'Location: Florida, United States',
		pathToMedia: 'placeholder',
		category: 'world-cities-landmarks-north-america',
	},
	{
		questionTitleHtml: '<strong>Kanyakumari (Cape Comorin)</strong>',
		questionDescriptionHtml: 'What is the location or description of this?',
		answerTitleHtml: '<strong>Kanyakumari (Cape Comorin)</strong>',
		answerDescriptionHtml: 'Location: Southern India',
		pathToMedia: 'placeholder',
		category: 'world-cities-landmarks-north-america',
	},
	{
		questionTitleHtml: '<strong>Cape of Good Hope</strong>',
		questionDescriptionHtml: 'What is the location or description of this?',
		answerTitleHtml: '<strong>Cape of Good Hope</strong>',
		answerDescriptionHtml: 'Location: South Africa',
		pathToMedia: 'placeholder',
		category: 'world-cities-landmarks-north-america',
	},
	{
		questionTitleHtml: '<strong>Balkan Peninsula</strong>',
		questionDescriptionHtml: 'What is the location or description of this?',
		answerTitleHtml: '<strong>Balkan Peninsula</strong>',
		answerDescriptionHtml: 'Location: Southeastern Europe',
		pathToMedia: 'placeholder',
		category: 'world-cities-landmarks-north-america',
	},
	{
		questionTitleHtml: '<strong>Iberian Peninsula</strong>',
		questionDescriptionHtml: 'What is the location or description of this?',
		answerTitleHtml: '<strong>Iberian Peninsula</strong>',
		answerDescriptionHtml: 'Location: Southwestern Europe (Spain, Portugal)',
		pathToMedia: 'placeholder',
		category: 'world-cities-landmarks-north-america',
	},
	{
		questionTitleHtml: '<strong>Scandinavian Peninsula</strong>',
		questionDescriptionHtml: 'What is the location or description of this?',
		answerTitleHtml: '<strong>Scandinavian Peninsula</strong>',
		answerDescriptionHtml: 'Location: Northern Europe (Norway, Sweden)',
		pathToMedia: 'placeholder',
		category: 'world-cities-landmarks-north-america',
	},
	{
		questionTitleHtml: '<strong>Sinai Peninsula</strong>',
		questionDescriptionHtml: 'What is the location or description of this?',
		answerTitleHtml: '<strong>Sinai Peninsula</strong>',
		answerDescriptionHtml: 'Location: Egypt',
		pathToMedia: 'placeholder',
		category: 'world-cities-landmarks-north-america',
	},
	{
		questionTitleHtml: '<strong>Korean Peninsula</strong>',
		questionDescriptionHtml: 'What is the location or description of this?',
		answerTitleHtml: '<strong>Korean Peninsula</strong>',
		answerDescriptionHtml: 'Location: East Asia (North Korea, South Korea)',
		pathToMedia: 'placeholder',
		category: 'world-cities-landmarks-north-america',
	},
	{
		questionTitleHtml: '<strong>Olympic Peninsula</strong>',
		questionDescriptionHtml: 'What is the location or description of this?',
		answerTitleHtml: '<strong>Olympic Peninsula</strong>',
		answerDescriptionHtml: 'Location: Washington, United States',
		pathToMedia: 'placeholder',
		category: 'world-cities-landmarks-north-america',
	},
	{
		questionTitleHtml: '<strong>Baja California Peninsula</strong>',
		questionDescriptionHtml: 'What is the location or description of this?',
		answerTitleHtml: '<strong>Baja California Peninsula</strong>',
		answerDescriptionHtml: 'Location: Mexico',
		pathToMedia: 'placeholder',
		category: 'world-cities-landmarks-north-america',
	},
	{
		questionTitleHtml: '<strong>Great Barrier Reef</strong>',
		questionDescriptionHtml: 'What is the location or description of this?',
		answerTitleHtml: '<strong>Great Barrier Reef</strong>',
		answerDescriptionHtml: 'Location: Australia (off the coast of Queensland)',
		pathToMedia: 'placeholder',
		category: 'world-cities-landmarks-north-america',
	},
	{
		questionTitleHtml: '<strong>English Channel</strong>',
		questionDescriptionHtml: 'What is the location or description of this?',
		answerTitleHtml: '<strong>English Channel</strong>',
		answerDescriptionHtml: 'Location: Between England and France',
		pathToMedia: 'placeholder',
		category: 'world-cities-landmarks-north-america',
	},
	{
		questionTitleHtml: '<strong>Strait of Gibraltar</strong>',
		questionDescriptionHtml: 'What is the location or description of this?',
		answerTitleHtml: '<strong>Strait of Gibraltar</strong>',
		answerDescriptionHtml: 'Location: Between Spain and Morocco, connecting Mediterranean Sea and Atlantic Ocean',
		pathToMedia: 'placeholder',
		category: 'world-cities-landmarks-north-america',
	},
	{
		questionTitleHtml: '<strong>Bosporus</strong>',
		questionDescriptionHtml: 'What is the location or description of this?',
		answerTitleHtml: '<strong>Bosporus</strong>',
		answerDescriptionHtml: 'Location: Turkey, connecting Black Sea and Sea of Marmara',
		pathToMedia: 'placeholder',
		category: 'world-cities-landmarks-north-america',
	},
	{
		questionTitleHtml: '<strong>Dardanelles</strong>',
		questionDescriptionHtml: 'What is the location or description of this?',
		answerTitleHtml: '<strong>Dardanelles</strong>',
		answerDescriptionHtml: 'Location: Turkey, connecting Sea of Marmara and Aegean Sea',
		pathToMedia: 'placeholder',
		category: 'world-cities-landmarks-north-america',
	},
	{
		questionTitleHtml: '<strong>Straits of Malacca</strong>',
		questionDescriptionHtml: 'What is the location or description of this?',
		answerTitleHtml: '<strong>Straits of Malacca</strong>',
		answerDescriptionHtml: 'Location: Between Malaysia and Indonesia',
		pathToMedia: 'placeholder',
		category: 'world-cities-landmarks-north-america',
	},
	{
		questionTitleHtml: '<strong>Erie Canal</strong>',
		questionDescriptionHtml: 'What is the location or description of this?',
		answerTitleHtml: '<strong>Erie Canal</strong>',
		answerDescriptionHtml: 'Location: New York, United States',
		pathToMedia: 'placeholder',
		category: 'world-cities-landmarks-north-america',
	},
	{
		questionTitleHtml: '<strong>Suez Canal</strong>',
		questionDescriptionHtml: 'What is the location or description of this?',
		answerTitleHtml: '<strong>Suez Canal</strong>',
		answerDescriptionHtml: 'Location: Egypt, connecting Mediterranean Sea and Red Sea',
		pathToMedia: 'placeholder',
		category: 'world-cities-landmarks-north-america',
	},
	{
		questionTitleHtml: '<strong>Panama Canal</strong>',
		questionDescriptionHtml: 'What is the location or description of this?',
		answerTitleHtml: '<strong>Panama Canal</strong>',
		answerDescriptionHtml: 'Location: Panama, connecting Atlantic and Pacific Oceans',
		pathToMedia: 'placeholder',
		category: 'world-cities-landmarks-north-america',
	},
	{
		questionTitleHtml: '<strong>Venice Canals</strong>',
		questionDescriptionHtml: 'What is the location or description of this?',
		answerTitleHtml: '<strong>Venice Canals</strong>',
		answerDescriptionHtml: 'Location: Venice, Italy',
		pathToMedia: 'placeholder',
		category: 'world-cities-landmarks-north-america',
	},
	{
		questionTitleHtml: '<strong>Greenland</strong>',
		questionDescriptionHtml: 'What is the location or description of this?',
		answerTitleHtml: '<strong>Greenland</strong>',
		answerDescriptionHtml: 'Location: North Atlantic Ocean (autonomous territory of Denmark)',
		pathToMedia: 'placeholder',
		category: 'world-cities-landmarks-north-america',
	},
	{
		questionTitleHtml: '<strong>Barbados</strong>',
		questionDescriptionHtml: 'What is the location or description of this?',
		answerTitleHtml: '<strong>Barbados</strong>',
		answerDescriptionHtml: 'Location: Caribbean Sea',
		pathToMedia: 'placeholder',
		category: 'world-cities-landmarks-north-america',
	},
	{
		questionTitleHtml: '<strong>Trinidad</strong>',
		questionDescriptionHtml: 'What is the location or description of this?',
		answerTitleHtml: '<strong>Trinidad</strong>',
		answerDescriptionHtml: 'Location: Caribbean Sea (part of Trinidad and Tobago)',
		pathToMedia: 'placeholder',
		category: 'world-cities-landmarks-north-america',
	},
	{
		questionTitleHtml: '<strong>Sicily</strong>',
		questionDescriptionHtml: 'What is the location or description of this?',
		answerTitleHtml: '<strong>Sicily</strong>',
		answerDescriptionHtml: 'Location: Mediterranean Sea (part of Italy)',
		pathToMedia: 'placeholder',
		category: 'world-cities-landmarks-north-america',
	},
	{
		questionTitleHtml: '<strong>Sumatra</strong>',
		questionDescriptionHtml: 'What is the location or description of this?',
		answerTitleHtml: '<strong>Sumatra</strong>',
		answerDescriptionHtml: 'Location: Indian Ocean (part of Indonesia)',
		pathToMedia: 'placeholder',
		category: 'world-cities-landmarks-north-america',
	},
	{
		questionTitleHtml: '<strong>New Guinea</strong>',
		questionDescriptionHtml: 'What is the location or description of this?',
		answerTitleHtml: '<strong>New Guinea</strong>',
		answerDescriptionHtml: 'Location: Western Pacific Ocean (Papua New Guinea, Indonesia)',
		pathToMedia: 'placeholder',
		category: 'world-cities-landmarks-north-america',
	},
	{
		questionTitleHtml: '<strong>Tasmania</strong>',
		questionDescriptionHtml: 'What is the location or description of this?',
		answerTitleHtml: '<strong>Tasmania</strong>',
		answerDescriptionHtml: 'Location: Southern Ocean (state of Australia)',
		pathToMedia: 'placeholder',
		category: 'world-cities-landmarks-north-america',
	},
	{
		questionTitleHtml: '<strong>Madagascar</strong>',
		questionDescriptionHtml: 'What is the location or description of this?',
		answerTitleHtml: '<strong>Madagascar</strong>',
		answerDescriptionHtml: 'Location: Indian Ocean (country)',
		pathToMedia: 'placeholder',
		category: 'world-cities-landmarks-north-america',
	},
	{
		questionTitleHtml: '<strong>Aleutian Islands</strong>',
		questionDescriptionHtml: 'What is the location or description of this?',
		answerTitleHtml: '<strong>Aleutian Islands</strong>',
		answerDescriptionHtml: 'Location: Northern Pacific Ocean (Alaska, United States)',
		pathToMedia: 'placeholder',
		category: 'world-cities-landmarks-north-america',
	},
	{
		questionTitleHtml: '<strong>Hawaiian Islands</strong>',
		questionDescriptionHtml: 'What is the location or description of this?',
		answerTitleHtml: '<strong>Hawaiian Islands</strong>',
		answerDescriptionHtml: 'Location: Central Pacific Ocean (state of United States)',
		pathToMedia: 'placeholder',
		category: 'world-cities-landmarks-north-america',
	},
	{
		questionTitleHtml: '<strong>Bora Bora</strong>',
		questionDescriptionHtml: 'What is the location or description of this?',
		answerTitleHtml: '<strong>Bora Bora</strong>',
		answerDescriptionHtml: 'Location: South Pacific Ocean (French Polynesia)',
		pathToMedia: 'placeholder',
		category: 'world-cities-landmarks-north-america',
	},
	{
		questionTitleHtml: '<strong>Azores</strong>',
		questionDescriptionHtml: 'What is the location or description of this?',
		answerTitleHtml: '<strong>Azores</strong>',
		answerDescriptionHtml: 'Location: North Atlantic Ocean (autonomous region of Portugal)',
		pathToMedia: 'placeholder',
		category: 'world-cities-landmarks-north-america',
	},
	{
		questionTitleHtml: '<strong>Spice Islands</strong>',
		questionDescriptionHtml: 'What is the location or description of this?',
		answerTitleHtml: '<strong>Spice Islands</strong>',
		answerDescriptionHtml: 'Location: Indonesia (Maluku Islands)',
		pathToMedia: 'placeholder',
		category: 'world-cities-landmarks-north-america',
	},
	{
		questionTitleHtml: '<strong>Koeppen\'s Climate Zones: Polar</strong>',
		questionDescriptionHtml: 'What is the description of this climate zone?',
		answerTitleHtml: '<strong>Koeppen\'s Climate Zones: Polar</strong>',
		answerDescriptionHtml: 'Very cold year-round, found in polar regions',
		pathToMedia: 'placeholder',
		category: 'world-cities-landmarks-north-america',
	},	{
		questionTitleHtml: '<strong>Leaning Tower of Pisa</strong>',
		questionDescriptionHtml: 'What is the location or description of this?',
		answerTitleHtml: '<strong>Leaning Tower of Pisa</strong>',
		answerDescriptionHtml: 'Location: Pisa, Italy',
		pathToMedia: 'placeholder',
		category: 'world-cities-landmarks-north-america',
	},
	{
		questionTitleHtml: '<strong>Stonehenge</strong>',
		questionDescriptionHtml: 'What is the location or description of this?',
		answerTitleHtml: '<strong>Stonehenge</strong>',
		answerDescriptionHtml: 'Location: England, United Kingdom',
		pathToMedia: 'placeholder',
		category: 'world-cities-landmarks-north-america',
	},
	{
		questionTitleHtml: '<strong>Versailles</strong>',
		questionDescriptionHtml: 'What is the location or description of this?',
		answerTitleHtml: '<strong>Versailles</strong>',
		answerDescriptionHtml: 'Location: France',
		pathToMedia: 'placeholder',
		category: 'world-cities-landmarks-north-america',
	},
	{
		questionTitleHtml: '<strong>Great Wall of China</strong>',
		questionDescriptionHtml: 'What is the location or description of this?',
		answerTitleHtml: '<strong>Great Wall of China</strong>',
		answerDescriptionHtml: 'Location: China',
		pathToMedia: 'placeholder',
		category: 'world-cities-landmarks-north-america',
	},
	{
		questionTitleHtml: '<strong>The Pyramids</strong>',
		questionDescriptionHtml: 'What is the location or description of this?',
		answerTitleHtml: '<strong>The Pyramids</strong>',
		answerDescriptionHtml: 'Location: Egypt',
		pathToMedia: 'placeholder',
		category: 'world-cities-landmarks-north-america',
	},
	{
		questionTitleHtml: '<strong>Taj Mahal</strong>',
		questionDescriptionHtml: 'What is the location or description of this?',
		answerTitleHtml: '<strong>Taj Mahal</strong>',
		answerDescriptionHtml: 'Location: India',
		pathToMedia: 'placeholder',
		category: 'world-cities-landmarks-north-america',
	},
	{
		questionTitleHtml: '<strong>The Colosseum</strong>',
		questionDescriptionHtml: 'What is the location or description of this?',
		answerTitleHtml: '<strong>The Colosseum</strong>',
		answerDescriptionHtml: 'Location: Rome, Italy',
		pathToMedia: 'placeholder',
		category: 'world-cities-landmarks-north-america',
	},
	{
		questionTitleHtml: '<strong>Chichen Itza</strong>',
		questionDescriptionHtml: 'What is the location or description of this?',
		answerTitleHtml: '<strong>Chichen Itza</strong>',
		answerDescriptionHtml: 'Location: Mexico',
		pathToMedia: 'placeholder',
		category: 'world-cities-landmarks-north-america',
	},
	{
		questionTitleHtml: '<strong>The Tower of London</strong>',
		questionDescriptionHtml: 'What is the location or description of this?',
		answerTitleHtml: '<strong>The Tower of London</strong>',
		answerDescriptionHtml: 'Location: London, England, United Kingdom',
		pathToMedia: 'placeholder',
		category: 'world-cities-landmarks-north-america',
	},
	{
		questionTitleHtml: '<strong>Big Ben</strong>',
		questionDescriptionHtml: 'What is the location or description of this?',
		answerTitleHtml: '<strong>Big Ben</strong>',
		answerDescriptionHtml: 'Location: London, England, United Kingdom',
		pathToMedia: 'placeholder',
		category: 'world-cities-landmarks-north-america',
	},
	{
		questionTitleHtml: '<strong>Dome of the Rock</strong>',
		questionDescriptionHtml: 'What is the location or description of this?',
		answerTitleHtml: '<strong>Dome of the Rock</strong>',
		answerDescriptionHtml: 'Location: Jerusalem, Israel',
		pathToMedia: 'placeholder',
		category: 'world-cities-landmarks-north-america',
	},
	{
		questionTitleHtml: '<strong>Eiffel Tower</strong>',
		questionDescriptionHtml: 'What is the location or description of this?',
		answerTitleHtml: '<strong>Eiffel Tower</strong>',
		answerDescriptionHtml: 'Location: Paris, France',
		pathToMedia: 'placeholder',
		category: 'world-cities-landmarks-north-america',
	},
	{
		questionTitleHtml: '<strong>Forbidden City</strong>',
		questionDescriptionHtml: 'What is the location or description of this?',
		answerTitleHtml: '<strong>Forbidden City</strong>',
		answerDescriptionHtml: 'Location: Beijing, China',
		pathToMedia: 'placeholder',
		category: 'world-cities-landmarks-north-america',
	},
	{
		questionTitleHtml: '<strong>Red Square</strong>',
		questionDescriptionHtml: 'What is the location or description of this?',
		answerTitleHtml: '<strong>Red Square</strong>',
		answerDescriptionHtml: 'Location: Moscow, Russia',
		pathToMedia: 'placeholder',
		category: 'world-cities-landmarks-north-america',
	},
	{
		questionTitleHtml: '<strong>Sydney Opera House</strong>',
		questionDescriptionHtml: 'What is the location or description of this?',
		answerTitleHtml: '<strong>Sydney Opera House</strong>',
		answerDescriptionHtml: 'Location: Sydney, Australia',
		pathToMedia: 'placeholder',
		category: 'world-cities-landmarks-north-america',
	},
	{
		questionTitleHtml: '<strong>Vatican</strong>',
		questionDescriptionHtml: 'What is the location or description of this?',
		answerTitleHtml: '<strong>Vatican</strong>',
		answerDescriptionHtml: 'Location: Vatican City (within Rome, Italy)',
		pathToMedia: 'placeholder',
		category: 'world-cities-landmarks-north-america',
	},
	{
		questionTitleHtml: '<strong>Gibraltar Rock</strong>',
		questionDescriptionHtml: 'What is the location or description of this?',
		answerTitleHtml: '<strong>Gibraltar Rock</strong>',
		answerDescriptionHtml: 'Location: Gibraltar (British territory)',
		pathToMedia: 'placeholder',
		category: 'world-cities-landmarks-north-america',
	},
	{
		questionTitleHtml: '<strong>The Great Sphinx</strong>',
		questionDescriptionHtml: 'What is the location or description of this?',
		answerTitleHtml: '<strong>The Great Sphinx</strong>',
		answerDescriptionHtml: 'Location: Giza, Egypt',
		pathToMedia: 'placeholder',
		category: 'world-cities-landmarks-north-america',
	},
	{
		questionTitleHtml: '<strong>The Buried City</strong>',
		questionDescriptionHtml: 'What is the location or description of this?',
		answerTitleHtml: '<strong>The Buried City</strong>',
		answerDescriptionHtml: 'Location: Pakistan (ancient archaeological site)',
		pathToMedia: 'placeholder',
		category: 'world-cities-landmarks-north-america',
	},
	{
		questionTitleHtml: '<strong>Khyber Pass</strong>',
		questionDescriptionHtml: 'What is the location or description of this?',
		answerTitleHtml: '<strong>Khyber Pass</strong>',
		answerDescriptionHtml: 'Location: Afghanistan/Pakistan border',
		pathToMedia: 'placeholder',
		category: 'world-cities-landmarks-north-america',
	},
	{
		questionTitleHtml: '<strong>Polders</strong>',
		questionDescriptionHtml: 'What is the location or description of this?',
		answerTitleHtml: '<strong>Polders</strong>',
		answerDescriptionHtml: 'Location: Netherlands (low-lying land reclaimed from sea)',
		pathToMedia: 'placeholder',
		category: 'world-cities-landmarks-north-america',
	},
	{
		questionTitleHtml: '<strong>Hispaniola</strong>',
		questionDescriptionHtml: 'What is the location or description of this?',
		answerTitleHtml: '<strong>Hispaniola</strong>',
		answerDescriptionHtml: 'Location: Caribbean (island containing Haiti and Dominican Republic)',
		pathToMedia: 'placeholder',
		category: 'world-cities-landmarks-north-america',
	},
	{
		questionTitleHtml: '<strong>Low Countries</strong>',
		questionDescriptionHtml: 'What is the location or description of this?',
		answerTitleHtml: '<strong>Low Countries</strong>',
		answerDescriptionHtml: 'Location: Belgium, Netherlands, Luxembourg',
		pathToMedia: 'placeholder',
		category: 'world-cities-landmarks-north-america',
	},
	{
		questionTitleHtml: '<strong>Scandinavia</strong>',
		questionDescriptionHtml: 'What is the location or description of this?',
		answerTitleHtml: '<strong>Scandinavia</strong>',
		answerDescriptionHtml: 'Location: Northern Europe (Norway, Sweden, Denmark)',
		pathToMedia: 'placeholder',
		category: 'world-cities-landmarks-north-america',
	},
	{
		questionTitleHtml: '<strong>Ulster</strong>',
		questionDescriptionHtml: 'What is the location or description of this?',
		answerTitleHtml: '<strong>Ulster</strong>',
		answerDescriptionHtml: 'Location: Northern Ireland (province)',
		pathToMedia: 'placeholder',
		category: 'world-cities-landmarks-north-america',
	},
	{
		questionTitleHtml: '<strong>Bavaria</strong>',
		questionDescriptionHtml: 'What is the location or description of this?',
		answerTitleHtml: '<strong>Bavaria</strong>',
		answerDescriptionHtml: 'Location: Germany (state in southern Germany)',
		pathToMedia: 'placeholder',
		category: 'world-cities-landmarks-north-america',
	},
	{
		questionTitleHtml: '<strong>The Eternal City</strong>',
		questionDescriptionHtml: 'What is the location or description of this?',
		answerTitleHtml: '<strong>The Eternal City</strong>',
		answerDescriptionHtml: 'Location: Rome, Italy',
		pathToMedia: 'placeholder',
		category: 'world-cities-landmarks-north-america',
	},
	{
		questionTitleHtml: '<strong>Middle East</strong>',
		questionDescriptionHtml: 'What is the location or description of this?',
		answerTitleHtml: '<strong>Middle East</strong>',
		answerDescriptionHtml: 'Location: Western Asia and parts of North Africa',
		pathToMedia: 'placeholder',
		category: 'world-cities-landmarks-north-america',
	},
	{
		questionTitleHtml: '<strong>Fertile Crescent</strong>',
		questionDescriptionHtml: 'What is the location or description of this?',
		answerTitleHtml: '<strong>Fertile Crescent</strong>',
		answerDescriptionHtml: 'Location: Middle East (region from Egypt through Mesopotamia)',
		pathToMedia: 'placeholder',
		category: 'world-cities-landmarks-north-america',
	},
]
