import type { FlashCard } from '@/types'

export const world_country_capitals_north_america: FlashCard[] = [
	{
		questionTitleHtml: '<strong>Belize</strong>',
		questionDescriptionHtml: 'What is the capital of this country?',
		answerTitleHtml: '<strong>Belmopan</strong>',
		answerDescriptionHtml: 'Capital of <strong>Belize</strong>',
		pathToMedia: null,
		category: 'world-country-capitals-north-america',
	},
	{
		questionTitleHtml: '<strong>Canada</strong>',
		questionDescriptionHtml: 'What is the capital of this country?',
		answerTitleHtml: '<strong>Ottawa</strong>',
		answerDescriptionHtml: 'Capital of <strong>Canada</strong>',
		pathToMedia: null,
		category: 'world-country-capitals-north-america',
	},
	{
		questionTitleHtml: '<strong>Costa Rica</strong>',
		questionDescriptionHtml: 'What is the capital of this country?',
		answerTitleHtml: '<strong>San José</strong>',
		answerDescriptionHtml: 'Capital of <strong>Costa Rica</strong>',
		pathToMedia: null,
		category: 'world-country-capitals-north-america',
	},
	{
		questionTitleHtml: '<strong>Cuba</strong>',
		questionDescriptionHtml: 'What is the capital of this country?',
		answerTitleHtml: '<strong>Havana</strong>',
		answerDescriptionHtml: 'Capital of <strong>Cuba</strong>',
		pathToMedia: null,
		category: 'world-country-capitals-north-america',
	},
	{
		questionTitleHtml: '<strong>Dominican Republic</strong>',
		questionDescriptionHtml: 'What is the capital of this country?',
		answerTitleHtml: '<strong>Santo Domingo</strong>',
		answerDescriptionHtml: 'Capital of <strong>Dominican Republic</strong>',
		pathToMedia: null,
		category: 'world-country-capitals-north-america',
	},
	{
		questionTitleHtml: '<strong>El Salvador</strong>',
		questionDescriptionHtml: 'What is the capital of this country?',
		answerTitleHtml: '<strong>San Salvador</strong>',
		answerDescriptionHtml: 'Capital of <strong>El Salvador</strong>',
		pathToMedia: null,
		category: 'world-country-capitals-north-america',
	},
	{
		questionTitleHtml: '<strong>Grenada</strong>',
		questionDescriptionHtml: 'What is the capital of this country?',
		answerTitleHtml: '<strong>St. George\'s</strong>',
		answerDescriptionHtml: 'Capital of <strong>Grenada</strong>',
		pathToMedia: null,
		category: 'world-country-capitals-north-america',
	},
	{
		questionTitleHtml: '<strong>Guatemala</strong>',
		questionDescriptionHtml: 'What is the capital of this country?',
		answerTitleHtml: '<strong>Guatemala City</strong>',
		answerDescriptionHtml: 'Capital of <strong>Guatemala</strong>',
		pathToMedia: null,
		category: 'world-country-capitals-north-america',
	},
	{
		questionTitleHtml: '<strong>Haiti</strong>',
		questionDescriptionHtml: 'What is the capital of this country?',
		answerTitleHtml: '<strong>Port-au-Prince</strong>',
		answerDescriptionHtml: 'Capital of <strong>Haiti</strong>',
		pathToMedia: null,
		category: 'world-country-capitals-north-america',
	},
	{
		questionTitleHtml: '<strong>Honduras</strong>',
		questionDescriptionHtml: 'What is the capital of this country?',
		answerTitleHtml: '<strong>Tegucigalpa</strong>',
		answerDescriptionHtml: 'Capital of <strong>Honduras</strong>',
		pathToMedia: null,
		category: 'world-country-capitals-north-america',
	},
	{
		questionTitleHtml: '<strong>Jamaica</strong>',
		questionDescriptionHtml: 'What is the capital of this country?',
		answerTitleHtml: '<strong>Kingston</strong>',
		answerDescriptionHtml: 'Capital of <strong>Jamaica</strong>',
		pathToMedia: null,
		category: 'world-country-capitals-north-america',
	},
	{
		questionTitleHtml: '<strong>Mexico</strong>',
		questionDescriptionHtml: 'What is the capital of this country?',
		answerTitleHtml: '<strong>Mexico City</strong>',
		answerDescriptionHtml: 'Capital of <strong>Mexico</strong>',
		pathToMedia: null,
		category: 'world-country-capitals-north-america',
	},
	{
		questionTitleHtml: '<strong>Nicaragua</strong>',
		questionDescriptionHtml: 'What is the capital of this country?',
		answerTitleHtml: '<strong>Managua</strong>',
		answerDescriptionHtml: 'Capital of <strong>Nicaragua</strong>',
		pathToMedia: null,
		category: 'world-country-capitals-north-america',
	},
	{
		questionTitleHtml: '<strong>Panama</strong>',
		questionDescriptionHtml: 'What is the capital of this country?',
		answerTitleHtml: '<strong>Panama City</strong>',
		answerDescriptionHtml: 'Capital of <strong>Panama</strong>',
		pathToMedia: null,
		category: 'world-country-capitals-north-america',
	},
	{
		questionTitleHtml: '<strong>Trinidad and Tobago</strong>',
		questionDescriptionHtml: 'What is the capital of this country?',
		answerTitleHtml: '<strong>Port of Spain</strong>',
		answerDescriptionHtml: 'Capital of <strong>Trinidad and Tobago</strong>',
		pathToMedia: null,
		category: 'world-country-capitals-north-america',
	},
	{
		questionTitleHtml: '<strong>United States</strong>',
		questionDescriptionHtml: 'What is the capital of this country?',
		answerTitleHtml: '<strong>Washington, D.C.</strong>',
		answerDescriptionHtml: 'Capital of <strong>United States</strong>',
		pathToMedia: null,
		category: 'world-country-capitals-north-america',
	},
]
