import type { FlashCard } from '@/types'

export const world_country_locations_languages_asia: FlashCard[] = [
	{
		questionTitleHtml: '<strong>What\'s this country in Asia?</strong>',
		questionDescriptionHtml: 'And its principal language',
		answerTitleHtml: '<strong>Afghanistan</strong>',
		answerDescriptionHtml: 'Location: Central/South Asia<br>Principal Language: Pashto',
		pathToMedia: 'images/world-country-locations/asia/afghanistan.png',
		category: 'world-country-locations-languages-asia',
	},
	{
		questionTitleHtml: '<strong>What\'s this country in Asia?</strong>',
		questionDescriptionHtml: 'And its principal language',
		answerTitleHtml: '<strong>Bangladesh</strong>',
		answerDescriptionHtml: 'Location: South Asia<br>Principal Language: Bengali',
		pathToMedia: 'images/world-country-locations/asia/bangladesh.png',
		category: 'world-country-locations-languages-asia',
	},
	{
		questionTitleHtml: '<strong>What\'s this country in Asia?</strong>',
		questionDescriptionHtml: 'And its principal language',
		answerTitleHtml: '<strong>Burma (Myanmar)</strong>',
		answerDescriptionHtml: 'Location: Southeast Asia<br>Principal Language: Burmese',
		pathToMedia: 'images/world-country-locations/asia/myanmar.png',
		category: 'world-country-locations-languages-asia',
	},
	{
		questionTitleHtml: '<strong>What\'s this country in Asia?</strong>',
		questionDescriptionHtml: 'And its principal language',
		answerTitleHtml: '<strong>Cambodia</strong>',
		answerDescriptionHtml: 'Location: Southeast Asia<br>Principal Language: Khmer',
		pathToMedia: 'images/world-country-locations/asia/cambodia.png',
		category: 'world-country-locations-languages-asia',
	},
	{
		questionTitleHtml: '<strong>What\'s this country in Asia?</strong>',
		questionDescriptionHtml: 'And its principal language',
		answerTitleHtml: '<strong>China</strong>',
		answerDescriptionHtml: 'Location: East Asia<br>Principal Language: Mandarin Chinese',
		pathToMedia: 'images/world-country-locations/asia/china.png',
		category: 'world-country-locations-languages-asia',
	},
	{
		questionTitleHtml: '<strong>What\'s this country in Asia?</strong>',
		questionDescriptionHtml: 'And its principal language',
		answerTitleHtml: '<strong>India</strong>',
		answerDescriptionHtml: 'Location: South Asia<br>Principal Language: Hindi',
		pathToMedia: 'images/world-country-locations/asia/india.png',
		category: 'world-country-locations-languages-asia',
	},
	{
		questionTitleHtml: '<strong>What\'s this country in Asia?</strong>',
		questionDescriptionHtml: 'And its principal language',
		answerTitleHtml: '<strong>Indonesia</strong>',
		answerDescriptionHtml: 'Location: Southeast Asia<br>Principal Language: Indonesian',
		pathToMedia: 'images/world-country-locations/asia/indonesia.png',
		category: 'world-country-locations-languages-asia',
	},
	{
		questionTitleHtml: '<strong>What\'s this country in Asia?</strong>',
		questionDescriptionHtml: 'And its principal language',
		answerTitleHtml: '<strong>Iran</strong>',
		answerDescriptionHtml: 'Location: Western Asia (Middle East)<br>Principal Language: Persian (Farsi)',
		pathToMedia: 'images/world-country-locations/asia/iran.png',
		category: 'world-country-locations-languages-asia',
	},
	{
		questionTitleHtml: '<strong>What\'s this country in Asia?</strong>',
		questionDescriptionHtml: 'And its principal language',
		answerTitleHtml: '<strong>Iraq</strong>',
		answerDescriptionHtml: 'Location: Western Asia (Middle East)<br>Principal Language: Arabic',
		pathToMedia: 'images/world-country-locations/asia/iraq.png',
		category: 'world-country-locations-languages-asia',
	},
	{
		questionTitleHtml: '<strong>What\'s this country in Asia?</strong>',
		questionDescriptionHtml: 'And its principal language',
		answerTitleHtml: '<strong>Israel</strong>',
		answerDescriptionHtml: 'Location: Western Asia (Middle East)<br>Principal Language: Hebrew',
		pathToMedia: 'images/world-country-locations/asia/israel.png',
		category: 'world-country-locations-languages-asia',
	},
	{
		questionTitleHtml: '<strong>What\'s this country in Asia?</strong>',
		questionDescriptionHtml: 'And its principal language',
		answerTitleHtml: '<strong>Japan</strong>',
		answerDescriptionHtml: 'Location: East Asia<br>Principal Language: Japanese',
		pathToMedia: 'images/world-country-locations/asia/japan.png',
		category: 'world-country-locations-languages-asia',
	},
	{
		questionTitleHtml: '<strong>What\'s this country in Asia?</strong>',
		questionDescriptionHtml: 'And its principal language',
		answerTitleHtml: '<strong>Jordan</strong>',
		answerDescriptionHtml: 'Location: Western Asia (Middle East)<br>Principal Language: Arabic',
		pathToMedia: 'images/world-country-locations/asia/jordan.png',
		category: 'world-country-locations-languages-asia',
	},
	{
		questionTitleHtml: '<strong>What\'s this country in Asia?</strong>',
		questionDescriptionHtml: 'And its principal language',
		answerTitleHtml: '<strong>Kuwait</strong>',
		answerDescriptionHtml: 'Location: Western Asia (Middle East)<br>Principal Language: Arabic',
		pathToMedia: 'images/world-country-locations/asia/kuwait.png',
		category: 'world-country-locations-languages-asia',
	},
	{
		questionTitleHtml: '<strong>What\'s this country in Asia?</strong>',
		questionDescriptionHtml: 'And its principal language',
		answerTitleHtml: '<strong>Kyrgyzstan</strong>',
		answerDescriptionHtml: 'Location: Central Asia<br>Principal Language: Kyrgyz',
		pathToMedia: 'images/world-country-locations/asia/kyrgyzstan.png',
		category: 'world-country-locations-languages-asia',
	},
	{
		questionTitleHtml: '<strong>What\'s this country in Asia?</strong>',
		questionDescriptionHtml: 'And its principal language',
		answerTitleHtml: '<strong>Laos</strong>',
		answerDescriptionHtml: 'Location: Southeast Asia<br>Principal Language: Lao',
		pathToMedia: 'images/world-country-locations/asia/laos.png',
		category: 'world-country-locations-languages-asia',
	},
	{
		questionTitleHtml: '<strong>What\'s this country in Asia?</strong>',
		questionDescriptionHtml: 'And its principal language',
		answerTitleHtml: '<strong>Lebanon</strong>',
		answerDescriptionHtml: 'Location: Western Asia (Middle East)<br>Principal Language: Arabic',
		pathToMedia: 'images/world-country-locations/asia/lebanon.png',
		category: 'world-country-locations-languages-asia',
	},
	{
		questionTitleHtml: '<strong>What\'s this country in Asia?</strong>',
		questionDescriptionHtml: 'And its principal language',
		answerTitleHtml: '<strong>Malaysia</strong>',
		answerDescriptionHtml: 'Location: Southeast Asia<br>Principal Language: Malay',
		pathToMedia: 'images/world-country-locations/asia/malaysia.png',
		category: 'world-country-locations-languages-asia',
	},
	{
		questionTitleHtml: '<strong>What\'s this country in Asia?</strong>',
		questionDescriptionHtml: 'And its principal language',
		answerTitleHtml: '<strong>Mongolia</strong>',
		answerDescriptionHtml: 'Location: East Asia<br>Principal Language: Mongolian',
		pathToMedia: 'images/world-country-locations/asia/mongolia.png',
		category: 'world-country-locations-languages-asia',
	},
	{
		questionTitleHtml: '<strong>What\'s this country in Asia?</strong>',
		questionDescriptionHtml: 'And its principal language',
		answerTitleHtml: '<strong>Myanmar (Burma)</strong>',
		answerDescriptionHtml: 'Location: Southeast Asia<br>Principal Language: Burmese',
		pathToMedia: 'images/world-country-locations/asia/myanmar.png',
		category: 'world-country-locations-languages-asia',
	},
	{
		questionTitleHtml: '<strong>What\'s this country in Asia?</strong>',
		questionDescriptionHtml: 'And its principal language',
		answerTitleHtml: '<strong>Nepal</strong>',
		answerDescriptionHtml: 'Location: South Asia<br>Principal Language: Nepali',
		pathToMedia: 'images/world-country-locations/asia/nepal.png',
		category: 'world-country-locations-languages-asia',
	},
	{
		questionTitleHtml: '<strong>What\'s this country in Asia?</strong>',
		questionDescriptionHtml: 'And its principal language',
		answerTitleHtml: '<strong>North Korea</strong>',
		answerDescriptionHtml: 'Location: East Asia<br>Principal Language: Korean',
		pathToMedia: 'images/world-country-locations/asia/north-korea.png',
		category: 'world-country-locations-languages-asia',
	},
	{
		questionTitleHtml: '<strong>What\'s this country in Asia?</strong>',
		questionDescriptionHtml: 'And its principal language',
		answerTitleHtml: '<strong>Oman</strong>',
		answerDescriptionHtml: 'Location: Western Asia (Middle East)<br>Principal Language: Arabic',
		pathToMedia: 'images/world-country-locations/asia/oman.png',
		category: 'world-country-locations-languages-asia',
	},
	{
		questionTitleHtml: '<strong>What\'s this country in Asia?</strong>',
		questionDescriptionHtml: 'And its principal language',
		answerTitleHtml: '<strong>Pakistan</strong>',
		answerDescriptionHtml: 'Location: South Asia<br>Principal Language: Urdu',
		pathToMedia: 'images/world-country-locations/asia/pakistan.png',
		category: 'world-country-locations-languages-asia',
	},
	{
		questionTitleHtml: '<strong>What\'s this country in Asia?</strong>',
		questionDescriptionHtml: 'And its principal language',
		answerTitleHtml: '<strong>Philippines</strong>',
		answerDescriptionHtml: 'Location: Southeast Asia<br>Principal Language: Filipino',
		pathToMedia: 'images/world-country-locations/asia/philippines.png',
		category: 'world-country-locations-languages-asia',
	},
	{
		questionTitleHtml: '<strong>What\'s this country in Asia?</strong>',
		questionDescriptionHtml: 'And its principal language',
		answerTitleHtml: '<strong>Qatar</strong>',
		answerDescriptionHtml: 'Location: Western Asia (Middle East)<br>Principal Language: Arabic',
		pathToMedia: 'images/world-country-locations/asia/qatar.png',
		category: 'world-country-locations-languages-asia',
	},
	{
		questionTitleHtml: '<strong>What\'s this country in Asia?</strong>',
		questionDescriptionHtml: 'And its principal language',
		answerTitleHtml: '<strong>Saudi Arabia</strong>',
		answerDescriptionHtml: 'Location: Western Asia (Middle East)<br>Principal Language: Arabic',
		pathToMedia: 'images/world-country-locations/asia/saudi-arabia.png',
		category: 'world-country-locations-languages-asia',
	},
	{
		questionTitleHtml: '<strong>What\'s this country in Asia?</strong>',
		questionDescriptionHtml: 'And its principal language',
		answerTitleHtml: '<strong>Singapore</strong>',
		answerDescriptionHtml: 'Location: Southeast Asia<br>Principal Language: English',
		pathToMedia: 'images/world-country-locations/asia/singapore.png',
		category: 'world-country-locations-languages-asia',
	},
	{
		questionTitleHtml: '<strong>What\'s this country in Asia?</strong>',
		questionDescriptionHtml: 'And its principal language',
		answerTitleHtml: '<strong>South Korea</strong>',
		answerDescriptionHtml: 'Location: East Asia<br>Principal Language: Korean',
		pathToMedia: 'images/world-country-locations/asia/south-korea.png',
		category: 'world-country-locations-languages-asia',
	},
	{
		questionTitleHtml: '<strong>What\'s this country in Asia?</strong>',
		questionDescriptionHtml: 'And its principal language',
		answerTitleHtml: '<strong>Sri Lanka</strong>',
		answerDescriptionHtml: 'Location: South Asia<br>Principal Language: Sinhala',
		pathToMedia: 'images/world-country-locations/asia/sri-lanka.png',
		category: 'world-country-locations-languages-asia',
	},
	{
		questionTitleHtml: '<strong>What\'s this country in Asia?</strong>',
		questionDescriptionHtml: 'And its principal language',
		answerTitleHtml: '<strong>Syria</strong>',
		answerDescriptionHtml: 'Location: Western Asia (Middle East)<br>Principal Language: Arabic',
		pathToMedia: 'images/world-country-locations/asia/syria.png',
		category: 'world-country-locations-languages-asia',
	},
	{
		questionTitleHtml: '<strong>What\'s this country in Asia?</strong>',
		questionDescriptionHtml: 'And its principal language',
		answerTitleHtml: '<strong>Tajikistan</strong>',
		answerDescriptionHtml: 'Location: Central Asia<br>Principal Language: Tajik',
		pathToMedia: 'images/world-country-locations/asia/tajikistan.png',
		category: 'world-country-locations-languages-asia',
	},
	{
		questionTitleHtml: '<strong>What\'s this country in Asia?</strong>',
		questionDescriptionHtml: 'And its principal language',
		answerTitleHtml: '<strong>Thailand</strong>',
		answerDescriptionHtml: 'Location: Southeast Asia<br>Principal Language: Thai',
		pathToMedia: 'images/world-country-locations/asia/thailand.png',
		category: 'world-country-locations-languages-asia',
	},
	{
		questionTitleHtml: '<strong>What\'s this country in Asia?</strong>',
		questionDescriptionHtml: 'And its principal language',
		answerTitleHtml: '<strong>Turkmenistan</strong>',
		answerDescriptionHtml: 'Location: Central Asia<br>Principal Language: Turkmen',
		pathToMedia: 'images/world-country-locations/asia/turkmenistan.png',
		category: 'world-country-locations-languages-asia',
	},
	{
		questionTitleHtml: '<strong>What\'s this country in Asia?</strong>',
		questionDescriptionHtml: 'And its principal language',
		answerTitleHtml: '<strong>United Arab Emirates</strong>',
		answerDescriptionHtml: 'Location: Western Asia (Middle East)<br>Principal Language: Arabic',
		pathToMedia: 'images/world-country-locations/asia/united-arab-emirates.png',
		category: 'world-country-locations-languages-asia',
	},
	{
		questionTitleHtml: '<strong>What\'s this country in Asia?</strong>',
		questionDescriptionHtml: 'And its principal language',
		answerTitleHtml: '<strong>Uzbekistan</strong>',
		answerDescriptionHtml: 'Location: Central Asia<br>Principal Language: Uzbek',
		pathToMedia: 'images/world-country-locations/asia/uzbekistan.png',
		category: 'world-country-locations-languages-asia',
	},
	{
		questionTitleHtml: '<strong>What\'s this country in Asia?</strong>',
		questionDescriptionHtml: 'And its principal language',
		answerTitleHtml: '<strong>Vietnam</strong>',
		answerDescriptionHtml: 'Location: Southeast Asia<br>Principal Language: Vietnamese',
		pathToMedia: 'images/world-country-locations/asia/vietnam.png',
		category: 'world-country-locations-languages-asia',
	},
	{
		questionTitleHtml: '<strong>What\'s this country in Asia?</strong>',
		questionDescriptionHtml: 'And its principal language',
		answerTitleHtml: '<strong>Yemen</strong>',
		answerDescriptionHtml: 'Location: Western Asia (Middle East)<br>Principal Language: Arabic',
		pathToMedia: 'images/world-country-locations/asia/yemen.png',
		category: 'world-country-locations-languages-asia',
	},
]
