import type { FlashCard } from '@/types'

export const world_country_capitals_europe: FlashCard[] = [
	{
		questionTitleHtml: '<strong>Albania</strong>',
		questionDescriptionHtml: 'What is the capital of this country?',
		answerTitleHtml: '<strong>Tirana</strong>',
		answerDescriptionHtml: 'Capital of <strong>Albania</strong>',
		pathToMedia: null,
		category: 'world-country-capitals-europe',
	},
	{
		questionTitleHtml: '<strong>Armenia</strong>',
		questionDescriptionHtml: 'What is the capital of this country?',
		answerTitleHtml: '<strong>Yerevan</strong>',
		answerDescriptionHtml: 'Capital of <strong>Armenia</strong>',
		pathToMedia: null,
		category: 'world-country-capitals-europe',
	},
	{
		questionTitleHtml: '<strong>Austria</strong>',
		questionDescriptionHtml: 'What is the capital of this country?',
		answerTitleHtml: '<strong>Vienna</strong>',
		answerDescriptionHtml: 'Capital of <strong>Austria</strong>',
		pathToMedia: null,
		category: 'world-country-capitals-europe',
	},
	{
		questionTitleHtml: '<strong>Belgium</strong>',
		questionDescriptionHtml: 'What is the capital of this country?',
		answerTitleHtml: '<strong>Brussels</strong>',
		answerDescriptionHtml: 'Capital of <strong>Belgium</strong>',
		pathToMedia: null,
		category: 'world-country-capitals-europe',
	},
	{
		questionTitleHtml: '<strong>Bosnia and Herzegovina</strong>',
		questionDescriptionHtml: 'What is the capital of this country?',
		answerTitleHtml: '<strong>Sarajevo</strong>',
		answerDescriptionHtml: 'Capital of <strong>Bosnia and Herzegovina</strong>',
		pathToMedia: null,
		category: 'world-country-capitals-europe',
	},
	{
		questionTitleHtml: '<strong>Bulgaria</strong>',
		questionDescriptionHtml: 'What is the capital of this country?',
		answerTitleHtml: '<strong>Sofia</strong>',
		answerDescriptionHtml: 'Capital of <strong>Bulgaria</strong>',
		pathToMedia: null,
		category: 'world-country-capitals-europe',
	},
	{
		questionTitleHtml: '<strong>Croatia</strong>',
		questionDescriptionHtml: 'What is the capital of this country?',
		answerTitleHtml: '<strong>Zagreb</strong>',
		answerDescriptionHtml: 'Capital of <strong>Croatia</strong>',
		pathToMedia: null,
		category: 'world-country-capitals-europe',
	},
	{
		questionTitleHtml: '<strong>Czech Republic</strong>',
		questionDescriptionHtml: 'What is the capital of this country?',
		answerTitleHtml: '<strong>Prague</strong>',
		answerDescriptionHtml: 'Capital of <strong>Czech Republic</strong>',
		pathToMedia: null,
		category: 'world-country-capitals-europe',
	},
	{
		questionTitleHtml: '<strong>Denmark</strong>',
		questionDescriptionHtml: 'What is the capital of this country?',
		answerTitleHtml: '<strong>Copenhagen</strong>',
		answerDescriptionHtml: 'Capital of <strong>Denmark</strong>',
		pathToMedia: null,
		category: 'world-country-capitals-europe',
	},
	{
		questionTitleHtml: '<strong>Estonia</strong>',
		questionDescriptionHtml: 'What is the capital of this country?',
		answerTitleHtml: '<strong>Tallinn</strong>',
		answerDescriptionHtml: 'Capital of <strong>Estonia</strong>',
		pathToMedia: null,
		category: 'world-country-capitals-europe',
	},
	{
		questionTitleHtml: '<strong>Finland</strong>',
		questionDescriptionHtml: 'What is the capital of this country?',
		answerTitleHtml: '<strong>Helsinki</strong>',
		answerDescriptionHtml: 'Capital of <strong>Finland</strong>',
		pathToMedia: null,
		category: 'world-country-capitals-europe',
	},
	{
		questionTitleHtml: '<strong>France</strong>',
		questionDescriptionHtml: 'What is the capital of this country?',
		answerTitleHtml: '<strong>Paris</strong>',
		answerDescriptionHtml: 'Capital of <strong>France</strong>',
		pathToMedia: null,
		category: 'world-country-capitals-europe',
	},
	{
		questionTitleHtml: '<strong>Georgia</strong>',
		questionDescriptionHtml: 'What is the capital of this country?',
		answerTitleHtml: '<strong>Tbilisi</strong>',
		answerDescriptionHtml: 'Capital of <strong>Georgia</strong>',
		pathToMedia: null,
		category: 'world-country-capitals-europe',
	},
	{
		questionTitleHtml: '<strong>Germany</strong>',
		questionDescriptionHtml: 'What is the capital of this country?',
		answerTitleHtml: '<strong>Berlin</strong>',
		answerDescriptionHtml: 'Capital of <strong>Germany</strong>',
		pathToMedia: null,
		category: 'world-country-capitals-europe',
	},
	{
		questionTitleHtml: '<strong>Greece</strong>',
		questionDescriptionHtml: 'What is the capital of this country?',
		answerTitleHtml: '<strong>Athens</strong>',
		answerDescriptionHtml: 'Capital of <strong>Greece</strong>',
		pathToMedia: null,
		category: 'world-country-capitals-europe',
	},
	{
		questionTitleHtml: '<strong>Hungary</strong>',
		questionDescriptionHtml: 'What is the capital of this country?',
		answerTitleHtml: '<strong>Budapest</strong>',
		answerDescriptionHtml: 'Capital of <strong>Hungary</strong>',
		pathToMedia: null,
		category: 'world-country-capitals-europe',
	},
	{
		questionTitleHtml: '<strong>Iceland</strong>',
		questionDescriptionHtml: 'What is the capital of this country?',
		answerTitleHtml: '<strong>Reykjavík</strong>',
		answerDescriptionHtml: 'Capital of <strong>Iceland</strong>',
		pathToMedia: null,
		category: 'world-country-capitals-europe',
	},
	{
		questionTitleHtml: '<strong>Ireland</strong>',
		questionDescriptionHtml: 'What is the capital of this country?',
		answerTitleHtml: '<strong>Dublin</strong>',
		answerDescriptionHtml: 'Capital of <strong>Ireland</strong>',
		pathToMedia: null,
		category: 'world-country-capitals-europe',
	},
	{
		questionTitleHtml: '<strong>Italy</strong>',
		questionDescriptionHtml: 'What is the capital of this country?',
		answerTitleHtml: '<strong>Rome</strong>',
		answerDescriptionHtml: 'Capital of <strong>Italy</strong>',
		pathToMedia: null,
		category: 'world-country-capitals-europe',
	},
	{
		questionTitleHtml: '<strong>Latvia</strong>',
		questionDescriptionHtml: 'What is the capital of this country?',
		answerTitleHtml: '<strong>Riga</strong>',
		answerDescriptionHtml: 'Capital of <strong>Latvia</strong>',
		pathToMedia: null,
		category: 'world-country-capitals-europe',
	},
	{
		questionTitleHtml: '<strong>Liechtenstein</strong>',
		questionDescriptionHtml: 'What is the capital of this country?',
		answerTitleHtml: '<strong>Vaduz</strong>',
		answerDescriptionHtml: 'Capital of <strong>Liechtenstein</strong>',
		pathToMedia: null,
		category: 'world-country-capitals-europe',
	},
	{
		questionTitleHtml: '<strong>Lithuania</strong>',
		questionDescriptionHtml: 'What is the capital of this country?',
		answerTitleHtml: '<strong>Vilnius</strong>',
		answerDescriptionHtml: 'Capital of <strong>Lithuania</strong>',
		pathToMedia: null,
		category: 'world-country-capitals-europe',
	},
	{
		questionTitleHtml: '<strong>Luxembourg</strong>',
		questionDescriptionHtml: 'What is the capital of this country?',
		answerTitleHtml: '<strong>Luxembourg</strong>',
		answerDescriptionHtml: 'Capital of <strong>Luxembourg</strong>',
		pathToMedia: null,
		category: 'world-country-capitals-europe',
	},
	{
		questionTitleHtml: '<strong>Macedonia (North Macedonia)</strong>',
		questionDescriptionHtml: 'What is the capital of this country?',
		answerTitleHtml: '<strong>Skopje</strong>',
		answerDescriptionHtml: 'Capital of <strong>Macedonia (North Macedonia)</strong>',
		pathToMedia: null,
		category: 'world-country-capitals-europe',
	},
	{
		questionTitleHtml: '<strong>Malta</strong>',
		questionDescriptionHtml: 'What is the capital of this country?',
		answerTitleHtml: '<strong>Valletta</strong>',
		answerDescriptionHtml: 'Capital of <strong>Malta</strong>',
		pathToMedia: null,
		category: 'world-country-capitals-europe',
	},
	{
		questionTitleHtml: '<strong>Moldova</strong>',
		questionDescriptionHtml: 'What is the capital of this country?',
		answerTitleHtml: '<strong>Chișinău</strong>',
		answerDescriptionHtml: 'Capital of <strong>Moldova</strong>',
		pathToMedia: null,
		category: 'world-country-capitals-europe',
	},
	{
		questionTitleHtml: '<strong>Monaco</strong>',
		questionDescriptionHtml: 'What is the capital of this country?',
		answerTitleHtml: '<strong>Monaco</strong>',
		answerDescriptionHtml: 'Capital of <strong>Monaco</strong>',
		pathToMedia: null,
		category: 'world-country-capitals-europe',
	},
	{
		questionTitleHtml: '<strong>Montenegro</strong>',
		questionDescriptionHtml: 'What is the capital of this country?',
		answerTitleHtml: '<strong>Podgorica</strong>',
		answerDescriptionHtml: 'Capital of <strong>Montenegro</strong>',
		pathToMedia: null,
		category: 'world-country-capitals-europe',
	},
	{
		questionTitleHtml: '<strong>Netherlands</strong>',
		questionDescriptionHtml: 'What is the capital of this country?',
		answerTitleHtml: '<strong>Amsterdam</strong>',
		answerDescriptionHtml: 'Capital of <strong>Netherlands</strong>',
		pathToMedia: null,
		category: 'world-country-capitals-europe',
	},
	{
		questionTitleHtml: '<strong>Norway</strong>',
		questionDescriptionHtml: 'What is the capital of this country?',
		answerTitleHtml: '<strong>Oslo</strong>',
		answerDescriptionHtml: 'Capital of <strong>Norway</strong>',
		pathToMedia: null,
		category: 'world-country-capitals-europe',
	},
	{
		questionTitleHtml: '<strong>Poland</strong>',
		questionDescriptionHtml: 'What is the capital of this country?',
		answerTitleHtml: '<strong>Warsaw</strong>',
		answerDescriptionHtml: 'Capital of <strong>Poland</strong>',
		pathToMedia: null,
		category: 'world-country-capitals-europe',
	},
	{
		questionTitleHtml: '<strong>Portugal</strong>',
		questionDescriptionHtml: 'What is the capital of this country?',
		answerTitleHtml: '<strong>Lisbon</strong>',
		answerDescriptionHtml: 'Capital of <strong>Portugal</strong>',
		pathToMedia: null,
		category: 'world-country-capitals-europe',
	},
	{
		questionTitleHtml: '<strong>Romania</strong>',
		questionDescriptionHtml: 'What is the capital of this country?',
		answerTitleHtml: '<strong>Bucharest</strong>',
		answerDescriptionHtml: 'Capital of <strong>Romania</strong>',
		pathToMedia: null,
		category: 'world-country-capitals-europe',
	},
	{
		questionTitleHtml: '<strong>Russia</strong>',
		questionDescriptionHtml: 'What is the capital of this country?',
		answerTitleHtml: '<strong>Moscow</strong>',
		answerDescriptionHtml: 'Capital of <strong>Russia</strong>',
		pathToMedia: null,
		category: 'world-country-capitals-europe',
	},
	{
		questionTitleHtml: '<strong>Serbia</strong>',
		questionDescriptionHtml: 'What is the capital of this country?',
		answerTitleHtml: '<strong>Belgrade</strong>',
		answerDescriptionHtml: 'Capital of <strong>Serbia</strong>',
		pathToMedia: null,
		category: 'world-country-capitals-europe',
	},
	{
		questionTitleHtml: '<strong>Slovakia</strong>',
		questionDescriptionHtml: 'What is the capital of this country?',
		answerTitleHtml: '<strong>Bratislava</strong>',
		answerDescriptionHtml: 'Capital of <strong>Slovakia</strong>',
		pathToMedia: null,
		category: 'world-country-capitals-europe',
	},
	{
		questionTitleHtml: '<strong>Slovenia</strong>',
		questionDescriptionHtml: 'What is the capital of this country?',
		answerTitleHtml: '<strong>Ljubljana</strong>',
		answerDescriptionHtml: 'Capital of <strong>Slovenia</strong>',
		pathToMedia: null,
		category: 'world-country-capitals-europe',
	},
	{
		questionTitleHtml: '<strong>Spain</strong>',
		questionDescriptionHtml: 'What is the capital of this country?',
		answerTitleHtml: '<strong>Madrid</strong>',
		answerDescriptionHtml: 'Capital of <strong>Spain</strong>',
		pathToMedia: null,
		category: 'world-country-capitals-europe',
	},
	{
		questionTitleHtml: '<strong>Sweden</strong>',
		questionDescriptionHtml: 'What is the capital of this country?',
		answerTitleHtml: '<strong>Stockholm</strong>',
		answerDescriptionHtml: 'Capital of <strong>Sweden</strong>',
		pathToMedia: null,
		category: 'world-country-capitals-europe',
	},
	{
		questionTitleHtml: '<strong>Switzerland</strong>',
		questionDescriptionHtml: 'What is the capital of this country?',
		answerTitleHtml: '<strong>Bern</strong>',
		answerDescriptionHtml: 'Capital of <strong>Switzerland</strong>',
		pathToMedia: null,
		category: 'world-country-capitals-europe',
	},
	{
		questionTitleHtml: '<strong>Turkey</strong>',
		questionDescriptionHtml: 'What is the capital of this country?',
		answerTitleHtml: '<strong>Ankara</strong>',
		answerDescriptionHtml: 'Capital of <strong>Turkey</strong>',
		pathToMedia: null,
		category: 'world-country-capitals-europe',
	},
	{
		questionTitleHtml: '<strong>Ukraine</strong>',
		questionDescriptionHtml: 'What is the capital of this country?',
		answerTitleHtml: '<strong>Kyiv</strong>',
		answerDescriptionHtml: 'Capital of <strong>Ukraine</strong>',
		pathToMedia: null,
		category: 'world-country-capitals-europe',
	},
	{
		questionTitleHtml: '<strong>United Kingdom</strong>',
		questionDescriptionHtml: 'What is the capital of this country?',
		answerTitleHtml: '<strong>London</strong>',
		answerDescriptionHtml: 'Capital of <strong>United Kingdom</strong>',
		pathToMedia: null,
		category: 'world-country-capitals-europe',
	},
	{
		questionTitleHtml: '<strong>Vatican City</strong>',
		questionDescriptionHtml: 'What is the capital of this country?',
		answerTitleHtml: '<strong>Vatican City</strong>',
		answerDescriptionHtml: 'Capital of <strong>Vatican City</strong>',
		pathToMedia: null,
		category: 'world-country-capitals-europe',
	},
]
