import type { FlashCard } from '@/types'

export const world_country_locations_languages_north_america: FlashCard[] = [
	{
		questionTitleHtml: '<strong>Belize</strong>',
		questionDescriptionHtml: 'What is the location and principal language of this country?',
		answerTitleHtml: '<strong>Belize</strong>',
		answerDescriptionHtml: 'Location: Central America<br>Principal Language: English',
		pathToMedia: 'placeholder',
		category: 'world-country-locations-languages-north-america',
	},
	{
		questionTitleHtml: '<strong>Canada</strong>',
		questionDescriptionHtml: 'What is the location and principal language of this country?',
		answerTitleHtml: '<strong>Canada</strong>',
		answerDescriptionHtml: 'Location: North America<br>Principal Language: English',
		pathToMedia: 'placeholder',
		category: 'world-country-locations-languages-north-america',
	},
	{
		questionTitleHtml: '<strong>Costa Rica</strong>',
		questionDescriptionHtml: 'What is the location and principal language of this country?',
		answerTitleHtml: '<strong>Costa Rica</strong>',
		answerDescriptionHtml: 'Location: Central America<br>Principal Language: Spanish',
		pathToMedia: 'placeholder',
		category: 'world-country-locations-languages-north-america',
	},
	{
		questionTitleHtml: '<strong>Cuba</strong>',
		questionDescriptionHtml: 'What is the location and principal language of this country?',
		answerTitleHtml: '<strong>Cuba</strong>',
		answerDescriptionHtml: 'Location: Caribbean<br>Principal Language: Spanish',
		pathToMedia: 'placeholder',
		category: 'world-country-locations-languages-north-america',
	},
	{
		questionTitleHtml: '<strong>Dominican Republic</strong>',
		questionDescriptionHtml: 'What is the location and principal language of this country?',
		answerTitleHtml: '<strong>Dominican Republic</strong>',
		answerDescriptionHtml: 'Location: Caribbean<br>Principal Language: Spanish',
		pathToMedia: 'placeholder',
		category: 'world-country-locations-languages-north-america',
	},
	{
		questionTitleHtml: '<strong>El Salvador</strong>',
		questionDescriptionHtml: 'What is the location and principal language of this country?',
		answerTitleHtml: '<strong>El Salvador</strong>',
		answerDescriptionHtml: 'Location: Central America<br>Principal Language: Spanish',
		pathToMedia: 'placeholder',
		category: 'world-country-locations-languages-north-america',
	},
	{
		questionTitleHtml: '<strong>Grenada</strong>',
		questionDescriptionHtml: 'What is the location and principal language of this country?',
		answerTitleHtml: '<strong>Grenada</strong>',
		answerDescriptionHtml: 'Location: Caribbean<br>Principal Language: English',
		pathToMedia: 'placeholder',
		category: 'world-country-locations-languages-north-america',
	},
	{
		questionTitleHtml: '<strong>Guatemala</strong>',
		questionDescriptionHtml: 'What is the location and principal language of this country?',
		answerTitleHtml: '<strong>Guatemala</strong>',
		answerDescriptionHtml: 'Location: Central America<br>Principal Language: Spanish',
		pathToMedia: 'placeholder',
		category: 'world-country-locations-languages-north-america',
	},
	{
		questionTitleHtml: '<strong>Haiti</strong>',
		questionDescriptionHtml: 'What is the location and principal language of this country?',
		answerTitleHtml: '<strong>Haiti</strong>',
		answerDescriptionHtml: 'Location: Caribbean<br>Principal Language: French',
		pathToMedia: 'placeholder',
		category: 'world-country-locations-languages-north-america',
	},
	{
		questionTitleHtml: '<strong>Honduras</strong>',
		questionDescriptionHtml: 'What is the location and principal language of this country?',
		answerTitleHtml: '<strong>Honduras</strong>',
		answerDescriptionHtml: 'Location: Central America<br>Principal Language: Spanish',
		pathToMedia: 'placeholder',
		category: 'world-country-locations-languages-north-america',
	},
	{
		questionTitleHtml: '<strong>Jamaica</strong>',
		questionDescriptionHtml: 'What is the location and principal language of this country?',
		answerTitleHtml: '<strong>Jamaica</strong>',
		answerDescriptionHtml: 'Location: Caribbean<br>Principal Language: English',
		pathToMedia: 'placeholder',
		category: 'world-country-locations-languages-north-america',
	},
	{
		questionTitleHtml: '<strong>Mexico</strong>',
		questionDescriptionHtml: 'What is the location and principal language of this country?',
		answerTitleHtml: '<strong>Mexico</strong>',
		answerDescriptionHtml: 'Location: North America<br>Principal Language: Spanish',
		pathToMedia: 'placeholder',
		category: 'world-country-locations-languages-north-america',
	},
	{
		questionTitleHtml: '<strong>Nicaragua</strong>',
		questionDescriptionHtml: 'What is the location and principal language of this country?',
		answerTitleHtml: '<strong>Nicaragua</strong>',
		answerDescriptionHtml: 'Location: Central America<br>Principal Language: Spanish',
		pathToMedia: 'placeholder',
		category: 'world-country-locations-languages-north-america',
	},
	{
		questionTitleHtml: '<strong>Panama</strong>',
		questionDescriptionHtml: 'What is the location and principal language of this country?',
		answerTitleHtml: '<strong>Panama</strong>',
		answerDescriptionHtml: 'Location: Central America<br>Principal Language: Spanish',
		pathToMedia: 'placeholder',
		category: 'world-country-locations-languages-north-america',
	},
	{
		questionTitleHtml: '<strong>Trinidad and Tobago</strong>',
		questionDescriptionHtml: 'What is the location and principal language of this country?',
		answerTitleHtml: '<strong>Trinidad and Tobago</strong>',
		answerDescriptionHtml: 'Location: Caribbean<br>Principal Language: English',
		pathToMedia: 'placeholder',
		category: 'world-country-locations-languages-north-america',
	},
	{
		questionTitleHtml: '<strong>United States</strong>',
		questionDescriptionHtml: 'What is the location and principal language of this country?',
		answerTitleHtml: '<strong>United States</strong>',
		answerDescriptionHtml: 'Location: North America<br>Principal Language: English',
		pathToMedia: 'placeholder',
		category: 'world-country-locations-languages-north-america',
	},
]
