import type { FlashCard } from '@/types'

export const world_country_locations_languages_north_america: FlashCard[] = [
	{
		questionTitleHtml: '<strong>What\'s this country in North America?</strong>',
		questionDescriptionHtml: 'And its principal language',
		answerTitleHtml: '<strong>Belize</strong>',
		answerDescriptionHtml: 'Location: Central America<br>Principal Language: English',
		pathToMedia: 'images/world-country-locations/north-america/belize.png',
		category: 'world-country-locations-languages-north-america',
	},
	{
		questionTitleHtml: '<strong>What\'s this country in North America?</strong>',
		questionDescriptionHtml: 'And its principal language',
		answerTitleHtml: '<strong>Canada</strong>',
		answerDescriptionHtml: 'Location: North America<br>Principal Language: English',
		pathToMedia: 'images/world-country-locations/north-america/canada.png',
		category: 'world-country-locations-languages-north-america',
	},
	{
		questionTitleHtml: '<strong>What\'s this country in North America?</strong>',
		questionDescriptionHtml: 'And its principal language',
		answerTitleHtml: '<strong>Costa Rica</strong>',
		answerDescriptionHtml: 'Location: Central America<br>Principal Language: Spanish',
		pathToMedia: 'images/world-country-locations/north-america/costa-rica.png',
		category: 'world-country-locations-languages-north-america',
	},
	{
		questionTitleHtml: '<strong>What\'s this country in North America?</strong>',
		questionDescriptionHtml: 'And its principal language',
		answerTitleHtml: '<strong>Cuba</strong>',
		answerDescriptionHtml: 'Location: Caribbean<br>Principal Language: Spanish',
		pathToMedia: 'images/world-country-locations/north-america/cuba.png',
		category: 'world-country-locations-languages-north-america',
	},
	{
		questionTitleHtml: '<strong>What\'s this country in North America?</strong>',
		questionDescriptionHtml: 'And its principal language',
		answerTitleHtml: '<strong>Dominican Republic</strong>',
		answerDescriptionHtml: 'Location: Caribbean<br>Principal Language: Spanish',
		pathToMedia: 'images/world-country-locations/north-america/dominican-republic.png',
		category: 'world-country-locations-languages-north-america',
	},
	{
		questionTitleHtml: '<strong>What\'s this country in North America?</strong>',
		questionDescriptionHtml: 'And its principal language',
		answerTitleHtml: '<strong>El Salvador</strong>',
		answerDescriptionHtml: 'Location: Central America<br>Principal Language: Spanish',
		pathToMedia: 'images/world-country-locations/north-america/el-salvador.png',
		category: 'world-country-locations-languages-north-america',
	},
	{
		questionTitleHtml: '<strong>What\'s this country in North America?</strong>',
		questionDescriptionHtml: 'And its principal language',
		answerTitleHtml: '<strong>Grenada</strong>',
		answerDescriptionHtml: 'Location: Caribbean<br>Principal Language: English',
		pathToMedia: 'images/world-country-locations/north-america/grenada.png',
		category: 'world-country-locations-languages-north-america',
	},
	{
		questionTitleHtml: '<strong>What\'s this country in North America?</strong>',
		questionDescriptionHtml: 'And its principal language',
		answerTitleHtml: '<strong>Guatemala</strong>',
		answerDescriptionHtml: 'Location: Central America<br>Principal Language: Spanish',
		pathToMedia: 'images/world-country-locations/north-america/guatemala.png',
		category: 'world-country-locations-languages-north-america',
	},
	{
		questionTitleHtml: '<strong>What\'s this country in North America?</strong>',
		questionDescriptionHtml: 'And its principal language',
		answerTitleHtml: '<strong>Haiti</strong>',
		answerDescriptionHtml: 'Location: Caribbean<br>Principal Language: French',
		pathToMedia: 'images/world-country-locations/north-america/haiti.png',
		category: 'world-country-locations-languages-north-america',
	},
	{
		questionTitleHtml: '<strong>What\'s this country in North America?</strong>',
		questionDescriptionHtml: 'And its principal language',
		answerTitleHtml: '<strong>Honduras</strong>',
		answerDescriptionHtml: 'Location: Central America<br>Principal Language: Spanish',
		pathToMedia: 'images/world-country-locations/north-america/honduras.png',
		category: 'world-country-locations-languages-north-america',
	},
	{
		questionTitleHtml: '<strong>What\'s this country in North America?</strong>',
		questionDescriptionHtml: 'And its principal language',
		answerTitleHtml: '<strong>Jamaica</strong>',
		answerDescriptionHtml: 'Location: Caribbean<br>Principal Language: English',
		pathToMedia: 'images/world-country-locations/north-america/jamaica.png',
		category: 'world-country-locations-languages-north-america',
	},
	{
		questionTitleHtml: '<strong>What\'s this country in North America?</strong>',
		questionDescriptionHtml: 'And its principal language',
		answerTitleHtml: '<strong>Mexico</strong>',
		answerDescriptionHtml: 'Location: North America<br>Principal Language: Spanish',
		pathToMedia: 'images/world-country-locations/north-america/mexico.png',
		category: 'world-country-locations-languages-north-america',
	},
	{
		questionTitleHtml: '<strong>What\'s this country in North America?</strong>',
		questionDescriptionHtml: 'And its principal language',
		answerTitleHtml: '<strong>Nicaragua</strong>',
		answerDescriptionHtml: 'Location: Central America<br>Principal Language: Spanish',
		pathToMedia: 'images/world-country-locations/north-america/nicaragua.png',
		category: 'world-country-locations-languages-north-america',
	},
	{
		questionTitleHtml: '<strong>What\'s this country in North America?</strong>',
		questionDescriptionHtml: 'And its principal language',
		answerTitleHtml: '<strong>Panama</strong>',
		answerDescriptionHtml: 'Location: Central America<br>Principal Language: Spanish',
		pathToMedia: 'images/world-country-locations/north-america/panama.png',
		category: 'world-country-locations-languages-north-america',
	},
	{
		questionTitleHtml: '<strong>What\'s this country in North America?</strong>',
		questionDescriptionHtml: 'And its principal language',
		answerTitleHtml: '<strong>Trinidad and Tobago</strong>',
		answerDescriptionHtml: 'Location: Caribbean<br>Principal Language: English',
		pathToMedia: 'images/world-country-locations/north-america/trinidad-and-tobago.png',
		category: 'world-country-locations-languages-north-america',
	},
	{
		questionTitleHtml: '<strong>What\'s this country in North America?</strong>',
		questionDescriptionHtml: 'And its principal language',
		answerTitleHtml: '<strong>United States</strong>',
		answerDescriptionHtml: 'Location: North America<br>Principal Language: English',
		pathToMedia: 'images/world-country-locations/north-america/united-states.png',
		category: 'world-country-locations-languages-north-america',
	},
]
