import type { FlashCard } from '@/types'

export const world_cities_landmarks_asia: FlashCard[] = [
	{
		questionTitleHtml: '<strong>Hong Kong</strong>',
		questionDescriptionHtml: 'What is the location or description of this?',
		answerTitleHtml: '<strong>Hong Kong</strong>',
		answerDescriptionHtml: 'Location: China<br>Special administrative region, major financial center',
		pathToMedia: 'images/world-cities-landmarks-asia/hong-kong.png',
		category: 'world-cities-landmarks-asia',
	},
	{
		questionTitleHtml: '<strong>Nazareth</strong>',
		questionDescriptionHtml: 'What is the location or description of this?',
		answerTitleHtml: '<strong>Nazareth</strong>',
		answerDescriptionHtml: 'Location: Israel<br>Historic city in northern Israel',
		pathToMedia: 'images/world-cities-landmarks-asia/nazareth.jpg',
		category: 'world-cities-landmarks-asia',
	},
	{
		questionTitleHtml: '<strong>Osaka</strong>',
		questionDescriptionHtml: 'What is the location or description of this?',
		answerTitleHtml: '<strong>Osaka</strong>',
		answerDescriptionHtml: 'Location: Japan<br>Major port city in western Japan',
		pathToMedia: 'images/world-cities-landmarks-asia/osaka.jpg',
		category: 'world-cities-landmarks-asia',
	},
	{
		questionTitleHtml: '<strong>Shanghai</strong>',
		questionDescriptionHtml: 'What is the location or description of this?',
		answerTitleHtml: '<strong>Shanghai</strong>',
		answerDescriptionHtml: 'Location: China<br>Major port city and financial center',
		pathToMedia: 'images/world-cities-landmarks-asia/shanghai.jpg',
		category: 'world-cities-landmarks-asia',
	},
	{
		questionTitleHtml: '<strong>Gobi Desert</strong>',
		questionDescriptionHtml: 'What is the location or description of this?',
		answerTitleHtml: '<strong>Gobi Desert</strong>',
		answerDescriptionHtml: 'Location: China, Mongolia<br>Large desert in East Asia',
		pathToMedia: 'images/world-cities-landmarks-asia/gobi-desert.jpg',
		category: 'world-cities-landmarks-asia',
	},
	{
		questionTitleHtml: '<strong>Andaman Sea</strong>',
		questionDescriptionHtml: 'What is the location or description of this?',
		answerTitleHtml: '<strong>Andaman Sea</strong>',
		answerDescriptionHtml: 'Location: Eastern Indian Ocean, between India and Myanmar',
		pathToMedia: 'images/world-cities-landmarks-asia/andaman-sea.png',
		category: 'world-cities-landmarks-asia',
	},
	{
		questionTitleHtml: '<strong>Arabian Sea</strong>',
		questionDescriptionHtml: 'What is the location or description of this?',
		answerTitleHtml: '<strong>Arabian Sea</strong>',
		answerDescriptionHtml: 'Location: Northern Indian Ocean, between Arabian Peninsula and India',
		pathToMedia: 'images/world-cities-landmarks-asia/arabian-sea.png',
		category: 'world-cities-landmarks-asia',
	},
	{
		questionTitleHtml: '<strong>East China Sea</strong>',
		questionDescriptionHtml: 'What is the location or description of this?',
		answerTitleHtml: '<strong>East China Sea</strong>',
		answerDescriptionHtml: 'Location: Western Pacific Ocean, between China and Japan',
		pathToMedia: 'images/world-cities-landmarks-asia/east-china-sea.png',
		category: 'world-cities-landmarks-asia',
	},
	{
		questionTitleHtml: '<strong>Sea of Japan</strong>',
		questionDescriptionHtml: 'What is the location or description of this?',
		answerTitleHtml: '<strong>Sea of Japan</strong>',
		answerDescriptionHtml: 'Location: Between Japan and Korea',
		pathToMedia: 'images/world-cities-landmarks-asia/sea-of-japan.png',
		category: 'world-cities-landmarks-asia',
	},
	{
		questionTitleHtml: '<strong>Sea of Okhotsk</strong>',
		questionDescriptionHtml: 'What is the location or description of this?',
		answerTitleHtml: '<strong>Sea of Okhotsk</strong>',
		answerDescriptionHtml: 'Location: Northwestern Pacific Ocean, between Russia and Japan',
		pathToMedia: 'images/world-cities-landmarks-asia/sea-of-okhotsk.png',
		category: 'world-cities-landmarks-asia',
	},
	{
		questionTitleHtml: '<strong>South China Sea</strong>',
		questionDescriptionHtml: 'What is the location or description of this?',
		answerTitleHtml: '<strong>South China Sea</strong>',
		answerDescriptionHtml: 'Location: Western Pacific Ocean, between China and Southeast Asia',
		pathToMedia: 'images/world-cities-landmarks-asia/south-china-sea.jpg',
		category: 'world-cities-landmarks-asia',
	},
	{
		questionTitleHtml: '<strong>Kanyakumari (Cape Comorin)</strong>',
		questionDescriptionHtml: 'What is the location or description of this?',
		answerTitleHtml: '<strong>Kanyakumari (Cape Comorin)</strong>',
		answerDescriptionHtml: 'Location: Southern India',
		pathToMedia: 'images/world-cities-landmarks-asia/kanyakumari.jpg',
		category: 'world-cities-landmarks-asia',
	},
	{
		questionTitleHtml: '<strong>Korean Peninsula</strong>',
		questionDescriptionHtml: 'What is the location or description of this?',
		answerTitleHtml: '<strong>Korean Peninsula</strong>',
		answerDescriptionHtml: 'Location: East Asia (North Korea, South Korea)',
		pathToMedia: 'images/world-cities-landmarks-asia/korean-peninsula.png',
		category: 'world-cities-landmarks-asia',
	},
	{
		questionTitleHtml: '<strong>Straits of Malacca</strong>',
		questionDescriptionHtml: 'What is the location or description of this?',
		answerTitleHtml: '<strong>Straits of Malacca</strong>',
		answerDescriptionHtml: 'Location: Between Malaysia and Indonesia',
		pathToMedia: 'images/world-cities-landmarks-asia/straits-of-malacca.png',
		category: 'world-cities-landmarks-asia',
	},
	{
		questionTitleHtml: '<strong>Great Wall of China</strong>',
		questionDescriptionHtml: 'What is the location or description of this?',
		answerTitleHtml: '<strong>Great Wall of China</strong>',
		answerDescriptionHtml: 'Location: China',
		pathToMedia: 'images/world-cities-landmarks-asia/great-wall-of-china.jpg',
		category: 'world-cities-landmarks-asia',
	},
	{
		questionTitleHtml: '<strong>Forbidden City</strong>',
		questionDescriptionHtml: 'What is the location or description of this?',
		answerTitleHtml: '<strong>Forbidden City</strong>',
		answerDescriptionHtml: 'Location: Beijing, China',
		pathToMedia: 'images/world-cities-landmarks-asia/forbidden-city.jpg',
		category: 'world-cities-landmarks-asia',
	},
	{
		questionTitleHtml: '<strong>Taj Mahal</strong>',
		questionDescriptionHtml: 'What is the location or description of this?',
		answerTitleHtml: '<strong>Taj Mahal</strong>',
		answerDescriptionHtml: 'Location: India',
		pathToMedia: 'images/world-cities-landmarks-asia/taj-mahal.jpeg',
		category: 'world-cities-landmarks-asia',
	},
	{
		questionTitleHtml: '<strong>The Buried City</strong>',
		questionDescriptionHtml: 'What is the location or description of this?',
		answerTitleHtml: '<strong>The Buried City</strong>',
		answerDescriptionHtml: 'Location: Pakistan (ancient Indus Valley archaeological site)',
		pathToMedia: 'images/world-cities-landmarks-asia/buried-city.webp',
		category: 'world-cities-landmarks-asia',
	},
	{
		questionTitleHtml: '<strong>Khyber Pass</strong>',
		questionDescriptionHtml: 'What is the location or description of this?',
		answerTitleHtml: '<strong>Khyber Pass</strong>',
		answerDescriptionHtml: 'Location: Afghanistan/Pakistan border',
		pathToMedia: 'images/world-cities-landmarks-asia/khyber-pass.jpg',
		category: 'world-cities-landmarks-asia',
	},
	{
		questionTitleHtml: '<strong>Spice Islands</strong>',
		questionDescriptionHtml: 'What is the location or description of this?',
		answerTitleHtml: '<strong>Spice Islands</strong>',
		answerDescriptionHtml: 'Location: Indonesia (Maluku Islands)',
		pathToMedia: 'images/world-cities-landmarks-asia/spice-islands.png',
		category: 'world-cities-landmarks-asia',
	},
	{
		questionTitleHtml: '<strong>Sumatra</strong>',
		questionDescriptionHtml: 'What is the location or description of this?',
		answerTitleHtml: '<strong>Sumatra</strong>',
		answerDescriptionHtml: 'Location: Indian Ocean (part of Indonesia)',
		pathToMedia: 'images/world-cities-landmarks-asia/sumatra.png',
		category: 'world-cities-landmarks-asia',
	},
	{
		questionTitleHtml: '<strong>New Guinea</strong>',
		questionDescriptionHtml: 'What is the location or description of this?',
		answerTitleHtml: '<strong>New Guinea</strong>',
		answerDescriptionHtml: 'Location: Western Pacific Ocean (Papua New Guinea, Indonesia)',
		pathToMedia: 'images/world-cities-landmarks-asia/new-guinea.png',
		category: 'world-cities-landmarks-asia',
	},
	{
		questionTitleHtml: '<strong>Sinai Peninsula</strong>',
		questionDescriptionHtml: 'What is the location or description of this?',
		answerTitleHtml: '<strong>Sinai Peninsula</strong>',
		answerDescriptionHtml: 'Location: Egypt (geographically in Asia)',
		pathToMedia: 'images/world-cities-landmarks-asia/sinai-peninsula.jpg',
		category: 'world-cities-landmarks-asia',
	},
	{
		questionTitleHtml: '<strong>Middle East</strong>',
		questionDescriptionHtml: 'What is the location or description of this?',
		answerTitleHtml: '<strong>Middle East</strong>',
		answerDescriptionHtml: 'Location: Western Asia and parts of North Africa',
		pathToMedia: 'images/world-cities-landmarks-asia/middle-east.png',
		category: 'world-cities-landmarks-asia',
	},
	{
		questionTitleHtml: '<strong>Fertile Crescent</strong>',
		questionDescriptionHtml: 'What is the location or description of this?',
		answerTitleHtml: '<strong>Fertile Crescent</strong>',
		answerDescriptionHtml: 'Location: Middle East (region from Egypt through Mesopotamia)',
		pathToMedia: 'images/world-cities-landmarks-asia/fertile-crescent.png',
		category: 'world-cities-landmarks-asia',
	},
	{
		questionTitleHtml: '<strong>Dome of the Rock</strong>',
		questionDescriptionHtml: 'What is the location or description of this?',
		answerTitleHtml: '<strong>Dome of the Rock</strong>',
		answerDescriptionHtml: 'Location: Jerusalem, Israel',
		pathToMedia: 'images/world-cities-landmarks-asia/dome-of-the-rock.jpg',
		category: 'world-cities-landmarks-asia',
	},
]
