import type { FlashCard } from '@/types'

export const world_cities_landmarks_north_america: FlashCard[] = [
	{
		questionTitleHtml: '<strong>Atlantic City</strong>',
		questionDescriptionHtml: 'What is the location or description of this?',
		answerTitleHtml: '<strong>Atlantic City</strong>',
		answerDescriptionHtml: 'Location: New Jersey, United States<br>Famous resort city on the Atlantic coast',
		pathToMedia: 'images/world-cities-landmarks-north-america/atlantic-city.jpg',
		category: 'world-cities-landmarks-north-america',
	},
	{
		questionTitleHtml: '<strong>Chicago</strong>',
		questionDescriptionHtml: 'What is the location or description of this?',
		answerTitleHtml: '<strong>Chicago</strong>',
		answerDescriptionHtml: 'Location: Illinois, United States<br>Major city on Lake Michigan',
		pathToMedia: 'images/world-cities-landmarks-north-america/chicago.jpg',
		category: 'world-cities-landmarks-north-america',
	},
	{
		questionTitleHtml: '<strong>Los Angeles</strong>',
		questionDescriptionHtml: 'What is the location or description of this?',
		answerTitleHtml: '<strong>Los Angeles</strong>',
		answerDescriptionHtml: 'Location: California, United States<br>Major city on the Pacific coast, center of entertainment industry',
		pathToMedia: 'images/world-cities-landmarks-north-america/los-angeles.jpg',
		category: 'world-cities-landmarks-north-america',
	},
	{
		questionTitleHtml: '<strong>Montreal</strong>',
		questionDescriptionHtml: 'What is the location or description of this?',
		answerTitleHtml: '<strong>Montreal</strong>',
		answerDescriptionHtml: 'Location: Quebec, Canada<br>Major city in eastern Canada',
		pathToMedia: 'images/world-cities-landmarks-north-america/montreal.jpg',
		category: 'world-cities-landmarks-north-america',
	},
	{
		questionTitleHtml: '<strong>New York City</strong>',
		questionDescriptionHtml: 'What is the location or description of this?',
		answerTitleHtml: '<strong>New York City</strong>',
		answerDescriptionHtml: 'Location: New York, United States<br>Major city on the Atlantic coast, most populous city in the U.S.',
		pathToMedia: 'images/world-cities-landmarks-north-america/new-york-city.jpg',
		category: 'world-cities-landmarks-north-america',
	},
	{
		questionTitleHtml: '<strong>Philadelphia</strong>',
		questionDescriptionHtml: 'What is the location or description of this?',
		answerTitleHtml: '<strong>Philadelphia</strong>',
		answerDescriptionHtml: 'Location: Pennsylvania, United States<br>Historic city, birthplace of American independence',
		pathToMedia: 'images/world-cities-landmarks-north-america/philadelphia.jpg',
		category: 'world-cities-landmarks-north-america',
	},
	{
		questionTitleHtml: '<strong>San Francisco</strong>',
		questionDescriptionHtml: 'What is the location or description of this?',
		answerTitleHtml: '<strong>San Francisco</strong>',
		answerDescriptionHtml: 'Location: California, United States<br>Major city on the Pacific coast',
		pathToMedia: 'images/world-cities-landmarks-north-america/san-francisco.jpg',
		category: 'world-cities-landmarks-north-america',
	},
	{
		questionTitleHtml: '<strong>Bering Sea</strong>',
		questionDescriptionHtml: 'What is the location or description of this?',
		answerTitleHtml: '<strong>Bering Sea</strong>',
		answerDescriptionHtml: 'Location: Northern Pacific Ocean, between Alaska and Russia',
		pathToMedia: 'images/world-cities-landmarks-north-america/bering-sea.png',
		category: 'world-cities-landmarks-north-america',
	},
	{
		questionTitleHtml: '<strong>Gulf of America (formally Gulf of Mexico)</strong>',
		questionDescriptionHtml: 'What is the location or description of this?',
		answerTitleHtml: '<strong>Gulf of America (formally Gulf of Mexico)</strong>',
		answerDescriptionHtml: 'Location: Between United States and Mexico',
		pathToMedia: 'images/world-cities-landmarks-north-america/gulf-of-mexico.png',
		category: 'world-cities-landmarks-north-america',
	},
	{
		questionTitleHtml: '<strong>Hudson Bay</strong>',
		questionDescriptionHtml: 'What is the location or description of this?',
		answerTitleHtml: '<strong>Hudson Bay</strong>',
		answerDescriptionHtml: 'Location: Northeastern Canada',
		pathToMedia: 'images/world-cities-landmarks-north-america/hudson-bay.png',
		category: 'world-cities-landmarks-north-america',
	},
	{
		questionTitleHtml: '<strong>Caribbean Sea</strong>',
		questionDescriptionHtml: 'What is the location or description of this?',
		answerTitleHtml: '<strong>Caribbean Sea</strong>',
		answerDescriptionHtml: 'Location: Western Atlantic Ocean, between North and South America',
		pathToMedia: 'images/world-cities-landmarks-north-america/caribbean-sea.jpg',
		category: 'world-cities-landmarks-north-america',
	},
	{
		questionTitleHtml: '<strong>Cape Cod</strong>',
		questionDescriptionHtml: 'What is the location or description of this?',
		answerTitleHtml: '<strong>Cape Cod</strong>',
		answerDescriptionHtml: 'Location: Massachusetts, United States',
		pathToMedia: 'images/world-cities-landmarks-north-america/cape-cod.png',
		category: 'world-cities-landmarks-north-america',
	},
	{
		questionTitleHtml: '<strong>Cape Canaveral</strong>',
		questionDescriptionHtml: 'What is the location or description of this?',
		answerTitleHtml: '<strong>Cape Canaveral</strong>',
		answerDescriptionHtml: 'Location: Florida, United States',
		pathToMedia: 'images/world-cities-landmarks-north-america/cape-canaveral.webp',
		category: 'world-cities-landmarks-north-america',
	},
	{
		questionTitleHtml: '<strong>Olympic Peninsula</strong>',
		questionDescriptionHtml: 'What is the location or description of this?',
		answerTitleHtml: '<strong>Olympic Peninsula</strong>',
		answerDescriptionHtml: 'Location: Washington, United States',
		pathToMedia: 'images/world-cities-landmarks-north-america/olympic-peninsula.png',
		category: 'world-cities-landmarks-north-america',
	},
	{
		questionTitleHtml: '<strong>Baja California Peninsula</strong>',
		questionDescriptionHtml: 'What is the location or description of this?',
		answerTitleHtml: '<strong>Baja California Peninsula</strong>',
		answerDescriptionHtml: 'Location: Mexico',
		pathToMedia: 'images/world-cities-landmarks-north-america/baja-california.png',
		category: 'world-cities-landmarks-north-america',
	},
	{
		questionTitleHtml: '<strong>Erie Canal</strong>',
		questionDescriptionHtml: 'What is the location or description of this?',
		answerTitleHtml: '<strong>Erie Canal</strong>',
		answerDescriptionHtml: 'Location: New York, United States',
		pathToMedia: 'images/world-cities-landmarks-north-america/erie-canal.jpg',
		category: 'world-cities-landmarks-north-america',
	},
	{
		questionTitleHtml: '<strong>Panama Canal</strong>',
		questionDescriptionHtml: 'What is the location or description of this?',
		answerTitleHtml: '<strong>Panama Canal</strong>',
		answerDescriptionHtml: 'Location: Panama, connecting Atlantic and Pacific Oceans',
		pathToMedia: 'images/world-cities-landmarks-north-america/panama-canal.png',
		category: 'world-cities-landmarks-north-america',
	},
	{
		questionTitleHtml: '<strong>Greenland</strong>',
		questionDescriptionHtml: 'What is the location or description of this?',
		answerTitleHtml: '<strong>Greenland</strong>',
		answerDescriptionHtml: 'Location: North Atlantic Ocean (autonomous territory of Denmark)',
		pathToMedia: 'images/world-cities-landmarks-north-america/greenland.png',
		category: 'world-cities-landmarks-north-america',
	},
	{
		questionTitleHtml: '<strong>Barbados</strong>',
		questionDescriptionHtml: 'What is the location or description of this?',
		answerTitleHtml: '<strong>Barbados</strong>',
		answerDescriptionHtml: 'Location: Caribbean Sea',
		pathToMedia: 'images/world-cities-landmarks-north-america/barbados.png',
		category: 'world-cities-landmarks-north-america',
	},
	{
		questionTitleHtml: '<strong>Hispaniola</strong>',
		questionDescriptionHtml: 'What is the location or description of this?',
		answerTitleHtml: '<strong>Hispaniola</strong>',
		answerDescriptionHtml: 'Location: Caribbean (island containing Haiti and Dominican Republic)',
		pathToMedia: 'images/world-cities-landmarks-north-america/hispaniola.jpg',
		category: 'world-cities-landmarks-north-america',
	},
	{
		questionTitleHtml: '<strong>Aleutian Islands</strong>',
		questionDescriptionHtml: 'What is the location or description of this?',
		answerTitleHtml: '<strong>Aleutian Islands</strong>',
		answerDescriptionHtml: 'Location: Northern Pacific Ocean (Alaska, United States)',
		pathToMedia: 'images/world-cities-landmarks-north-america/aleutian-islands.png',
		category: 'world-cities-landmarks-north-america',
	},
	{
		questionTitleHtml: '<strong>Chichen Itza</strong>',
		questionDescriptionHtml: 'What is the location or description of this?',
		answerTitleHtml: '<strong>Chichen Itza</strong>',
		answerDescriptionHtml: 'Location: Mexico',
		pathToMedia: 'images/world-cities-landmarks-north-america/chichen-itza.webp',
		category: 'world-cities-landmarks-north-america',
	},
]
