import type { FlashCard } from '@/types'

export const world_country_flags_africa: FlashCard[] = [
	{
		questionTitleHtml: '<strong>What country is this flag?</strong>',
		questionDescriptionHtml: '',
		answerTitleHtml: '<strong>Algeria</strong>',
		answerDescriptionHtml: 'Country Flag',
		pathToMedia: 'node_modules/svg-country-flags/svg/dz.svg',
		category: 'world-country-flags-africa',
	},
	{
		questionTitleHtml: '<strong>What country is this flag?</strong>',
		questionDescriptionHtml: '',
		answerTitleHtml: '<strong>Angola</strong>',
		answerDescriptionHtml: 'Country Flag',
		pathToMedia: 'node_modules/svg-country-flags/svg/ao.svg',
		category: 'world-country-flags-africa',
	},
	{
		questionTitleHtml: '<strong>What country is this flag?</strong>',
		questionDescriptionHtml: '',
		answerTitleHtml: '<strong>Botswana</strong>',
		answerDescriptionHtml: 'Country Flag',
		pathToMedia: 'node_modules/svg-country-flags/svg/bw.svg',
		category: 'world-country-flags-africa',
	},
	{
		questionTitleHtml: '<strong>What country is this flag?</strong>',
		questionDescriptionHtml: '',
		answerTitleHtml: '<strong>Burundi</strong>',
		answerDescriptionHtml: 'Country Flag',
		pathToMedia: 'node_modules/svg-country-flags/svg/bi.svg',
		category: 'world-country-flags-africa',
	},
	{
		questionTitleHtml: '<strong>What country is this flag?</strong>',
		questionDescriptionHtml: '',
		answerTitleHtml: '<strong>Central African Republic</strong>',
		answerDescriptionHtml: 'Country Flag',
		pathToMedia: 'node_modules/svg-country-flags/svg/cf.svg',
		category: 'world-country-flags-africa',
	},
	{
		questionTitleHtml: '<strong>What country is this flag?</strong>',
		questionDescriptionHtml: '',
		answerTitleHtml: '<strong>Chad</strong>',
		answerDescriptionHtml: 'Country Flag',
		pathToMedia: 'node_modules/svg-country-flags/svg/td.svg',
		category: 'world-country-flags-africa',
	},
	{
		questionTitleHtml: '<strong>What country is this flag?</strong>',
		questionDescriptionHtml: '',
		answerTitleHtml: '<strong>Democratic Republic of the Congo</strong>',
		answerDescriptionHtml: 'Country Flag',
		pathToMedia: 'node_modules/svg-country-flags/svg/cd.svg',
		category: 'world-country-flags-africa',
	},
	{
		questionTitleHtml: '<strong>What country is this flag?</strong>',
		questionDescriptionHtml: '',
		answerTitleHtml: '<strong>Egypt</strong>',
		answerDescriptionHtml: 'Country Flag',
		pathToMedia: 'node_modules/svg-country-flags/svg/eg.svg',
		category: 'world-country-flags-africa',
	},
	{
		questionTitleHtml: '<strong>What country is this flag?</strong>',
		questionDescriptionHtml: '',
		answerTitleHtml: '<strong>Ethiopia</strong>',
		answerDescriptionHtml: 'Country Flag',
		pathToMedia: 'node_modules/svg-country-flags/svg/et.svg',
		category: 'world-country-flags-africa',
	},
	{
		questionTitleHtml: '<strong>What country is this flag?</strong>',
		questionDescriptionHtml: '',
		answerTitleHtml: '<strong>Ghana</strong>',
		answerDescriptionHtml: 'Country Flag',
		pathToMedia: 'node_modules/svg-country-flags/svg/gh.svg',
		category: 'world-country-flags-africa',
	},
	{
		questionTitleHtml: '<strong>What country is this flag?</strong>',
		questionDescriptionHtml: '',
		answerTitleHtml: '<strong>Guinea</strong>',
		answerDescriptionHtml: 'Country Flag',
		pathToMedia: 'node_modules/svg-country-flags/svg/gn.svg',
		category: 'world-country-flags-africa',
	},
	{
		questionTitleHtml: '<strong>What country is this flag?</strong>',
		questionDescriptionHtml: '',
		answerTitleHtml: '<strong>Kenya</strong>',
		answerDescriptionHtml: 'Country Flag',
		pathToMedia: 'node_modules/svg-country-flags/svg/ke.svg',
		category: 'world-country-flags-africa',
	},
	{
		questionTitleHtml: '<strong>What country is this flag?</strong>',
		questionDescriptionHtml: '',
		answerTitleHtml: '<strong>Liberia</strong>',
		answerDescriptionHtml: 'Country Flag',
		pathToMedia: 'node_modules/svg-country-flags/svg/lr.svg',
		category: 'world-country-flags-africa',
	},
	{
		questionTitleHtml: '<strong>What country is this flag?</strong>',
		questionDescriptionHtml: '',
		answerTitleHtml: '<strong>Libya</strong>',
		answerDescriptionHtml: 'Country Flag',
		pathToMedia: 'node_modules/svg-country-flags/svg/ly.svg',
		category: 'world-country-flags-africa',
	},
	{
		questionTitleHtml: '<strong>What country is this flag?</strong>',
		questionDescriptionHtml: '',
		answerTitleHtml: '<strong>Madagascar</strong>',
		answerDescriptionHtml: 'Country Flag',
		pathToMedia: 'node_modules/svg-country-flags/svg/mg.svg',
		category: 'world-country-flags-africa',
	},
	{
		questionTitleHtml: '<strong>What country is this flag?</strong>',
		questionDescriptionHtml: '',
		answerTitleHtml: '<strong>Mali</strong>',
		answerDescriptionHtml: 'Country Flag',
		pathToMedia: 'node_modules/svg-country-flags/svg/ml.svg',
		category: 'world-country-flags-africa',
	},
	{
		questionTitleHtml: '<strong>What country is this flag?</strong>',
		questionDescriptionHtml: '',
		answerTitleHtml: '<strong>Morocco</strong>',
		answerDescriptionHtml: 'Country Flag',
		pathToMedia: 'node_modules/svg-country-flags/svg/ma.svg',
		category: 'world-country-flags-africa',
	},
	{
		questionTitleHtml: '<strong>What country is this flag?</strong>',
		questionDescriptionHtml: '',
		answerTitleHtml: '<strong>Mozambique</strong>',
		answerDescriptionHtml: 'Country Flag',
		pathToMedia: 'node_modules/svg-country-flags/svg/mz.svg',
		category: 'world-country-flags-africa',
	},
	{
		questionTitleHtml: '<strong>What country is this flag?</strong>',
		questionDescriptionHtml: '',
		answerTitleHtml: '<strong>Niger</strong>',
		answerDescriptionHtml: 'Country Flag',
		pathToMedia: 'node_modules/svg-country-flags/svg/ne.svg',
		category: 'world-country-flags-africa',
	},
	{
		questionTitleHtml: '<strong>What country is this flag?</strong>',
		questionDescriptionHtml: '',
		answerTitleHtml: '<strong>Nigeria</strong>',
		answerDescriptionHtml: 'Country Flag',
		pathToMedia: 'node_modules/svg-country-flags/svg/ng.svg',
		category: 'world-country-flags-africa',
	},
	{
		questionTitleHtml: '<strong>What country is this flag?</strong>',
		questionDescriptionHtml: '',
		answerTitleHtml: '<strong>Republic of the Congo</strong>',
		answerDescriptionHtml: 'Country Flag',
		pathToMedia: 'node_modules/svg-country-flags/svg/cg.svg',
		category: 'world-country-flags-africa',
	},
	{
		questionTitleHtml: '<strong>What country is this flag?</strong>',
		questionDescriptionHtml: '',
		answerTitleHtml: '<strong>Rwanda</strong>',
		answerDescriptionHtml: 'Country Flag',
		pathToMedia: 'node_modules/svg-country-flags/svg/rw.svg',
		category: 'world-country-flags-africa',
	},
	{
		questionTitleHtml: '<strong>What country is this flag?</strong>',
		questionDescriptionHtml: '',
		answerTitleHtml: '<strong>Somalia</strong>',
		answerDescriptionHtml: 'Country Flag',
		pathToMedia: 'node_modules/svg-country-flags/svg/so.svg',
		category: 'world-country-flags-africa',
	},
	{
		questionTitleHtml: '<strong>What country is this flag?</strong>',
		questionDescriptionHtml: '',
		answerTitleHtml: '<strong>South Africa</strong>',
		answerDescriptionHtml: 'Country Flag',
		pathToMedia: 'node_modules/svg-country-flags/svg/za.svg',
		category: 'world-country-flags-africa',
	},
	{
		questionTitleHtml: '<strong>What country is this flag?</strong>',
		questionDescriptionHtml: '',
		answerTitleHtml: '<strong>Sudan</strong>',
		answerDescriptionHtml: 'Country Flag',
		pathToMedia: 'node_modules/svg-country-flags/svg/sd.svg',
		category: 'world-country-flags-africa',
	},
	{
		questionTitleHtml: '<strong>What country is this flag?</strong>',
		questionDescriptionHtml: '',
		answerTitleHtml: '<strong>Swaziland (Eswatini)</strong>',
		answerDescriptionHtml: 'Country Flag',
		pathToMedia: 'node_modules/svg-country-flags/svg/sz.svg',
		category: 'world-country-flags-africa',
	},
	{
		questionTitleHtml: '<strong>What country is this flag?</strong>',
		questionDescriptionHtml: '',
		answerTitleHtml: '<strong>Tanzania</strong>',
		answerDescriptionHtml: 'Country Flag',
		pathToMedia: 'node_modules/svg-country-flags/svg/tz.svg',
		category: 'world-country-flags-africa',
	},
	{
		questionTitleHtml: '<strong>What country is this flag?</strong>',
		questionDescriptionHtml: '',
		answerTitleHtml: '<strong>Tunisia</strong>',
		answerDescriptionHtml: 'Country Flag',
		pathToMedia: 'node_modules/svg-country-flags/svg/tn.svg',
		category: 'world-country-flags-africa',
	},
	{
		questionTitleHtml: '<strong>What country is this flag?</strong>',
		questionDescriptionHtml: '',
		answerTitleHtml: '<strong>Uganda</strong>',
		answerDescriptionHtml: 'Country Flag',
		pathToMedia: 'node_modules/svg-country-flags/svg/ug.svg',
		category: 'world-country-flags-africa',
	},
	{
		questionTitleHtml: '<strong>What country is this flag?</strong>',
		questionDescriptionHtml: '',
		answerTitleHtml: '<strong>Zambia</strong>',
		answerDescriptionHtml: 'Country Flag',
		pathToMedia: 'node_modules/svg-country-flags/svg/zm.svg',
		category: 'world-country-flags-africa',
	},
	{
		questionTitleHtml: '<strong>What country is this flag?</strong>',
		questionDescriptionHtml: '',
		answerTitleHtml: '<strong>Zimbabwe</strong>',
		answerDescriptionHtml: 'Country Flag',
		pathToMedia: 'node_modules/svg-country-flags/svg/zw.svg',
		category: 'world-country-flags-africa',
	},
]
