import type { FlashCard } from '@/types'

export const world_country_locations_languages_south_america: FlashCard[] = [
	{
		questionTitleHtml: '<strong>Argentina</strong>',
		questionDescriptionHtml: 'What is the location and principal language of this country?',
		answerTitleHtml: '<strong>Argentina</strong>',
		answerDescriptionHtml: 'Location: South America<br>Principal Language: Spanish',
		pathToMedia: 'placeholder',
		category: 'world-country-locations-languages-south-america',
	},
	{
		questionTitleHtml: '<strong>Bolivia</strong>',
		questionDescriptionHtml: 'What is the location and principal language of this country?',
		answerTitleHtml: '<strong>Bolivia</strong>',
		answerDescriptionHtml: 'Location: South America<br>Principal Language: Spanish',
		pathToMedia: 'placeholder',
		category: 'world-country-locations-languages-south-america',
	},
	{
		questionTitleHtml: '<strong>Brazil</strong>',
		questionDescriptionHtml: 'What is the location and principal language of this country?',
		answerTitleHtml: '<strong>Brazil</strong>',
		answerDescriptionHtml: 'Location: South America<br>Principal Language: Portuguese',
		pathToMedia: 'placeholder',
		category: 'world-country-locations-languages-south-america',
	},
	{
		questionTitleHtml: '<strong>Chile</strong>',
		questionDescriptionHtml: 'What is the location and principal language of this country?',
		answerTitleHtml: '<strong>Chile</strong>',
		answerDescriptionHtml: 'Location: South America<br>Principal Language: Spanish',
		pathToMedia: 'placeholder',
		category: 'world-country-locations-languages-south-america',
	},
	{
		questionTitleHtml: '<strong>Colombia</strong>',
		questionDescriptionHtml: 'What is the location and principal language of this country?',
		answerTitleHtml: '<strong>Colombia</strong>',
		answerDescriptionHtml: 'Location: South America<br>Principal Language: Spanish',
		pathToMedia: 'placeholder',
		category: 'world-country-locations-languages-south-america',
	},
	{
		questionTitleHtml: '<strong>Ecuador</strong>',
		questionDescriptionHtml: 'What is the location and principal language of this country?',
		answerTitleHtml: '<strong>Ecuador</strong>',
		answerDescriptionHtml: 'Location: South America<br>Principal Language: Spanish',
		pathToMedia: 'placeholder',
		category: 'world-country-locations-languages-south-america',
	},
	{
		questionTitleHtml: '<strong>Guyana</strong>',
		questionDescriptionHtml: 'What is the location and principal language of this country?',
		answerTitleHtml: '<strong>Guyana</strong>',
		answerDescriptionHtml: 'Location: South America<br>Principal Language: English',
		pathToMedia: 'placeholder',
		category: 'world-country-locations-languages-south-america',
	},
	{
		questionTitleHtml: '<strong>Paraguay</strong>',
		questionDescriptionHtml: 'What is the location and principal language of this country?',
		answerTitleHtml: '<strong>Paraguay</strong>',
		answerDescriptionHtml: 'Location: South America<br>Principal Language: Spanish',
		pathToMedia: 'placeholder',
		category: 'world-country-locations-languages-south-america',
	},
	{
		questionTitleHtml: '<strong>Peru</strong>',
		questionDescriptionHtml: 'What is the location and principal language of this country?',
		answerTitleHtml: '<strong>Peru</strong>',
		answerDescriptionHtml: 'Location: South America<br>Principal Language: Spanish',
		pathToMedia: 'placeholder',
		category: 'world-country-locations-languages-south-america',
	},
	{
		questionTitleHtml: '<strong>Suriname</strong>',
		questionDescriptionHtml: 'What is the location and principal language of this country?',
		answerTitleHtml: '<strong>Suriname</strong>',
		answerDescriptionHtml: 'Location: South America<br>Principal Language: Dutch',
		pathToMedia: 'placeholder',
		category: 'world-country-locations-languages-south-america',
	},
	{
		questionTitleHtml: '<strong>Uruguay</strong>',
		questionDescriptionHtml: 'What is the location and principal language of this country?',
		answerTitleHtml: '<strong>Uruguay</strong>',
		answerDescriptionHtml: 'Location: South America<br>Principal Language: Spanish',
		pathToMedia: 'placeholder',
		category: 'world-country-locations-languages-south-america',
	},
	{
		questionTitleHtml: '<strong>Venezuela</strong>',
		questionDescriptionHtml: 'What is the location and principal language of this country?',
		answerTitleHtml: '<strong>Venezuela</strong>',
		answerDescriptionHtml: 'Location: South America<br>Principal Language: Spanish',
		pathToMedia: 'placeholder',
		category: 'world-country-locations-languages-south-america',
	},
]
