import type { FlashCard } from '@/types'

export const world_country_locations_languages_europe: FlashCard[] = [
	{
		questionTitleHtml: '<strong>Albania</strong>',
		questionDescriptionHtml: 'What is the location and principal language of this country?',
		answerTitleHtml: '<strong>Albania</strong>',
		answerDescriptionHtml: 'Location: Southeastern Europe (Balkans)<br>Principal Language: Albanian',
		pathToMedia: 'placeholder',
		category: 'world-country-locations-languages-europe',
	},
	{
		questionTitleHtml: '<strong>Armenia</strong>',
		questionDescriptionHtml: 'What is the location and principal language of this country?',
		answerTitleHtml: '<strong>Armenia</strong>',
		answerDescriptionHtml: 'Location: Western Asia (Caucasus)<br>Principal Language: Armenian',
		pathToMedia: 'placeholder',
		category: 'world-country-locations-languages-europe',
	},
	{
		questionTitleHtml: '<strong>Austria</strong>',
		questionDescriptionHtml: 'What is the location and principal language of this country?',
		answerTitleHtml: '<strong>Austria</strong>',
		answerDescriptionHtml: 'Location: Central Europe<br>Principal Language: German',
		pathToMedia: 'placeholder',
		category: 'world-country-locations-languages-europe',
	},
	{
		questionTitleHtml: '<strong>Belgium</strong>',
		questionDescriptionHtml: 'What is the location and principal language of this country?',
		answerTitleHtml: '<strong>Belgium</strong>',
		answerDescriptionHtml: 'Location: Western Europe<br>Principal Language: Dutch',
		pathToMedia: 'placeholder',
		category: 'world-country-locations-languages-europe',
	},
	{
		questionTitleHtml: '<strong>Bosnia and Herzegovina</strong>',
		questionDescriptionHtml: 'What is the location and principal language of this country?',
		answerTitleHtml: '<strong>Bosnia and Herzegovina</strong>',
		answerDescriptionHtml: 'Location: Southeastern Europe (Balkans)<br>Principal Language: Bosnian',
		pathToMedia: 'placeholder',
		category: 'world-country-locations-languages-europe',
	},
	{
		questionTitleHtml: '<strong>Bulgaria</strong>',
		questionDescriptionHtml: 'What is the location and principal language of this country?',
		answerTitleHtml: '<strong>Bulgaria</strong>',
		answerDescriptionHtml: 'Location: Southeastern Europe<br>Principal Language: Bulgarian',
		pathToMedia: 'placeholder',
		category: 'world-country-locations-languages-europe',
	},
	{
		questionTitleHtml: '<strong>Croatia</strong>',
		questionDescriptionHtml: 'What is the location and principal language of this country?',
		answerTitleHtml: '<strong>Croatia</strong>',
		answerDescriptionHtml: 'Location: Southeastern Europe<br>Principal Language: Croatian',
		pathToMedia: 'placeholder',
		category: 'world-country-locations-languages-europe',
	},
	{
		questionTitleHtml: '<strong>Czech Republic</strong>',
		questionDescriptionHtml: 'What is the location and principal language of this country?',
		answerTitleHtml: '<strong>Czech Republic</strong>',
		answerDescriptionHtml: 'Location: Central Europe<br>Principal Language: Czech',
		pathToMedia: 'placeholder',
		category: 'world-country-locations-languages-europe',
	},
	{
		questionTitleHtml: '<strong>Denmark</strong>',
		questionDescriptionHtml: 'What is the location and principal language of this country?',
		answerTitleHtml: '<strong>Denmark</strong>',
		answerDescriptionHtml: 'Location: Northern Europe (Scandinavia)<br>Principal Language: Danish',
		pathToMedia: 'placeholder',
		category: 'world-country-locations-languages-europe',
	},
	{
		questionTitleHtml: '<strong>Estonia</strong>',
		questionDescriptionHtml: 'What is the location and principal language of this country?',
		answerTitleHtml: '<strong>Estonia</strong>',
		answerDescriptionHtml: 'Location: Northern Europe (Baltic)<br>Principal Language: Estonian',
		pathToMedia: 'placeholder',
		category: 'world-country-locations-languages-europe',
	},
	{
		questionTitleHtml: '<strong>Finland</strong>',
		questionDescriptionHtml: 'What is the location and principal language of this country?',
		answerTitleHtml: '<strong>Finland</strong>',
		answerDescriptionHtml: 'Location: Northern Europe<br>Principal Language: Finnish',
		pathToMedia: 'placeholder',
		category: 'world-country-locations-languages-europe',
	},
	{
		questionTitleHtml: '<strong>France</strong>',
		questionDescriptionHtml: 'What is the location and principal language of this country?',
		answerTitleHtml: '<strong>France</strong>',
		answerDescriptionHtml: 'Location: Western Europe<br>Principal Language: French',
		pathToMedia: 'placeholder',
		category: 'world-country-locations-languages-europe',
	},
	{
		questionTitleHtml: '<strong>Georgia</strong>',
		questionDescriptionHtml: 'What is the location and principal language of this country?',
		answerTitleHtml: '<strong>Georgia</strong>',
		answerDescriptionHtml: 'Location: Western Asia (Caucasus)<br>Principal Language: Georgian',
		pathToMedia: 'placeholder',
		category: 'world-country-locations-languages-europe',
	},
	{
		questionTitleHtml: '<strong>Germany</strong>',
		questionDescriptionHtml: 'What is the location and principal language of this country?',
		answerTitleHtml: '<strong>Germany</strong>',
		answerDescriptionHtml: 'Location: Central Europe<br>Principal Language: German',
		pathToMedia: 'placeholder',
		category: 'world-country-locations-languages-europe',
	},
	{
		questionTitleHtml: '<strong>Greece</strong>',
		questionDescriptionHtml: 'What is the location and principal language of this country?',
		answerTitleHtml: '<strong>Greece</strong>',
		answerDescriptionHtml: 'Location: Southeastern Europe<br>Principal Language: Greek',
		pathToMedia: 'placeholder',
		category: 'world-country-locations-languages-europe',
	},
	{
		questionTitleHtml: '<strong>Hungary</strong>',
		questionDescriptionHtml: 'What is the location and principal language of this country?',
		answerTitleHtml: '<strong>Hungary</strong>',
		answerDescriptionHtml: 'Location: Central Europe<br>Principal Language: Hungarian',
		pathToMedia: 'placeholder',
		category: 'world-country-locations-languages-europe',
	},
	{
		questionTitleHtml: '<strong>Iceland</strong>',
		questionDescriptionHtml: 'What is the location and principal language of this country?',
		answerTitleHtml: '<strong>Iceland</strong>',
		answerDescriptionHtml: 'Location: Northern Europe (North Atlantic)<br>Principal Language: Icelandic',
		pathToMedia: 'placeholder',
		category: 'world-country-locations-languages-europe',
	},
	{
		questionTitleHtml: '<strong>Ireland</strong>',
		questionDescriptionHtml: 'What is the location and principal language of this country?',
		answerTitleHtml: '<strong>Ireland</strong>',
		answerDescriptionHtml: 'Location: Northern Europe<br>Principal Language: English',
		pathToMedia: 'placeholder',
		category: 'world-country-locations-languages-europe',
	},
	{
		questionTitleHtml: '<strong>Italy</strong>',
		questionDescriptionHtml: 'What is the location and principal language of this country?',
		answerTitleHtml: '<strong>Italy</strong>',
		answerDescriptionHtml: 'Location: Southern Europe<br>Principal Language: Italian',
		pathToMedia: 'placeholder',
		category: 'world-country-locations-languages-europe',
	},
	{
		questionTitleHtml: '<strong>Latvia</strong>',
		questionDescriptionHtml: 'What is the location and principal language of this country?',
		answerTitleHtml: '<strong>Latvia</strong>',
		answerDescriptionHtml: 'Location: Northern Europe (Baltic)<br>Principal Language: Latvian',
		pathToMedia: 'placeholder',
		category: 'world-country-locations-languages-europe',
	},
	{
		questionTitleHtml: '<strong>Liechtenstein</strong>',
		questionDescriptionHtml: 'What is the location and principal language of this country?',
		answerTitleHtml: '<strong>Liechtenstein</strong>',
		answerDescriptionHtml: 'Location: Central Europe<br>Principal Language: German',
		pathToMedia: 'placeholder',
		category: 'world-country-locations-languages-europe',
	},
	{
		questionTitleHtml: '<strong>Lithuania</strong>',
		questionDescriptionHtml: 'What is the location and principal language of this country?',
		answerTitleHtml: '<strong>Lithuania</strong>',
		answerDescriptionHtml: 'Location: Northern Europe (Baltic)<br>Principal Language: Lithuanian',
		pathToMedia: 'placeholder',
		category: 'world-country-locations-languages-europe',
	},
	{
		questionTitleHtml: '<strong>Luxembourg</strong>',
		questionDescriptionHtml: 'What is the location and principal language of this country?',
		answerTitleHtml: '<strong>Luxembourg</strong>',
		answerDescriptionHtml: 'Location: Western Europe<br>Principal Language: Luxembourgish',
		pathToMedia: 'placeholder',
		category: 'world-country-locations-languages-europe',
	},
	{
		questionTitleHtml: '<strong>Macedonia (North Macedonia)</strong>',
		questionDescriptionHtml: 'What is the location and principal language of this country?',
		answerTitleHtml: '<strong>Macedonia (North Macedonia)</strong>',
		answerDescriptionHtml: 'Location: Southeastern Europe (Balkans)<br>Principal Language: Macedonian',
		pathToMedia: 'placeholder',
		category: 'world-country-locations-languages-europe',
	},
	{
		questionTitleHtml: '<strong>Malta</strong>',
		questionDescriptionHtml: 'What is the location and principal language of this country?',
		answerTitleHtml: '<strong>Malta</strong>',
		answerDescriptionHtml: 'Location: Southern Europe (Mediterranean)<br>Principal Language: Maltese',
		pathToMedia: 'placeholder',
		category: 'world-country-locations-languages-europe',
	},
	{
		questionTitleHtml: '<strong>Moldova</strong>',
		questionDescriptionHtml: 'What is the location and principal language of this country?',
		answerTitleHtml: '<strong>Moldova</strong>',
		answerDescriptionHtml: 'Location: Eastern Europe<br>Principal Language: Romanian',
		pathToMedia: 'placeholder',
		category: 'world-country-locations-languages-europe',
	},
	{
		questionTitleHtml: '<strong>Monaco</strong>',
		questionDescriptionHtml: 'What is the location and principal language of this country?',
		answerTitleHtml: '<strong>Monaco</strong>',
		answerDescriptionHtml: 'Location: Western Europe<br>Principal Language: French',
		pathToMedia: 'placeholder',
		category: 'world-country-locations-languages-europe',
	},
	{
		questionTitleHtml: '<strong>Montenegro</strong>',
		questionDescriptionHtml: 'What is the location and principal language of this country?',
		answerTitleHtml: '<strong>Montenegro</strong>',
		answerDescriptionHtml: 'Location: Southeastern Europe (Balkans)<br>Principal Language: Montenegrin',
		pathToMedia: 'placeholder',
		category: 'world-country-locations-languages-europe',
	},
	{
		questionTitleHtml: '<strong>Netherlands</strong>',
		questionDescriptionHtml: 'What is the location and principal language of this country?',
		answerTitleHtml: '<strong>Netherlands</strong>',
		answerDescriptionHtml: 'Location: Western Europe<br>Principal Language: Dutch',
		pathToMedia: 'placeholder',
		category: 'world-country-locations-languages-europe',
	},
	{
		questionTitleHtml: '<strong>Norway</strong>',
		questionDescriptionHtml: 'What is the location and principal language of this country?',
		answerTitleHtml: '<strong>Norway</strong>',
		answerDescriptionHtml: 'Location: Northern Europe (Scandinavia)<br>Principal Language: Norwegian',
		pathToMedia: 'placeholder',
		category: 'world-country-locations-languages-europe',
	},
	{
		questionTitleHtml: '<strong>Poland</strong>',
		questionDescriptionHtml: 'What is the location and principal language of this country?',
		answerTitleHtml: '<strong>Poland</strong>',
		answerDescriptionHtml: 'Location: Central Europe<br>Principal Language: Polish',
		pathToMedia: 'placeholder',
		category: 'world-country-locations-languages-europe',
	},
	{
		questionTitleHtml: '<strong>Portugal</strong>',
		questionDescriptionHtml: 'What is the location and principal language of this country?',
		answerTitleHtml: '<strong>Portugal</strong>',
		answerDescriptionHtml: 'Location: Southern Europe<br>Principal Language: Portuguese',
		pathToMedia: 'placeholder',
		category: 'world-country-locations-languages-europe',
	},
	{
		questionTitleHtml: '<strong>Romania</strong>',
		questionDescriptionHtml: 'What is the location and principal language of this country?',
		answerTitleHtml: '<strong>Romania</strong>',
		answerDescriptionHtml: 'Location: Eastern Europe<br>Principal Language: Romanian',
		pathToMedia: 'placeholder',
		category: 'world-country-locations-languages-europe',
	},
	{
		questionTitleHtml: '<strong>Russia</strong>',
		questionDescriptionHtml: 'What is the location and principal language of this country?',
		answerTitleHtml: '<strong>Russia</strong>',
		answerDescriptionHtml: 'Location: Eastern Europe/Asia<br>Principal Language: Russian',
		pathToMedia: 'placeholder',
		category: 'world-country-locations-languages-europe',
	},
	{
		questionTitleHtml: '<strong>Serbia</strong>',
		questionDescriptionHtml: 'What is the location and principal language of this country?',
		answerTitleHtml: '<strong>Serbia</strong>',
		answerDescriptionHtml: 'Location: Southeastern Europe (Balkans)<br>Principal Language: Serbian',
		pathToMedia: 'placeholder',
		category: 'world-country-locations-languages-europe',
	},
	{
		questionTitleHtml: '<strong>Slovakia</strong>',
		questionDescriptionHtml: 'What is the location and principal language of this country?',
		answerTitleHtml: '<strong>Slovakia</strong>',
		answerDescriptionHtml: 'Location: Central Europe<br>Principal Language: Slovak',
		pathToMedia: 'placeholder',
		category: 'world-country-locations-languages-europe',
	},
	{
		questionTitleHtml: '<strong>Slovenia</strong>',
		questionDescriptionHtml: 'What is the location and principal language of this country?',
		answerTitleHtml: '<strong>Slovenia</strong>',
		answerDescriptionHtml: 'Location: Southern Europe<br>Principal Language: Slovenian',
		pathToMedia: 'placeholder',
		category: 'world-country-locations-languages-europe',
	},
	{
		questionTitleHtml: '<strong>Spain</strong>',
		questionDescriptionHtml: 'What is the location and principal language of this country?',
		answerTitleHtml: '<strong>Spain</strong>',
		answerDescriptionHtml: 'Location: Southern Europe<br>Principal Language: Spanish',
		pathToMedia: 'placeholder',
		category: 'world-country-locations-languages-europe',
	},
	{
		questionTitleHtml: '<strong>Sweden</strong>',
		questionDescriptionHtml: 'What is the location and principal language of this country?',
		answerTitleHtml: '<strong>Sweden</strong>',
		answerDescriptionHtml: 'Location: Northern Europe (Scandinavia)<br>Principal Language: Swedish',
		pathToMedia: 'placeholder',
		category: 'world-country-locations-languages-europe',
	},
	{
		questionTitleHtml: '<strong>Switzerland</strong>',
		questionDescriptionHtml: 'What is the location and principal language of this country?',
		answerTitleHtml: '<strong>Switzerland</strong>',
		answerDescriptionHtml: 'Location: Central Europe<br>Principal Language: German',
		pathToMedia: 'placeholder',
		category: 'world-country-locations-languages-europe',
	},
	{
		questionTitleHtml: '<strong>Turkey</strong>',
		questionDescriptionHtml: 'What is the location and principal language of this country?',
		answerTitleHtml: '<strong>Turkey</strong>',
		answerDescriptionHtml: 'Location: Western Asia/Southeastern Europe<br>Principal Language: Turkish',
		pathToMedia: 'placeholder',
		category: 'world-country-locations-languages-europe',
	},
	{
		questionTitleHtml: '<strong>Ukraine</strong>',
		questionDescriptionHtml: 'What is the location and principal language of this country?',
		answerTitleHtml: '<strong>Ukraine</strong>',
		answerDescriptionHtml: 'Location: Eastern Europe<br>Principal Language: Ukrainian',
		pathToMedia: 'placeholder',
		category: 'world-country-locations-languages-europe',
	},
	{
		questionTitleHtml: '<strong>United Kingdom</strong>',
		questionDescriptionHtml: 'What is the location and principal language of this country?',
		answerTitleHtml: '<strong>United Kingdom</strong>',
		answerDescriptionHtml: 'Location: Northern Europe<br>Principal Language: English',
		pathToMedia: 'placeholder',
		category: 'world-country-locations-languages-europe',
	},
	{
		questionTitleHtml: '<strong>Vatican City</strong>',
		questionDescriptionHtml: 'What is the location and principal language of this country?',
		answerTitleHtml: '<strong>Vatican City</strong>',
		answerDescriptionHtml: 'Location: Southern Europe (within Rome, Italy)<br>Principal Language: Italian',
		pathToMedia: 'placeholder',
		category: 'world-country-locations-languages-europe',
	},
]
