import type { FlashCard } from '@/types'

export const world_country_locations_languages_africa: FlashCard[] = [
	{
		questionTitleHtml: '<strong>Algeria</strong>',
		questionDescriptionHtml: 'What is the location and principal language of this country?',
		answerTitleHtml: '<strong>Algeria</strong>',
		answerDescriptionHtml: 'Location: North Africa<br>Principal Language: Arabic',
		pathToMedia: 'placeholder',
		category: 'world-country-locations-languages-africa',
	},
	{
		questionTitleHtml: '<strong>Angola</strong>',
		questionDescriptionHtml: 'What is the location and principal language of this country?',
		answerTitleHtml: '<strong>Angola</strong>',
		answerDescriptionHtml: 'Location: Southern Africa<br>Principal Language: Portuguese',
		pathToMedia: 'placeholder',
		category: 'world-country-locations-languages-africa',
	},
	{
		questionTitleHtml: '<strong>Botswana</strong>',
		questionDescriptionHtml: 'What is the location and principal language of this country?',
		answerTitleHtml: '<strong>Botswana</strong>',
		answerDescriptionHtml: 'Location: Southern Africa<br>Principal Language: English',
		pathToMedia: 'placeholder',
		category: 'world-country-locations-languages-africa',
	},
	{
		questionTitleHtml: '<strong>Burundi</strong>',
		questionDescriptionHtml: 'What is the location and principal language of this country?',
		answerTitleHtml: '<strong>Burundi</strong>',
		answerDescriptionHtml: 'Location: East Africa<br>Principal Language: Kirundi',
		pathToMedia: 'placeholder',
		category: 'world-country-locations-languages-africa',
	},
	{
		questionTitleHtml: '<strong>Central African Republic</strong>',
		questionDescriptionHtml: 'What is the location and principal language of this country?',
		answerTitleHtml: '<strong>Central African Republic</strong>',
		answerDescriptionHtml: 'Location: Central Africa<br>Principal Language: French',
		pathToMedia: 'placeholder',
		category: 'world-country-locations-languages-africa',
	},
	{
		questionTitleHtml: '<strong>Chad</strong>',
		questionDescriptionHtml: 'What is the location and principal language of this country?',
		answerTitleHtml: '<strong>Chad</strong>',
		answerDescriptionHtml: 'Location: Central Africa<br>Principal Language: French',
		pathToMedia: 'placeholder',
		category: 'world-country-locations-languages-africa',
	},
	{
		questionTitleHtml: '<strong>Democratic Republic of the Congo</strong>',
		questionDescriptionHtml: 'What is the location and principal language of this country?',
		answerTitleHtml: '<strong>Democratic Republic of the Congo</strong>',
		answerDescriptionHtml: 'Location: Central Africa<br>Principal Language: French',
		pathToMedia: 'placeholder',
		category: 'world-country-locations-languages-africa',
	},
	{
		questionTitleHtml: '<strong>Egypt</strong>',
		questionDescriptionHtml: 'What is the location and principal language of this country?',
		answerTitleHtml: '<strong>Egypt</strong>',
		answerDescriptionHtml: 'Location: North Africa/Middle East<br>Principal Language: Arabic',
		pathToMedia: 'placeholder',
		category: 'world-country-locations-languages-africa',
	},
	{
		questionTitleHtml: '<strong>Ethiopia</strong>',
		questionDescriptionHtml: 'What is the location and principal language of this country?',
		answerTitleHtml: '<strong>Ethiopia</strong>',
		answerDescriptionHtml: 'Location: East Africa<br>Principal Language: Amharic',
		pathToMedia: 'placeholder',
		category: 'world-country-locations-languages-africa',
	},
	{
		questionTitleHtml: '<strong>Ghana</strong>',
		questionDescriptionHtml: 'What is the location and principal language of this country?',
		answerTitleHtml: '<strong>Ghana</strong>',
		answerDescriptionHtml: 'Location: West Africa<br>Principal Language: English',
		pathToMedia: 'placeholder',
		category: 'world-country-locations-languages-africa',
	},
	{
		questionTitleHtml: '<strong>Guinea</strong>',
		questionDescriptionHtml: 'What is the location and principal language of this country?',
		answerTitleHtml: '<strong>Guinea</strong>',
		answerDescriptionHtml: 'Location: West Africa<br>Principal Language: French',
		pathToMedia: 'placeholder',
		category: 'world-country-locations-languages-africa',
	},
	{
		questionTitleHtml: '<strong>Kenya</strong>',
		questionDescriptionHtml: 'What is the location and principal language of this country?',
		answerTitleHtml: '<strong>Kenya</strong>',
		answerDescriptionHtml: 'Location: East Africa<br>Principal Language: English',
		pathToMedia: 'placeholder',
		category: 'world-country-locations-languages-africa',
	},
	{
		questionTitleHtml: '<strong>Liberia</strong>',
		questionDescriptionHtml: 'What is the location and principal language of this country?',
		answerTitleHtml: '<strong>Liberia</strong>',
		answerDescriptionHtml: 'Location: West Africa<br>Principal Language: English',
		pathToMedia: 'placeholder',
		category: 'world-country-locations-languages-africa',
	},
	{
		questionTitleHtml: '<strong>Libya</strong>',
		questionDescriptionHtml: 'What is the location and principal language of this country?',
		answerTitleHtml: '<strong>Libya</strong>',
		answerDescriptionHtml: 'Location: North Africa<br>Principal Language: Arabic',
		pathToMedia: 'placeholder',
		category: 'world-country-locations-languages-africa',
	},
	{
		questionTitleHtml: '<strong>Madagascar</strong>',
		questionDescriptionHtml: 'What is the location and principal language of this country?',
		answerTitleHtml: '<strong>Madagascar</strong>',
		answerDescriptionHtml: 'Location: East Africa (Indian Ocean)<br>Principal Language: Malagasy',
		pathToMedia: 'placeholder',
		category: 'world-country-locations-languages-africa',
	},
	{
		questionTitleHtml: '<strong>Mali</strong>',
		questionDescriptionHtml: 'What is the location and principal language of this country?',
		answerTitleHtml: '<strong>Mali</strong>',
		answerDescriptionHtml: 'Location: West Africa<br>Principal Language: French',
		pathToMedia: 'placeholder',
		category: 'world-country-locations-languages-africa',
	},
	{
		questionTitleHtml: '<strong>Morocco</strong>',
		questionDescriptionHtml: 'What is the location and principal language of this country?',
		answerTitleHtml: '<strong>Morocco</strong>',
		answerDescriptionHtml: 'Location: North Africa<br>Principal Language: Arabic',
		pathToMedia: 'placeholder',
		category: 'world-country-locations-languages-africa',
	},
	{
		questionTitleHtml: '<strong>Mozambique</strong>',
		questionDescriptionHtml: 'What is the location and principal language of this country?',
		answerTitleHtml: '<strong>Mozambique</strong>',
		answerDescriptionHtml: 'Location: Southeast Africa<br>Principal Language: Portuguese',
		pathToMedia: 'placeholder',
		category: 'world-country-locations-languages-africa',
	},
	{
		questionTitleHtml: '<strong>Niger</strong>',
		questionDescriptionHtml: 'What is the location and principal language of this country?',
		answerTitleHtml: '<strong>Niger</strong>',
		answerDescriptionHtml: 'Location: West Africa<br>Principal Language: French',
		pathToMedia: 'placeholder',
		category: 'world-country-locations-languages-africa',
	},
	{
		questionTitleHtml: '<strong>Nigeria</strong>',
		questionDescriptionHtml: 'What is the location and principal language of this country?',
		answerTitleHtml: '<strong>Nigeria</strong>',
		answerDescriptionHtml: 'Location: West Africa<br>Principal Language: English',
		pathToMedia: 'placeholder',
		category: 'world-country-locations-languages-africa',
	},
	{
		questionTitleHtml: '<strong>Republic of the Congo</strong>',
		questionDescriptionHtml: 'What is the location and principal language of this country?',
		answerTitleHtml: '<strong>Republic of the Congo</strong>',
		answerDescriptionHtml: 'Location: Central Africa<br>Principal Language: French',
		pathToMedia: 'placeholder',
		category: 'world-country-locations-languages-africa',
	},
	{
		questionTitleHtml: '<strong>Rwanda</strong>',
		questionDescriptionHtml: 'What is the location and principal language of this country?',
		answerTitleHtml: '<strong>Rwanda</strong>',
		answerDescriptionHtml: 'Location: East Africa<br>Principal Language: Kinyarwanda',
		pathToMedia: 'placeholder',
		category: 'world-country-locations-languages-africa',
	},
	{
		questionTitleHtml: '<strong>Somalia</strong>',
		questionDescriptionHtml: 'What is the location and principal language of this country?',
		answerTitleHtml: '<strong>Somalia</strong>',
		answerDescriptionHtml: 'Location: East Africa<br>Principal Language: Somali',
		pathToMedia: 'placeholder',
		category: 'world-country-locations-languages-africa',
	},
	{
		questionTitleHtml: '<strong>South Africa</strong>',
		questionDescriptionHtml: 'What is the location and principal language of this country?',
		answerTitleHtml: '<strong>South Africa</strong>',
		answerDescriptionHtml: 'Location: Southern Africa<br>Principal Language: English',
		pathToMedia: 'placeholder',
		category: 'world-country-locations-languages-africa',
	},
	{
		questionTitleHtml: '<strong>Sudan</strong>',
		questionDescriptionHtml: 'What is the location and principal language of this country?',
		answerTitleHtml: '<strong>Sudan</strong>',
		answerDescriptionHtml: 'Location: Northeast Africa<br>Principal Language: Arabic',
		pathToMedia: 'placeholder',
		category: 'world-country-locations-languages-africa',
	},
	{
		questionTitleHtml: '<strong>Swaziland (Eswatini)</strong>',
		questionDescriptionHtml: 'What is the location and principal language of this country?',
		answerTitleHtml: '<strong>Swaziland (Eswatini)</strong>',
		answerDescriptionHtml: 'Location: Southern Africa<br>Principal Language: Swati',
		pathToMedia: 'placeholder',
		category: 'world-country-locations-languages-africa',
	},
	{
		questionTitleHtml: '<strong>Tanzania</strong>',
		questionDescriptionHtml: 'What is the location and principal language of this country?',
		answerTitleHtml: '<strong>Tanzania</strong>',
		answerDescriptionHtml: 'Location: East Africa<br>Principal Language: Swahili',
		pathToMedia: 'placeholder',
		category: 'world-country-locations-languages-africa',
	},
	{
		questionTitleHtml: '<strong>Tunisia</strong>',
		questionDescriptionHtml: 'What is the location and principal language of this country?',
		answerTitleHtml: '<strong>Tunisia</strong>',
		answerDescriptionHtml: 'Location: North Africa<br>Principal Language: Arabic',
		pathToMedia: 'placeholder',
		category: 'world-country-locations-languages-africa',
	},
	{
		questionTitleHtml: '<strong>Uganda</strong>',
		questionDescriptionHtml: 'What is the location and principal language of this country?',
		answerTitleHtml: '<strong>Uganda</strong>',
		answerDescriptionHtml: 'Location: East Africa<br>Principal Language: English, Swahili',
		pathToMedia: 'placeholder',
		category: 'world-country-locations-languages-africa',
	},
	{
		questionTitleHtml: '<strong>Zambia</strong>',
		questionDescriptionHtml: 'What is the location and principal language of this country?',
		answerTitleHtml: '<strong>Zambia</strong>',
		answerDescriptionHtml: 'Location: Southern Africa<br>Principal Language: English',
		pathToMedia: 'placeholder',
		category: 'world-country-locations-languages-africa',
	},
	{
		questionTitleHtml: '<strong>Zimbabwe</strong>',
		questionDescriptionHtml: 'What is the location and principal language of this country?',
		answerTitleHtml: '<strong>Zimbabwe</strong>',
		answerDescriptionHtml: 'Location: Southern Africa<br>Principal Language: English',
		pathToMedia: 'placeholder',
		category: 'world-country-locations-languages-africa',
	},
]
