import type { FlashCard } from '@/types'

export const world_country_locations_languages_africa: FlashCard[] = [
	{
		questionTitleHtml: '<strong>What\'s this country in Africa?</strong>',
		questionDescriptionHtml: 'And its principal language',
		answerTitleHtml: '<strong>Algeria</strong>',
		answerDescriptionHtml: 'Location: North Africa<br>Principal Language: Arabic',
		pathToMedia: 'images/world-country-locations/africa/algeria.png',
		category: 'world-country-locations-languages-africa',
	},
	{
		questionTitleHtml: '<strong>What\'s this country in Africa?</strong>',
		questionDescriptionHtml: 'And its principal language',
		answerTitleHtml: '<strong>Angola</strong>',
		answerDescriptionHtml: 'Location: Southern Africa<br>Principal Language: Portuguese',
		pathToMedia: 'images/world-country-locations/africa/angola.png',
		category: 'world-country-locations-languages-africa',
	},
	{
		questionTitleHtml: '<strong>What\'s this country in Africa?</strong>',
		questionDescriptionHtml: 'And its principal language',
		answerTitleHtml: '<strong>Botswana</strong>',
		answerDescriptionHtml: 'Location: Southern Africa<br>Principal Language: English',
		pathToMedia: 'images/world-country-locations/africa/botswana.png',
		category: 'world-country-locations-languages-africa',
	},
	{
		questionTitleHtml: '<strong>What\'s this country in Africa?</strong>',
		questionDescriptionHtml: 'And its principal language',
		answerTitleHtml: '<strong>Burundi</strong>',
		answerDescriptionHtml: 'Location: East Africa<br>Principal Language: Kirundi',
		pathToMedia: 'images/world-country-locations/africa/burundi.png',
		category: 'world-country-locations-languages-africa',
	},
	{
		questionTitleHtml: '<strong>What\'s this country in Africa?</strong>',
		questionDescriptionHtml: 'And its principal language',
		answerTitleHtml: '<strong>Central African Republic</strong>',
		answerDescriptionHtml: 'Location: Central Africa<br>Principal Language: French',
		pathToMedia: 'images/world-country-locations/africa/central-african-republic.png',
		category: 'world-country-locations-languages-africa',
	},
	{
		questionTitleHtml: '<strong>What\'s this country in Africa?</strong>',
		questionDescriptionHtml: 'And its principal language',
		answerTitleHtml: '<strong>Chad</strong>',
		answerDescriptionHtml: 'Location: Central Africa<br>Principal Language: French, Arabic',
		pathToMedia: 'images/world-country-locations/africa/chad.png',
		category: 'world-country-locations-languages-africa',
	},
	{
		questionTitleHtml: '<strong>What\'s this country in Africa?</strong>',
		questionDescriptionHtml: 'And its principal language',
		answerTitleHtml: '<strong>Democratic Republic of the Congo</strong>',
		answerDescriptionHtml: 'Location: Central Africa<br>Principal Language: French',
		pathToMedia: 'images/world-country-locations/africa/democratic-republic-of-the-congo.png',
		category: 'world-country-locations-languages-africa',
	},
	{
		questionTitleHtml: '<strong>What\'s this country in Africa?</strong>',
		questionDescriptionHtml: 'And its principal language',
		answerTitleHtml: '<strong>Egypt</strong>',
		answerDescriptionHtml: 'Location: North Africa/Middle East<br>Principal Language: Arabic',
		pathToMedia: 'images/world-country-locations/africa/egypt.png',
		category: 'world-country-locations-languages-africa',
	},
	{
		questionTitleHtml: '<strong>What\'s this country in Africa?</strong>',
		questionDescriptionHtml: 'And its principal language',
		answerTitleHtml: '<strong>Ethiopia</strong>',
		answerDescriptionHtml: 'Location: East Africa<br>Principal Language: Amharic',
		pathToMedia: 'images/world-country-locations/africa/ethiopia.png',
		category: 'world-country-locations-languages-africa',
	},
	{
		questionTitleHtml: '<strong>What\'s this country in Africa?</strong>',
		questionDescriptionHtml: 'And its principal language',
		answerTitleHtml: '<strong>Ghana</strong>',
		answerDescriptionHtml: 'Location: West Africa<br>Principal Language: English',
		pathToMedia: 'images/world-country-locations/africa/ghana.png',
		category: 'world-country-locations-languages-africa',
	},
	{
		questionTitleHtml: '<strong>What\'s this country in Africa?</strong>',
		questionDescriptionHtml: 'And its principal language',
		answerTitleHtml: '<strong>Guinea</strong>',
		answerDescriptionHtml: 'Location: West Africa<br>Principal Language: French',
		pathToMedia: 'images/world-country-locations/africa/guinea.png',
		category: 'world-country-locations-languages-africa',
	},
	{
		questionTitleHtml: '<strong>What\'s this country in Africa?</strong>',
		questionDescriptionHtml: 'And its principal language',
		answerTitleHtml: '<strong>Kenya</strong>',
		answerDescriptionHtml: 'Location: East Africa<br>Principal Language: Swahili, English',
		pathToMedia: 'images/world-country-locations/africa/kenya.png',
		category: 'world-country-locations-languages-africa',
	},
	{
		questionTitleHtml: '<strong>What\'s this country in Africa?</strong>',
		questionDescriptionHtml: 'And its principal language',
		answerTitleHtml: '<strong>Liberia</strong>',
		answerDescriptionHtml: 'Location: West Africa<br>Principal Language: English',
		pathToMedia: 'images/world-country-locations/africa/liberia.png',
		category: 'world-country-locations-languages-africa',
	},
	{
		questionTitleHtml: '<strong>What\'s this country in Africa?</strong>',
		questionDescriptionHtml: 'And its principal language',
		answerTitleHtml: '<strong>Libya</strong>',
		answerDescriptionHtml: 'Location: North Africa<br>Principal Language: Arabic',
		pathToMedia: 'images/world-country-locations/africa/libya.png',
		category: 'world-country-locations-languages-africa',
	},
	{
		questionTitleHtml: '<strong>What\'s this country in Africa?</strong>',
		questionDescriptionHtml: 'And its principal language',
		answerTitleHtml: '<strong>Madagascar</strong>',
		answerDescriptionHtml: 'Location: East Africa (Indian Ocean)<br>Principal Language: Malagasy, French',
		pathToMedia: 'images/world-country-locations/africa/madagascar.png',
		category: 'world-country-locations-languages-africa',
	},
	{
		questionTitleHtml: '<strong>What\'s this country in Africa?</strong>',
		questionDescriptionHtml: 'And its principal language',
		answerTitleHtml: '<strong>Mali</strong>',
		answerDescriptionHtml: 'Location: West Africa<br>Principal Language: French',
		pathToMedia: 'images/world-country-locations/africa/mali.png',
		category: 'world-country-locations-languages-africa',
	},
	{
		questionTitleHtml: '<strong>What\'s this country in Africa?</strong>',
		questionDescriptionHtml: 'And its principal language',
		answerTitleHtml: '<strong>Morocco</strong>',
		answerDescriptionHtml: 'Location: North Africa<br>Principal Language: Arabic',
		pathToMedia: 'images/world-country-locations/africa/morocco.png',
		category: 'world-country-locations-languages-africa',
	},
	{
		questionTitleHtml: '<strong>What\'s this country in Africa?</strong>',
		questionDescriptionHtml: 'And its principal language',
		answerTitleHtml: '<strong>Mozambique</strong>',
		answerDescriptionHtml: 'Location: Southeast Africa<br>Principal Language: Portuguese',
		pathToMedia: 'images/world-country-locations/africa/mozambique.png',
		category: 'world-country-locations-languages-africa',
	},
	{
		questionTitleHtml: '<strong>What\'s this country in Africa?</strong>',
		questionDescriptionHtml: 'And its principal language',
		answerTitleHtml: '<strong>Niger</strong>',
		answerDescriptionHtml: 'Location: West Africa<br>Principal Language: French',
		pathToMedia: 'images/world-country-locations/africa/niger.png',
		category: 'world-country-locations-languages-africa',
	},
	{
		questionTitleHtml: '<strong>What\'s this country in Africa?</strong>',
		questionDescriptionHtml: 'And its principal language',
		answerTitleHtml: '<strong>Nigeria</strong>',
		answerDescriptionHtml: 'Location: West Africa<br>Principal Language: English',
		pathToMedia: 'images/world-country-locations/africa/nigeria.png',
		category: 'world-country-locations-languages-africa',
	},
	{
		questionTitleHtml: '<strong>What\'s this country in Africa?</strong>',
		questionDescriptionHtml: 'And its principal language',
		answerTitleHtml: '<strong>Republic of the Congo</strong>',
		answerDescriptionHtml: 'Location: Central Africa<br>Principal Language: French',
		pathToMedia: 'images/world-country-locations/africa/republic-of-the-congo.png',
		category: 'world-country-locations-languages-africa',
	},
	{
		questionTitleHtml: '<strong>What\'s this country in Africa?</strong>',
		questionDescriptionHtml: 'And its principal language',
		answerTitleHtml: '<strong>Rwanda</strong>',
		answerDescriptionHtml: 'Location: East Africa<br>Principal Language: Kinyarwanda',
		pathToMedia: 'images/world-country-locations/africa/rwanda.png',
		category: 'world-country-locations-languages-africa',
	},
	{
		questionTitleHtml: '<strong>What\'s this country in Africa?</strong>',
		questionDescriptionHtml: 'And its principal language',
		answerTitleHtml: '<strong>Somalia</strong>',
		answerDescriptionHtml: 'Location: East Africa<br>Principal Language: Somali',
		pathToMedia: 'images/world-country-locations/africa/somalia.png',
		category: 'world-country-locations-languages-africa',
	},
	{
		questionTitleHtml: '<strong>What\'s this country in Africa?</strong>',
		questionDescriptionHtml: 'And its principal language',
		answerTitleHtml: '<strong>South Africa</strong>',
		answerDescriptionHtml: 'Location: Southern Africa<br>Principal Language: English',
		pathToMedia: 'images/world-country-locations/africa/south-africa.png',
		category: 'world-country-locations-languages-africa',
	},
	{
		questionTitleHtml: '<strong>What\'s this country in Africa?</strong>',
		questionDescriptionHtml: 'And its principal language',
		answerTitleHtml: '<strong>Sudan</strong>',
		answerDescriptionHtml: 'Location: Northeast Africa<br>Principal Language: Arabic, English',
		pathToMedia: 'images/world-country-locations/africa/sudan.png',
		category: 'world-country-locations-languages-africa',
	},
	{
		questionTitleHtml: '<strong>What\'s this country in Africa?</strong>',
		questionDescriptionHtml: 'And its principal language',
		answerTitleHtml: '<strong>Eswatini (former official name: Swaziland)</strong>',
		answerDescriptionHtml: 'Location: Southern Africa<br>Principal Language: Swati, English',
		pathToMedia: 'images/world-country-locations/africa/eswatini.png',
		category: 'world-country-locations-languages-africa',
	},
	{
		questionTitleHtml: '<strong>What\'s this country in Africa?</strong>',
		questionDescriptionHtml: 'And its principal language',
		answerTitleHtml: '<strong>Tanzania</strong>',
		answerDescriptionHtml: 'Location: East Africa<br>Principal Language: Swahili',
		pathToMedia: 'images/world-country-locations/africa/tanzania.png',
		category: 'world-country-locations-languages-africa',
	},
	{
		questionTitleHtml: '<strong>What\'s this country in Africa?</strong>',
		questionDescriptionHtml: 'And its principal language',
		answerTitleHtml: '<strong>Tunisia</strong>',
		answerDescriptionHtml: 'Location: North Africa<br>Principal Language: Arabic, French',
		pathToMedia: 'images/world-country-locations/africa/tunisia.png',
		category: 'world-country-locations-languages-africa',
	},
	{
		questionTitleHtml: '<strong>What\'s this country in Africa?</strong>',
		questionDescriptionHtml: 'And its principal language',
		answerTitleHtml: '<strong>Uganda</strong>',
		answerDescriptionHtml: 'Location: East Africa<br>Principal Language: English, Swahili',
		pathToMedia: 'images/world-country-locations/africa/uganda.png',
		category: 'world-country-locations-languages-africa',
	},
	{
		questionTitleHtml: '<strong>What\'s this country in Africa?</strong>',
		questionDescriptionHtml: 'And its principal language',
		answerTitleHtml: '<strong>Zambia</strong>',
		answerDescriptionHtml: 'Location: Southern Africa<br>Principal Language: English',
		pathToMedia: 'images/world-country-locations/africa/zambia.png',
		category: 'world-country-locations-languages-africa',
	},
	{
		questionTitleHtml: '<strong>What\'s this country in Africa?</strong>',
		questionDescriptionHtml: 'And its principal language',
		answerTitleHtml: '<strong>Zimbabwe</strong>',
		answerDescriptionHtml: 'Location: Southern Africa<br>Principal Language: English',
		pathToMedia: 'images/world-country-locations/africa/zimbabwe.png',
		category: 'world-country-locations-languages-africa',
	},
]
